### ISSUE TITLE
getObservableQueries should not warn on missing queries

### ISSUE THREAD

**Issue by danilobuerger** [apollographql/apollo-client#10000]
**Intended outcome:**

Calling `getObservableQueries` via the client should not result in warnings if some of the included queries are missing. Calling this method directly is useful to check if a query is active or not.

**Actual outcome:**

Warning is emitted.

**How to reproduce the issue:**

Use `getObservableQueries` with a non-active query:

```ts
client.getObservableQueries(["name_of_non_active_query"]);
```

**Versions**

main

**Comment by jpvajda** [comment]
Hi @danilobuerger! Thanks for letting us know. It be helpful to see a reproduction of this issue. You can create a reproduction using https://github.com/apollographql/react-apollo-error-template and link to it here. If you prefer an in-browser way to create reproduction, try: https://codesandbox.io/s/github/apollographql/react-apollo-error-template

Also congrats on being the creating issue `10,000` in this repository! 🥳 🎈

**Comment by danilobuerger** [comment]
Hi @jpvajda, I don't understand how a reproduction would enhance this specific issue. Is there something unclear about it?

**Comment by jpvajda** [comment]
@danilobuerger it's helpful for us to see the problem in the code itself you are attempting to execute. It also helps others in our community to see a working code example of the bug, if they are facing the same issue. It's not required, but it will aid us attempting to troubleshoot, so if you have the time and share the code, we'd appreciate it.  Thank you!

**Comment by danilobuerger** [comment]
@jpvajda I added the relevant code snippet above. It doesn't matter how anything else is setup as it will always lead to the same code path.

**Comment by jerelmiller** [comment]
Hey @danilobuerger 👋 !

I definitely hear your concern and understand its an annoyance. I'd like to propose leaving this as-is since this API is used as a part of [`refetchQueries`](https://github.com/apollographql/apollo-client/blob/1d13de4f190150e96d61a9e987274ee6c249dbef/src/core/QueryManager.ts#L1263) which is commonly used in conjunction with [mutations](https://www.apollographql.com/docs/react/data/mutations#refetching-queries). This warning is only active in development and will be hidden in prod.

This warning can be useful to identify user mistakes such as typos and could potentially save a developer some debugging time by highlighting potential issues with their `refetchQueries` configuration. We've had some [issues](https://github.com/apollographql/apollo-client/issues/5917) where not logging a warning can cause headaches, so we try and be helpful where possible.

---

If the warning gets in the way too much, you might consider calling `getObservableQueries` with `"active"` or `"all"` as the parameter and perform the filtering yourself. These 2 values won't trigger console warnings. This might look something like this:

```ts
const queries = client.getObservableQueries('active');
const isActive = Array.from(queries.values())
  .some((observableQuery) => observableQuery.queryName === 'name_of_non_active_query')
```

Hope that helps!
