### ISSUE TITLE
useLazyQuery with the same document as useQuery triggers onCompleted for the latter

### ISSUE THREAD

**Issue by jbaccarelli-equinix** [apollographql/apollo-client#10017]
A simple question i think, i don't know if this is on purpose.

I have a table, for which I use `useQuery` to get it's data, paginated, on load, but then I have a button in a menu, where I want to fetch all the available records from the backend to print to CSV, the problem is that when I execute the `useLazyQuery` (using the same document but with more records requested) the call is fine, but the `onCompleted` of the original useQuery is executed too, I can't find a way to prevent this from happening, maybe if I had some flag I can use there to say "don't do what it's in here since the call was from another hook"?

Any ideas?

**Comment by RustamKarimov3** [comment]
+1

Also if I use two useLazyQuery on the same app page I get infinite loop. Response from the second useLazyQuery triggers the first useLazyQuery and the first useLazyQuery triggers the second useLazyQuery and so on. I believe this case is probably related to situation above.

**Comment by jpvajda** [comment]
@jbaccarelli-equinix Can you share some example code of how you set this up?

**Comment by jerelmiller** [comment]
Hey @jbaccarelli-equinix 👋 

I believe what you're seeing was due to the fact that `onCompleted` was triggered by cache writes. We fixed this in [`3.8.0`](https://github.com/apollographql/apollo-client/releases/tag/v3.8.0) via https://github.com/apollographql/apollo-client/pull/10340. Try upgrading to 3.8.0 or greater.

As such, I'm going to go ahead and close this out. Feel free to reopen if I've made a mistake!
