### ISSUE TITLE
(regression?) Apollo-client throws when it receives error response

### ISSUE THREAD

**Issue by thebigredgeek** [apollographql/apollo-client#1003]
https://github.com/apollostack/graphql-server/issues/236

**Comment by helfer** [comment]
Without a stack trace or a reproduction it's a bit difficult to get to the bottom of this. The only thing I see is that `resultBehaviors` are affected, which may be a hint that it has to do with query reducers.

@thebigredgeek Since you think it may be a regression, can you say what version of Apollo Client started breaking things?

**Comment by thebigredgeek** [comment]
Not sure.  I've updated several times in the last couple of weeks and only started noticing it yesterday.  It should be pretty simple to reproduce though.  Per @stubailo there are times when the server does not return `result.data` under error conditions.  This is what causes the exception.  You could probably reproduce that at the unit level ;)

**Comment by stubailo** [comment]
> You could probably reproduce that at the unit level ;)

Would you mind sending a PR with a unit test reproduction of your situation?

**Comment by helfer** [comment]
I don't think this is an issue any longer. If it is, we can reopen.
