### ISSUE TITLE
change `onSubscriptionData` and `onSubscriptionComplete` to `onData` and `onComplete`

### ISSUE THREAD

**Issue by jpvajda** [apollographql/apollo-client#10116]
- relates to #9495 
- see [comment](https://github.com/apollographql/apollo-client/pull/9495/files#r866194974)

As  a follow up to #9495 we want to change `onSubscriptionData` and `onSubscriptionComplete` to `onData` and `onComplete` so we are consistent in our types naming convention.

**Comment by jerelmiller** [comment]
@jpvajda I'd like to consider taking this on. Since `onSubscriptionData` and `onSubscriptionComplete` are currently in the stable API, I assume we'd want to deprecate these existing APIs (by showing a deprecation message) in addition to adding the new `onData` and `onComplete`.

Does this sound correct?

Should we allow users to use both together? My initial thinking is no, since one will replace the other. Perhaps we error in this situation?

**Comment by jpvajda** [comment]
Hi @jerelmiller! 

>  I assume we'd want to deprecate these existing APIs (by showing a deprecation message)

- great question! I don't know what our standard is for this type of change yet, but that' s a good suggestion we can talk more in our team planning today. This might go into our 4.0 release depending on the impacts to a developers. 

> Should we allow users to use both together?

 - I'd also say no on this and agree with your take on it.

**Comment by jerelmiller** [comment]
Done in https://github.com/apollographql/apollo-client/pull/10134
