### ISSUE TITLE
Cache returning inconsistent results

### ISSUE THREAD

**Issue by OliverDowd** [apollographql/apollo-client#10113]
**Intended outcome:**

When the client is used to perform a query, then every time after that when we get a cache hit for the same query with the same params we should receive the same data.

**Actual outcome:**

In certain situations, the client returns different data for the same query and params if there have been multiple different queries in a row. See repro steps for explanation of situations.

**How to reproduce the issue:**

For context I am working on a react website where a user queries for a school subject and they can see various lessons for a subject along with other information about these lessons. The issue happens when we do the following:

Step 1: Query the client for all piano lessons:
```
const data = await client.query<Type, Variables>({
  query: someGQLTemplate,
  variables: {subject: "piano"}
})
```

we receive the following data:

```
{
  lessons: [
    {title: "Piano lessons", instructor: "Bach", daysTaught: ["Mon", "Tues", "Wed"], id: 1, __typename: "lesson"}
  ]
}
```

From what I understand the cache key for the lesson object is "lesson:1"

Step 2: Query the client for all piano lessons on Wednesday

```
const data = await client.query<Type, Variables>({
  query: someGQLTemplate,
  variables: {subject: "piano", daysTaught: ["Wed"]}
})
```

we receive the following data:

```
{
  lessons: [
    {title: "Piano lessons", instructor: "Bach", daysTaught: ["Wed"], id: 1, __typename: "lesson"}
  ]
}
```

From what I understand the cache key for the lesson object is still "lesson:1" but this was the same as the previous call so the cache value gets replaced

Step 3: Query the client for all piano lessons

```
const data = await client.query<Type, Variables>({
  query: someGQLTemplate,
  variables: {subject: "piano"}
})
```

We see that this query has been asked before and there is a reference to "lesson:1" in the query response. We then look up the cache value with that key and replace it to receive the following data:

```
{
  lessons: [
    {title: "Piano lessons", instructor: "Bach", daysTaught: ["Wed"], id: 1, __typename: "lesson"}
  ]
}
```
However, this is incorrect since we had a cache collision between query 1 and 2, instead we should have received the full list of ``daysTaught`` as we did in query 1

Initialize an apollo client
```
new ApolloClient({
    cache: new InMemoryCache(),
    defaultOptions: {
      // Do not cache results for mutations
      mutate: {
        fetchPolicy: 'no-cache',
      },
    },
  });
```

**Versions**

 System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - 
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.33)
  npmPackages:
    @apollo/client: ^3.6.9 => 3.6.9
    apollo: ^2.34.0 => 2.34.0
    apollo-link-timeout: ^4.0.0 => 4.0.0

**Comment by dylanwulf** [comment]
Hi there,
I believe the cache is behaving within expectations here. Apollo client makes the assumption that the entity `lesson:1` will always contain the same data (unless it gets mutated) no matter what the query arguments are. The reason it makes this assumption is because most GraphQL APIs work that way. There are a couple ways this could be solved:
1. [Disable cache normalization](https://www.apollographql.com/docs/react/caching/cache-configuration#disabling-normalization) for the `lesson` type. This will fix your queries so that they can both display the correct data. But it has the drawback that any of your mutations which mutate the lesson data will no longer be able to automatically update your query data.
    ```js
    const client = new ApolloClient({
      // ...other arguments...
      cache: new InMemoryCache({
        typePolicies: {
          lesson: { // this should match the __typename
            keyFields: false,
          },
        },
      })
    });
    ```
2. I don't know what your GraphQL API looks like or whether you have the ability to change it, but I'm going to work with the assumption that the `daysTaught` variable is being passed as an argument into the `lesson` field. You could change the server so that the returned `daysTaught` field data will have all the days of that lesson no matter what the query variables are (personally this is how I would expect an API to behave and I would recommend this option if possible). Or another option would be to give the `daysTaught` field its own arguments separate from the `lesson` field's arguments, which would allow the apollo client cache to understand the difference between the two queries.
