### ISSUE TITLE
`AC 3 Docs` Explain new cache console.log warnings, what they mean, how to resolve them

### ISSUE THREAD

**Issue by jpvajda** [apollographql/apollo-client#10179]
Explain new cache console.log warnings, what they mean, how to resolve them.

**Comment by jerelmiller** [comment]
Since there aren't any code examples and I'm struggling to find context in the original issue, I'm going to go ahead and close this. I'd be happy to reopen if we discover the need for this or there is more confusion, though ideally we'd just make our console warnings clearer if they are too ambiguous 🙂
