### ISSUE TITLE
Confusing documentation of a readQuery

### ISSUE THREAD

**Issue by patrikniebur** [apollographql/apollo-client#10233]
I'm confused by this example in the documentation for `readQuery`  
https://github.com/apollographql/apollo-client/blob/6875d3ced43162557cbd507558dfbdbc37512a69/docs/source/caching/cache-interaction.mdx?plain=1#L40-L48

How would you use this with the cached data? Unless I'm missing something you can't retrieve cached reference with this query - I  [asked about this in the community](https://community.apollographql.com/t/readquery-get-data-from-cache/348)  

The only way this example retrieves the data is if it was written to the cache using the same query like in the example below:  
https://github.com/apollographql/apollo-client/blob/6875d3ced43162557cbd507558dfbdbc37512a69/docs/source/caching/cache-interaction.mdx?plain=1#L81-L87  

But in this scenario you are not able to get all the todos using:  
```gql
query AllTodos { 
  todo { 
    id 
    text 
    completed 
  } 
}
```

So what is the real world use case for readQuery with the `id`? Am I missing something? Thanks in advance for any help with this.

**Comment by jerelmiller** [comment]
Hey @patrikniebur 👋 

I know its been some time since you opened this issue and I know you've had some responses over in the [community thread](https://community.apollographql.com/t/readquery-get-data-from-cache), but I wanted to come back here and offer a bit more of an explanation as I can see where the confusion comes from.

`readQuery` relies on the top-level field you're querying to be available under the `ROOT_QUERY` type in the cache. This means you would have had to execute at least one query in your application that uses that field in your schema in order for this to work. The reason for this is because we don't know what your schema is, therefore its impossible for us to tell just looking at the query document that the `todo` _field_ returns a `Todo` type. Instead, `readQuery` will traverse the query starting at the `ROOT_QUERY`, look for a field called `todo` that contains the arguments passed to that field (since they are serialized into the field key), then if it finds it, will grab all the fields within that type.

In other words, your cache needs to look like this in order for this to work:

```
{
  ROOT_QUERY: {
    'todo({"id":5})': { 
      __ref: 'Todo:5'
    }
  },
  'Todo:5': { ... }
}
```

> But in this scenario you are not able to get all the todos

The same thing applies here. The cache needs a field under `ROOT_QUERY` called `todos` in order to be able to get any data for it. Looking at the above example, you can see that there is no `todos` field under `ROOT_QUERY`, therefore its unable to get anything from the cache.

> what is the real world use case for readQuery

This can be beneficial when you are rendering a list of data from a query with a mutation that may add/remove data from that list of data. See [this example](https://www.apollographql.com/docs/react/data/mutations#the-update-function) of the `update` function on `useMutation`. This particular example uses `cache.modify`, but `cache.readQuery`/`cache.writeQuery` could also be used here to read/write this data.

---

I'll take a stab at updating our documentation to see if I can clarify this bit of info. Does this at least help some to understand why `readQuery` might not always work?
