### ISSUE TITLE
How can I add custom headers in sandbox

### ISSUE THREAD

**Issue by saiteja9177** [apollographql/apollo-client#10318]
Hi There I have few headers like transactionId, Correlation-Id, recently we migrated from Apollo V2 to V3 so using Sandbox as landing page.

In sandbox I can see predefined headers like authorization and other things but if I try to provide custom headers getting error like "Unable to reach server"

**Comment by alessbell** [comment]
Hi @saiteja9177 👋 Can you share a bit more info? I'm able to pass custom headers in the Studio sandbox explorer if I:

- navigate to https://studio.apollographql.com/sandbox/explorer
- use the API URL https://flyby-locations-sub.herokuapp.com/ and the following query
```graphql
query ExampleQuery {
  locations {
    name
  }
}
```
- add a custom header, e.g. `Custom-Header: foo`
- run the query and view the request headers in the network tab

Result:
![CleanShot 2022-11-29 at 16 33 09](https://user-images.githubusercontent.com/5139846/204652746-ec3981a6-9bcf-440d-895c-c4f6b263d0fe.png)

Please feel free to share some more context here and I'd be happy to look into it further, but since this is the repository for Apollo Client I may eventually redirect you to https://github.com/apollographql/embeddable-explorer :) Thanks!

**Comment by alessbell** [comment]
I'm going to close this issue out, @saiteja9177, but feel free to re-open with additional info or create a new issue in https://github.com/apollographql/embeddable-explorer. Thanks :)
