### ISSUE TITLE
ts-invariant Unknown Token 'export' Recurrence... Again :(

### ISSUE THREAD

**Issue by lgants** [apollographql/apollo-client#10409]
I'm creating a bug ticket as a follow-up to a previously closed issue, namely [ts-invariant: Unknown token 'export'](https://github.com/apollographql/apollo-client/issues/9535), due to another recurrence.

**Intended outcome:**
Node should not encounter an unexpected export when using ts-invaraint of @apollo/client 3.7.3.

**Actual outcome:**

Node _did_ encounter an unexpected export when using ts-invaraint and subsequently stopped the app. Here's the trace:

<img width="1073" alt="Screenshot 2023-01-05 at 2 54 30 AM" src="https://user-images.githubusercontent.com/18373573/210732653-85b72f6b-9984-4245-bb33-9170ac85cdc2.png">

**How to reproduce the issue:**
I encountered the error while poking around with the [Apollo Universal Starter Kit](https://github.com/sysgears/apollo-universal-starter-kit) from a few years ago - I'm entertaining updating it to migrate off of HOCs. Unfortunately, any @apollo/client version update after 3.4.0 breaks the server implementation due to this issue (webpack config is available [here](https://github.com/sysgears/apollo-universal-starter-kit/blob/a4c7b182c0ac767a3aee3d020cb9e5dec7d5df87/packages/server/webpack.config.js)). I updated a few additional dependencies (e.g. webpack to 5.75.0, and React 18, but it's otherwise the same). I've spent most of today debugging and trying every workaround imaginable to no avail. 

**Versions**
 System:
    OS: macOS 13.1
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    Yarn: 3.2.2 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.2/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 103.0.2
    Safari: 16.2

**Comment by bignimbus** [comment]
Hi @lgants 👋🏻  thanks for opening this issue and for upgrading!  This definitely looks frustrating.  Here are the steps I took in order to reproduce this issue:

1. Clone `apollo-universal-starter-kit`
2. `yarn install` (error YN000: Failed with errors in 1m 24s, appears related to having the wrong `python` locally. Disregard)
3. Update `packages/client/package.json` to replace `"apollo-client": "..."` with `"@apollo/client": "latest"`
4. `rm -rf node_modules && yarn`
5. Due to the error building one of the dependencies, I'm unable to start the server.  But when I run `cat yarn.lock | grep "ts-invariant"` I see three different resolutions. This is likely the source of the issue you're experiencing.

Based on the above, I recommend opening an issue in the `apollo-universal-starter-kit` repository since this dependency conflict is outside of the `apollo-client` project.  Thanks!
