### ISSUE TITLE
Use local state with "no-cache"

### ISSUE THREAD

**Issue by danielvanmil** [apollographql/apollo-client#10413]
For a not yet implemented server side caching policy we might want to use local state without using the cache ("no-cache" policy), but we would (also) like to use the query language instead of using the useReactiveVar hook to read the state as it seems a nice option.

Unfortunately the typePolicy with the read function seems to be ignored with the "no-cache" policy.

Any options to achieve this?

We could use the "network-only" policy which seems to make it work, but it seems a bit overkill to fill the cache when it is not used.

**Comment by jerelmiller** [comment]
Hey @danielvanmil 👋 !

You might try using [local resolvers](https://www.apollographql.com/docs/react/local-state/local-resolvers). I believe these run regardless of the cache policy. 

Just an FYI, be aware that this form of local resolvers is deprecated and will be moved in a future major version. We plan to move this into a [link](https://github.com/apollographql/apollo-client/issues/10060), likely in v4. Try this out and see if this gets you what you're looking for!

**Comment by danielvanmil** [comment]
thanks @jerelmiller !

That looks like an option that works, but:

1. It would not be wise to build on a solution that may not be supported in the future. How certain is it 10060 will be resolved?
2. Would it be more wise to just use "network-only" policy and ignore the cache. Will a large cache cause memory issues maybe?

**Comment by jerelmiller** [comment]
Hey @danielvanmil 👋 !

> How certain is it 10060 will be resolved?

Apologies, I probably should have gone into a bit more detail here. When I say "deprecated", I mean that the way in which you add local resolvers for use with the `@client` directive will change in v4 by moving the logic out of core and into the link chain. This however won't be done until v4 to avoid breaking changes. While I can't say for certain what this will look like in v4, my guess is that it will resemble today's solution, but placed in an Apollo Link instead.

Initially we had planned to deprecate local resolvers completely in favor of the new cache APIs, but we have changed our minds and instead plan to support them in the link chain (see [this comment](https://github.com/apollographql/apollo-client/issues/8189#issuecomment-857199932) for more info). 

> Will a large cache cause memory issues maybe?

That's very possible, though its hard for me to issue a blanket "yes" or "no" since every app and it's data requirements are different. I'd advise doing some perf measurement on your end to see what constraints you're up against. That being said, we have many users with large apps that are use the cache effectively. If you need fine-grained control over cache management, I'd recommend checking out the [`cache.gc()`](https://www.apollographql.com/docs/react/api/cache/InMemoryCache#gc) and [`cache.evict()`](https://www.apollographql.com/docs/react/api/cache/InMemoryCache#evict) APIs that will allow you to remove data from the cache. This should help in the event the cache grows to a size that causes memory issues.

> Would it be more wise to just use "network-only" policy and ignore the cache

Given the above info, I'll leave this up to you to decide 😄 . If churn might be an issue for you using local resolvers, this is definitely an option. 

Hope this helps!
