### ISSUE TITLE
SSR http and batch-http uses headers that are now illegal in Node 18

### ISSUE THREAD

**Issue by mschipperheyn** [apollographql/apollo-client#10475]
### Issue Description

http and batch-http link retrieve and overwrite user specified headers that are considered illegal in Node 18 [undici: offending header keys can be found here](https://github.com/nodejs/undici/blob/9e5316c8b04a7b35522d0d5b8de71f67fa2a3c34/lib/fetch/constants.js#L3) which has replaced node-fetch.

It results in the error:

```
 networkError: TypeError: fetch failed
      at Object.fetch (node:internal/deps/undici/undici:11118:11) {
    cause: InvalidArgumentError: invalid connection header
        at processHeader (/Users/mschipperheyn/eclipse-workspace/semina/node_modules/next/dist/compiled/undici/index.js:7:11)
        at new Request (/Users/mschipperheyn/eclipse-workspace/semina/node_modules/next/dist/compiled/undici/index.js:1:80981)
```

When you remove the "illegal" headers yourself and supply the corrected options object to `new BatchHttpLink(options)` or `createHttpLink(options)`, unfortunately, the internals force those headers back, in particular: `host, connection, accept-encoding, referer, cookie`, because context headers take precedence.

### Link to Reproduction

https://comeonguys

**Comment by jerelmiller** [comment]
Hey @mschipperheyn 👋 ! Thanks for reporting the issue! 

I'd love to clarify some things to best understand the behavior you're seeing.

> When you remove the "illegal" headers yourself and supply the corrected options

When you say "remove the illegal headers yourself", do you mean you're trying to do something like this?

```ts
const httpLink = createHttpLink({
  headers: {
    host: undefined,
    referer: undefined,
    // etc
  }
})
```

> unfortunately, the internals force those headers back ... because context headers take precedence.

To make sure I understand what's happening here, are you saying that a query like the following is overwriting the "illegal" headers because they are defined in context?

```ts
await client.query({
  context: {
    headers: { host: 'foo', referer: 'bar' }
  }
});
```

If my understanding is incorrect, a reproduction or some code samples would go a long way to help me understand what's happening.

---

I'll note that Apollo Client currently only sets [2 default headers](https://github.com/apollographql/apollo-client/blob/49ffcfab0165dc61a7475b2e18f0ecae00f7c22c/src/link/http/selectHttpOptionsAndBody.ts#L105-L121) in requests: `accept` and `content-type`. These look they are "legal" according to that list you linked to. Is it safe to assume those "illegal" headers are being set somewhere in your app? And if so, I'd like to better understand why you're unable to remove those headers set in context.

---

In general, I'd love to understand you're ask here. Are you looking for Apollo Client to always filter out those headers? For Apollo Client to do a better job of merging headers defined in `HttpLink`/`BatchHttpLink` and context? Something else entirely? Any information you can provide would be helpful.

For now, you could consider creating a custom Apollo Link that strips these headers out for you. You should be able to overwrite any of those illegal headers yourself coming from other parts of the app. Using [Apollo Link Context](https://www.apollographql.com/docs/react/api/link/apollo-link-context), this might give you a rough idea on how you could do this:

```ts
import { setContext } from "@apollo/client/link/context";

const stripIllegalHeadersLink = setContext((_request, previousContext) => ({
  headers: {
    ...previousContext.headers,
    host: undefined,
    referer: undefined,
    // etc
  }
});
```

Thanks!

**Comment by mschipperheyn** [comment]
> Hey @mschipperheyn 👋 ! Thanks for reporting the issue!
> 
> I'd love to clarify some things to best understand the behavior you're seeing.
> 
> > When you remove the "illegal" headers yourself and supply the corrected options
> 
> When you say "remove the illegal headers yourself", do you mean you're trying to do something like this?
> 
> ```ts
> const httpLink = createHttpLink({
>   headers: {
>     host: undefined,
>     referer: undefined,
>     // etc
>   }
> })
> ```
> 

Correct
> > unfortunately, the internals force those headers back ... because context headers take precedence.
> 
> To make sure I understand what's happening here, are you saying that a query like the following is overwriting the "illegal" headers because they are defined in context?
> 
> ```ts
> await client.query({
>   context: {
>     headers: { host: 'foo', referer: 'bar' }
>   }
> });
> ```
> 
Correct. In your code headers are retrieved from the request. When you output them immediately after, you see that they contain all the request headers, including cookie etc: a normal request header structure.
But these headers are then merged with the specified headers. So, the user specified headers are treated as a kind of add-on.

```
var context = operation.getContext();
console.log('context1', context.headers);
[...]

```
> If my understanding is incorrect, a reproduction or some code samples would go a long way to help me understand what's happening.

Using node 18.12.1 should reproduce the issue on any query is what I'm guessing. 
> 
> I'll note that Apollo Client currently only sets [2 default headers](https://github.com/apollographql/apollo-client/blob/49ffcfab0165dc61a7475b2e18f0ecae00f7c22c/src/link/http/selectHttpOptionsAndBody.ts#L105-L121) in requests: `accept` and `content-type`. These look they are "legal" according to that list you linked to. Is it safe to assume those "illegal" headers are being set somewhere in your app? And if so, I'd like to better understand why you're unable to remove those headers set in context.

It's always possible that it's me. I tried to go this way:

```
import { createHttpLink, split } from '@apollo/client';

const createBatchHttpLink = (() => {
	let _batchHttpLink: BatchHttpLink;
	return (options: BatchHttpLink.Options) => {
		if (!_batchHttpLink) {
			_batchHttpLink = new BatchHttpLink(options);
		}
		return _batchHttpLink;
	};
})();

const httpLink = (isServer: boolean, opts: Record<string, any>) => {
	const options: HttpOptions = {
		fetch: isServer && opts.fetch,
		uri: graphqlUrl(),
		fetchOptions: {
			credentials: isServer ? 'same-origin' : 'include',
			timeout: 30000,
		},
		credentials: isServer ? 'same-origin' : 'include',
	};

	if (isServer) {
		const incomingHeader = { ...(opts?.req?.headers || {}) }
		delete incomingHeader.connection;
		delete incomingHeader.cookie;
		delete incomingHeader.host;
		delete incomingHeader.referer;
		delete incomingHeader['accept-encoding'];
		options.headers = incomingHeader;
	}
	return split(
		operation => optout(operation) || isServer,
		createHttpLink(options),
		createBatchHttpLink(options),
	);
};
```
> 
> In general, I'd love to understand you're ask here. Are you looking for Apollo Client to always filter out those headers? For Apollo Client to do a better job of merging headers defined in `HttpLink`/`BatchHttpLink` and context? Something else entirely? Any information you can provide would be helpful.
> 
> For now, you could consider creating a custom Apollo Link that strips these headers out for you. You should be able to overwrite any of those illegal headers yourself coming from other parts of the app. Using [Apollo Link Context](https://www.apollographql.com/docs/react/api/link/apollo-link-context), this might give you a rough idea on how you could do this:
> 
> ```ts
> import { setContext } from "@apollo/client/link/context";
> 
> const stripIllegalHeadersLink = setContext((_request, previousContext) => ({
>   headers: {
>     ...previousContext.headers,
>     host: undefined,
>     referer: undefined,
>     // etc
>   }
> });
> ```
> 
> Thanks!
Yeah, that was my approach. It lead me to conclude Apollo itself put those headers back. Perhaps I was wrong. I hope so.

**Comment by jerelmiller** [comment]
@mschipperheyn I'll point you to a couple places in code that I think might help. Looking at your link definition above, I think the headers being removed are happening too early in the process and the work you're doing to try and remove them are being overridden by `context`. Let me see if I can show you what I mean.

When you initialize an `HttpLink` either through the [constructor](https://github.com/apollographql/apollo-client/blob/main/src/link/http/HttpLink.ts), or through [`createHttpLink`](https://github.com/apollographql/apollo-client/blob/main/src/link/http/createHttpLink.ts), the headers end up in a variable called `linkConfig`

https://github.com/apollographql/apollo-client/blob/d8f28c3da80ff898d11c636d8b688e6d471432fa/src/link/http/createHttpLink.ts#L47-L52

And the `context` headers end up in a variable called `contextConfig`

https://github.com/apollographql/apollo-client/blob/d8f28c3da80ff898d11c636d8b688e6d471432fa/src/link/http/createHttpLink.ts#L82-L87

We send both of these options through a function called `selectHttpOptionsAndBodyInternal` and get back the request `options` and request `body`:

https://github.com/apollographql/apollo-client/blob/d8f28c3da80ff898d11c636d8b688e6d471432fa/src/link/http/createHttpLink.ts#L90-L96

(you can see these options are passed through to `fetch` here)

https://github.com/apollographql/apollo-client/blob/d8f28c3da80ff898d11c636d8b688e6d471432fa/src/link/http/createHttpLink.ts#L167

If we take a look more in-depth at `selectHttpOptionsAndBodyInternal`, we can see that we get all the configs passed to the function

https://github.com/apollographql/apollo-client/blob/d8f28c3da80ff898d11c636d8b688e6d471432fa/src/link/http/selectHttpOptionsAndBody.ts#L148-L152

then we try and merge all the options together in a loop, where the configs passed last in the function override configs before them. You can see the merging of http headers here:

https://github.com/apollographql/apollo-client/blob/d8f28c3da80ff898d11c636d8b688e6d471432fa/src/link/http/selectHttpOptionsAndBody.ts#L160-L163

Recall that `contextConfig` is passed to `selectHttpOptionsAndBodyInternal` after the `linkConfig`, which means any header set in `context` is going to override anything from the link config.

Looking at your code, it looks like you're setting headers in what amounts to the `linkConfig`, so any headers that are set inside of `context` are going to override the work you're doing in your `httpLink` function. In order for the headers to be removed, you'll need to intercept the `context` and make modifications there before it reaches your `HttpLink` so that by the time `HttpLink` calls [`operation.getContext()`](https://github.com/apollographql/apollo-client/blob/d8f28c3da80ff898d11c636d8b688e6d471432fa/src/link/http/createHttpLink.ts#L57), the values are already overridden.

In my opinion, the Apollo Link Context gives you your best shot at intercepting that `context` object and making modifications to it (you can do this with a plain `ApolloLink` as well, but Apollo Link Context is a nice shortcut). That would mean your code might look something like this with this in place:

```ts
import { 
  createHttpLink, 
  from, // <------ NEW
  split 
} from '@apollo/client';
import { setContext } from '@apollo/client/link/context'; // <--- NEW

const createBatchHttpLink = (() => {
  let _batchHttpLink: BatchHttpLink;
  return (options: BatchHttpLink.Options) => {
    if (!_batchHttpLink) {
      _batchHttpLink = new BatchHttpLink(options);
    }
    return _batchHttpLink;
  };
})();

// NEW
const stripIllegalHeadersLink = setContext((_request, previousContext) => {
  const incomingHeader = { ...(previousContext.headers || {}) };

  // Moved from `httpLink` to here
  if (isServer) {
    delete incomingHeader.connection;
    delete incomingHeader.cookie;
    delete incomingHeader.host;
    delete incomingHeader.referer;
    delete incomingHeader['accept-encoding'];
  }

  return {
    headers: incomingHeaders
  }
})

const httpLink = (isServer: boolean, opts: Record<string, any>) => {
  const options: HttpOptions = {
    fetch: isServer && opts.fetch,
    uri: graphqlUrl(),
    fetchOptions: {
      credentials: isServer ? 'same-origin' : 'include',
      timeout: 30000,
    },
    credentials: isServer ? 'same-origin' : 'include',
  };

  // removal of headers moved to stripIllegalHeadersLink

  return from( // <---- NEW
    stripIllegalHeadersLink, // <---- NEW
    split(
      (operation) => optout(operation) || isServer,
      createHttpLink(options),
      createBatchHttpLink(options)
    )
  );
};
```

See if you can get something similar to that working! Hope this helps!

**Comment by mschipperheyn** [comment]
Thanks for the kind detailed response. I'll give a go tomorrow and let you know if it worked out!

**Comment by jerelmiller** [comment]
You're welcome! Here's to hoping it works 🍻 🤞

**Comment by mschipperheyn** [comment]
Yes, it did. Thank you. Small correction (`from` expects an array):

```
return from([ // <---- NEW
    stripIllegalHeadersLink, // <---- NEW
    split(
      (operation) => optout(operation) || isServer,
      createHttpLink(options),
      createBatchHttpLink(options)
    )
  ]);
```

**Comment by jerelmiller** [comment]
Whoops, you're right. I meant to wrap that in an array. Good catch! Glad that's working for you!
