### ISSUE TITLE
useQuery stuck on loading when ssrForceFetchDelay is set and ssr: false

### ISSUE THREAD

**Issue by Ellarddekoeijer** [apollographql/apollo-client#10474]
### Issue Description

We ran into the issue where a useQuery does not resolve and gets stuck on loading. After much debugging we figured out that it is due to the combination of useQuery's ssr option being false and ssrForceFetchDelay being set. As a workaround we are using the onCompleted hook to manually set the fetched data.

In our app, where the problem occurred, ssrForceFetchDelay is set to 100. However, to reproduce it I had to set it to 1000 before the issue occurred. Due to circumstances outside of our control we are unable to stray away from using ssrForceFetchDelay. I have seen a few issues about this subject but since these have been closed without the issue seemingly being resolved I am opening another.

### Link to Reproduction

https://github.com/Ellarddekoeijer/apollo-ssr-force-fetch-delay

### Reproduction Steps

1. npm i
2. npm start
3. notice that the app is stuck on loading
4. fill in the form to add a name
5. notice that the data has been fetched

**Comment by bignimbus** [comment]
Thanks for opening this issue @Ellarddekoeijer 👋🏻 

Since I haven't used this config in a production app I'll have to speculate a bit.  From [the docs](https://www.apollographql.com/docs/react/performance/server-side-rendering/#overriding-fetch-policies-during-initialization):

https://github.com/apollographql/apollo-client/blob/895ddcb546b5692cd53caae1b604412728641374/docs/source/performance/server-side-rendering.mdx#L198

Here's another relevant snippet:

https://github.com/apollographql/apollo-client/blob/895ddcb546b5692cd53caae1b604412728641374/src/react/hooks/useQuery.ts#L308-L315

When I drop a breakpoint at line 315, I can no longer reproduce the issue.  Interesting!  This snippet is also notable:

https://github.com/apollographql/apollo-client/blob/895ddcb546b5692cd53caae1b604412728641374/src/core/ApolloClient.ts#L170-L180

I was curious whether changing `client.disableNetworkFetches` in userland would make a difference.  When I applied this diff, I resolved the issue in your reproduction:

```diff
diff --git a/src/index.jsx b/src/index.jsx
index 5310419..c7ee939 100644
--- a/src/index.jsx
+++ b/src/index.jsx
@@ -40,6 +40,8 @@ function App() {
     ssr: false
   });
 
+  client.disableNetworkFetches = false;
+
   const [addPerson] = useMutation(ADD_PERSON, {
     update: (cache, { data: { addPerson: addPersonData } }) => {
       const peopleResult = cache.readQuery({ query: ALL_PEOPLE });

```

Because of this, I wonder whether we need to update the subscription function in our `useSyncExternalStore` instance here:

https://github.com/apollographql/apollo-client/blob/895ddcb546b5692cd53caae1b604412728641374/src/react/hooks/useQuery.ts#L160-L167

I'm not sure exactly how we might do that given that `disableNetworkFetches` is a simple boolean.  That's as far as I've gotten so far.  I hope that helps, I'll see if the rest of the team has any insights at some point.

**Comment by Ellarddekoeijer** [comment]
Thanks for your intricate explanation @bignimbus 

I have applied the disableNetworkFetches workaround to both the reproduction repo and our app (where the problem first occurred), in both cases the query resolved properly and the loading state did not hang. Is there any downside to setting disableNetworkFetches to false at all? I can not seem to find any docs on this topic. 

Thanks again!

**Comment by bignimbus** [comment]
Thanks for the quick reply @Ellarddekoeijer - if you're noticing that manually unsetting `disableNetworkFetches` solves the problem then I'm curious to learn more about this statement from the issue description:

> Due to circumstances outside of our control we are unable to stray away from using ssrForceFetchDelay

The only source code file in Apollo Client that uses `ssrForceFetchDelay` is in the snippets I posted above.  Its sole function is to set `disableNetworkFetches` to `false` after X milliseconds.  So if manually resetting `disableNetworkFetches` is working for you, would that change whether you need to continue using `ssrForceFetchDelay` in your app?
