### ISSUE TITLE
Using the MockedProvider with a client arg seems to break the tests

### ISSUE THREAD

**Issue by ac-onarchipelago** [apollographql/apollo-client#10495]
### Issue Description

At our company we are in a unique position where we have to run two simultaneous Apollo clients, and in the queries where we need the second client, we do something like this:

```
  const { data: projectData, loading: projectLoading } = useQuery(QUERY_NAME, {
    client: secondApolloClient,
    variables: {
      pageSize: 20,
    },
  });
```

and our test mock looks like:
```
const mocks = [
  {
    request: {
      query: QUERY_NAME,
      variables: {
        pageSize: 20,
   },
    },
    result: {
    ....
```

Which was working great, up until we added that `client: secondApolloClient` line, now it keeps returning undefined data and the tests understandably fail. I've attempted to just import the client and change the mock to 

```
const mocks = [
  {
    request: {
      query: QUERY_NAME,
      client: secondApolloClient,
      variables: {
        pageSize: 20,
   },
    },
    result: {
    ....
```

to match what we do, but it doesn't seem that approach is working. What am I missing? Any insight would be much appreciated! 

### Link to Reproduction

https://codesandbox.io/s/github/apollographql/react-apollo-error-template

**Comment by jerelmiller** [comment]
Hey @ac-onarchipelago 👋 !

It looks like the reproduction URL you gave us points to our default error template. Did you mean to replace that with your own reproduction URL?

---

Something to keep in mind with mocks and querying is that the mocks are client-specific. Assuming you're using `MockedProvider` in your test, what I mean by this is [`MockedProvider`](https://github.com/apollographql/apollo-client/blob/main/src/testing/react/MockedProvider.tsx) will [instantiate an `ApolloClient`](https://github.com/apollographql/apollo-client/blob/b4a4bd16a911a233de6ada47780c84512f885401/src/testing/react/MockedProvider.tsx#L45) and pass the [`mocks` to a new `MockLink`](https://github.com/apollographql/apollo-client/blob/b4a4bd16a911a233de6ada47780c84512f885401/src/testing/react/MockedProvider.tsx#L48-L51). 

I see in your example, you're trying to set `client` on the mock itself, but it doesn't work because the `secondApolloClient` doesn't use the same `link` as the `ApolloClient` created from `MockedProvider`. You're going to need to make sure `secondApolloClient`'s link is set to its own `MockLink`, or the same as `MockedProvider`. Here are both of those approaches as an example:

* Use separate mocks for each client:

```ts
const mocks1 = [
  // ...
]
const secondApolloClientMocks = [
  // ...
]

const secondApolloClient = new ApolloClient({
  link: new MockLink(secondApolloClientMocks)
})

<MockedProvider mocks={mocks1}>
  {children}
</MockedProvider>
```

* Use the same `MockLink` for both clients

```ts
const mocks = [
  // ... mocks for both clients
]

const mockLink = new MockLink(mocks)
const secondApolloClient = new ApolloClient({ link: mockLink });

<MockedProvider link={mockLink}>
  {children}
</MockedProvider>
```

Let me know if that helps!

**Comment by trevorglick** [comment]
I have also run into this issue where you have a useQuery that uses the client property(because we have two apollo clients) and then for some reason the MockedProvider just doesn't care about your provided mocks.

The solution @jerelmiller provided did not work.

I thought that the MockedProvider created its own ApolloClient to handle the mocks so why does it care that we provided a "client" property to our useQuery/useMutations.

**Comment by jerelmiller** [comment]
@trevorglick coming back to this months later, I'm realizing that my solution probably doesn't provide enough context on how it solves the original issue. The truth is, I don't exactly know how `secondApolloClient` is imported in the component under test from the issue description. I made some assumptions in my provided solution that might be inadequate with the actual setup. 

My solution using `secondApolloClient` was meant to override whatever was passed to the component using its mocks. It just wasn't obvious that was my intent. My assumption here is that the "first" client was used via React context, which is provided via `<ApolloProvider />` (of which `<MockedProvider />` [relies on](https://github.com/apollographql/apollo-client/blob/8c0e20c2e63c3914c5ef56db1d542970e2b77f39/src/testing/react/MockedProvider.tsx#L64-L66)).

I'm not sure how you've got your component setup or how you get the `client` that you pass to the `client` prop on `useQuery`. There are a couple different options that you can use to make this work. 

- If you're importing the second client from another module, use a jest [module mock](https://jestjs.io/docs/29.4/manual-mocks#mocking-user-modules) to provide an instance of `ApolloClient` that uses the `MockLink` as I've described above. This assumes you're using Jest for your tests.
- Use something like [msw](https://mswjs.io/) or [`fetch-mock`](https://github.com/wheresrhys/fetch-mock) to mock out the actual network request. This allows you to use your real `ApolloClient`, but avoids an actual network call.

If you're willing to provide a more clear picture of your setup, or provide me with a link where I can clone a repo, I can provide more detailed and helpful instructions.

---

FYI, we plan to provide more robust testing utilities sometime in the next minor release or two of the client. We realize `MockedProvider` has its shortcomings. Keep an eye on our [roadmap](https://github.com/apollographql/apollo-client/blob/main/ROADMAP.md) for updates regarding these features.

**Comment by trevorglick** [comment]
ooooooh wow ok that makes a lot of sense. I was totally buying into the notion that MockedProvider created its own ApolloClient instance and it would just use that agnostic of your client. 

Our case is similar to several others that run into this issue, we have two or more clients and when writing tests we want to be able to use MockedProvider and pass in a specific client to it.

So what I started doing is just setting any queries or mutations that use the `client` property as an option, to a ternary that says 
```
const { data, loading, error } = useQuery(GET_CHECKLISTS, {
    client: TEST_MODE ? undefined : ourSecondClient,
    onError: error => {
      message.error(`There was an error retreiving checklist data: ${error.message}`);
    },
  });
```

Then we run tests with the env variable `TEST_MODE=true`.

Which is a workaround that I dislike. I'm sure everyone that uses this MockedProvider would love a way to just pass in a specific client to it.

**Comment by jerelmiller** [comment]
@trevorglick definitely agree that the workaround you presented feels a bit off.

>  I was totally buying into the notion that MockedProvider created its own ApolloClient instance 

This is actually correct. It _does_ [create its own instance of `ApolloClient`](https://github.com/apollographql/apollo-client/blob/fc79f7f04d398fd5c4476fc4e9a58ae950644d62/src/testing/react/MockedProvider.tsx#L47),  but this is provided via React context. Your tests can still override this created client by passing the `client` directly to the hook, as you've done here.

> I'm sure everyone that uses this MockedProvider would love a way to just pass in a specific client to it

Honestly if you need the override, you can just bypass `MockedProvider` altogether in your tests and just use `ApolloProvider` directly. If you have a specific test client and you want to use mocks like you would with `MockedProvider`, just use `MockLink` directly. 

That `MockedProvider` just provides some small out-of-the-box shortcuts, but no reason you couldn't do something like this in your test, which essentially mimics `MockedProvider`:

```tsx
const mockClient = new ApolloClient({
  link: new MockLink(mocks),
  cache: new InMemoryCache()
});

// ...

<ApolloProvider client={mockClient}>
 {/* ... */}
</ApolloProvider>
```

Again, this only works if you rely on `client` being used via React context. 

If you're willing to give a bit more context/code on your full component (sans the JSX) and how `ourSecondClient` is passed to the component/hook, I should be able to provide more detailed and helpful guidance. I think you'd feel more comfortable without that `TEST_MODE ? undefined` in there.

**Comment by jerelmiller** [comment]
To clarify:

> if you're willing to give a bit more context/code on your full component (sans the JSX)

What I mean is:

Is your component setup something like this?

```tsx
function MyComponent({ client }) {
  const { data } = useQuery(QUERY, { client });
}
```

or like this:

```tsx
import secondClient from './path/to/apollo/config';

function MyComponent() {
  const { data } = useQuery(QUERY, { client: secondClient });
}
```

**Comment by trevorglick** [comment]
@jerelmiller when running a test with this code: 

```
const mockClient = new ApolloClient({
  link: new MockLink(mocks),
  cache: new InMemoryCache(),
});

test('full app rendering/navigating', async () => {
  render(
    <ApolloProvider client={mockClient}>
      <MemoryRouter initialEntries={['/homepage']}>
        <App />
      </MemoryRouter>
    </ApolloProvider>
  );
```

I'm running into: 
```
error: ApolloError: Failed to construct 'Request. Invalid URL "about://:undefined/graphql" on document location 'about:blank'. Relative URLs are not permitted on current document location.
```

**Comment by jerelmiller** [comment]
@trevorglick the issue here is that your `<App />` is using `secondClient` via the override, not `mockClient` provided to `<ApolloProvider />`, so its trying to make a real request in your test (in case you're wondering how this works, here is where we prefer the [override](https://github.com/apollographql/apollo-client/blob/fc79f7f04d398fd5c4476fc4e9a58ae950644d62/src/react/hooks/useApolloClient.ts#L10). `useQuery` uses `useApolloClient` [under the hood](https://github.com/apollographql/apollo-client/blob/fc79f7f04d398fd5c4476fc4e9a58ae950644d62/src/react/hooks/useQuery.ts#L49)).

My guess is your `secondClient` is constructed as something similar to this:

```tsx
const httpLink = createHttpLink({
  uri: `http:${process.env.GRAPHQL_URI}`
})

const secondClient = new ApolloClient({
  link: httpLink
})
```

where you're interpolating the endpoint from some environment variable. In your test, this is likely undefined, hence why you're seeing the "invalid URL" error; again because `<App />` is trying to make a real network request via `secondClient`. `mockClient` will only ever be used in components that don't pass a `client` option (i.e. it becomes your "DEFAULT client" as you put it).

As mentioned above, I'd recommend one of two things:

* Use a jest [module mock](https://jestjs.io/docs/29.4/manual-mocks#mocking-user-modules) to provide an instance of ApolloClient that replaces `secondClient` with your `mockClient`.

```tsx
// warning: not tested

jest.mock('utils/secondClient', () => ({
  secondClient: new ApolloClient({ 
    // ...
    link: new MockLink() 
  })
});
```

You'll have to play around with this a bit. You'll find pretty quickly though that you'll need to figure out how to "reset" the `mocks` passed to `MockLink` between tests, which might prove tricky.

* Use something like [msw](https://mswjs.io/) or [fetch-mock](https://github.com/wheresrhys/fetch-mock) to mock out the actual network request. This allows you to use your real `secondClient`, but avoids an actual network call. `HttpLink` uses `fetch` under the hood, so anything that replaces the real `fetch` with a mock version of it would work. You might find this approach to be more straightforward.

---

At this point I think I've provided a good foundation to determine the best testing approach for your setup. Please let me know if anything is unclear, but hopefully this helps!

If you'd like additional help from the community to get ideas on how others have approached this, I'd highly recommend checking out our [Apollo Discord server](https://discord.gg/graphos) to get some ideas from the community. Thanks!

**Comment by trevorglick** [comment]
Thanks, you have helped tremendously. There are a couple other opened cases about this same thing in the issues section. Appreciate your responses.

**Comment by jerelmiller** [comment]
@trevorglick you're welcome! I definitely can't wait until we get some more robust testing utilities in place. I think this will ease this pain much much more. We'll make sure to keep this use case in mind.

**Comment by trevorglick** [comment]
Also I know this is closed but just incase anyone finds this and is using jest or vitest to mock this is what finally worked for me!

```
import { render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { MockLink } from '@apollo/client/testing';
import { ApolloClient, InMemoryCache } from '@apollo/client';
import { vi } from 'vitest';

import App from './App';

vi.mock('utils/secondClient', async () => {
  const actual = await vi.importActual<typeof import('utils/secondClient')>('utils/secondClient');
  const mocks = await vi.importActual<typeof import('App.mocks')>('App.mocks');

  return {
    ...actual,
    secondClient: new ApolloClient({
      link: new MockLink(mocks.checklistMocks),
      cache: new InMemoryCache(),
    }),
  };
});

test('full app rendering/navigating', async () => {
  const { getByText } = render(
    <MemoryRouter initialEntries={['/homepage']}>
      <App />
    </MemoryRouter>
  );

  await waitFor(() => {
    expect(getByText(/daily checks/i)).toBeInTheDocument();
  });
});

```

Inside of App.mocks is my import of my graphql query, and my mocks array that includes 
[
  {
    request: { query: GET_CHECKLISTS }, 
    result: {
      data: {
        checklists: [...checklistData]
   }
]

Without using  `const mocks = await vi.importActual<typeof import('App.mocks')>('App.mocks');`

I was getting errors about not having access to the exported mocks object from App.mocks because of this error
```
Error: [vitest] There was an error when mocking a module. If you are using "vi.mock" factory, make sure there are no top level variables inside, since this call is hoisted to top of the file. Read more: https://vitest.dev/api/vi.html#vi-mock
```
