### ISSUE TITLE
Allow to use `useSuspenseQuery` without wrapping it in `ApolloProvider`

### ISSUE THREAD

**Issue by patrick91** [apollographql/apollo-client#10503]
Hi there! I was testing `useSuspenseQuery` in a Next.js demo app using the new app directory. 

## Context

Pages inside Next.js' app directory are Server Components by default, this means you can't use things like `useContext`, `useState`, etc. (You have to use "use client" for those to work).

I think our recommendation would be to use `await client.query` inside Server Components for data fetching, which makes a lot of sense, but there are cases where people might mix and match Server Components and Client Components. This is especially true with mutations (since those should run only on the client based on user interaction).

For client queries and mutations I've been doing something like this:

```tsx
"use client";

import { client } from "@/lib/apollo";

const Component = () => {
  const [mutate, {loading}] = useMutation(DOC, { client });

  ...
}
```

this works pretty well and allows you to not have to wrap your app or individual components with `ApolloProvider`

## Issue with `useSuspenseQuery`

`useSuspenseQuery` is very similar to `useMutation` and `useQuery`, but it also needs a new property, `suspenseCache`, at the moment it doesn't seem you can pass this without using the `ApolloProvider`, this is the error I get if I try to use `useSuspenseQuery` without a provider in Next.js:

<img width="817" alt="image" src="https://user-images.githubusercontent.com/667029/216395795-02752006-04b7-417f-a119-d46baa1fb49c.png">

**Comment by jerelmiller** [comment]
Finished in https://github.com/apollographql/apollo-client/issues/10503

**Comment by TimurKr** [comment]
I am having issue with using the suspenseCache option. I am using the next.js experimental app directory, which rules out using ApolloProvider, so I am trying to use the client and the suspenseCache options of the useSuspenseQuery. The issue is, that the page stays in the suspense state indefinitely. 

Here is the component:
```
export default function Search() {

  const client = getClient();
  const suspenseCache = new SuspenseCache();
  const { data } = useSuspenseQuery(ingredientsQuery, {
    client,
    suspenseCache,
  });

  return (
    <div className="h-full w-full">
      loaded
    </div>
  );
```

And this is how I am using it: 
```
<Suspense fallback={<Loading />}>
  <Search />
</Suspense>
```

I am not sure if I am doing something wrong, or if this is worth a separate issue. 

Thanks for any tips

**Comment by phryneas** [comment]
You are creating your SuspenseCache within your component - that means that every time this component tries to run, it creates a new, empty suspense cache.  
That way, you will never resolve, because every time the component will think "I haven't made a request yet" and will start yet another request.

**Comment by TimurKr** [comment]
@phryneas Thanks for the fast response, so simply moving the 
```
const suspenseCache = new SuspenseCache();
```
 ouside of the function will solve this? Or should the 'suspenseCache' object be passed down by props from the parent?

**Comment by phryneas** [comment]
As you are working with client components within a server-rendered tree, that should work. Just be aware that this should not be done server-side.
