### ISSUE TITLE
modified in flight query not reflecting modification

### ISSUE THREAD

**Issue by dontsave** [apollographql/apollo-client#10530]
hi. i wasn't sure if this was expected behavior or not, so i figured i'd ask:

we have a fairly slow query that takes a few seconds to return. during this time we want to write a modification to a normalized entity referenced by the query. we've noticed that the modification broadcasts a change and rerenders the component consuming the query only in the event the query is not in flight. when the query _is_ in flight, no broadcast seems to happen and nothing rerenders until the query returns. is this expected?

we're on Apollo client 3.7.4. thanks!

**Comment by bignimbus** [comment]
Hi @dontsave 👋🏻  can you share some more information?  The `fetchPolicy` and `notifyOnNetworkStatusChange` values will be relevant here.  A runnable reproduction would really help address your question in concrete terms.  Happy to offer a second set of eyes!

To start with, you might try setting `notifyOnNetworkStatusChange` to `true` to see if that does enough for you.  Our new `useFragment_experimental` hook may also be of interest since it doesn't concern itself with network status at all.

Here's a source code snippet that may be instructive as well, if that helps:

https://github.com/apollographql/apollo-client/blob/1d13de4f190150e96d61a9e987274ee6c249dbef/src/core/QueryInfo.ts#L268-L283

**Comment by dontsave** [comment]
@bignimbus ah thanks for the quick response. it was indeed the `fetch-policy` bailing out of the modification. it was the default `cache-first`. changing to `cache-and-network` allowed the query to rerender with the modified entity, then the fetch overwrote the modification upon returning, as expected. 

this wasn't very intuitive behavior however. what's the rationale for `cache-first` bailing out but not `cache-and-network`?

**Comment by bignimbus** [comment]
@dontsave I went deep into the commit history for this one - it turns out this behavior was introduced with the introduction of the fetch policy feature nearly six years ago!  Here's the PR where this logic was introduced: https://github.com/apollographql/apollo-client/pull/1371/files#diff-5fb8ad16cfbcb51bc035d32b5963734561c440b48417a1c2dbf80a16098be67bR348-R349

None of the folks in that PR are actively involved with Apollo Client nowadays so your guess is as good as mine as to what the rationale might have been at the time.  FWIW, my guess is that the `cache-and-network` policy guarantees a network call so the result of the operation is technically not known until the fetch completes and the cache is updated.  So anything depending on data potentially being updated by that fetch operation should not receive updates until completion.  In contrast, `cache-first` can resolve without a network call so there's a different assumption of what constitutes the "correct" data.  Again, just my two cents.  Let us know if you need more support here!
