### ISSUE TITLE
react-native - Network request failed only on android NOT LOCALHOST

### ISSUE THREAD

**Issue by MelMayssonOwen** [apollographql/apollo-client#10562]
Did anyone solve this?

Getting the same error, only on android. I'm not using a local server.
I've set ```android:usesCleartextTraffic="true"``` in the manifest (app/src/main).
The ssl certificate are good.
Tried setting ```@xml/network_security_config``` with corresponding file.

And it works fine on IOS
using Apollo/client version : 3.7.6

If I do the same request with Axios it works
```javascript
import {print} from 'graphql';

  const onSubmit = async ({email, password}) => {
    try {
      const res = await axios.post(`${baseUrl}/graphql`, {
        query: print(LOGIN_MUTATION),
        variables: {
          email,
          password,
        },
      });
      console.log('🚀 ~ file: SignIn.tsx:86 ~ res', res);
    } catch (error) {
      console.log('🚀 ~ file: SignIn.tsx:90 ~ error', error);
    }
  };
```

this doesn't

```javascript
    const [signIn] = useMutation(LOGIN_MUTATION);

    const onSubmit = async ({email, password}) => {
      const res = await signIn({
        variables: {email, password},
      });
      console.log('🚀 ~ file: SignIn.tsx:86 ~ res', res);
    };
```

The only error I'm getting is ```Network request failed```

I found this comment in an old issue that have been closed a while ago. It seems to be the same

          I am getting the same error. My queries work in iOS but give me a network request failed error in Android. Some other solutions suggested that I shouldn't be using ```localhost``` for my ```uri``` and should use my computer's IP address. But I am already not using localhost. 
```
const httpLink = createHttpLink({
    uri: 'https://gateway_dev.companyName.en/v1/graphql',
  });

  const authLink = setContext(async (_, { headers }) => {
    const token = await auth().currentUser?.getIdToken();
    return {
      headers: {
        ...headers,
        authorization: token ? `Bearer ${token}` : '',
      },
    };
  });

  const client = new ApolloClient({
    link: authLink.concat(httpLink),
    cache: new InMemoryCache({}),
  });

  return (
    <Provider store={store}>
        <ApolloProvider client={client}>
...
```
The uri I am using is the Graphql Endpoint POST url from my Hasura console. I am testing by using an Android emulator from the Android Studio and not on a real device. What else could I try?

I also tried adding this ```android:usesCleartextTraffic="true"``` to **AndroidManifest.xml** file but it doesn't make a difference.

_Originally posted by @johnneuland in https://github.com/apollographql/apollo-client/issues/4740#issuecomment-704208872_

**Comment by jerelmiller** [comment]
Hey @MelMayssonOwen 👋 

I'll be honest, I'm a bit unfamiliar with Android development, so I'll try and give some pointers that might help you narrow down the issue you're seeing.

This is definitely a bit odd. Just to make sure, do you have the [internet permission](https://developer.android.com/training/basics/network-ops/connecting) declared in your manifest? Given the fact that your axios call works, I'm inclined to say it is, but figured I'd check.

Under the hood, `HttpLink` uses plain [`fetch`](https://github.com/apollographql/apollo-client/blob/1f9ec12ca0370697ee9a698090bcdc21f8db42d0/src/link/http/createHttpLink.ts#L26) to execute the network request. Looking through the axios source code, it looks like it either uses [XMLHTTPRequest](https://github.com/axios/axios/blob/v1.x/lib/adapters/xhr.js) or [Node's `http`](https://github.com/axios/axios/blob/v1.x/lib/adapters/http.js) library, depending on which is available in the environment.

This might be a good starting place. Check to make sure `fetch` is available inside your environment. Here is the request `HttpLink` is making under-the-hood, including its [default headers](https://github.com/apollographql/apollo-client/blob/1f9ec12ca0370697ee9a698090bcdc21f8db42d0/src/link/http/selectHttpOptionsAndBody.ts#L105-L121). Try executing this yourself.

```ts
import { print } from 'graphql';

fetch('https://gateway_dev.companyName.en/v1/graphql', {
  method: 'POST',
  headers: {
    accept: '*/*',
    'content-type': 'application/json'
  },
  body: JSON.stringify({ 
    query: print(LOGIN_MUTATION),
    variables: { email, password },
    operationName: 'LoginMutation'  // assuming LOGIN_MUTATION sets the operation name to this
  })
})
  .then(res => res.json())
  .then(res => console.log(res))
```

If you're seeing the same error as before, that means we can eliminate other areas of Apollo Client itself being the culprit here, so we should be able to focus on getting your `fetch` configuration dialed in. I'd move to check the headers you're sending. 

I believe axios might add some default headers, depending on your request, so you'll need to mimic those. I haven't followed axios for quite some time, so you might have a better understanding of the headers it sets out-of-the-box. Try updating the headers using the snippet above until you're able to get a successful response. You can then pass these options to [`fetchOptions`](https://www.apollographql.com/docs/react/api/link/apollo-link-http#fetchoptions-1) or [`headers`](https://www.apollographql.com/docs/react/api/link/apollo-link-http#headers-1) depending on the configuration that works for you.

If all else fails, you can always use axios to execute your request by [overridding the `fetch` function](https://www.apollographql.com/docs/react/api/link/apollo-link-http#customizing-fetch).

```ts
createHttpLink({
  uri: 'https://gateway_dev.companyName.en/v1/graphql',
  fetch: (uri, options) => {
    const { query, operationName, variables } = JSON.parse(options.body);

    return axios.post(uri, { query, operationName, variables })
  }
})
```

**Comment by jerelmiller** [comment]
Something I missed in my previous post that _could_ be important. I see you're setting the `authorization` header in your request via Apollo, but its missing in your axios request. That could also be something to check in case your server is rejecting one but allowing the other.

**Comment by MelMayssonOwen** [comment]
Hello @jerelmiller, 

Thank you so much, you've made me realise two silly mistakes I've done.
So first of all, you're right. Axios was adding quite a few headers that wasn't in the Apollo query.

Secondly for anyone stumbling on this issue, I had a problem with my environment variable that acted differently on android for some reason. And assumed it wasn't an issue because of the error message I was getting.

Thanks again, just spent the day on this one thing.

**Comment by jerelmiller** [comment]
In all of my software engineering career so far, I've always found its the smallest of things that end up sucking most of my time away 😂 . I remember spending 3 hours on an issue because I overlooked a typo where two letters were swapped in a word 😬 . Seems it never gets better no matter how long you're writing software.

Anyways, have a great day! Glad to hear you've discovered the issue!

**Comment by MelMayssonOwen** [comment]
It really is like that...

Have a great day too wherever you are! Thanks again

**Comment by martinbonnin** [comment]
> Seems it never gets better no matter how long you're writing software.

I think it only gets worse because you tend to overlook the simple things and then when you're realize, you're like: oh noooooooo 😓
