### ISSUE TITLE
flyby-gateway.herokuapp.com gives Application error

### ISSUE THREAD

**Issue by aleksandr-vin** [apollographql/apollo-client#10571]
### Issue Description

[React get started page](https://www.apollographql.com/docs/react/get-started/) ([source](https://github.com/apollographql/apollo-client/blob/main/docs/source/get-started.mdx)) has a link [FlyBy GraphQL API](https://flyby-gateway.herokuapp.com/) that gives Application error from heroku

### Link to Reproduction

https://www.apollographql.com/docs/react/get-started/

### Reproduction Steps

1. Open the get started page
2. Follow the link in section:
    > Our example application will use the [FlyBy GraphQL API](https://flyby-gateway.herokuapp.com/) from Apollo Odyssey's [Voyage tutorial series](https://www.apollographql.com/tutorials/voyage-part1/)

**Comment by alessbell** [comment]
Hi @aleksandr-vin 👋 Thanks for opening this issue: it appears our docs had fallen out of date, apologies about that!

The correct URL for the FlyBy GraphQL API is https://flyby-router-demo.herokuapp.com/. The docs are redeploying as we speak so that change will be reflected shortly, and please let us know if you run into any other issues. Thanks!
