### ISSUE TITLE
'cache-and-network' fetch policy is redundant in V3?

### ISSUE THREAD

**Issue by wrgoto** [apollographql/apollo-client#10593]
Because V3 changed the behavior of `data` returning `undefined` when fetching, that means there's no difference between `cache-and-network` and `network-only` policies. Both return `undefined` for `data` during the network request, is that correct?

The purpose of `cache-and-network` was to load the cached results to provide a near instantaneous result. It doesn't work that way now and requires the use of something like `data ?? previousData` to work.

**Comment by jerelmiller** [comment]
Hey @wrgoto 👋 

Not quite, they are still distinct. `cache-and-network` will attempt to read data from the cache while also executing a network request in the background. The cached response however _requires data in the cache_ in order to provide the instantaneous response. If the cached data is not there, or its incomplete, `data` is returned as `undefined`, hence why you still need to handle this case.

`network-only` won't even attempt to read from the cache and will just issue the network request.

Hope that helps!
