### ISSUE TITLE
React 18 with Apollo v2

### ISSUE THREAD

**Issue by chasewestover** [apollographql/apollo-client#10618]
I saw [this open question](https://community.apollographql.com/t/apollo-client-version-2-still-compatible-with-react-18/3473) but hasn't been answered yet

Thoughts/context on running Apollo v2 with React 18? I'm unable to upgrade `@apollo/client` to 3.x.x at the moment so I have to make do with `react-apollo` components. I have checked and all the components have [explicitly typed children (which is the most obvious breaking change)](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-typescript-definitions), but I'm somewhat concerned about altered behavior [automatic batching](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#automatic-batching) and other changes I might be missing. Would appreciate any thoughts, thanks!

**Comment by phryneas** [comment]
The last release of Apollo Client 2 was in May 2020, so long before even React 17 was a release candidate.

React has generally been very backward-compatible, but you are right that there have been subtle changes that might have some impact. 

I fear that, at this point, your best bet is trying it out - I don't think that we have done a lot of experimentation with Apollo-Client 2 and React 18, since there has just been so much time between these releases and most users that stay on one of those old packages also don't upgrade the other. You are pretty much in uncharted territory here.

Is there anything, in particular, blocking you from upgrading Apollo Client?

**Comment by chasewestover** [comment]
Gotcha, that was about what I expected. I work on a pretty big codebase and we have downstream apps that we pass our Apollo instance to so that is one reason, and then the other is that we have a very long-term plan to migrate to relay and our architects don't want to throw resources behind a library that we plan to eventually phase out.

Thank you Lenz, I really appreciate the response!

**Comment by jerelmiller** [comment]
@chasewestover no obligation to answer, but if you'd be willing to help us out, we'd be curious why you/your architects are looking to migrate to Relay.

We're always looking for ways to improve the library, so if there is any feedback you'd be willing to share, that would be super helpful. Again, no obligation to answer. Thanks!
