### ISSUE TITLE
Is there any way to use extends for fragments on client

### ISSUE THREAD

**Issue by michael-vasyliv** [apollographql/apollo-client#10628]
Let's imagine we have a base projection on **server**
```
// some code on java ...
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
@Data
@GraphQLType(name = "BaseProjection")
public class BaseProjection implements IBaseProjection {

    private UUID id;
    private String name;
    private DateTime createdOn;

    /** here are a lot of other fields */

    public BaseProjection(BaseProjectionDto dto) {
        this.id = dto.getId();
        this.name = dto.getName();
        this.createdOn = dto.getCreatedOn();
    }

}

@Data
@SuperBuilder
@NoArgsConstructor
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = true)
@GraphQLType(name = "AnswerProjection")
public class AnswerProjection extends BaseProjection {

    private String answer;

    /** here are a lot of other fields */

    public AnswerProjection(AnswerProjectionDto dto) {
        super(dto);
        this.answer = dto.getAnswer();
    }
}


@Data
@SuperBuilder
@NoArgsConstructor
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = true)
@GraphQLType(name = "QuestionProjection")
public class QuestionProjection extends BaseProjection {

    private String question;

    /** here are a lot of other fields */

    public QuestionProjection(QuestionProjectionDto dto) {
        super(dto);
        this.question = dto.getQuestion();
    }
}
```

as result, we have next query for **client**
```
query FetchAnyDataWithBaseProjection($params: ParamsInput) {
	fetchAnyDataWithBaseProjection(params: $params) {
		...on QuestionProjection {
			question

			id
			name
			createdOn
			/** ... here are a lot of other fields */
		}
		...on AnswerProjection {
			answer

			id
			name
			createdOn
			/** ... here are a lot of other fields */
		}
	}
}
```
The question is - is there any way to create a fragment on `BaseProjection` and use it inside `QuestionProjection` because `QuestionProjection` extends from `BaseProjection`?

what I want will look like this
```
fragment BaseFragment on BaseProjection {
    id
    name
    createdOn
    /** ... here are a lot of other fields */
}
query FetchAnyDataWithBaseProjection($params: ParamsInput) {
	fetchAnyDataWithBaseProjection(params: $params) {
		...on QuestionProjection {
			question
			...BaseFragment
		}
		...on AnswerProjection {
			answer
			...BaseFragment
		}
	}
}
```
The reason for this is getting rid of duplicated fields which are based in BaseFragment

**Comment by jerelmiller** [comment]
Hey @michael-vasyliv 👋 

I'm not super familiar with the way GraphQL Java implements schemas, but does that server code generate a GraphQL [interface type](https://graphql.org/learn/schema/#interfaces) for `BaseProjection`? I assume so, but just wanted to check because that GraphQL query would otherwise be invalid :)

To work with unions and interfaces in Apollo Client, check out [this doc](https://www.apollographql.com/docs/react/data/fragments/#using-fragments-with-unions-and-interfaces) for gives some great information on how to use them! The most important part is ensuring you have `possibleTypes` defined, otherwise you'll find some issues interacting with the cache. This might look something like this:

```ts
const cache = new InMemoryCache({
  possibleTypes: {
    BaseProjection: ['QuestionProjection', 'AnswerProjection'],
  }
});
```

Check out that [doc](https://www.apollographql.com/docs/react/data/fragments/#using-fragments-with-unions-and-interfaces) if you want to be able to generate these types a bit more automatically (in case your app defines many interfaces/subtypes).

---

One small note about your GraphQL query above: since `BaseProjection` is an interface type, you can move the fragment "up" a level since that interface for the fragment would guarantee all fields are defined for each subtype. This can be nice if you have lots of subtypes on that interface since you won't need to include that fragment on each one.

```graphql
fragment BaseFragment on BaseProjection {
  id
  name
  createdOn
  # a lot of other fields
}

query FetchAnyDataWithBaseProjection($params: ParamsInput) {
  fetchAnyDataWithBaseProjection(params: $params) {
    ...BaseFragment # <-- This can be moved here to avoid needing to define it for each subtype

    ...on QuestionProjection {
      question
    }
    ...on AnswerProjection {
      answer
    }
  }
}
```

Hope this helps!

**Comment by michael-vasyliv** [comment]
@jerelmiller thanks a lot
