### ISSUE TITLE
`loading` for useQuery is not set to true for fetch-policy: cache-first

### ISSUE THREAD

**Issue by Ewall198** [apollographql/apollo-client#10677]
### Issue Description

Expected: When refetching a query, `loading` will be set to true while the query is in flight.
Actual: if the query has rule `cache-first`, `loading` is not set to true for refetches.

### Link to Reproduction

https://codesandbox.io/s/relaxed-black-zkwveo

**Comment by jerelmiller** [comment]
Hey @Ewall198 👋 

I see in your reproduction that you're using `client.refetchQueries(...)` to refetch the data. Is this intentional to demonstrate the issue? Or are you specifically looking to be able to refetch the query and show the loading state?

If the latter, there are two changes that you'll need to make to get the behavior that you desire.

1. Use the `refetch` function returned from `useQuery`.

```ts
const { data, loading, refetch } = useQuery(...)

useEffect(() => {
  setTimeout(() => {
    refetch();
  }, 1000);
}, []);
```

2. Set `notifyOnNetworkStatusChange` to `true` in the `useQuery` options. Without this, the query will only rerender when the query is fetched. By adding this property, it will rerender when kicking off the query as well.

```tsx
const { data, loading, refetch } = useQuery(query, { notifyOnNetworkStatusChange: true });
```

I've forked your codesandbox and made these changes. You'll see the behavior you're looking for here: https://codesandbox.io/s/lucid-austin-9mnix5

Let me know if this helps!
