### ISSUE TITLE
useQuery is not updating polling value

### ISSUE THREAD

**Issue by sven-ahrens** [apollographql/apollo-client#10692]
Hey,

## Problem

I'm using [Polling](https://www.apollographql.com/docs/react/data/queries/#polling) to check a state. If the state has been changed, apollo can stop the polling.

This works fine. The actual problem is, that I wanted to increase the number from 500 to 5000 because in my case 0.5 seconds is just too fast.

I did update it, but it's still requesting each 0.5 seconds and I don't know how to fix it. It must be a cache issue somehow because when I use a different config setup (changing the variables) then Apollo uses the new numbers instead. If I change it back, it's still using the 500.

## System

I'm using

ApolloClient 3.7.10
GraphQL 16.5.0
Next.js: 12.3.0
React.js: 18.2.0

## Example

```
  const [hasPendingOrder, setHasPendingOrder] = useState(false)
  const { startPolling, stopPolling } = useQuery(GET_ORDERS, {
    variables: {
      first: 1,
      page: 1
    },
    onCompleted: (data) => {
      if (data && data.orders.data.length > 0) {
        setHasPendingOrder(true)
      }

      if (data && data.orders.data.length === 0) {
        setHasPendingOrder(false)
      }
    }
  })

  // When we leave the page, stop polling
  useEffect(() => {
    return () => {
      stopPolling()
    }
  }, [])

  // Start polling when we have a pending order or stop polling when we don't
  useEffect(() => {
    if (hasPendingOrder) {
      startPolling(5000)
    } else { stopPolling() }
  }, [hasPendingOrder])
```

So because I started that exact query with 500ms at first, it now keeps that value and doesn't change it, even when I use ``startPolling(5000)``

For my Next.js Page I'm using ``getServerSideProps`` to render the page.

## Proof / Video

https://user-images.githubusercontent.com/18313443/228498646-6d376002-5e6b-41bd-b0f3-18e912f7b0d1.mov

## Client Setup

```
  return new ApolloClient({
    link: from([
      setContext((_, { headers }) => {
        return {
          headers: {
            ...headers,
            authorization: token ? `Bearer ${token}` : '',
            'Accept-Language': locale
          }
        }
      }),
      createUploadLink({ uri: process.env.NEXT_PUBLIC_GRAPHQL_URL })
    ]),
    cache: new InMemoryCache()
  })
```

**Comment by alessbell** [comment]
Hi @sven-ahrens 👋

> The actual problem is, that I wanted to increase the number from 500 to 5000 because in my case 0.5 seconds is just too fast.

It sounds like you're referring to the default of `500ms` here, since I see you're not passing an initial `pollInterval` via your `useQuery` options. This doesn't seem like it should matter, however, since:

1. without `options.pollInterval` you aren't polling immediately after your component mounts, and
2. if you call `data.startPolling` when your query is already polling then the current polling process will be cancelled and a new process will be started with the interval you specified.

So, with the usual caveat of 'I may be missing something since I can't run your code', it seems what you have should work :) I've made my own reproduction in a CodeSandbox [here](https://codesandbox.io/s/modest-rhodes-ls983n?file=/src/index.jsx) that shows a component dynamically polling at a 5000ms interval: https://codesandbox.io/s/modest-rhodes-ls983n?file=/src/index.jsx

With a runnable reproduction, I can help investigate further, but I'm hoping that sandbox helps you identify the problem. Let me know if it helps!
