### ISSUE TITLE
cannot use with Expo (React Native), throws undefined for InMemoryCache

### ISSUE THREAD

**Issue by zdnk** [apollographql/apollo-client#10719]
### Issue Description

Hello,

I am unable to use Apollo Client in Expo application. Whatever I am trying it says some functions or classes are undefined.
![IMG_585A67E75881-1](https://user-images.githubusercontent.com/2551911/229776150-bf7977bf-45fd-47c0-b883-fbb5da3e9de8.jpeg)

### Link to Reproduction

https://snack.expo.dev/@zdnk/grounded-ramen

### Reproduction Steps

install @apollo/client in Expo app
try to instantiate ApolloClient with InMemoryCache

**Comment by alessbell** [comment]
Hi @zdnk 👋 

It looks like the metro bundler needs additional configuration in order to _implicitly_ resolve files with the `.cjs` extension (see https://github.com/facebook/metro/issues/535#issuecomment-1198071838).

You can change your import statement to `import { ApolloClient, InMemoryCache } from '@apollo/client/main.cjs';`, or you can configure `config.resolver.sourceExts` in `metro.config.js` so that `import { ApolloClient, InMemoryCache } from '@apollo/client';` can be resolved.

After npm installing `@expo/metro-config`, I was able to get the `grounded-ramen` app running with the following config:

```js
const { getDefaultConfig } = require('@expo/metro-config');

const config = getDefaultConfig(__dirname);

config.resolver.sourceExts.push(
  'cjs'
);

module.exports = config;
```

Hope that helps! Happy hacking :)
