### ISSUE TITLE
What is the better way to handle conditional `useQuery` calls?

### ISSUE THREAD

**Issue by valerii15298** [apollographql/apollo-client#10791]
We have this query with according types:
```tsx
const GET_ITEM = gql`
  query GetItem($itemId: Int!) {
    item(where: { itemId: $itemId }) {
      name
    }
  }
`;
type TQuery = { item: string };
type TVariables = { itemId: number };
```

What is the better approach to fetch our item conditionally in the component?
First option:
```tsx
function Item({ itemId }: { itemId: number | undefined }) {
  const { data } = useQuery<TQuery, TVariables>(GET_ITEM, {
    variables: { itemId: itemId! },
    skip: !itemId,
  });

  return <>{data?.item}</>;
}
```

Second option:
```tsx
function Item({ itemId }: { itemId: number | undefined }) {
  const [fetchItem, { data }] = useLazyQuery<TQuery, TVariables>(GET_ITEM);

  useEffect(() => {
    if (itemId) {
      fetchItem({ variables: { itemId } });
    }
  }, [itemId, fetchItem]);

  return <>{data?.item}</>;
}
```

Which approach is correct/better and why?

**Comment by dylanwulf** [comment]
Just my opinion, but I'd say they're both correct. In my app I have something pretty close to your first example:
```
variables: { itemId: itemId ?? '' },
skip: !itemId,
```

**Comment by jerelmiller** [comment]
Hey @valerii15298 👋 

As an FYI, these types of question are more suitable for our [discord server](https://discord.gg/graphos) or [community forums](https://community.apollographql.com). These are great ways to get input from community members as well. Generally we try and limit our issues to bugs and feature requests when possible.

---

That being said, I wouldn't necessarily say one is more "correct" or "better". Each of these have different tradeoffs that may better suite your use cases in different situations. 

Here is my take on the tradeoff of each these options.

Option 1:
```tsx
function Item({ itemId }: { itemId: number | undefined }) {
  const { data } = useQuery<TQuery, TVariables>(GET_ITEM, {
    variables: { itemId: itemId! },
    skip: !itemId,
  });

  return <>{data?.item}</>;
}
```

One of the advantages of this API is that it feels simpler. Notice how much less code you have to use to get this to work, simply because `useQuery` is reactive to its inputs. `useLazyQuery` _requires_ you to interact with its execute function in order to work, so you need some additional code to ensure the fetch kicks off.

On the flip-side, this one feels a bit weird because you essentially have to lie to TypeScript to get this to work. You've specified simultaneously that `itemId` is both `number | undefined`, yet its also non-null (`itemId!`). This definitely raises some red flags. While this is small in scope, working with TypeScript in this manner can lead to odd bugs if you're not careful.

Option 2:

```tsx
function Item({ itemId }: { itemId: number | undefined }) {
  const [fetchItem, { data }] = useLazyQuery<TQuery, TVariables>(GET_ITEM);

  useEffect(() => {
    if (itemId) {
      fetchItem({ variables: { itemId } });
    }
  }, [itemId, fetchItem]);

  return <>{data?.item}</>;
}
```

The big advantage right away is that all of your types line up. You're no longer stuck with trying to lie to TypeScript just to be able to use this hook.

On the flip-side, you're now tasked with having to manage the lifecycle of fetches. `useQuery` is built to react to props changes and refetch when necessary. Here if `itemId` changes, you're going to need manage when to refetch that data with the new `itemId`. Thankfully your setup via `useEffect` will handle this nicely so you don't have to think of this too much, but it is something to note (hence why this feels more complicated than `useQuery`).

If I were in your shoes and I absolutely had to pick one vs the other, I would go with option 2 because the TypeScript mismatch is too weird to me.

---

I want to present you with a third option though. Consider your app in this state:

```tsx
<Item itemId={undefined} />
```

To me, this is like saying you're trying to render an item that isn't even defined yet (i.e. its "undefined"). Does this even make sense when thinking of it in these terms? I'd go so far as to describe this as an impossible state.

Instead, you might consider conditionally rendering `Item` itself.

```tsx
function Parent() {
  const [itemId, setItemId] = useState<number>();
  
  return (
    <>
      <button onClick={() => setItemId(1)}>Fetch item 1</button>
      {itemId && <Item itemId={itemId} />}
    </>
  );
}

function Item({ itemId }: { itemId: number }) {
  const { data } = useQuery(GET_ITEM, { variables: { itemId }});

  // ...other loading/error handling here

  return <>{data?.item}</>
}
```

Because you've moved the conditional to the component level, you're able to leverage the simpler `useQuery`, this time without the `skip` option.

I find this also keeps `Item` clean since it better follows [SRP](https://en.wikipedia.org/wiki/Single-responsibility_principle). It only has to focus on rendering an `Item` and never placeholder state when its `id` is undefined.

If you find yourself needing to display some placeholder UI when you don't yet have an `itemId`, consider creating a separate component for this:

```tsx
function PlaceholderItem() {
  return <div>...</div>
}

function Parent() {
  // ...
  
  if (!itemId) {
    return <PlaceholderItem />
  }

  return <Item itemId={itemId} />;
}
```

I find this to be more predicable and readable. The placeholder UI is no longer entangled with `Item` and you can scale these components independently of each other.

Hope this helps!

**Comment by valerii15298** [comment]
@jerelmiller thank you very much for such a detailed answer!!!
We use mui Dialog which should be mounted always in order for Transition to work properly that is why we didn't pick idea to conditionally render component itself.

Also I rethought the first approach to use it like this:
```tsx
function Item({ itemId }: { itemId: number | undefined }) {
  const { data } = useQuery<TQuery, TVariables>(GET_ITEM, {
    variables: { itemId: itemId ?? 0 },
    skip: itemId === undefined,
  });

  return <>{data?.item}</>;
}
```
In this case it is almost the same(except we don't use `!`). Can you please give any comments if this approach seems better or you would choose the second one anyway? Thanks!

And about using placeholder component, that is interesting way, though in such case we lose previous data(before mui Dialog starts transition to close it clears old data and shows placeholder.

**Comment by jerelmiller** [comment]
> We use mui Dialog which should be mounted always in order for Transition to work properly

This is super helpful! I wasn't sure how you were using `Item`, but this requirement makes sense. 

I find your updated example to be much more reasonable personally. If for whatever reason you did have bugs, I find the errors much easier to reason about and track down (e.g. "item with ID 0 doesn't exist" vs "item id cannot be null". Hopefully this makes sense 🙂)

One last question: Are you clearing `itemId` in the `onClose` handler somehow? I have no idea how you set `itemId` to begin with, how you trigger the open state of the dialog, or what other components depend on `itemId`, but another idea would be to actually hang on to `itemId` as long as possible. This would mean that your dialog would render an `Item` in its closed state. As long as `itemId` changes before the dialog is opened the next time, I think you can get the same UX you're after.

```tsx
function MyComponent() {
  const [open, setOpen] = useState(false)
  const [itemId, setItemId] = useState<number>()

  return (
    <>
      <button 
        onClick={() => {
          setItemId(1);
          setOpen(true);
        }
      >
        Open item 1
      </button>
      
      <Dialog 
        open={open} 
        onClose={() => {
          // important.. don't clear `itemId`
          setOpen(false);
        }
      >
        {/* Now when this is closed, it will render the "old" item until changed */}
        {itemId && <Item itemId={itemId} />}
      </Dialog>
  );
}
```

This may introduce additional complexities you might not want to deal with, but figured I'd point it out as an option if you like the "purity" of `<Item itemId={number} />` vs `<Item itemId={undefined} />`. Food for thought! Such is the fun of software development. Everything has a tradeoff and you have to find the one that works best for you 🙂.

---

Too bad mui dialog doesn't have some kind of `onHidden` callback that allows you to handle when the dialog is actually closed (at least I couldn't find it in the [docs](https://mui.com/material-ui/api/dialog/)). This would likely help your last point about the transition from open to close and not showing placeholder content.

**Comment by dylanwulf** [comment]
> Too bad mui dialog doesn't have some kind of onHidden callback that allows you to handle when the dialog is actually closed (at least I couldn't find it in the [docs](https://mui.com/material-ui/api/dialog/)). This would likely help your last point about the transition from open to close and not showing placeholder content.

It's not very obvious in the docs but MUI actually uses react-transition-group for default transitions, which has an [onExited callback](https://reactcommunity.org/react-transition-group/css-transition#CSSTransition-prop-onExited) that works exactly like you're describing. It can be specified in the Dialog component's `TransitionProps` prop.

```jsx
<Dialog TransitionProps={{ onExited: () => console.log('Dialog is done exiting!') }}>
  <div>dialog contents</div>
</Dialog>
```

**Comment by jerelmiller** [comment]
> MUI actually uses react-transition-group for default transitions, which has an [onExited callback](https://reactcommunity.org/react-transition-group/css-transition#CSSTransition-prop-onExited)

TIL. Thanks for that info @dylanwulf! I haven't used MUI much myself, so I don't know the API super well.

**Comment by valerii15298** [comment]
@jerelmiller 🚀 your last example is super helpful. No other components depend on `itemId`. Introducing additional open, setOpen state makes sense. Combining with onExited property from @dylanwulf answer it is basically perfect(I will clear itemId when transition finishes). I will definitely use additional open, setOpen state and onExited property. Thank you very much guys!!!

One last question just out of curiosity, to clarify, what would you prefer to use @jerelmiller (imagine if you don't know better options):

My updated example useQuery with
```tsx
variables: { itemId: itemId ?? 0 },
skip: itemId === undefined,
```
Or second option with `useLazyQuery` + `useEffect`.



Again thank you very much guys, I would come to solution with additional `open, setOpen state + onExited` myself.

**Comment by jerelmiller** [comment]
If I had to choose, I like your updated example since `useQuery` will manage the lifecycle for you (such as when `itemId` changes).

Glad you're able to get something you're happy with!
