### ISSUE TITLE
 HTTPS Client Error

### ISSUE THREAD

**Issue by bksun** [apollographql/apollo-client#10870]
I'm making https client from react running on localhost:9001 to my expressjs server running on localhost:8080 (http only).

When I make api call, the response from backend is received but in case of graphql query, we are not getting any response though graphql-controller is able to build, format and send response I cross-checked in debug-mode.

what could be the issue ?

```

 [1684140807677] ERROR (redbird/94311 on m-c02f5akymd6n): HTTPS Client Error
     Error: read ECONNRESET
         at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
 [1684140807679] ERROR (redbird/94311 on m-c02f5akymd6n): HTTPS Client Error
    Error: read ECONNRESET
         at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
```
```

ERROR (redbird/94311 on m-c02f5akymd6n): HTTPS Client Error
 Error: 140704594961216:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1558:SSL alert number 46

```

**Comment by jerelmiller** [comment]
Hey @bksun 👋 

According to [this article](https://support.oneidentity.com/syslog-ng-premium-edition/kb/4279556/sslv3-alert-certificate-unknown), it looks like the SSL certificate you're using to make requests to your server is either invalid, expired, or unknown. You'll need to make sure your server trusts the SSL certificate you're trying to make requests with.

I found [this article](https://www.section.io/engineering-education/how-to-get-ssl-https-for-localhost/) that looks like it might be able to help you create a self-signed certificate that you can use here. Hopefully that article can help!

Since this isn't so much an Apollo Client issue and more of a general networking issue, I'm going to go ahead and close out this issue. Hope this helps!
