### ISSUE TITLE
Cache mix up for queries with the same return type

### ISSUE THREAD

**Issue by jorgerodrigues** [apollographql/apollo-client#10930]
### Issue Description

If you have two queries share a return type defined in the schema AND you call this two queries together, apollo client will consistently merge the two results as one in cache.

Ex: 
```
returnThis(arg1: string, arg2: string)
returnThat(arg1: string, arg2: string)

Return type

type GenericReturn {
  value1: string
  value2: int
}
```

The interesting part is that if you inspect the network tab, the right results are returned by the server which indicates that the querying is done correctly. However, if you print the resulting `data` variable, you will see that the data is then merged. 

Note that the behaviour can be avoided by either:
- Using a `no-cache` fetch policy, or
- Using independent return types

### Link to Reproduction

na

### Reproduction Steps

1. Create two distinct queries that accept the same arguments (same name and same type)
2. Create one generic return type that is used by both queries
3. Call both queries at the same type (E.g in the same page in a Next environment)
4. Check the result of the `data` variable in code

**Comment by bignimbus** [comment]
Hi @jorgerodrigues - this seems like expected behavior from the information given.  It's hard to tell without a concrete reproduction scenario.  Since `GenericReturn` has no `id` or `__id` field and the queries you're returning are not distinguished by variables, there's nothing to distinguish one `GenericReturn` instance from another.  I recommend either including an `id` in your query document or [setting `keyArgs` in your type policy](https://www.apollographql.com/docs/react/caching/cache-field-behavior/#specifying-key-arguments) for `GenericReturn`.  Does that address your issue?

**Comment by jorgerodrigues** [comment]
Interesting. The queries are distinguished by the variables that are passed to it, and still it happens. 
I would expect to be able to run even the very same query in multiples places (albeit with different arguments) and have it fetch and cache properly. 
Do I have an incorrect mental model of how it is supposed to work?

**Comment by phryneas** [comment]
Could you please try to create a minimal reproduction for this? Right now, it is a bit hard to tell if this is working as intended or not.
