### ISSUE TITLE
How to get the uri from context before sending the request in HttpLink

### ISSUE THREAD

**Issue by EmmanuelPonnudurai** [apollographql/apollo-client#10952]
Hello, I am trying to get the uri, change it and set it back, right before the final link sends out the request. 

However, I am not able to get the value of the uri using `operation.getContext().uri`. 

```ts
const httpLink = new HttpLink({
  uri,
  useGETForQueries: true
});

const customLink = new ApolloLink((operation, forward) => {
  const context = operation.getContext();
  console.log(context); // I do not see uri property here
  operation.setContext({ uri: 'https://testing.com/api/doesnotexist' }); // Strangely this works.
  return forward(operation);
});

const client = new ApolloClient<NormalizedCacheObject>({ link: from([customLInk, httpLink]) ));
```

My intent is to use the option `useGETForQueries`, however right before sending out the request, I need to inspect the URL in order to compress it using some custom logic because I want to shorten the URL's. My backend is in my control so I use some custom decompression to interpret the values from that compressed data. 

At the end of the day, i need access to the URI but i just cant seem to get a hold of it. `operation.setContext({ uri: "/something" })` works but when i do getContext I dont see uri property. Why is this the case?

Can someone suggest an approach of how I can go about with this please?

**Comment by jerelmiller** [comment]
Hey @EmmanuelPonnudurai 👋 

Just to make sure I'm understanding the ask here, are you trying to get access the `uri` set on the `HttpLink` from your `customLink`? If so, unfortunately you won't be able to do this since the `uri` property is set on a link _further in the chain_ than your `customLink`.

The reason `operation.setContext({ uri: ... })` works for you is because `HttpLink` will try and read the `uri` from `context` [first](https://github.com/apollographql/apollo-client/blob/a1dac639839ffc5c2de332db2ee4b29bb0723815/src/link/http/selectURI.ts#L8-L11) which allows the URI to be overridden per-query if need-be. You can see that the `uri` is not fully determined until the [HttpLink is run](https://github.com/apollographql/apollo-client/blob/a1dac639839ffc5c2de332db2ee4b29bb0723815/src/link/http/createHttpLink.ts#LL56C27-L56C27).

If you need access to it earlier in the link chain, you'll either need to to extract that `uri` to a common variable that can be used by both `httpLink` and `customLink`, or you'll just need to make sure your custom link sets it via `operation.setContext({ uri: ... })` like you're doing there.

Let me know if this helps!

**Comment by EmmanuelPonnudurai** [comment]
Hi @jerelmiller thank you for your reply. 

Ok I understood why the uri is not available earlier. 

However, I need access to the uri right before it's finalized. Is there some api within http link that allows access to the finally formed uri and a way to me to then set it in context ? 

I can't use a variable to be passed along within my links because I need to know the uri which Apollo is creating. So that I can update it and then set it back. 

Example, if uri that is formed by Apollo is, http://mybackend.com?operationName=test, I need to update that to http://mybackend.com?on=t1 

Note that I need to know what the current url is and based on that, I will change things and set it again. So it's dynamic based on current value and cannot statically set things. 

Is there no way to get hold of the finally formed uri and update it ?

**Comment by EmmanuelPonnudurai** [comment]
I'm all set. Thank you.
