### ISSUE TITLE
useGETForQueries is accepted but doesn't work with BatchHttpLink

### ISSUE THREAD

**Issue by lhguerra** [apollographql/apollo-client#10956]
### Issue Description

I'm setting my link like this:
```
const httpLink = new BatchHttpLink({
  uri: apiUri,
  batchMax: 5,
  batchInterval: 20,
  useGETForQueries: true,
  fetchOptions: {
    agent: new Agent({ keepAlive: true }),
  },
})
```

I got no warning from TS or at runtime, so I just assumed my batched link would keep doing get requests as previously configured, but it only does post. I don't get why only do batched queries with post, it's not like there is a limitation, I simulated the same behavior with get (serializing the queries array so it can be used in a get request string) and my graphql server gave me the same response.

### Link to Reproduction

.

### Reproduction Steps

 - Create the Apollo Link with BatchHttpLink constructor
 - Set useGETForQueries to true
 - Make any request to the graphql api, it will be sent always via post method

**Comment by jerelmiller** [comment]
Hey @lhguerra 👋 

Digging through the codebase, I found this comment: https://github.com/apollographql/apollo-client/blob/a1dac639839ffc5c2de332db2ee4b29bb0723815/src/link/batch-http/batchHttpLink.ts#L112-L117

It looks like this code was originally pulled over from the [`apollo-link-batch-http`](https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-batch-http) package. Looking through the Git history, I found this commit: https://github.com/apollographql/apollo-link/commit/2084620f311fd1a10ad757458e6144224e423c49

While your server might understand batching via GET requests, my best guess is not every server might have support for it, hence why we disable it. If you're able to help me do a bit of sleuthing to determine if popular GraphQL server implementations allow HTTP batching via GET, that would go a long ways to help us determine whether to add formal support for it in the library.

At the very least, we should fix the TypeScript issue. Allowing this option via TypeScript seems like an oversight. It looks like we naively pull in all [`HttpOptions`](https://github.com/apollographql/apollo-client/blob/a1dac639839ffc5c2de332db2ee4b29bb0723815/src/link/batch-http/batchHttpLink.ts#L21) from `HttpLink`, which is why TypeScript isn't yelling at you.

**Comment by lhguerra** [comment]
> If you're able to help me do a bit of sleuthing to determine if popular GraphQL server implementations allow HTTP batching via GET, that would go a long ways to help us determine whether to add formal support for it in the library.

I don't think that's the case, as this automatic interpretation of arrays in the get request is a feature of the request lib of the framework i'm using (RoR), not part of the graphql server implementation (I actually discovered it by accident when writting tests for the graphql controller). So my use case might be too specific to support, and a type error should do.
