### ISSUE TITLE
Non selected fields are getting removed from cache. 

### ISSUE THREAD

**Issue by dulguun0225** [apollographql/apollo-client#10976]
### Issue Description

In case of types without `ID`, If some query doesn't select all the fields of a type, non-selected fields are getting removed from the cache.
This causes other queries that rely on the removed fields to unnecessarily send requests to the server.

### Link to Reproduction

https://github.com/dulguun0225/apollo-client-cache-reproduction

### Reproduction Steps

Run the server and client. Press getUser button and see the user data is stored in the cache. Press getPost button and see the unselected `b` field dissappear from `User.fields`.

**Comment by jerelmiller** [comment]
Copying my [reply](https://community.apollographql.com/t/cache-incoming-fields-have-missing-fields-if-the-responses-fields-are-null/6361/19?u=jerelmiller) from the forum.

---

The reason its getting replaced is because `details` is a non-normalized field on the `User` type and the cache doesn’t know how best to merge that field data together. By default, the cache assumes that any non-normalized field should be overwritten. Take a look at the [“Merging non-normalized objects”](https://www.apollographql.com/docs/react/caching/cache-field-behavior#merging-non-normalized-objects) section in the docs and I think you’ll see that example given is almost identical to this one. You’ll need to define a merge function for that field in order to get this to work.

---

Seeing how this is working as designed, I'm going to go ahead and close out this issue. If you have an idea of a feature request that would make this easier, feel free to file this over in the [feature requests repo](https://github.com/apollographql/apollo-feature-requests). Thanks!

**Comment by dulguun0225** [comment]
No, atleast update the selected fields. You literally have that mergeObject
function. Now I have to write merge config for 100s of types? Didn't expect
upgrading my client would make my life miserable.

**Comment by jerelmiller** [comment]
> atleast update the selected fields. You literally have that mergeObject function

@dulguun0225 I'm not quite sure what you mean by this. Would you mind elaborating?

> Now I have to write merge config for 100s of types?

This isn't necessarily true. You should only need to define type policies for types that contain fields with non-normalized data and whose types might have overlapping data between different queries. While I don't know the full scope of your app, I'm hoping you don't have a ton of different queries with overlapping data, which would mean you'd only need to add type policies to a few of the types.

> Didn't expect upgrading my client would make my life miserable.

As with any major version, there are bound to be breaking changes as new features and ideas are added to the library. Apollo Client is no different. 

I apologize this isn't as straight forward as you had hoped. Do you have any suggestions or ideas on how this might be improved?

**Comment by dulguun0225** [comment]
It's necessarily true that I have to write merge: true for every type that
doesn't have id field. Because in a big project I don't know who will write
what query, especially which fields they would select.

Now every time a backend developer adds a type with no id they also have to
change the front-end's client code.

Why is there no option to enable merge for everything?

**Comment by jerelmiller** [comment]
> Why is there no option to enable merge for everything?

@benjamn not sure if you have some context here or if this has been discussed in the past, but perhaps you could weigh in on the pros/cons of something like this?

**Comment by jerelmiller** [comment]
@dulguun0225 I was able to chat with @benjamn a bit on this.

Generally if you can't tell the identities of two objects, there is no guarantee they are the same object so blindly merging them may result in corrupted data if you're not careful (for example, imagine a field that returns an interface or union type that might change types between queries. Merging two unrelated objects wouldn't be a good idea here!).

Something that @benjamn brought my attention to is that the cache does have the ability to define [inheritance-like types](https://github.com/apollographql/apollo-client/pull/7065) along with [fuzzy matched types](https://github.com/apollographql/apollo-client/pull/6901) (using a regex like syntax) which can help you define a single type policy for potentially many types.

Take a look at those PRs and see if either of those features would help you out here. This might help you avoid the 100s of type policy declarations that you mentioned.

**Comment by phryneas** [comment]
Adding to that, the best course of actions for you would to make that data normalizable: give `details` an `id` field (and add that to your query), which will allow the client to recognize "these are the same details we saw with the last request, and they are not a completely different object - they can safely be merged together". 

`merge: true` is really just a band-aid for the fact that the data you are requesting is ambiguous.
