### ISSUE TITLE
React Native (iOS network error 403)

### ISSUE THREAD

**Issue by nazrincode** [apollographql/apollo-client#10980]
### Issue Description

Hi, I got this weird issue using this library in my React Native project.

### Link to Reproduction

df

### Reproduction Steps

These are the flows for both platform iOS and Android:

1. Success Fetch > Kill app from background > Open app again > And the results are different for both platform which is:

Android : Success Fetch
iOS : Keep getting Network Error with status code 403.

**Comment by phryneas** [comment]
Are you using any kind of persistance?

**Comment by phryneas** [comment]
Did you set up something like [apollo-cache-persist](https://github.com/apollographql/apollo-cache-persist)? 

If you did not, restarting your app will always completely clear your cache. In that case you are probably not completely killing your app on iOS - have you tried rebooting your phone?

**Comment by nazrincode** [comment]
No I'm not using that.

By the way this is my option:

``
defaultOptions: {
    watchQuery: {
      fetchPolicy: 'no-cache',
      errorPolicy: 'ignore',
    },
    query: {
      fetchPolicy: 'no-cache',
      errorPolicy: 'all',
    },
  }
``

**Comment by phryneas** [comment]
Oh, wait, I reread that - so this is not an issue with an error persisting over an app restart, but you getting a 403 error?

A 403 is sent by your server to your client - can you take a look at your server logs?

**Comment by nazrincode** [comment]
I can confirm that is nothing wrong on my server side. Keep getting networkError 403 code.

**Comment by phryneas** [comment]
403 is a code sent by your server. That cannot change on the way to the client, and the client does also not pull that out of thin air. 

The 403 might be sent by the server for good reasons, because it is getting a different request from your Android clients vs. your iOS clients, but you would still see in the server logs that the server sent a 403, and why that 403 was sent.

The only alternative is that you have a load balancer or something that changes your status code to a 403, but that is highly unprobably, usually a load balancer would only change the status to a 5xx error code.

**Comment by bignimbus** [comment]
Hi @nazrincode 👋🏻 sorry you're dealing with issue, sounds frustrating.  Unfortunately I don't think there's anything we can offer besides some general advice.  Let us know if there's a way for us to reproduce this scenario and I'm sure we'd be able to figure it out.  I'll echo Lenz's comments above RE: inspecting the server response, it's likely the source of this problem 🙏🏻
