### ISSUE TITLE
Approach of Apollo persisted queries

### ISSUE THREAD

**Issue by EmmanuelPonnudurai** [apollographql/apollo-client#11054]
Hello all. thank you for this really cool library. I have a question on the approach for [Apollo persisted queries](https://www.apollographql.com/docs/apollo-server/performance/apq/)

While I was reading through it, I got a few curious questions,
 - Essentially there are 2 roundtrips, until a request is fulfilled. Also, it relies on a failure mechanism. For HTTP work, this seems odd that a failure is used as a means to fall back and drive the next operation. 
 - 3 roundtrips, until data can be cached on a CDN provider. It takes 3 full roundtrips until the data can get cached on the CDN servers Meaning, 4th call is when we get from CDN. Only after this do we get 100% cache hit ratio. 
 - Someone can beat the system and overload backed to save queries which are not done within the context of the web application. I can find out the 2nd query which goes out with the SHA256 and all other stuff (operation name, query, variables). I can then create a random SHA256 hash and pass the same operation name, query and variables. Essentially making the backend store things which is not done by the app. My point is, where is the validation on the SHA256 hash? Client cannot be trusted to send hashes because it's not secure unless it's originated from server using some data protection algorithm or a key which server controls (hence ability to actually validate if the hash has been tampered with). 

Like I said, I'm trying to understand some aspects here out of curiosity. There must be a reason things are done this way. I'm facing my fair share of headaches trying to get graphql play well with CDN caching without buying more tools (not that I don't want to but just feeling there must be another way). 

HTTP POST is just BAD when it comes to caching at CDN. CDN's are good at caching HTTP GET but unfortunately, graphql does things the HTTP POST way even for querying which also I can understand cos the query can't be fit in the URL (everyone doesn't follow 8k/16k limit or what the specs say)

With all this said, I am using this approach as explained below. In fact, this is something that i got inspired from after reading [this article](https://www.apollographql.com/blog/community/5-benefits-of-static-graphql-queries/) and trying out a bunch of stuff. May be this is something everyone knows already but I'm just adding it (:D). conceptually its similar to https://github.com/apollographql/persistgraphql ( I'm not actually using it but i noticed its archived, not sure why)

- I run a custom script every time a query is added to the code base (I can also run it as a pre push hook or as a build step) This script uses graphql-tools and graphql tag pluck to parse entire graphql queries & fragments on the client side.
- I then store this information on my backend. i put it in DB or just a file on the backend or in memory. Basically, on the server side in a key and value store. Key is operation name and value is the query contents. 
- When a request is made on client side, I send only the operation name and variables Json in the URL as query params. This is a HTTP GET. 
- When server receives the request, it looks up from the in-memory store on backend and gets the query and all the fragments( i look up all fragments involved recursively) and then construct the query.
- Server fulfills the request and client gets the data. 
- This ensure that the next time, for the same operation name and variables, the data is then cached on the CDN right away. I have a bunch of rules also on backend on which request can be cacheable etc.

**Comment by jerelmiller** [comment]
Hello again @EmmanuelPonnudurai 👋 let me do my best to answer your questions:

> Essentially there are 2 roundtrips, until a request is fulfilled. Also, it relies on a failure mechanism. For HTTP work, this seems odd that a failure is used as a means to fall back and drive the next operation.

The key part of the docs article you reference is that this is _automatic_ persisted queries. Persisted queries rely on the query string to be stored somewhere in your backend, that way when the client sends only the `id` of the operation, it can lookup that `id` and get the query string to execute the query. But what happens when that query hasn't yet been persisted? In this case, Apollo Client's persisted queries feature gives the server a chance to register the raw query by re-sending the query with the full query string, hence the 2nd network request. Take a look at the [Persisted Query Link](https://www.apollographql.com/docs/react/api/link/persisted-queries) on the client which also goes into a bit more detail on the client end of things.

Something to note here is that because this work is done in the link, hooks or other parts of the client will be able to wait for the whole process to play out before the query is fulfilled which is pretty neat!

> 3 roundtrips, until data can be cached on a CDN provider. It takes 3 full roundtrips until the data can get cached on the CDN servers Meaning, 4th call is when we get from CDN. Only after this do we get 100% cache hit ratio.

I'm curious what your question is here :) Perhaps how to reduce the number of requests? You can also consider pre-registering your queries before you deploy with Apollo Server before you run your app so that you prime the cache. See [this section](https://www.apollographql.com/docs/react/api/link/persisted-queries#protocol) for the protocol used to communicate with Apollo Server. Again, you should only ever see several round trips if you're using _automatic_ persisted queries and a query hasn't yet been registered with the server.

> Someone can beat the system and overload backed to save queries which are not done within the context of the web application. I can find out the 2nd query which goes out with the SHA256 and all other stuff (operation name, query, variables). I can then create a random SHA256 hash and pass the same operation name, query and variables. Essentially making the backend store things which is not done by the app. My point is, where is the validation on the SHA256 hash? Client cannot be trusted to send hashes because it's not secure unless it's originated from server using some data protection algorithm or a key which server controls (hence ability to actually validate if the hash has been tampered with).

This may require a bit of playing around, but if I were in your shoes, I'd find a way during your deploy process to pre-register your queries with your server in a way that is trusted (i.e. have your deploy process authenticate with your server in some way so that you know its a trusted source). See [this section](https://www.apollographql.com/docs/apollo-server/performance/apq/#cache-configuration) on cache configuration with Apollo Server and [this section](https://www.apollographql.com/docs/apollo-server/performance/cache-backends) on configuring a cache backend, which should (hopefully) give you the control you need to determine which queries are trusted and which aren't. The key here would be rejecting queries that aren't trusted (to be honest, I haven't done this myself, so I'd recommend hitting up our [forum](https://community.apollographql.com/) or [discord channel](https://discord.gg/graphos) to ask specifics about this).

---

FYI, we just released a [tool](https://www.npmjs.com/package/@apollo/generate-persisted-query-manifest) that will extract queries from your app into a manifest file with a SHA-256 generated `id` for each of your queries. You may find this to be a useful tool in getting all those queries from your app that you can send to your server.

---

Not sure how much this helps, but hopefully thats some information you can do something with! Again, I'd recommend checking out our [discord channel](https://discord.gg/graphos) where you should be able to get some really solid community advice on how best to set this whole process up. Let me know if you need anything else! I'm going to go ahead and close this issue :)
