### ISSUE TITLE
MockedProvider not returning mocked response or calling onCompleted/onError for useQuery using jest, @testing-library/react

### ISSUE THREAD

**Issue by Deelane** [apollographql/apollo-client#11059]
Hello,

I am experiencing an issue with the MockedProvider that I cannot find information for anywhere else. I am testing a login callback component that calls useQuery with a fairly simple query. I know the shape and variables for the query are correct in the mocks array because when I change them a warning is thrown informing me that I no longer have responses set for the given query. 

The query is supposed to return some data and call and await a mutation if the data returns anything. However, it would seem that the query is called and returns, but does not return anything, error or otherwise. I know this from debugging the loading state and seeing that it properly changes. 

I would greatly appreciate any insight on what is going on here.

Here are the relevant code bits: 

mocks:
```   
const mocks = [
        {
            request: {
                query: getUser(usersUserId),
                variables: {
                    filter: {
                        label: {
                            equalTo: userEmail
                        }
                    }
                }
            },
            result: {
                data: {
                    "users": {
                        "totalCount": 1,
                        "pageInfo": {
                            "startCursor": "eyJvZmZzZXQiOiIxIn0=",
                            "endCursor": "eyJvZmZzZXQiOiIxIn0=",
                            "hasNextPage": false,
                            "hasPreviousPage": false
                        },
                        "edges": [
                            {
                                "node": {
                                    "userId": "some userId"
                                },
                                "cursor": "eyJvZmZzZXQiOiIxIn0="
                            }
                        ]
                    }
                }
            }
        },
        {
            request: {
                query: createUser,
                variables: {
                    input: {
                        label: userEmail
                    }
                }
            },
            result: {
                data: {
                    createUser: {
                        userId: "some userId",
                        label: userEmail
                    }
                }
            }
        }
    ];
```

mocked provider:
```                
render(<MockedProvider mocks={mocks} addTypename={false}>
                    <LoginCallback history={historyFromRouter}
                                   location={locationFromRouter}
                    />
                </MockedProvider>);
```

query and mutation:
```
    const {
        loading,
    } = useQuery<{ [key: string]: GraphQLConnection }>(
        getUser(usersUserId), {
            skip: !userEmail,
            variables: {
                filter: {
                    label: {
                        equalTo: userEmail
                    }
                }
            },
            onCompleted: async (result) => {
                const graphQLConnection = result['users'];
                const graphQLNodes = getGraphQLNodes(graphQLConnection);
                if (graphQLNodes.length === 0)
                    await createUserMutation({
                        variables: {
                            input: {
                                label: userEmail
                            }
                        },
                    })
                windowLocation.assign(destinationUrl);
            },
            onError: () => windowLocation.assign(destinationUrl)
        });
```

**Comment by jerelmiller** [comment]
Hey @Deelane 👋 

Is there a possibility you could put this into a runnable repo for us? I'd be happy to dig in a bit further to understand what might be happening here. At first glance, I don't see anything wrong, but having the ability to interact with your queries/data/mocks would be a huge help. Thanks!

**Comment by Deelane** [comment]
Hi @jerelmiller,

I would really like to, but I am on a bit of a tight schedule trying to get these tests out and it would take a bit of work to set up an environment for this. I can potentially do it soon, but in the meantime is there any other information that might help that I can provide? I don't imagine you guys do screensharing sessions  😆.

**Comment by Deelane** [comment]
Okay, it took a little less time than I thought. I was able to get a light version up on replit with the key portions. I am not seeing loading go back to false on this repo, however. 

Kindly fork [the repo](https://replit.com/@Deelane/MockedProvider) and run yarn test from the shell please!

**Comment by jerelmiller** [comment]
@Deelane thank you! I'll dig into this now. I'm not against a screenshare if need be 🤣. Let me try this out and I'll let you know if thats needed!

**Comment by jerelmiller** [comment]
@Deelane I've had a chance to run this and I'd love to dig a bit deeper here (we may be approaching screenshare territory). There are a couple things that stuck out to me, but I'm not sure if its because of trying to pare down the example for the reproduction, if this is how your test is setup. Here are the things I noticed with this repro that may or may not be related to the issues you're seeing.

Something to note about `MockedProvider` is that it resolves the query asynchronously (via `setTimeout`) so that it tries to mimic the async nature of the component. This means your test will be in the "loading" state for at least a tic before it will resolve with your mock data. The reason you're not seeing the `loading` flag change is because the test completes before the query is able to resolve the data. If I add something like an `await waitFor(...)` call in the test, the test is around long enough where I see the loading flag change from `true` to `false`.

The mutation in this particular test seems irrelevant and will never be called. I see you're mocking `edges` to have at least 1 item in that array, but your `onCompleted` handler only runs the mutation if there are no edges. Regardless, it looks like `windowLocation.assign` is called regardless of whether the mutation runs.

I noticed your test uses a local `location` variable with a jest mock on the `assign` function, but the `location` used in the `<LoginCallbackLite />` component uses `window.location`, which isn't the same mock you provided in your test. The test fails because it never receives a call to your mocked `location`. I do see in your original issue description, it looks like you passed the `location` as a prop to your `<LoginCallback />` component, so perhaps this is just an issue with the reproduction?

Given these couple things, I'm unsure whether the test failure is expected, or what other issue you are seeing. If you could provide a bit more detail, that would be super helpful so that I can give good advice.

---

Side note about best practices, I highly recommend that you create a new `mocks` variable in each test, rather than using a global `mocks` variable that is shared among multiple tests. The biggest reason for this is that `MockedProvider` will actually _mutate_ the `mocks` array by [splicing](https://github.com/apollographql/apollo-client/blob/3119d46668356059811bf75eaebc8fbc71cc3d69/src/testing/core/mocking/mockLink.ts#L125) the matched result out of the array. This allows you to create 2 different mocks for the same query/variables to allow your tests to simulate a `refetch`, where the results might differ.

If you end up using the same `mocks` array for more than a single test, you'll quickly Have A Bad Time™️  because each test will mutate that `mocks` array. These issues are tough to debug, because an `it.only` might make a test pass that previously failed when all tests were running.

If you need to share mocks, I'd recommend a helper function that generates these mocks that you call in each test:

```ts
it('test 1', () => {
  const mocks = createMocks();
});

it('test 2', () => {
  const mocks = createMocks();
});
```

**Comment by Deelane** [comment]
Interesting note about the mocks, I will definitely take that into account. I may have missed a few parts when I was porting the test, and callback component, as the real versions are a bit more verbose. In the real version I am actually not hanging on loading = true, and it properly returns back to false. About the mutation piece, I had actually not gotten to the test logic for that as I was having trouble reproducing the query return to begin with. However, I take it you were still seeing that no data was being returned even though the query shape/variables matched?

**Comment by jerelmiller** [comment]
@Deelane I'm seeing data come through just fine, both in the `data` property and the callback. Here is the relevant jest output I'm seeing:

```
  console.log
    loading ===>  true

      at LoginCallBackLite (src/LoginCallBackLite.tsx:45:11)

  console.log
    data ===> undefined

      at LoginCallBackLite (src/LoginCallBackLite.tsx:46:11)

  console.error
    Error: Not implemented: navigation (except hash changes)
        at module.exports (/Users/jerelmiller/code/mocked-provider-repro-again/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
        at navigateFetch (/Users/jerelmiller/code/mocked-provider-repro-again/node_modules/jsdom/lib/jsdom/living/window/navigation.js:76:3)
        at exports.navigate (/Users/jerelmiller/code/mocked-provider-repro-again/node_modules/jsdom/lib/jsdom/living/window/navigation.js:54:3)
        at LocationImpl._locationObjectNavigate (/Users/jerelmiller/code/mocked-provider-repro-again/node_modules/jsdom/lib/jsdom/living/window/Location-impl.js:31:5)
        at LocationImpl.assign (/Users/jerelmiller/code/mocked-provider-repro-again/node_modules/jsdom/lib/jsdom/living/window/Location-impl.js:217:10)
        at Location.assign (/Users/jerelmiller/code/mocked-provider-repro-again/node_modules/jsdom/lib/jsdom/living/generated/Location.js:70:36)
        at InternalState.onCompleted (/Users/jerelmiller/code/mocked-provider-repro-again/src/LoginCallBackLite.tsx:40:22)
        at /Users/jerelmiller/code/mocked-provider-repro-again/node_modules/@apollo/client/react/hooks/useQuery.js:257:27 undefined

      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at module.exports (node_modules/jsdom/lib/jsdom/browser/not-implemented.js:12:26)
      at navigateFetch (node_modules/jsdom/lib/jsdom/living/window/navigation.js:76:3)
      at exports.navigate (node_modules/jsdom/lib/jsdom/living/window/navigation.js:54:3)
      at LocationImpl._locationObjectNavigate (node_modules/jsdom/lib/jsdom/living/window/Location-impl.js:31:5)
      at LocationImpl.assign (node_modules/jsdom/lib/jsdom/living/window/Location-impl.js:217:10)

  console.log
    loading ===>  false

      at LoginCallBackLite (src/LoginCallBackLite.tsx:45:11)

  console.log
    data ===> {
      users: {
        totalCount: 1,
        pageInfo: {
          startCursor: 'eyJvZmZzZXQiOiIxIn0=',
          endCursor: 'eyJvZmZzZXQiOiIxIn0=',
          hasNextPage: false,
          hasPreviousPage: false
        },
        edges: [ [Object] ]
      }
    }

      at LoginCallBackLite (src/LoginCallBackLite.tsx:46:11)
```

**Comment by Deelane** [comment]
Ah, it seems you were exactly right with the query not having returned due to its async nature. I saw a lot of issues explaining the solution to that problem, but I figured mine was different because my loading state was properly switching but data was still being returned as undefined. Anyway, thank you for the help!

**Comment by jerelmiller** [comment]
@Deelane glad that worked for you! Let us know if you need anything else.
