### ISSUE TITLE
The jwt token used in the header is retrieved from AsyncStorage every time, but there is an issue with TypeScript linting(TS2345).

### ISSUE THREAD

**Issue by daheeahn** [apollographql/apollo-client#11081]
Hi, I'm using `@apollo/client` in `react native`.
Since jwtToken is managed by AsyncStorage,
As in the code below, access AsyncStorage every time and prepare the header.
```
import React, { useEffect, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {
  ApolloProvider,
  InMemoryCache,
  ApolloClient,
  HttpLink,
  ApolloLink,
  concat,
  NormalizedCacheObject,
} from '@apollo/client';

const App = () => {
  // state
  const [apolloClient, setApolloClient] = useState<ApolloClient<NormalizedCacheObject> | null>(
    null,
  );

  /**
   * Apollo Client 세팅
   */
  const settingApolloClient = () => {
    const authMiddleware = new ApolloLink(async (operation, forward) => { // <<< 🚨linting🚨
      const jwtToken = await AsyncStorage.getItem(asyncUtil.jwt);
      operation.setContext({
        headers: {
          authorization: jwtToken ?? '',
          'roubit-env': __DEV__ ? 'dev' : 'prod', // ⭐️여기 바뀌면 axios.ts의 roubit-env도 바꿔야 함
          'roubit-version': verNumsToString, // "5.7.5(1)" // ⭐️여기 바뀌면 axios.ts의 roubit-version도 바꿔야 함
        },
      });
      return forward(operation);
    });
    const httpLink = new HttpLink({ uri: `${API_URL}/graphql` });
    const _client: ApolloClient<NormalizedCacheObject> = new ApolloClient({
      cache: new InMemoryCache(),
      link: concat(authMiddleware, httpLink),
      assumeImmutableResults: true,
      credentials: 'include',
      defaultOptions: {
        watchQuery: {
          errorPolicy: 'all',
        },
        query: {
          errorPolicy: 'all',
        },
        mutate: {
          errorPolicy: 'all',
        },
      },
    });

    setApolloClient(_client);
  };

  // useEffect
  useEffect(() => {
    settingApolloClient();
  }, []);

  if (!apolloClient) return null;

  return (
    <ApolloProvider client={apolloClient}>
      {children}
    </ApolloProvider>
  );
};

```
![image](https://github.com/apollographql/apollo-client/assets/38369729/728461c5-71b6-4ec5-8044-696b03b21f43)
![image](https://github.com/apollographql/apollo-client/assets/38369729/6c1a800d-5189-4ed3-aaa2-0aacb65739a4)

The api call works fine, but async/await is not allowed within ApolloLink.
So, is there a way to get rid of that lint and get the jwtToken out of AsyncStorage every time?

**Comment by jerelmiller** [comment]
Hey @daheeahn 👋 

While the `async` function work in some cases, `ApolloLink` isn't quite setup to handle all cases. If your link chain ends up growing, you might run into issues down the line (I'll spare you the details unless you're curious 😄).

Since you're just trying to set context from some async source, try using the [Context Link](https://www.apollographql.com/docs/react/api/link/apollo-link-context) which is designed for this purpose. This link allows an async function and won't have the same type errors.

**Comment by jerelmiller** [comment]
On a side note, I have a small recommendation for your `ApolloClient` setup in that code sample above. 

Since you're setting up the client in `useEffect`, you're triggering an extra re-render unnecessarily in your `App` component. There are a couple ways you can optimize your code to setup the client that will result in only a single render pass.

1. `useState` takes an initialization function that will only run the first time the state is initialized. Its perfect like this to prevent you from creating a new `ApolloClient` instance on each render. This is also optimal because you don't need the 2nd render pass to get this to work. This eliminates `useEffect` and that `if (!apolloClient)` check:

```tsx
import React, { useEffect, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {
  ApolloProvider,
  InMemoryCache,
  ApolloClient,
  HttpLink,
  ApolloLink,
  concat,
  NormalizedCacheObject,
} from '@apollo/client';

const App = () => {
  const [client] = useState(() => {
    const authMiddleware = new ApolloLink(async (operation, forward) => {
      const jwtToken = await AsyncStorage.getItem(asyncUtil.jwt);
      operation.setContext({
        headers: {
          authorization: jwtToken ?? '',
          'roubit-env': __DEV__ ? 'dev' : 'prod', // ⭐️여기 바뀌면 axios.ts의 roubit-env도 바꿔야 함
          'roubit-version': verNumsToString, // "5.7.5(1)" // ⭐️여기 바뀌면 axios.ts의 roubit-version도 바꿔야 함
        },
      });
      return forward(operation);
    });
    
    const httpLink = new HttpLink({ uri: `${API_URL}/graphql` });
    
    return new ApolloClient({
      cache: new InMemoryCache(),
      link: concat(authMiddleware, httpLink),
      assumeImmutableResults: true,
      credentials: 'include',
      defaultOptions: {
        watchQuery: {
          errorPolicy: 'all',
        },
        query: {
          errorPolicy: 'all',
        },
        mutate: {
          errorPolicy: 'all',
        },
      },
    });
  });

  return (
    <ApolloProvider client={apolloClient}>
      {children}
    </ApolloProvider>
  );
})
```

3. Since it doesn't appear that you have dependencies from the `App` component in your `ApolloClient`, consider extracting the client to outside the function. This means your component is already instantiated by the time your app renders for the first time. This also eliminates the need for both `useState` and `useEffect` and you can get rid of that `if (!apolloClient)` check. FWIW this is my preferred approach.

```tsx
import React, { useEffect, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {
  ApolloProvider,
  InMemoryCache,
  ApolloClient,
  HttpLink,
  ApolloLink,
  concat,
  NormalizedCacheObject,
} from '@apollo/client';

const authMiddleware = new ApolloLink(async (operation, forward) => {
  const jwtToken = await AsyncStorage.getItem(asyncUtil.jwt);
  operation.setContext({
    headers: {
      authorization: jwtToken ?? '',
      'roubit-env': __DEV__ ? 'dev' : 'prod', // ⭐️여기 바뀌면 axios.ts의 roubit-env도 바꿔야 함
      'roubit-version': verNumsToString, // "5.7.5(1)" // ⭐️여기 바뀌면 axios.ts의 roubit-version도 바꿔야 함
    },
  });
  return forward(operation);
});

const httpLink = new HttpLink({ uri: `${API_URL}/graphql` });

const apolloClient = new ApolloClient({
  cache: new InMemoryCache(),
  link: concat(authMiddleware, httpLink),
  assumeImmutableResults: true,
  credentials: 'include',
  defaultOptions: {
    watchQuery: {
      errorPolicy: 'all',
    },
    query: {
      errorPolicy: 'all',
    },
    mutate: {
      errorPolicy: 'all',
    },
  },
});

const App = () => {
  return (
    <ApolloProvider client={apolloClient}>
      {children}
    </ApolloProvider>
  );
};
```

---

Both of these options work. I personally prefer the 2nd approach because it allows me to avoid cluttering up the `App` component and also because its easier to extract into its own file. Option 1 works great if you have external input that is only available in React state/props in order to instantiate your client.

Feel free to take or leave this advice! Just figured I'd recommend a slightly more optimal setup for your client instance than having to render twice 🙂
