### ISSUE TITLE
`useSuspenseQuery`'s `refetch` keeps suspending when variables not changed

### ISSUE THREAD

**Issue by izumin5210** [apollographql/apollo-client#11085]
### Issue Description

When `useSuspenseQuery`'s `refetch` is executed, `Suspense` fallback is still drawn and does not move forward

### Link to Reproduction

https://codesandbox.io/s/apollo-client-v18-use-suspense-query-bug-yg6rzy?file=/src/App.tsx

**Comment by izumin5210** [comment]
In the following reproduced code, the process continues correctly when the query result changes.
https://codesandbox.io/s/cranky-gould-6npmlm?file=/src/index.jsx

It seems that the Promise is not resolved correctly when there is no change in the Apollo Cache.

**Comment by jerelmiller** [comment]
Hey @izumin5210 👋

I'm pretty sure I broke this in https://github.com/apollographql/apollo-client/pull/11035 for the final beta release while trying to fix a separate issue (incrementally re-rendering queries with `@defer` in a refetch).    Using your reproduction, I can see that `3.8.0-beta.6` works correctly, but `3.8.0-beta.7` is where the bug is introduced.

I will make sure to get a fix in for the next `rc` release. Thanks so much for bringing this to our attention!!

**Comment by izumin5210** [comment]
Thanks for the quick reply! Looking forward to your next release!

**Comment by jerelmiller** [comment]
@izumin5210 I've got #11086 up that fixes this issue. I've created a snapshot release that you can try out if you'd like to see this in your own app. 

```
npm i @apollo/client@0.0.0-pr-11086-20230721035547
```

I've confirmed this snapshot release fixes the issue demonstrated in your reproduction: https://codesandbox.io/s/apollo-client-v18-use-suspense-query-bug-forked-cqstj9

**Comment by jerelmiller** [comment]
Fixed with #11086. This will go out with the next `rc` release.
