### ISSUE TITLE
Vague documentation regarding Modifier and readField

### ISSUE THREAD

**Issue by JonasDoe** [apollographql/apollo-client#11135]
As a short introduction where I come from: I want to modify my Apollo cache with a Modifier which merges old and new data like:
```graphql
const myModifier: Modifier<Reference> = (prevData, details) => {
   return {
      ... prevData,
      someField: 'updatedValue'
   }
}
```
But this leaves me puzzled: According to the [documentation](https://www.apollographql.com/docs/react/caching/cache-interaction/#values-vs-references), `prevData` will be a reference (since I'm modifying an object here). What will happen when an item with `__ref` and some other props will be returned? Will that be resolved accordingly? The [documentation](https://www.apollographql.com/docs/react/caching/cache-interaction/#parameters) says I should return "whatever value should replace it." - so I'ld replacing an object like `{__ref: "someRef"}` with `{__ref: "someRef", someField: 'updatedValue'}`, but don't touch the real item myself. Can this happen, and if so, is that intended?

Going on from there, I tried something like 
```graphql
const myModifier: Modifier<Reference> = (prevData, details) => {
   return {
      ... details.readField(details.storeFieldName), // this is something with stringified arguments, and in the cache at the expected position
      someField: 'updatedValue'
   }
}
```
but that won't work b/c `readField` returns undefined.  According to the [documentation](https://www.apollographql.com/docs/react/api/cache/InMemoryCache/#readfield), it should read "other fields within the current object" - what's the `current object` then? I'ld expect it to be the object whose property [`fieldName`] I'm modifying here.

(I've also posted a similar question at [stackoverflow](https://stackoverflow.com/questions/76858579/apollo-client-cache-how-do-merge-items-within-a-modifier), but it doesn't seem like anybody there knows. So think it's a documentaton issue and it would be neat if you could provide some clarification here!)

**Comment by bignimbus** [comment]
Hi @JonasDoe 👋🏻 thanks for opening this issue and for the detailed question!  I'll do my best to address your points.  Since it's a multi-part question I'll do my best to stay on-track, let me know if my response misses something!

My understand is that when you're using a `Modifier` function to update the cache, the `prevData` argument is, as you say, a reference to the existing data in the cache. If you return an object that includes a `__ref` field along with other properties, Apollo Client will update the cache with this new object, replacing the existing reference. This means that the object `{__ref: "someRef", someField: 'updatedValue'}` will replace the existing object `{__ref: "someRef"}` in the cache.

However, IIRC this doesn't directly modify the actual data that the reference points to. The `__ref` field is used by Apollo Client to establish relationships between different pieces of data in the cache.  So that `someField` value is stored on the _reference_, not the object to which the reference refers.

Regarding your second question, the `readField` function is used to read the value of a field from the current object being processed by the `Modifier` function. The "current object" in this context is the object that the `Modifier` function is operating on, which is represented by the `prevData` argument. If `readField` is returning `undefined`, it could mean that the field you're trying to read doesn't exist on the current object, but this is where a runnable reproduction or Replay recording would be really helpful so we can get specific.

Does that help?  I think there might be room for improvement on the docs here but I want to be sure this info is useful before suggesting specific changes 🙏🏻

**Comment by JonasDoe** [comment]
Hi @bignimbus - thank your for the fast reply!

> My understand is that when you're using a `Modifier` function to update the cache, the `prevData` argument is, as you say, a reference to the existing data in the cache. If you return an object that includes a `__ref` field along with other properties, Apollo Client will update the cache with this new object, replacing the existing reference. This means that the object `{__ref: "someRef", someField: 'updatedValue'}` will replace the existing object `{__ref: "someRef"}` in the cache.
> 
> However, IIRC this doesn't directly modify the actual data that the reference points to. The `__ref` field is used by Apollo Client to establish relationships between different pieces of data in the cache. So that `someField` value is stored on the _reference_, not the object to which the reference refers.
If I understand correctly, we end up with to - inconsistent - variants of data if I return `{__ref: "someRef", someField: 'updatedValue'}`: the updated `Reference` object at the very place bears another value for `someField` afterward than the the referenced object. Additionally, other `References` aren't updated either. I'm not complaining, I just want to make sure I got that right!
I had another look into the documenation `"If you return a different reference in your modifier function, you change which other cached object is contained in this field. You don't modify the original cached object's data."` - I guessed (wrongly) that "original cached object's data" meant: I don't modify the "actual data that the reference points to" (as you put it) if I return an object with a different `__ref` value, but [i]otherwise I will[/i]. That's why I expected some "update/resolving" magic to take place after I've returned the new object. But from what I understand now, another `__ref` value would just make the parent object to point to another object, but any referenced object themselves remained unchanged in any case.

> Regarding your second question, the `readField` function is used to read the value of a field from the current object being processed by the `Modifier` function. The "current object" in this context is the object that the `Modifier` function is operating on, which is represented by the `prevData` argument. If `readField` is returning `undefined`, it could mean that the field you're trying to read doesn't exist on the current object, but this is where a runnable reproduction or Replay recording would be really helpful so we can get specific.
I think I just misunderstood what the "current object" (according to the documentation) was. I expected it to be the parent object of the one that is passed, as the passed object is just the "value" of the parent's property. I hoped that `readField(details.storeFieldName)` would give me access to the dereferenced, underlying object of `prevData`. Maybe it would clarify things if the documentation stated that `readField(fieldName)` is just a shortcut for `readField(fieldName, prevData)`.

**Comment by bignimbus** [comment]
Glad my response was helpful!  I'll leave this issue open so we track this suggestion for docs.  Please do feel free to open a PR, we're always happy to get new contributors and would be eager to review it!

> What will happen if I call `readFeld('someField')` on `{__ref: "someRef", someField: 'updatedValue'}` at a later point? Will I receive `'updatedValue'` or the value of the referenced object?

Yes - `readField` reads the value of a field from the current object, not from the object that a reference points to.
