### ISSUE TITLE
Type error with apollo client package

### ISSUE THREAD

**Issue by SaumilNagariya** [apollographql/apollo-client#11131]
### Issue Description

Hi team,

We are using node v18.16.1 and apollo-client 3.8.0 for Nexjs Commerce repo. It was working fine till yesterday, but now it is failing the build.

Yarn build

<img width="901" alt="image" src="https://github.com/apollographql/apollo-client/assets/105697535/963566dc-16fd-419e-b6b8-5e72025b7219">

can you please help me asap?

### Link to Reproduction

n/a

**Comment by jerelmiller** [comment]
Hey @SaumilNagariya 👋 

Could I get a little more info from you. When you say "working fine till yesterday", were you using a prerelease version of 3.8? If so, which one? 

Not much has changed between the `rc.2` version and the public release version so I'm a bit surprised to see this. Do you have a reproduction that we can dig into further?

**Comment by alessbell** [comment]
What versions of Next.js and TypeScript are you using? I've tried to reproduce this with no luck so far.

I've cloned the latest https://github.com/vercel/commerce project, pnpm installed @apollo/client@3.8.0 and imported + called `useBackgroundQuery` in a client component. (For streaming SSR support, you'd want to use our https://www.npmjs.com/package/@apollo/experimental-nextjs-app-support package when using Next.js's app router, but that isn't material to this bug occurring during the build.)

As you can see here, it passes linting and type checking but later fails to generate static pages because I don't have API keys for a Shopify store in my env variables:

![CleanShot 2023-08-08 at 12 13 14](https://github.com/apollographql/apollo-client/assets/5139846/6c1f8bae-551a-415b-b898-a56c8e65b7c7)

**Comment by alessbell** [comment]
In the meantime, you can try the snapshot release from https://github.com/apollographql/apollo-client/pull/11134 by doing `npm i @apollo/client@0.0.0-pr-11134-20230808160421`.

This subtly changes the import syntax in the built `useBackgroundQuery.d.ts`:

```diff
- import { type QueryReference } from "../cache/QueryReference.js";
+ import type { QueryReference } from "../cache/QueryReference.js";
```

But I'd be very curious to look at a reproduction since AFAIK the syntax we're currently using has been supported since [TypeScript 4.5](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#type-modifiers-on-import-names).
