### ISSUE TITLE
How to get rid of ssrForceFetchDelay with React 18

### ISSUE THREAD

**Issue by SanNic20** [apollographql/apollo-client#11142]
I'd like to return to a subject that has already been discussed here [Get rid of ssrForceFetchDelay](https://github.com/apollographql/apollo-client/issues/4814) by @darkowic He suggested to use the code below instead of use `ssrForceFetchDelay` (Also I think is a better solution)
```
client.disableNetworkFetches = true;
ReactDOM.hydrate(
  <ApolloProvider client={client}>
    <MyApp />
  </ApolloProvider>,
  MOUNT_NODE,
  () => {
    // app is hydrated!
    client.disableNetworkFetches = false;
  }
)
```
The problem is that this solution is no longer compatible with `HydrateRoot` (under React 18). `HydrateRoot` no longer has the callback option as with `Hydrate`.

Does anyone have another solution that is compatible with `HydrateRoot`? Is it possible to reproduce something similar?

Thank you in advance for your help. Best regards.

**Comment by plausible-phry** [comment]
This is a difficult one, since we are in a weird in-between state here:

`hydrateRoot` is the "opposite" to `renderToPipeableStream`, and with those two you opt into a very different paradigm than with classic SSR: you are doing streaming SSR now.
  
That means that if you have `Suspense` boundaries in your code, your app will already start to hydrate in the browser while it is still rendering on the server.  
Having a single point in time where you forbid or allow network requests for the whole application doesn't make any sense anymore, since your application might already be interactive long before the server finished rendering - and user interaction might trigger additional network requests.

The way we work around that in https://github.com/apollographql/apollo-client-nextjs is that we encourage the use of the `useSuspenseQuery` or `useBackgroundQuery` hooks and transport the "a query started" and "a query finished with result X" information from server to client as soon as possible, and use Apollo Client's deduplication mechanism to prevent identical requests from happening on the client - they latch onto the server request instead and resolve once the "a query finished" information is available.

Unfortunately, the method we use for data transport here is not natively provided by React, so we have to use the `ServerInsertedHTMLContext` of Next.js to work around that.  
Until React ships with a similar API, I am not sure if we can support anything similar directly from the Apollo Client side. 
We'll have to ship a separate helper package for every framework, and hopefully will at some point have found an abstraction that can also be used by non-framework users - but that will require a lot of manual code, I fear.
