### ISSUE TITLE
useQuery loading flag get updated to false before onCompleted function has been called

### ISSUE THREAD

**Issue by majoncas-ue** [apollographql/apollo-client#11161]
### Issue Description

Hi Apollo team!

Previously with version "3.7.1 " loading flag from useQuery hook was updated to false after the onCompleted function has been called but after upgrade to "3.8.1" version order of execution has been changed. The problem is that I make data manipulations in the onCompleted function and the fact that the loading is updated prior this data manipulation creates an intermediate unwanted render. I wish it could work as before so I can be sure that my data has been transformed before loading flag is being updated.

Thank you for your help in advance!

### Link to Reproduction

https://codesandbox.io/s/relaxed-sound-th2ht3?file=/src/index.jsx

### Reproduction Steps

Open dev tools and look at the console outputs. You can clearly see that "loading: false" trace comes from before "onCompleted" one. Compare with previous 3.7.1 version and see that it's the other way around.

**Comment by jerelmiller** [comment]
Hey @majoncas-ue 👋 

I'd like to explore this statement a bit further:

> The problem is that I make data manipulations in the onCompleted function and the fact that the loading is updated prior this data manipulation creates an intermediate unwanted render

Would you be willing to share a bit more about what kind of data manipulations you're doing? I presume you're doing some kind of `set` from a `useState` in here?

---

Generally we don't recommend these kinds of data manipulations in `onCompleted` and instead recommend that you use a _derived_ value. It's going to be more accurate and reduce the number of renders to achieve the same thing. To see a great example of this and the pitfalls, I'd highly recommend taking a look at [Dominik's blog](https://tkdodo.eu/blog/breaking-react-querys-api-on-purpose) on this topic for React Query and the [state syncing problem](https://tkdodo.eu/blog/breaking-react-querys-api-on-purpose#state-syncing).

See if this applies to your situation and let us know!

**Comment by majoncas-ue** [comment]
@jerelmiller Thank you for your quick answer!

I understand the context of that article, however what I am trying to achieve is to take data returned from the useQuery hook and then notify a reducer (useReducer hook) through a dispatched action. The reducer is responsible to transform data received from the backend into a "ready to use" by the UI one and then returning manipulated data into a state object. I've also tried the useEffect pattern to notify my reducer upon data property changes but again it's being triggered after the loading flag has been changed to false :/ 

I don't really understand what changed between Apollo versions...

**Comment by jerelmiller** [comment]
I believe this was caused by https://github.com/apollographql/apollo-client/pull/11083 which adjusts the relative timing of renders in `useQuery` so that it more closely aligns with `useFragment`. This was introduced in `3.8.0-rc.2` and I can see that [switching to `3.8.0-rc.1`](https://codesandbox.io/s/fervent-sky-rqltxy) reverts back to the behavior you describe. I'd recommend taking a look at https://github.com/apollographql/apollo-client/issues/11039 which gives some context on what this PR fixed.

Something else I'd like to call attention to here that could be problematic. Do you expect cache updates to find its way through the reducer? We fixed a regression in 3.8 where `onCompleted` was called for cache writes (https://github.com/apollographql/apollo-client/pull/10229). This callback is meant to be executed on completion of network requests, so you won't have any way of syncing those cache updates using `onCompleted` to your reducer state. Because of this, you might miss those updates in your UI, which means your component is going to render stale data.

>  I've also tried the useEffect pattern to notify my reducer upon data property changes but again it's being triggered after the loading flag has been changed to false

I'm curious to explore this more. Could you post some sample code of what you're doing? 

The timing of `onCompleted`/`loading` shouldn't affect the `useEffect` approach from one version to the next, so I'd expect you'd have the same problem in 3.7.x.

---

Again, I'd really like to recommend that you avoid syncing state this way and instead use derived data. You'll be able to render updated data properly from cache updates this way and avoid unnecessary re-renders to compute the data.

Totally understand you want to transform the data in some way in the "ready to use" shape that you want, but you should be able to achieve this with `useMemo` (if you need reference equality between renders) + a function.

```tsx
// presumably this contains the logic you've currently got in your reducer
function transformDataForUI(data) {
  // ... transform the data
  return transformedData
}

function MyComponent() {
  const { data } = useQuery(query)

  const dataForUI = useMemo(() => transformDataForUI(data), [data])
}
```

This won't have the same state syncing issues described above, especially when it comes to cache updates since you just rerun the transformation whenever `data` changes.

Is there a technical limitation or something else preventing you from using this approach? If so, I'd love if you can provide a more detailed reproduction that I can take a look at to understand why this might not work in your situation.

**Comment by majoncas-ue** [comment]
I think I understand more the context of that change now. Thank you for the heads up about cache. This wasn't a problem for us since we are not leveraging the cache at this point. 

The problem with your suggested approach is that it doesn't suit well with our current architecture. We wanted to delegate all states change to a reducer so all data manipulations must happen there. If it was a readonly page I would be open to use suggested pattern but we have to handle data manipulations upon receiving data from useQuery hook but we have other user interaction to handle that can have an effect on the state!

**Comment by jerelmiller** [comment]
Ok good to know!

Revisiting the original problem, I'm still not sure I'm understanding why the timing of `loading` relative to `onCompleted` is a problem here. You're going to have additional re-renders regardless of which executes first (since both `useQuery` and your reducer causes state changes), so why would the timing of these cause issues in your app? Could you perhaps explain this a bit further? Even better, if you could provide a runnable example, this would help me understand where the problem lies.

I'd also appreciate a reason why `useEffect` doesn't work in this situation. Without a code example, I'm not entirely sure what problem you're experiencing here. Any more info would be appreciated!

**Comment by plausible-phry** [comment]
You could call your reducer's dispatch synchronously during render and prevent out-of-sync rendering that way (yes, that's allowed in React):


```js
const { data } = useQuery(...)
const [{ data: reducerData, lastSeen }), dispatch] = useReducer(({ data, lastSeen }, action) => {
  if (action.type == 'updateFromApollo') {
    const calculatedData = data + action.data // your calculation for a new value here
    return { data: calculatedData, lastSeen: action.data }
  }
  // other calculations here
})
if (lastSeen !== data) {
  dispatch({ type: 'updateFromApollo', data })
}
// work with `reducerData` here.
```


Generally: while that change was a change from our side, we only changed towards React's recommendation for usage of `useSyncExternalStore`, using the method that React provides to signal an update.

Theoretically, that update should be batched together with `setState` and `dispatch` updates that are called synchronously, but in reality, that doesn't happen, due to a bug in React. 
You might want to go over to https://github.com/facebook/react/issues/25191 and give that issue a :+1: - hopefully at some point the React team will fix this batching bug.

**Comment by majoncas-ue** [comment]
Finally I ended up with @plausible-phry solution : handling reducer updates synchronously. This way I've got a predictable way to handle my states as it was for previous Apollo version. Thank you a lot for your explanations and recommandations. I got the full picture now. I will close this ticket.
