### ISSUE TITLE
Subscriptions are cleaned up in sequence rather than in parallel

### ISSUE THREAD

**Issue by raymondwang** [apollographql/apollo-client#11214]
### Issue Description

I'm working on a large project that can render up to 5,000 items on a page at once. Apollo is totally capable of handling this scale in every way except one: unmounting. Performance profiles revealed that the long tail of navigating away from our page is associated with individual `cleanupSubscription` calls, which seem to run in sequence, rather than in parallel:

![Screenshot 2023-09-11 at 1 29 14 PM](https://github.com/apollographql/apollo-client/assets/4248263/154e7399-8a42-405f-a3a4-865401a890ca)

The individual `cleanupSubscription` executions are trivial in speed, but I can't fathom why there's a delay between each one. What can we do to speed this up?

### Link to Reproduction

https://codesandbox.io/s/green-waterfall-zm95k4?file=/src/schema.js

### Reproduction Steps

- Give the page a few seconds to load, it's pre-populated with 2,000 names
- Open browser dev tools
- Set your execution context selector to the iframe (https://stackoverflow.com/a/8581276)
- Open the performance tab in dev tools
- Start recording performance
- Click the "Toggle names" button to unmount all names
- After a second, stop recording performance
- Examine performance profile

A screenshot I grabbed of this performance profile:

![Screenshot 2023-09-13 at 12 25 46 PM](https://github.com/apollographql/apollo-client/assets/4248263/7617832b-63ee-48e7-8f92-114fbb1dc314)

**Comment by phryneas** [comment]
By calling `useQuery` with 2000 different objects, you are creating 2000 instances of `ObservableQuery`, which internally all are observables that your 2000 components subscribe to. 

These are independent objects, each maintaining their own subscribers, so once your 2k components unmount, each of them has to clean up itself.  
Given that JavaScript is a single-threaded language, that *has* to happen in sequence, and since all of these `Observable` objects are independent of each other (watching completely different parts of your cache), it also cannot be batched, as these subscriptions are not held in a central place.

So, from an architectural standpoint: there's nothing we really can do to batch these unsubscribe calls together.

We are already delaying cleanup/unsubscribe for a short moment with `setTimeout` to allow another (or the same) component to synchronously re-subscribe an `ObservableQuery` before it is finally torn down, to prevent additional work from happening here.  
That should play in your favor here, as it might "buffer" things out a bit, with a chance of not totally freezing the browser in-between.

That said, I wonder what would happen if we switched the `setTimeout` for a `requestAnimationFrame` here. Things might get smoother. Let me try that.

**Comment by phryneas** [comment]
Looking at it further, this isn't only about the subscription itself - the example calls `useQuery` with 2000 different arguments, so we simulate 2000 network requests.
This is the real overhead here: not only tearing down the component, but also tearing down the (still running) 2000 network requests.

Take a look at [this "baseline" I derived from your example](https://codesandbox.io/p/sandbox/ac-11214-baseline-n6k4mt?file=/src/layout.jsx:10,13): It has 2001 different subscriptions that also handle network requests etc. - there is just a lot of teardown work to do.

Then compare it with [this example using `useFragment`](https://codesandbox.io/p/sandbox/ac-11214-baseline-forked-wkgfcg?file=/src/index.jsx:33,21) instead. 
It has only one network call, and then 2000 cache reads - tearing down the subscriptions in the end hardly hurts performance here.

**Comment by raymondwang** [comment]
@phryneas Thanks for the reply. I didn't dig into the source to validate whether `useFragment` would have a lighter teardown, and that's extremely good news — we'll get to work converting our nested queries to fragments now!

I'd definitely be curious to see whether a `requestIdleCallback` might improve page performance for cleaning up queries, too! Let me put up a PR for that to see how it feels.
