### ISSUE TITLE
Peer dependency graphql error from apollo-cache-inmemory

### ISSUE THREAD

**Issue by shiraz** [apollographql/apollo-client#11247]
### Issue Description

I get peer dependencies errors regarding graphql package from apollo-cache-inmemory package. The error is below:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: aetn.web.tve@9.50.0
npm ERR! Found: graphql@16.8.1
npm ERR! node_modules/graphql
npm ERR!   graphql@"^16.6.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0" from apollo-cache-inmemory@1.6.6
npm ERR! node_modules/apollo-cache-inmemory
npm ERR!   apollo-cache-inmemory@"^1.6.6" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
```

### Link to Reproduction

https://github.com/shiraz/test-app/blob/main/package.json

### Reproduction Steps

1. Clone https://github.com/shiraz/test-app
2. Cd into the test-app directory
3. Execute the command, `npm i`
4. Observe the errors

Ensure that you are using Node 18 before running the above steps.

**Comment by shiraz** [comment]
It works fine with `legacy-peer-deps` but I do not want to use that option. I'm looking for a better solution without it.

**Comment by bignimbus** [comment]
Hi @shiraz 👋🏻 I see you're using some outdated packages - `apollo-cache-inmemory`, `apollo-client`, `apollo-link`, `apollo-link-http`, and `apollo-link-persisted queries` are years old at this point.  The error you're seeing is due to your `graphql` dependency being set at `16.6.0` where the `apollo-cache-inmemory` package requires `^15.0.0` at the latest.

My recommendation would be to upgrade to the latest version of Apollo Client or, if that's not feasible at the moment, try downgrading `graphql` to a 15.x release.  Thanks!
