### ISSUE TITLE
Unable to globally set ignoreResults mutation option

### ISSUE THREAD

**Issue by namoscato** [apollographql/apollo-client#11312]
### Issue Description

Is the Apollo Client [`defaultOptions`](https://www.apollographql.com/docs/react/api/core/ApolloClient/#defaultoptions) constructor option type:

https://github.com/apollographql/apollo-client/blob/0bcbb2c258c5771e6bb170c59a9ce360645351b4/src/core/ApolloClient.ts#L41

intentionally different from from the `BaseMutationOptions` used in downstream `mutate` / `useMutation` APIs? For example, it does not seem possible to globally override [`ignoreResults`](https://www.apollographql.com/docs/react/data/mutations/#ignoreresults).

### Link to Reproduction

https://codesandbox.io/s/default-options-mutate-type-error-gzjhzq?file=/src/App.tsx:131-441

### Reproduction Steps

```ts
import { DefaultOptions } from "@apollo/client";

const defaultOptions: DefaultOptions = {
  mutate: {
    ignoreResults: true
    // ^ Type '{ ignoreResults: true; }' is not assignable to type 'Partial<MutationOptions<any, any, any, ApolloCache<any>>>'.
    //   Object literal may only specify known properties, and 'ignoreResults' does not exist in type 'Partial<MutationOptions<any, any, any, ApolloCache<any>>>'.
  }
};
```

**Comment by bignimbus** [comment]
Hi @namoscato 👋🏻 thanks for opening this Issue!  This is expected behavior at the moment, the `ApolloClient` constructor doesn't know anything about the React API, which is optional for users.  So the `defaultOptions` object won't accept settings that only apply to the `useMutation` hook, for example.  That said, @phryneas and I were chatting recently and thought it might be nice to expose a new global default options configuration for React-specific settings, but we don't know how/whether this will ship.

Does that answer your question?

**Comment by namoscato** [comment]
Yeah, makes sense – thanks @bignimbus!

We use GraphQL Code Generator's [TypeScript React Apollo](https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-react-apollo) plugin to generate Apollo Client hooks and ended up configuring [`defaultBaseOptions`](https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-react-apollo#defaultbaseoptions) within that context.
