### ISSUE TITLE
Cors issue with Apollo client

### ISSUE THREAD

**Issue by kod-man** [apollographql/apollo-client#11325]
Hi. I have a question about Cors.

I have a login mutation.  

```
const LOGIN_USER = gql`
  mutation ($email: String!, $password: String!) {
    auth_login(email: $email, password: $password) {
      access_token
      refresh_token
    }
  }
`;
```

My index setup here:

```
const client = new ApolloClient({
  uri: 'https://ufuk.site/graphql/system',  cache: new InMemoryCache()
});
```

But I am getting Cors issue
![cors1](https://github.com/apollographql/apollo-client/assets/54946794/ef1f9245-1443-4d74-9361-941b861fcdcf)

If I convert my code to this ( which I found somewhere )

```
const client = new ApolloClient({
  link: new HttpLink({
     uri: 'https://ufuk.site/graphql/system',
    fetchOptions: {
      mode: 'no-cors'
    }
  }),
  cache: new InMemoryCache()
});
```

I got another error.

![cors2](https://github.com/apollographql/apollo-client/assets/54946794/d48e8ad4-7070-437e-8ade-fc8bd35e3133)

Can someone help me to fix it?

**Comment by hunginf** [comment]
Same with me on nextjs (_ _!)

**Comment by bignimbus** [comment]
Hi @kod-man and @hunginf 👋🏻 thanks for opening/commenting on this Issue!  Without more information I doubt we can narrow down the specific issue in your application code.  There's nothing here to indicate a bug in Apollo Client so I'm going to close this - thanks for understanding 🙏🏻  I would like to invite you to join our [Discord](https://discord.gg/graphos) and/or our [Forum](https://community.apollographql.com) to ask questions like these, and I encourage you to share as much information as you can in order to get high-quality answers.  Thanks!
