### ISSUE TITLE
useQuery can unexpectedly return partial data

### ISSUE THREAD

**Issue by PhoebeSzmucer** [apollographql/apollo-client#11400]
### Issue Description

I found a bug that can cause useQuery to return partial data if one query fails, a second **overlapping** query then succeeds, and **notifyOnNetworkStatusChange** is enabled.

This partial data can be missing fields that are required, which can easily crash the application (happened twice already in my production app).

### Link to Reproduction

https://codesandbox.io/p/devbox/muddy-frog-qgryrg?file=%2Fsrc%2Findex.jsx

**Comment by krhsiung** [comment]
We are running into a similar issue. High level:
- In our app a `list` has many `books`
- We have a `ComponentA` that has a `useQuery` hook executing a query `query BooksForList_A(listid) {  books { id status } }`. `notifyOnNetworkStatusChange` is true
- We have a `ComponentB` that has a `useQuery` hook executing a query `query BooksForList_B(listid) {  books { id } }`. `notifyOnNetworkStatusChange` is true.
- `ComponentB` learns about a new book under this list, it's listening to updates on the server. It executes its query and places a new book with just the id into the cache
- *Something* (in our case an api response) causes the app to run the same `BooksForList_A` query as `ComponentA` against just the cache. `diffQueryAgainstStore` correctly detects that there are missing fields and returns null on this read.
==> This read appears to cause the `useQuery` inside `ComponentA` to return new partial data. `ComponentA` fails to render because it expects `status` to be present on all `books`

**Comment by Kavian77** [comment]
We are experiencing the exact same issue. Is anybody looking into it by any chance? 🙂

**Comment by dylanwulf** [comment]
@jerelmiller That's fine, thanks for taking a look!
