### ISSUE TITLE
Can't disable cache normalization globally

### ISSUE THREAD

**Issue by amannn** [apollographql/apollo-client#11488]
### Issue Description

@phryneas [mentioned on Twitter](https://twitter.com/phry/status/1737159481656541346) that it should be possible to disable cache normalization globally in Apollo Client:

> You could have the `dataIdFromObject` option set to a function that always returns `null` - that should do it.

I tried this approach in an app, but unfortunately, the cache still appears to be normalized, leading to an error being printed when queries overlap.

### Link to Reproduction

https://codesandbox.io/p/devbox/apollo-client-disable-normalization-svk8yx

### Reproduction Steps

1. Go to [reproduction](https://codesandbox.io/p/devbox/apollo-client-disable-normalization-svk8yx?file=%2Fsrc%2FApp.jsx%3A34%2C65)
2. See error on console

> An error occurred! For more details, see the full error text at [link](https://go.apollo.dev/c/err#%7B%22version%22%3A%223.8.8%22%2C%22message%22%3A14%2C%22args%22%3A%5B%22person%22%2C%22Query%22%2C%22either%20ensure%20all%20objects%20of%20type%20Person%20have%20an%20ID%20or%20a%20custom%20merge%20function%2C%20or%20%22%2C%22Query.person%22%2C%22%7B%5Cn%20%20%5C%22__typename%5C%22%3A%20%5C%22Person%5C%22%2C%5Cn%20%20%5C%22id%5C%22%3A%20%5C%221%5C%22%2C%5Cn%20%20%5C%22firstName%5C%22%3A%20%5C%22John%5C%22%5Cn%7D%22%2C%22%7B%5Cn%20%20%5C%22__typename%5C%22%3A%20%5C%22Person%5C%22%2C%5Cn%20%20%5C%22id%5C%22%3A%20%5C%221%5C%22%2C%5Cn%20%20%5C%22lastName%5C%22%3A%20%5C%22Smith%5C%22%5Cn%7D%22%5D%7D)

The cache looks like this after the two queries have executed:

<img width="191" alt="Screenshot 2024-01-15 at 13 43 48" src="https://github.com/apollographql/apollo-client/assets/4038316/d2a907dd-cdb1-4e70-9efa-2c9cd10a1b5a">

I'd expect that if normalization is disabled, the _query names_ would correspond to the cache keys of individual documents (`Query1` and `Query2` in my example). E.g. if you compare urql for example, they use an approach called [document caching](https://formidable.com/open-source/urql/docs/basics/document-caching/) by default, where a query and its variables are serialized to a cache key, avoiding the issue outlined here.

## Additional context

In the same Twitter discussion, there was a mention that [fuzzy type policies could be used for this purpose](https://github.com/apollographql/apollo-client/issues/11480), but that's not unfortunately not the case since [there are no fuzzy type policies](https://github.com/apollographql/apollo-client/issues/11480) (only fuzzy possible types).

Related:
- https://github.com/apollographql/apollo-client/issues/6509
- https://github.com/apollographql/apollo-feature-requests/issues/109

**Comment by phryneas** [comment]
The error you are getting here is exactly because your query is not normalized.

Let's look at the cache contents with query normalization not disabled:

```json
{
  "Person:1": {
    "__typename": "Person",
    "id": "1",
    "firstName": "John",
    "lastName": "Smith"
  },
  "ROOT_QUERY": {
    "__typename": "Query",
    "person({\"id\":1})": {
      "__ref": "Person:1"
    }
  }
}
```

Here, `Person:1` is normalized into it's own cache entry - each entity is stored independently of each other entity, you have no nesting and only references.

Now, look at the cache you get when you disabled normalization:
```json
{
  "ROOT_QUERY": {
    "__typename": "Query",
    "person({\"id\":1})": {
      "__typename": "Person",
      "id": "1",
//    "firstName": "John",
      "lastName": "Smith"
    }
  }
}
```

Now, the cache has only one cache entry: `ROOT_QUERY` -  and it's fields just get merged together - and when merging the old `ROOT_QUERY["person({\"id\":1})"]` with the new `ROOT_QUERY["person({\"id\":1})"]` field, Apollo Client has no knowledge of "object identity", so it cannot tell if the old value stored here actually corresponds with the new value that should be stored here, so it cannot blindly merge them (unless you tell it so in a type policy). To be on the safe side, it will assume they are different objects and the new one will override the old one completely.

Now, from this we can kinda see that "disabling normalization" is not really the same as "getting a document cache" - as that lacks the second part of "each query stored individually".

> the query names would correspond to the cache keys of individual documents 

That's unfortunately not the case - the document doesn't really play a role in the cache. Right now I'm not sure if it's possible to emulate this behaviour, but I'll try to think of it more, maybe I come up with something.

**Comment by amannn** [comment]
Thank you for the detailed response! 

I see, I guess the question about "is the cache normalized" can be answered differently based on if normalization is considered as merging real entities in the cache based on an ID, or if it's about merging any kind of objects in the cache from multiple queries (e.g. based on a field and its argument on the root type).

I'll close this issue then as I understand this is working as designed.
