### ISSUE TITLE
How to do request in ssr component Strapi + Next js App Router with GraphQL + Apollo

### ISSUE THREAD

**Issue by ZaharBerku** [apollographql/apollo-client#11646]
### I have set up a next js project with strapi and I am querying with GraphQL + Apollo, and now I want to query using Apollo in ssr component, I get this error -

> Error: Attempted to call query() from the server but query is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.

How to make a request to use Apollo in an SSR component without using "@apollo/experimental-nextjs-app-support/ssr" or maybe someone knows good alternatives to [Apollo](https://www.apollographql.com/docs/)

My code
```
lib/client.tsx

"use client";

import { InMemoryCache, ApolloClient, ApolloProvider } from "@apollo/client";
import { PropsWithChildren } from "react";

const STRAPI_URL = process.env.STRAPI_URL || "http://localhost:1337";

export function createApolloClient() {
  const client = new ApolloClient({
    uri: `${STRAPI_URL}/graphql`,
    cache: new InMemoryCache()
  });
  return client;
}
export const client = createApolloClient();

export function ApolloWrapper({ children }: PropsWithChildren) {
  return <ApolloProvider client={client}>{children}</ApolloProvider>;
}
```

```
app/page.tsx

import { RootFooter, RootMain } from "@/compoents/organisms";
import { GETQUERY } from "@/query/schema";

import { client } from "@/lib/client";

export default async function Home() {
  const data = await client.query({
    query: GETQUERY
  });
  console.log(data, "data");
  return (
    <>
      <RootMain>
        <h1 className="text-white">{}</h1>
      </RootMain>
      <RootFooter />
    </>
  );
}
```

```
query/schema.ts

import { gql } from "@apollo/client";

export const GETQUERY = gql`
  {
    todos(sort: "id:desc") {
      data {
        id
        attributes {
          todoText
          createdAt
        }
      }
    }
  }
`;
```

**Comment by phryneas** [comment]
> How to make a request to use [Apollo](https://www.apollographql.com/docs/) in an SSR component without using "@apollo/experimental-nextjs-app-support/ssr" or maybe someone knows good alternatives to Apollo

The only supported way of using Apollo Client in the Next.js app directory is the `@apollo/experimental-nextjs-app-support`  package.

Please don't get intimidated by the word `experimental` in the title - it's as stable as any client library can at this point possibly be with the Next.js App router implementation that uses React Server Components and Streaming SSR.  

It has some edge cases where timing is not optimal (and those are documented in the README and documents linked to from there), but this is due to missing React APIs. If you want to use Next.js there is no way to get around those edge cases, neither with a library (other libraries use the exact same workarounds we use) nor with hand-written code.  
We just keep the word `experimental` in the package name to put emphasis on that fact, which everyone using the App Router should be aware of.

**Comment by phryneas** [comment]
Also, please be aware that the code you are currently using is extremely unsafe - you create one global Apollo Client instance.  

During SSR, this will mix data from all your users, so as soon as you have authenticated user data in cache, it will be mixed up between users (and because you are not using the `nextjs-app-support` package, there is also no way of transporting data from SSR to the Browser, duplicating all your requests).

The patterns we have documented over in the `nextjs-app-support` README will steer you around those risks.

I *assume* that with all that, the question has *kinda* been answered, so it's probably okay for me to close the issue. If you have any more questions, please do so, though :)
