### ISSUE TITLE
useFragment accepts a generic type, but it converts it into a DeepPartialObject. what is the best usage in here to avoid using DeepPartialObject?

### ISSUE THREAD

**Issue by paolojulian** [apollographql/apollo-client#11701]
We have just started implementing useFragment. But the problem is we need to add typeguard of use typecast for the DeepPartialObject. useQuery is not doing this.

<img width="747" alt="image" src="https://github.com/apollographql/apollo-client/assets/20264121/6835b6bf-2671-490c-a259-98fb37a01daa">

**Comment by jerelmiller** [comment]
Hey @paolojulian 👋 

This happens because we don't know if the cache can fulfill the entirety of the `fragment` or not. `useFragment` will return any data it can, therefore it can be partial. `useFragment` also returns a `complete` property that you can use to determine if the cache could fulfill the entire fragment. The types will adjust to the non-partial type if you check for `complete` first.

```ts
const { complete, data } = useFragment<MyFragment>({ fragment })
//                 ^? DeepPartial<MyFragment>

if (complete) {
  data
// ^? MyFragment
}
```

Hope this helps!

**Comment by paolojulian** [comment]
@jerelmiller 
Ahhh, I wonder why I didn't notice it 😅 , i was also looking at the useFragment.d.ts but didn't catch it, thanks for this!

**Comment by jerelmiller** [comment]
You're welcome! Glad I could help 🙂
