### ISSUE TITLE
[Testing utilities] Custom fetch implementation via context

### ISSUE THREAD

**Issue by alessbell** [apollographql/apollo-client#11710]
### Issue Description

@phryneas had a great idea here: instead of requiring users to use an test env-specific terminating link of `SchemaLink`, use a custom `fetch` implementation via context that effectively turns `HttpLink` into a `SchemaLink`.

### Link to Reproduction

N/A

### `@apollo/client` version

N/A

**Comment by alessbell** [comment]
@jerelmiller also had an idea here around setting a threshold (min/max) values for response timing

**Comment by jerelmiller** [comment]
Yes! To write it out, we want to mimic a real client/server interaction as much as possible, which means that there will always be variable latency in the request. We absolutely DON'T want the mocked request to be synchronous because a network request is always asynchronous (something we see too often in `MockedProvider` unfortunately). Allowing a min/max for response timing allows us to randomize the synthetic latency to better mimic a production environment. This also provides better guarantees that your tests aren't passing purely because the request timing is favorable.

**Comment by alessbell** [comment]
Completed via https://github.com/apollographql/apollo-client/pull/11605
