### ISSUE TITLE
Polling does not stop after unmounting query

### ISSUE THREAD

**Issue by dylanwulf** [apollographql/apollo-client#11750]
### Issue Description

When I mount a polling query and then later unmount it, I would expect the polling to stop. But instead the polling seems to continue.

### Link to Reproduction

https://github.com/dylanwulf/react-apollo-error-template/tree/polling-doesnt-stop

### Reproduction Steps

- Start my reproduction on branch `polling-doesnt-stop`
- Open the console
- Click the "Toggle Polling" button to start polling
- See the polling query log to the console
- Click the "Toggle Polling" button again to stop polling
- See that the polling query continues being logged to the console

### `@apollo/client` version

tried 3.7.12 & 3.9.9, problem exists in both

**Comment by jerelmiller** [comment]
Thanks for the report @dylanwulf! We've got 3.10 in rc that we'll be releasing next week. We'll see if we can take a look at this sometime after that goes out 🙂

**Comment by jerelmiller** [comment]
Hey @dylanwulf 👋 

I've got a fix for this issue in #11837. Thanks so much for your reproduction which helped me narrow down the issue here!

I can confirm that installing the snapshot release fixes this issue. If you'd like to try it yourself, you can install it with the following command:

```
npm i @apollo/client@0.0.0-pr-11837-20240509172621
```

We should be able to get this out with the next patch release.
