### ISSUE TITLE
React functionality 'useContext' is not available in this environment [Nextjs app]

### ISSUE THREAD

**Issue by MiguelG97** [apollographql/apollo-client#11857]
### Issue Description

I encountered this issue while integrating apollo client graphql in a nextjs app.

Apparently apollo is using rehackt npm package and somehow it's not exporting the useContext functionality:

### Link to Reproduction

code below

### Reproduction Steps

in a nextjs project, wrap the content with the apolloProvider in a LAYOUT page!:

```
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ReduxContext>{children}</ReduxContext> */}

        <ReduxContext>
          <ApolloProvider client={client}>
            {children}
          </ApolloProvider>
        </ReduxContext>
      </body>
    </html>
  );
}
```

### `@apollo/client` version

^3.10.4

**Comment by alessbell** [comment]
Hi @MiguelG97 👋  If you haven't already, you may want to check out our `@apollo/experimental-nextjs-app-support` library at https://github.com/apollographql/apollo-client-nextjs

To your question, Apollo Client does use `rehackt` - if you're curious as to why, there's more information in [its README](https://github.com/phryneas/rehackt).

But back to the error you're seeing: is an RSC rendering your `RootLayout`? If that's the case, I would expect you to see that error since React context is not supported in Server Components.

**Comment by MiguelG97** [comment]
thanks for the hints, apparently if I create another react component and label it as "use client", it lets me wrap the layout content without issues
