### ISSUE TITLE
Custom ApolloLink using `next.subscribe` is making duplicated requests

### ISSUE THREAD

**Issue by jca41** [apollographql/apollo-client#11871]
### Issue Description

Given the example custom link

```ts
export class MyLink extends ApolloLink {
  constructor() {
    super((operation, forward) => {
      const next: Observable<FetchResult> = forward(operation);

      next.subscribe({
        error: (e) => {
          console.log(e);
        },
        next: (result) => {
          console.log(result);
        },
      });

      return next;
    });
  }
}
```

By using `next.subscribe` i'm seeing duplicated queries/mutations.

This happened after bumping from `3.7.14` to `3.10.4`.

Any help debugging this issue would be appreciated!

### Link to Reproduction

https://github.com/jca41/link-subscribe-duplicated-requests

### `@apollo/client` version

3.10.4

**Comment by jca41** [comment]
Updated description with repro link: https://github.com/jca41/link-subscribe-duplicated-requests

**Comment by jca41** [comment]
Also would suggest the team to have a bug report template that uses an external API via HTTP.

**Comment by jerelmiller** [comment]
Hey @jca41 👋 

This is actually expected behavior due to how observables work. Anytime you `subscribe` to it, it will execute that observable's callback function. If you look at `HttpLink`, you'll see that [callback function](https://github.com/apollographql/apollo-client/blob/d502a69654d8ffa31e09467da028304a934a9874/src/link/http/createHttpLink.ts#L179-L214) is where the `fetch` happens. In the example you've given, you're calling `subscribe` in the link and returning the same observable back to `ApolloClient` which subscribes itself to that observable, hence why you end up with two network requests.

There are a couple different ways you can fix this:

1: Use `.map` instead of `.subscribe` which lets you observe the emitted result but returns a new observable back to Apollo Client core. The downside here is that you'll only be able to observe the `next` values and not the `error` values. If you need access to errors, try #2.

```js
export class MyLink extends ApolloLink {
  constructor() {
    super((operation, forward) => {
      const next: Observable<FetchResult> = forward(operation);

      return forward(operation).map((result) => {
        console.log(result);
      });
    });
  }
}
```

2. Return a new observable that emits results from the forwarded observable. This ensures the observable that Apollo Client subscribes to isn't the same one that creates the network request. This is the technique that several of our built-in links do in order to add additional behavior.

```js
export class MyLink extends ApolloLink {
  constructor() {
    super((operation, forward) => {
      return new Observable((observer) => {
        const subscription = forward(operation).subscribe({
          next: (result) => {
            console.log(result);
            observer.next(result);
          },
          error: (e) => {
            console.log(e);
            observer.error(e);
          },
          // very important that you include this to ensure you let the observer
          // know this operation is completed!
          complete: observer.complete.bind(observer)
        });
      })
    });
  }
}
```

Try either of these and see if this works better for you!

**Comment by jerelmiller** [comment]
Definitely interesting that it deduped before since it probably shouldn't have 😆. Hope the suggestions work for you 🤞

**Comment by jca41** [comment]
Thanks @jerelmiller second option seems to be working great! 😊

**Comment by jerelmiller** [comment]
Glad to hear it!
