### ISSUE TITLE
Improving updateQueries

### ISSUE THREAD

**Issue by marktani** [apollographql/apollo-client#1200]
This is primarly feedback based on a discussion I had with @helfer.

I'm having a hard time wrapping my head around `updateQueries`, especially when things go wrong. So I'm starting this discussion to see if we can come up with an improvement here.

Consider this mutation with `updateQueries` from [this Apollo subscriptions example](https://github.com/graphcool-examples/react-apollo-instagram-subscriptions-example):

```js
const addMutation = gql`
  mutation addPost($description: String!, $imageUrl: String!) {
    createPost(description: $description, imageUrl: $imageUrl) {
      id
      description
      imageUrl
    }
  }
`

const PageWithMutation = graphql(addMutation, {
  props: ({ ownProps, mutate }) => ({
    addPost: ({ description, imageUrl }) =>
      mutate({
        variables: { description, imageUrl },
        updateQueries: {
          allPosts: (state, { mutationResult }) => {
            const newPost = mutationResult.data.createPost
            return {
              allPosts: [...state.allPosts, newPost]
            }
          },
        },
      })
  })
})(withRouter(CreatePage))
```
and this query:

```js
const FeedQuery = gql`query allPosts {
  allPosts(orderBy: createdAt_DESC) {
    id
    imageUrl
    description
  }
}`

const ListPageWithData = graphql(FeedQuery)(ListPage)
```
A few pains I have with the current API:

* the definition of a `updatedQueries` requires me to nest functions and objects all over the place. Whenever I come back to a `updateQueries` definition that I've written a week ago and something is not working, it takes a lot of time to compare with the examples [in the docs](http://dev.apollodata.com/react/cache-updates.html#updateQueries) 

* Having to deal with multiple names is really confusing - the query can be referred to with `FeedQuery` or `allPosts`. I could probably change `query allPosts` to `query FeedQuery` - would I then have to update the `allPosts` in `updateQueries` to `FeedQuery` as well? The same is true for mutations - `addMutation`, `addPost` and `createPost` appear above. Should we throw a warning when the variable name of a query/mutation is different than the operation name? Apollo seems to only need the operation name.

* I have found no way to debug `updateQueries` when it is not called. For example, if I choose a wrong name as discussed earlier - there could be a warning because there is no known query with that name. Maybe other features could be added to Apollo Dev Tools to help with this problem.

Looking forward for your thoughts :slightly_smiling_face:

**Comment by helfer** [comment]
Thanks for writing this up @marktani !

For the first point, is your concern with the syntax that react-apollo makes you use, or is it a general thing about updateQueries? I.e. is the complexity in the update function, or is it around it? If it's the latter have you tried using `reducer` instead? That could make the code a bit cleaner.

For the second point, I agree that it's not great that we depend on global names here, but the only alternative I can think of is to explicitly pass the query and variables in there, and I'm not sure if that's more or less convenient. If you had to pass the query itself, would that be better for you? E.g. instead of writing:

```
updateQueries: {
    Comment: (prev, { mutationResult }) => {
        /// ....
    },
},
```
You would have to write something along the lines of:
```
updateQueries: {
updateQueries: [
    {
      query: COMMENT_QUERY,
      variables: { ... },
      updateFunction: (prev, { mutationResult }) => {
        /// ....
    ],
},
```

Another idea for the second point is to use the `reducer` function on that query, because then you don't have to name the query any more, and each query will be responsible for updating its own part of the cache.

The third point is definitely something which we should improve. Once we settle on a solution for the updateQueries/reducers not running issue, we'll see how we can improve integration with devtools so it's easy to figure out why an updateQueries/reducer function ran or didn't run.

**Comment by marktani** [comment]
>  If it's the latter have you tried using reducer instead? That could make the code a bit cleaner.

Have to check that out, haven't looked at `reducer` yet. See my concerns regarding `reducer` below.

> If you had to pass the query itself, would that be better for you?

No, I don't think so. So maybe using global names is the best we can get. Actually this is more of a problem because of my inconsistent naming - but it's not obvious how the naming work. A best-practice in the docs regarding naming queries and mutations could help with that.

> Another idea for the second point is to use the reducer function on that query, because then you don't have to name the query any more, and each query will be responsible for updating its own part of the cache.

Hm, right. This could be an improvement, however I think controlling the cache update when the mutation happens is more natural. What if I have different 'overlapping' queries in different parts of my app? Then it's not clear how their `reducer`s would interact.

**Comment by calebmer** [comment]
> > If you had to pass the query itself, would that be better for you?
>
> No, I don't think so.

@marktani could you go in more depth here why this wouldn’t work for you? I’m personally in favor of this option because it would also allow you to essentially write a single “fat query” that needs to be updated like so:

```js
{
  updateQuery: {
    query: gql`{
      fieldA
      fieldB
      myConnection(page: 1) {
        fieldC
        fieldD
      }
    }`,
    updateFunction: () => { ... },
  },
}
```

One addition to @helfer’s proposal, though. Instead of passing variables, you would pass literals or you could use a special `ALL` value like so:

```js
{
  updateQuery: {
    query: gql`{
      fieldA
      fieldB
      myConnection(page: ALL) {
        fieldC
        fieldD
      }
    }`,
    updateFunction: () => { ... },
  },
}
```

That would update any variable set that Apollo Client has seen for that field. This also solves some other issues people are seeing with update queries and changing variables.

**Comment by marktani** [comment]
I think @helfer suggested to `import` a query from another component which creates dependencies between components independent from React's component hierarchy - my initial feeling tells me that's not good.

Not sure about your proposal. It's a dramatic change of the API, I think this would require a lot of refactoring. Even though having this option feels really powerful to me.

**Comment by calebmer** [comment]
I think it could be trivial to have support for both `import`ing queries and allowing users to write free form queries. As far as implementation goes the hardest part would be tracking variables to allow support for an `ALL` styled feature. Otherwise we just use the current read/write store logic.

**Comment by marktani** [comment]
Ah, this could also be useful regarding helfer's proposal: https://dev-blog.apollodata.com/webpacking-your-graphql-documents-bf9697ed259b#.bars4yk39

**Comment by Poincare** [comment]
Agree with @calebmer. Given that we now have webpack support for query imports, it seems reasonable to use those instead of introducing a global namespace across query names.

**Comment by helfer** [comment]
Let's continue this discussion in #1224
