### ISSUE TITLE
Query results are merged together even when parameters are different

### ISSUE THREAD

**Issue by Tam** [apollographql/apollo-client#12235]
### Issue Description

I have two queries that get different data from the same endpoint:

```gql
query {
    departments: options(condition: { type: department }) {
        nodes {
            id
            label: name
            value: id
        }
    }
    jobTitles: options(condition: { type: job_title }) {
        nodes {
            id
            label: name
            value: id
        }
    }
}
```

When I output the data `data.departments` and `data.jobTitles` both show the same data, with their results merged.

We're using the `InMemoryCache` and `@apollo/experimental-nextjs-app-support` version 0.11.7

### Link to Reproduction

N/A

### Reproduction Steps

Try to query data from the same endpoint with different parameters in a single query.

### `@apollo/client` version

3.12.2

**Comment by jerelmiller** [comment]
Hey @Tam 👋 

What do your type policies look like? These should write to separate cache keys as long as you haven't set `keyArgs` to `false`, otherwise they will get merged into the same cache key. Can you check the cache and see what it looks like after you execute this? You can either use the [devtools browser extension](https://chromewebstore.google.com/detail/apollo-client-devtools/jdkknkkbebbapilgoeccciglkfbmbnfm) or log it to the console with `client.extract()`

**Comment by Tam** [comment]
@jerelmiller Ah, yep, we had a pagination function that was setting `keyArgs` incorrectly. Thanks for your help!
