### ISSUE TITLE
Add support for `queryTransformers`

### ISSUE THREAD

**Issue by ckimes89** [apollographql/apollo-client#1239]
I would like to be able to arbitrarily transform each query before it reaches the network layer (and before it reaches the cache). Possible usage could look like this:

```
import ApolloClient, { addTypenameTransformer } from 'apollo-client';

const myQueryTransformer = function(query) {
    transformedQuery = // do transformation here
};

const client = new ApolloClient({
  queryTransformers: [ addTypenameTransformer, myQueryTransformer ]
});
```

As shown in the example, the existing special case `addTypename` field could be replaced with a general purpose array of transformation functions.

Implementation would be fairly simple - each place that `addTypenameToDocument` is called ([example](https://github.com/apollostack/apollo-client/blob/d6b3dcffdabb661920fa029ca655c820189b9982/src/core/QueryManager.ts#L694)) could simply be replaced with a reduce through the `queryTransformers` array. Something like:

```
query = this.queryTransformers.reduce((q, transform) => transform(query), query);
```

I think this would be a nice addition to allow users to modify queries before they are executed, and to remove the special case handling of `addTypename`.

**Comment by helfer** [comment]
@ckimes89 We used to have that, and it's in fact how `addTypename` is implemented. However, it turned out that `addTypename` was the only use-case anyone came up with, so we removed the feature and now recommend that people transform queries before passing them to Apollo Client.

To have a more useful discussion, what is the specific use-case you have in mind?

**Comment by ckimes89** [comment]
I would like to remove fields at runtime based on user permissions. I had planned to use a fake directive that only the client-side knew about. For example, you could write a query like this:

```
{
  employees {
    id
    name
    salary @has(role: 'admin')
  }
}
```

The query transformer would then check each field for the directive. If the directive exists and the user does not have the specified permission, then the field is removed from the query. If the directive exists and the user does have the permission, then the field is kept but just the directive is removed.

It's important to note that this is not relying on the client for security. On the server we would like to return an error if the client queries for a field that they're not allowed to see. However, that means that the client needs to shape queries based on user roles and permissions.

I'm currently working with `react-apollo` where React components are wrapped with a static query before they are used in JSX. I haven't found a particularly clean way to transform a query before execution in that situation.

**Comment by calebmer** [comment]
I think there are a couple of better options here for you @ckimes89 then implementing a `queryTransformers`.

Firstly, we are hesitant to add a `queryTransformers` feature because we want to move Apollo Client to a static query world. A static query world has a number of important benefits when it comes to predictability for the server team. This is why Apollo Client does not do query diffing.

Your proposal here is inherently dynamic. It would modify a query in unpredictable ways that depend on runtime variables making queries very hard to persist and to predict. So in general, we want to push users to a static query world which makes us hesitant to add this feature.

Secondly, there is an alternative to what you have implemented which is in the GraphQL specification! So you know we will support it forever 😊

You could use the `@include` or `@skip` directives like so:

```graphql
query ($isRoleAdmin: Boolean!) {
  employees {
    id
    name
    ... @include(if: $isRoleAdmin) {
      salary
    }
  }
}
```

This provides the same basic functionality as your proposal except it is supported by the spec, and most importantly *static*. While yes you will need to convert a complex role system to a set of boolean variables, I don’t think that drawback alone is enough to pursue a dynamic query approach like the one you suggest. We could also discuss adding some basic boolean operators to the GraphQL specification `==` and `!=` if the combinatorial combination of booleans in your role system really is too big.

Thirdly, I hope I convinced you that static queries are better than dynamic queries, but in case I haven’t I don’t see how a global query transformer is better than a local query transformer. A function like `stripRoleBasedFields` that you call before passing your queries into the Apollo Client.

This approach has an important advantage because there are no more implicit global transformations or costs associated with creating a query, but also there is no more implicit global dependency on a user object. The signature could be: `stripRoleBasedFields(user, documentAST)`.

Personally, I feel like this would be a better approach, but I would love to hear if your opinion differs from mine on this one and why.

Finally, if there’s a change we *really* need to make in Apollo Client to support your pattern it is to make sure that GraphQL errors are not fatal.

This means that if the GraphQL server returns an error with `errors`, but still returns some `data` then `react-apollo` should still give you the data it got from the server along with the errors instead of just dying as it does now.

We should also strive to find a better way to represent GraphQL errors with paths. My favorite approach to this is to make an object for your errors, the shape of which mirrors your data except all of the scalar values are `null`. For all errors with a path then the null at the position in that path will be replaced with an error. With this, you would be able to render components with their errors like:

```jsx
<Employee employee={data.employees[i]} employeeError={errors.data.employees[i]}/>
```

Then the errors you throw on the server would not destroy the client. The client could instead handle your errors directly.

If you can’t wait for this feature you could just start returning `null` for `salary` for non-admins right now! It would provide this same basic functionality and as long as this behavior is documented you have the lowest friction way of hiding data from unprivileged users.

* * *

Let me know what you think. Ultimately I think `queryTransformers` (while a cool idea) could become an anti-pattern if used for dynamic purposes, and it would not be worth implementing when there are viable alternatives.

**Comment by helfer** [comment]
I think @calebmer put it pretty well. For the use-case you mentioned, a queryTransform would not be the right approach.

**Comment by ckimes89** [comment]
> Firstly, we are hesitant to add a queryTransformers feature because we want to move Apollo Client to a static query world.

@calebmer I understand the back-end benefits of static queries, but I don't see why that should impact the design choices a front-end library. It seems that Apollo Client could benefit from supporting a wider variety of querying patterns rather than just trying to enforce that everyone use static queries.

> You could use the @include or @skip directives like so:

That was one of the first things I considered, however it doesn't quite work out with the way we intend the server to work. We would like for fields to be completely hidden from the user if they don't have access to them, that is to say that they aren't returned from introspection and they are not queryable. The ideal case is that each user could be handed a GraphiQL client and be presented a completely consistent view of the world - without leaking information through the existence of admin-only fields.

The `@include` and `@skip` directives don't work very well with this, since in my understanding of the spec the fields that the user doesn't have access to would be a validation error before the directives are ever handled.

> Thirdly, I hope I convinced you that static queries are better than dynamic queries, but in case I haven’t I don’t see how a global query transformer is better than a local query transformer.

I agree. However, as I mentioned in my above post I am using `react-apollo` which seems to be designed around wrapping React components with static queries. If you have any thoughts on how to intercept those queries in `react-apollo` before they are passed to `apollo-client` then that would be very helpful.

**Comment by calebmer** [comment]
> The `@include` and `@skip` directives don't work very well with this, since in my understanding of the spec the fields that the user doesn't have access to would be a validation error before the directives are ever handled.

Yes it would cause in error in this case, but it’s your GraphQL server, so do whatever you want with validation rules! 😊

You could also add a `@has` directive on the backend and do query transforms there. This might be the best option for your use case.
