### ISSUE TITLE
Idea: Split network layer

### ISSUE THREAD

**Issue by DxCx** [apollographql/apollo-client#1272]
Hi,

I was thinking maybe we should create another repo,
mono-repo for network interfaces. (or even split this one, open for discussion of-course)
so the base package will hold only the interfaces (as typescript interface)
then the sub-packages will hold the network layer implementation.
then we can achieve a similar solution to what we have on `graphql-server`
while also gaining the ability to use only the network interface,
so for example, you will be able to import just network interface and send graphql requests for the server without the whole apollo management system. (for example, use the same network interface in graphiql as we use in apollo client)

also, people will try and contribute  to here rather then open another repo,
and people who looks for a specific solution will come to this repo to see if someone else already worked on that solution.

@helfer @stubailo @Urigo (and ofcourse others are welcome to comment as well.. :))
what do you think?

**Comment by helfer** [comment]
@DxCx I think that's a great idea! I remember we thought about this a couple of times. I also like @calebmer 's idea of getting rid of the name `networkInterface`. We should call it `executor` instead, because in some cases there may not be any network involved, and the client really doesn't need to know where the GraphQL query really gets executed. From the perspective of the client, calling the executor should be just like calling `graphql`.

**Comment by helfer** [comment]
Let's keep track of this in #774, which talks about roughly the same thing.
