### ISSUE TITLE
Global query / mutation state - any requests running

### ISSUE THREAD

**Issue by manuelfink** [apollographql/apollo-client#1311]
I'm thinking of implementing a global loading indicator which is independent from the single request observers. Is it anyhow possible to monitor the global request state from apollo-client to know if any queries / mutation are running to show one loading / saving notifications based on it?

**Comment by calebmer** [comment]
We currently don’t provide any public method for accessing this information, but you could look into `apollo-client` Redux state and select the information yourself. You’d be looking at the `queries` map which contains all queries that Apollo has made during the current session’s lifetime, and includes `networkStatus` information for each of these queries.

It is possible and we encourage you to try this if you are interested, but we do not officially recommend this approach. Test this part of your code _thoroughly_ and be ready to tolerate errors because the internal Redux store format for queries may break in any version and without warning. Although it is worth noting that unless we do some major refactors then the store shape for queries is relatively stable.

I don’t think this is a feature we would want to add at the moment, but we may consider it in the future.

**Comment by amannn** [comment]
@manuelfink I just released a library that solves this problem for Apollo 2: [react-apollo-network-status](https://github.com/molindo/react-apollo-network-status)

Maybe this is helpful to you 🙂
