### ISSUE TITLE
IE10 issue with findIndex on retQuerySubscription in ObservableQuery.ts

### ISSUE THREAD

**Issue by unkleho** [apollographql/apollo-client#1394]
Hi Apollo Team,

Just having an issue with this line here in IE10:
https://github.com/apollographql/apollo-client/blob/master/src/core/ObservableQuery.ts#L432

IE10 shows:
```SCRIPT438: Object doesn't support property or method 'findIndex'```

I got it working by adding the polyfill from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex

Not sure what the best permanent fix is - perhaps a slight refactor to use something other than findIndex.

Thanks

**Comment by helfer** [comment]
Thanks @unkleho ! I think IE 10 has less than 0.5% market share now, so this is not high priority for us to fix. However, I would definitely accept a PR that uses something other than `findIndex`. 🙂

**Comment by unkleho** [comment]
Totally understand. We are only supporting it because our organisation is still using it. Anyway at least it is now documented. I'll submit a PR if I find some time.

Btw we just soft launched this last week - https://collection.maas.museum. Uses apollo-client and react-apollo.

**Comment by djshapiro** [comment]
I assume @unkleho was using an older version of apollo-client, like I was. When I pulled v1 in order to try to fix this with a polyfill for findIndex, I found I also needed polyfills for startsWith and forEach. So I tried adding babel-polyfill and way surpassed the 27kB size limit for apollo-client. That's as far as I can go, unless @helfer has any suggestions.
