### ISSUE TITLE
Feature Request: Option to show deprecated field warnings

### ISSUE THREAD

**Issue by frankdugan3** [apollographql/apollo-client#1402]
**Use case**
It would be very helpful for code maintenance if there were an option to show console warnings when a query/mutation/subscription uses a deprecated field. Presumably, this would only occur in a dev environment unless otherwise specified.

**Could this be a plugin?**
It would make more sense as a core config option, but either way is fine.

**Is there a workaround?**
To my knowledge, no. But I'd be happy to learn of one.

**Comment by helfer** [comment]
@frankdugan3 I think the best way right now would be to use eslint-plugin-graphql and make it print warnings when deprecated fields are used.

I think it's a great idea, but in Apollo Client such a feature is currently not possible, because Apollo Client doesn't load the schema from the server, so it has no knowledge of which fields are deprecated.

**Comment by stubailo** [comment]
Another great way to do this would be for the server to return warnings in this case.
