### ISSUE TITLE
Imperative API and cache invalidation

### ISSUE THREAD

**Issue by tlvenn** [apollographql/apollo-client#1459]
Hi, in some cases, we need to be able to simply notify clients to invalidate some data rather than giving them a payload to update their store.

I was wondering why the store API does not expose any method to do so.

Thanks

**Comment by stubailo** [comment]
> I was wondering why the store API does not expose any method to do so.

We don't have that feature yet, here's the main discussion about it: https://github.com/apollographql/apollo-client/issues/621

**Comment by tlvenn** [comment]
Hi @stubailo,

The linked issue seems to refer to conditional or time based invalidations, i am simply asking to invalidate fields on a given root node and was wondering was this was missing from the new imperative API.

**Comment by stubailo** [comment]
The new imperative API only has the ability to update the store contents - currently the store format has no way of representing an invalidation, time-based or otherwise, so the API doesn't have that feature.

I agree that the first comment is about conditional/time based invalidation, but the whole discussion overall is about all different kinds of invalidation, so I'd encourage you to add some comments there! If you read the thread and feel that it doesn't represent the right topic I'm happy to reopen this issue as well.

**Comment by tlvenn** [comment]
Thanks for the clarification, wanted to make sure that even simple invalidation was not possible at the moment.
