### ISSUE TITLE
how to do return partial data on pollinterval

### ISSUE THREAD

**Issue by gmchaturvedi1** [apollographql/apollo-client#1472]
Dear team,

My component is working fine till beforore ver 1. After ver 1 returnpartialdata is removed now my whole conponent is rerendder on pollinterval. Kindly suggest me how to get changed data with pollinterval like return partial data.

regards 
gm

**Intended outcome:**

**Actual outcome:**

**How to reproduce the issue:**

**Comment by stubailo** [comment]
I think this might have to do with the notify on network status default change by @helfer.

**Comment by helfer** [comment]
@gmchaturvedi1 this has to do with the recent change to `notifyOnNetworkStatusChange` and the loading state that you're most likely using in your component. We're reverting the change (releasing tomorrow), but for now you should be able to keep your components from re-rendering into the loading state by checking at `networkStatus` instead of `loading` inside your component. Most likely you want to only show loading when `networkStatus` is 1.

**Comment by gmchaturvedi1** [comment]
Thanx it is done with your suggestion I have just set 5
