### ISSUE TITLE
Feature idea: Abort pending requests

### ISSUE THREAD

**Issue by lucasfeliciano** [apollographql/apollo-client#1541]
I saw that in the middleware the `req` object has a `request` object with `operationName`.

```js
{query: Object, variables: Object, operationName: "Search"}
```

So I'm figuring out a way to cancel previous request with the same operationName.

### Motivation

The motivation behind is to use this feature on search's autocomplete/suggestions.

So when a new query is made we cancel the last request if it is not completed yet, so make it easy to treat the asynchronism in the frontend.

**Comment by helfer** [comment]
@lucasfeliciano in a sense this already happens. If the same component makes queries in quick succession, server responses from previous requests are ignored when there's a more recent request already under way. What more would you need?

**Comment by joefraley** [comment]
I was having this conversation at work today. What about these two cases:

1. Terminating a file upload.
2. Sparing the clients data usage. Apollo throws out the old result, but the client is still forced to _load_ the result, right?

**Comment by helfer** [comment]
@joefraley there's no way for us to cancel the request once it's been sent to the server. That would require specific logic on the server that we have no control over. Currently Apollo Client will receive the result, but it will throw it away if it's not the most recent request made by an active observable query.

I'm closing this since it seems the feature requested is already implemented 🙂

**Comment by joefraley** [comment]
@helfer I understand that users would need to implement their own server side logic to handle the cancellation. But that's only possible if the Apollo client fires a cancellation.

With no client cancellation, there is no way to handle the desired case. With client cancellation, people that need it can account for it on the server, and people that don't need it will not notice any change from the present day behavior.

I understand that the client can't cancel because it's using the native fetch call today, so I guess this proposal is partly to use a different request method that permits cancellation (like axios or the native XHR).

**Comment by lucasfeliciano** [comment]
@helfer I have to agree with @joefraley 

Support this on client side is kinda a must have feature for big and high quality applications

**Comment by joefraley** [comment]
@helfer @lucasfeliciano it's possible to set up your own custom network interface that does support cancellation of your using apollo-react, but it basically requires rebuilding the apollo-client network layer and extending it's API. I don't know if other Apollo libraries support that idea or not.

My product basically can't support GraphQL without cancellation though.

Another possibility is to simply set your cancellation endpoints aside from gql. So keep hitting a one of rest point for search, but gql your other stuff. That only works if a limited subset of your app needs cancellation though.

**Comment by stalniy** [comment]
It looks like it's not hard to implement custom network interface which extends `HttpFetchNetworkInterface` And override `fetchFromRemoteEndpoint` method, use inside `XMLHttpRequest` and do custom logic with request abort

**Comment by felixfbecker** [comment]
The latest version of the fetch API is cancellable (implemented in Chrome): https://developer.mozilla.org/en-US/docs/Web/API/AbortController

Any plans to implement that?

**Comment by larube** [comment]
In my project, I also need that feature. I launch a query but i would be able to cancel it depending on user action .... Do you think that this feature will be implemented ?

**Comment by klis87** [comment]
I think this feature is really needed. For example, lets say some private data is being fetched and user clicks logout. With a slow network, we could have a race condition, when private data would arrive after user logged out. Aborting a pending request in the case like this would prevent such a disaster.

**Comment by Timopheym** [comment]
Heeey! @helfer Is there news about it? Could it be done?

**Comment by pennyandsean** [comment]
Running into this problem now in relation to data coming back to unmounted components.  Looks like [Dan's in favour of cancellation for api libraries](https://github.com/facebook/react/issues/2787#issuecomment-304485634).

**Comment by bgentry** [comment]
I think this issue should at the very least be reopened now that it is possible to cancel fetches with AbortController. As Dan pointed out in the above link, there are many classes of problems which are best solved by canceling the ongoing request.

And since most browsers and modern CDNs have HTTP/2 support, those requests can often be canceled without ending the connection and without the server sending any unwanted data.

**Comment by abhandaru** [comment]
Please reopen this issue.

Request cancellation from the client offers many benefits including but not limited to:
- Conserving data usage
- Implementing timeouts retry policies
- Resolving race conditions and winners
- Allowing servers to appropriately conserve resources and terminate requests

There is ample precedent for adding cancellation to asynchronous APIs.

**Comment by stalniy** [comment]
Guys I believe this was implemented as part of Apollo link. Check the source code : https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-http/src/httpLink.ts

**Comment by klis87** [comment]
@stalniy  this would probably work if observable responsible for a request is cancelled (abort would be triggered then), but does it ever happen actually? lets say we have a `query` pending and before it finished, a component just unmounted - I guess this query will finish executing and abort will never be triggered

**Comment by nagman** [comment]
@stalniy I'm using the `unsubscribe()` method of the Observer generated by apollo, and it doesn't kill the query at all.
The callback isn't triggered because I unsubscribed it, but apollo is still polling for the server's answer.

I'm using it inside of an autocomplete component, and I unsubscribe the previous subscription each time I type a key.
But instead of killing previous fetches, they pile up and the more I type, the longer it takes to display the results (because all the queries are executed and the final result only displays at the end).

However, when I copy/paste an entire word, as it triggers only one request, it's blazing fast.

So... there's still a need for this feature. The `unsubscribe()` method should abort the fetch query.

**Comment by stefanholzapfel** [comment]
Same problem here. I have an autocomplete where every keystroke changes/re-fires the query. At the moment I unsubscribe in a delayed timeout function to avoid that issue, which is VERY ugly and unreliable.

Is there any property on the subscription which indicates wether the subscription is already in an "unsubscribeable" state?

Thanks!

**Comment by klis87** [comment]
Any news re potential introducing of requests aborts? For REST APIS, I am heavy user of Redux-Saga, and I really appreciate control which it gives me - saga aborts, effects like `takeLastest, takeEvery, all, race`, which give awesome control which can prevents subtle race condition bugs, especially on mobile devices. 

I really like Apollo and I think that it is really the future of the way apps should be written, but because it is declarative, we dont have much networking control, Apollo does all the lifting for us, but this has a cost, and I believe that introducing aborts, `takeLastest, takeEvery, all, race` counterparts would be a missing puzzle to the equation.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

Anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Feature%20idea%3A%20Abort%20pending%20requests&body=Migrated%20from:%20apollographql/apollo-client%231541) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
