### ISSUE TITLE
union types without fragment matcher makes entire result undefined.

### ISSUE THREAD

**Issue by edvinerikson** [apollographql/apollo-client#1562]
I've talked with @stubailo on Slack which suggested opening a issue.
We have had some issues with unions in our app.

given this schema

```graphql
enum TransactionType {
  ACCOUNT
  CASINO
  SPORT
}

type TransactionAccount implements Node {
  id: ID!
  date: String!
  amount: Int!
  fee: Int!
}

type TransactionCasino implements Node {
  id: ID!
  date: String!
  result: Int!
  wager: Int!
  gameName: String!
}

union Transaction = TransactionAccount | TransactionCasino

type UserHistoryConnection {
  edges: [UserHistoryEdge]
}

type UserHistoryEdge {
  cursor: String!
  node: Transaction!
}

type User implements Node {
  id: ID!
  history(type: TransactionType!, first: Int!, after: String): UserHistoryConnection
}


type Query {
   me: User
}
```

and this query
```graphql
query {
  me {
    history(type: ACCOUNT, first: 5) {
      edges {
         node {
            __typename
            ... on AccountTransaction {
               id
              date
              amount
              fee
            }
            ... on CasinoTransaction {
                  id
                 date
               result
               wager
               gameName
            }
         }
      }
    }
  }
}
```

```
client.query({ query });
```

**Intended outcome:**
I receive the data I queried.
```
({ data }) => expect(data).toEqual({ me: expect.any(Object) })
```

**Actual outcome:**
```
({ data }) => expect(data).toEqual(undefined)
```

**How to reproduce the issue:**
Try to query a union with fragments that contain unique fields for that type.

----

I know that this is solvable by implementing a custom fragment matcher and I will do that.

but it took me a few hours to realise that and I think this should be addressed somehow.

**Comment by helfer** [comment]
@edvinerikson agreed, this is definitely unexpected and I'd really like to find a way to solve this. I think the first thing we could do is document the alternative fragment matcher much better, and maybe even make it the default.

The main issue is that we can't actually detect when you're trying to match a fragment on a union or an interface type. All we know is that a fragment type condition didn't match, but we don't know if that is because it shouldn't match, or because we don't have the information about interfaces and unions that we'd need to match it.  If we could somehow get past this, it would be easy to throw an error or print a warning and tell the developer to use the introspectionFragmentMatcher.

What do folks think? Should we use the introspection fragment matcher with no schema information by default, which would just never match unions and interfaces, and then let people figure out that they need to give the client some schema information to match interfaces and unions? I think that may make Apollo Client a lot more predictable.

**Comment by helfer** [comment]
Closing this in favor of #1555 which is the same underlying issue.
