### ISSUE TITLE
Add GET support to NetworkInterface

### ISSUE THREAD

**Issue by camd** [apollographql/apollo-client#1614]
I have an application where the ReactJS app is hosted on one domain, and the Django service (using Graphene) is hosted on another.  The ReactJS app needs to access the data in the Django app.

## Steps to Reproduce

Since Apollo defaults to using POST for queries, I'm hitting a CSRF issue when trying to access the data.  At this time, since these APIs are all read-only, I'm using ``csrf_exempt`` on the ``GraphQLView`` and this is working OK.

However, I would much prefer to use ``GET`` for my read requests.

After some digging, I found that I could modify the method to GET by using ``applyMiddleware`` and modifying ``req.options.method = "GET"``.  However, It is still trying to post a BODY, which is not allowed in a GET.  I tried doing ``delete req.request.query`` but that didn't seem to help.  I didn't really expect that second part to work, but gave it a shot anyway...  :)

### Expected Behavior

Would you be able to either provide an additional ``NetworkInterface`` that uses GET or some documentation on how to create our own?

### Version
- apollo-client@1.0.2
- react-apollo@1.0.1

#### Note:
This issue was originally posted on ``react-apollo`` but closed because it really belongs here.  
https://github.com/apollographql/react-apollo/issues/624#issuecomment-293742620

I may create a PR for this feature at some point, if I get the bandwidth.

**Comment by ravikiran438** [comment]
Ideally it would be best to add `useGetForQueries: true` option to [persistgraphql](https://github.com/apollographql/persistgraphql) as it will be too brittle as each browser limit varies.

**Comment by nirmaljingar** [comment]
+1
It would be really great if we can use GET for persistgraphql.

**Comment by helfer** [comment]
@camd if you have time, a PR would be great!

**Comment by pgdejardin** [comment]
I have tried to modify the `BaseNetworkInterface` in apollo-client/transport to accept method GET and pass the query and variables from body to url query string.
It works well for me, but I didn't tried on the consequences on mutations, fragments, etc.

To know if The client have to fetch data with a GET or a POST method, I check if in NetworkInterfaceOption of `createNetworkInterface` if the options a the key method which is equals to `'GET'`. since this options is based on `RequestInit` type of `isomorphic-fetch`

I can make a PR if this way of thinking is valid with the rest of apollo-client.

**Comment by helfer** [comment]
@pgdejardin GET requests should only be used for queries, so it's fine if it doesn't work for mutations. In fact, for mutations it should always make a POST request. A PR to the default network interface would be really cool! 👍

**Comment by n1ru4l** [comment]
I implemented such a network interface in an application a few days ago: https://gist.github.com/n1ru4l/cb24401592417bda7fad989d416f0b9f
