### ISSUE TITLE
update on subscribe (Direct Cache Access)

### ISSUE THREAD

**Issue by mitjade** [apollographql/apollo-client#1623]
I would like to replace `updateQueries` with `update` (Apollo Client’s new imperative store API), but it seems `update` is currently only available on `mutations`.

### Expected Behaviour
You should be also able to use `update` on `subscribeToMore`, like you are able to on mutations

### Version
- apollo-client@1.0.3

**Comment by mitjade** [comment]
https://github.com/apollographql/react-apollo/issues/634

**Comment by mitjade** [comment]
@helfer Would love to get some pointers on how to fix this, if I would be able to.

**Comment by helfer** [comment]
@mitjade thinking about this again, I'm not sure it makes sense to add the `update` function to `subscribeToMore`, because we currently also don't have it for `fetchMore`. Both of these are mainly intended to update a single query/view (whether that makes sense or not is probably worth its own discussion).

Instead of adding it to `subscribeToMore`, how about we add it to `client.subscribe`? That way you could create a subscription using the client directly, and then update any queries you'd like from there. To implement it, you could simply add it to the `SubscriptionOptions` definition, and then make the reducer that handles `APOLLO_SUBSCRIPTION_RESULT` apply the update the way the mutation reducer does (apart from the logic that handles optimistic updates).

**Comment by scf4** [comment]
Any update on this?

**Comment by lgaovf** [comment]
I'd like this feature, apollo keeps updating the cache with old values.

**Comment by sorokinvj** [comment]
@lgaovf Gustavo, did you manage to solve it? 

I have subscribeToMore that doesn't update store and stuck with updating it directly. Neither client.writeQuery not refetch don't work
