### ISSUE TITLE
Fragment "X" is never used. Suggest: warning instead of error.

### ISSUE THREAD

**Issue by smeijer** [apollographql/apollo-client#1649]
When including a fragment that is not actually being used in the query, `react-apollo` throws the error: `Fragment "${name}" is never used`.

Can this error not just be a warning? I understand that we can leave the fragment away for optimization, but it doesn't seem to be a blocking issue to me.

**Intended outcome:**
`console.warn('Fragment "X" is never used.')`

**Actual outcome:**
`console.error('Fragment "X" is never used.')`

**How to reproduce the issue:**
```js
const frag = gql`
  fragment X on Y {
    _id
    name
  }
`;

export const Y_QUERY = gql`
  query blog($id: ID!) {
    blog(id: $id) {
      _id
      name
      users
    }
  }
  
  ${frag}
`;

graphql(query, {
  options: ({ id }) => ({
    id,
  })
});
```

**Comment by stubailo** [comment]
This is actually an error from your GraphQL server - it's running validation on the query and that's a default validation rule for GraphQL.js. In order to prevent this, Apollo would have to actively remove fragments that aren't used, which doesn't at first glance seem like a good idea for a GraphQL client to do.

**Comment by helfer** [comment]
Yeah, this is an issue with the GraphQL validation on the server.

**Comment by smeijer** [comment]
Aaah, I see. Thanks for the clarification.
