### ISSUE TITLE
Accessing apollo redux data via selectors?

### ISSUE THREAD

**Issue by tnrich** [apollographql/apollo-client#1685]
Hey there,

So at the top of my app I have a query for the `currentUser` and based on this query I either redirect to a login page or let the user continue on with their business. I'd also like to get the currentUser's id in other places in the app, and I was wondering what the recommended way to do this would be. Is there something like a redux selector that I can use that would allow me to access the current user's info without needing to wrap the interested component in the apollo query?

Thanks!

**Comment by stubailo** [comment]
You can use a query with the `cache-only` fetch policy: http://dev.apollodata.com/react/api-queries.html#graphql-config-options-fetchPolicy

That basically just makes the query act just like a selector, and doesn't send anything to the network! Would that work for you?

Going to close since this is a question and not an issue.
