### ISSUE TITLE
Results from network not overwriting cached results due to query.lastRequestId

### ISSUE THREAD

**Issue by StevePotter** [apollographql/apollo-client#1706]
We have a query that has a cache expiration.  So we fetch the query using 'cache-first' and if it's cached value has expired, we call `data.refetch()` and we get the new data with a future expiration date.

But the refetch doesn't get saved in redux!  I debugged the library and found the redux write gets cancelled at https://github.com/apollographql/apollo-client/blob/d420cbdbb3e6637ee2e8e8c211e3d28850b93c6e/src/queries/store.ts#L135.  
```
// Ignore results from old requests
    if (action.requestId < previousState[action.queryId].lastRequestId) {
      return previousState;
    }
```

Here's the thing.  `requestId` gets reset each time the app loads.  And `lastRequestId` gets persisted to redux.  So in my case, `action.requestId` was less than the saved result's `lastRequestId`, but the data was in fact newer.  The requestId is a pretty bad comparison.  

One option would be to persist the requestId in redux.  Another would be to store a timestamp to compare.  Or let us write a custom 'shouldCache' function.

Am I the only one with this problem?  Personally I like option 2 (timestamp) and would be happy to do a PR for it.

**Comment by helfer** [comment]
@StevePotter I take it you are having this problem because you're persisting state to disk, then hydrating the client with it on startup? The way we intended for this to happen was to only hydrate the store data, but not the query state. Is that not possible with the expiration mechanism that you've built on top?

Personally I think a decent way to patch this would be to add a way to retrieve the largestRequestId and tell apolloClient what requestId to start from. I'd be happy to review a PR that implements this, if you have time :wink:

I think the timestamp solution you mentioned could work under many circumstances, but given enough devices there would almost certainly be situations where requests get erroneously dropped because the clock on a device changed (for example due to syncing with an NTP server).

**Comment by sanyam-coursera** [comment]
I am facing this issue too while using react-native and redux-persist to persist/hydrate my store. I think this is going to affect more and more people as react-native is adopted since mobile apps need to persist their apollo state for faster bootup time. 

@StevePotter Any luck making a PR for this issue or were you able to find a workaround?

**Comment by leethree** [comment]
Yes we are also using react-native together with redux-persist and we are facing this problem now.

Would it be helpful to only include `data` key when persisting the Apollo reducer?
