### ISSUE TITLE
Missing field warning: escalate to error instead of silently logging?

### ISSUE THREAD

**Issue by avindra** [apollographql/apollo-client#1719]
Relevant source code: https://github.com/apollographql/apollo-client/blob/dc0d1a722212e671144cc75439beb91589cbaed2/src/data/writeToStore.ts#L202-L206

**Intended outcome:**
I get an error thrown with the message `Missing field ${fieldName}`

**Actual outcome:**
A warning is silently output in the console.

**How to reproduce the issue:**
Make a query that uses fragments on interfaces or unions.

It seems that some consideration was made historically for throwing errors, but it was since removed?

https://github.com/apollographql/apollo-client/blob/9c0c2eb8248202352bfcf49134fe00c287634b65/CHANGELOG.md#v0328

----

On a related note, is there any way to get `apollo-client` to be quiet about all logging? In apps log in a structured way, having third party dependencies logging in arbitrary formats can break structured logging setups.

**Comment by helfer** [comment]
Hi @avindra. Yeah, I'd like to throw an error in that case, but it would not be a backwards-compatible change, so we decided against it.

The real problem with your setup is probably that you're using fragments on interfaces or unions without using the IntrospectionFragmentMatcher.

I don't think it's possible to make Apollo Client shut up completely at the moment, but if you're running in production, there should be basically no logs output at all (with the exception of critical things, like missing fields). Rather than not logging at all, maybe it would be better to provide a way for people to format the logs that apollo client outputs? In any case, I'd be interested in hearing suggestions!
