### ISSUE TITLE
The uri of createNetworkIntreface is overwrite by webapck devServer option

### ISSUE THREAD

**Issue by developerworks** [apollographql/apollo-client#1743]
![image](https://cloud.githubusercontent.com/assets/725190/26526010/626477c0-439d-11e7-9ebb-054c6a1701af.png)

I have created a project [HERE](https://github.com/developerworks/apollo-subscription) to re-produce the issue, if you have time to see this, thank you.

The issue could be fixed by add a proxy config to devServer like this:

```
  devServer: {
    contentBase: path.join(__dirname, 'dist'),
    port: 9001,
    hot: true,
    publicPath: '/',
    proxy: {
      '/graphql': {
        target: 'http://localhost:7001/api',
        secure: false,
      },
    },
  }
```

But why the uri property of createNetworkInterface is no effect, it's weird

**Comment by stubailo** [comment]
Can you point to the part of the code where you are trying to specify the URL? All I see is this line: https://github.com/developerworks/apollo-subscription/blob/3d64e9d35621b6ad1cf9a479e855bc4a3b955be5/client/index.js#L24

Which I would expect to point to the same address as the webpack dev server, so I'm not sure what the problem is.

**Comment by helfer** [comment]
@developerworks are you still having this issue?
