### ISSUE TITLE
Automatically create networkInterface

### ISSUE THREAD

**Issue by benbro** [apollographql/apollo-client#1749]
Instead of this:
```javascript
const client = new ApolloClient({
  networkInterface: createNetworkInterface({
    uri: 'https://graphql.example.com',
  }),
});
```

Use this:
```javascript
const client = new ApolloClient({
  networkInterface: {
    uri: 'https://graphql.example.com',
  },
});
```
If networkInterface is an object, ApolloClient can automatically call createNetworkInterface with the networkInterface config.
https://github.com/apollographql/apollo-client/blob/master/src/transport/networkInterface.ts

**Comment by helfer** [comment]
@benbro I don't think that's a good idea, because it would either make things more complicated or mean that you can no longer provide your own networkInterface. However, I agree that we could make things simpler. @stubailo had the idea of making the networkInterface argument completely optional if your server is on the same origin as the app and the GraphQL API is at `/graphql`, which seems to be the standard approach.

Would you be interested in making a PR that makes the `networkInterface` argument optional?

**Comment by benbro** [comment]
Thanks
