### ISSUE TITLE
fetchMore and updateQuery vs update

### ISSUE THREAD

**Issue by seeden** [apollographql/apollo-client#1768]
Hi guys I can see in the documentation that updateQuery can be deprecated in the feature and therefore I have started to use update. But when I use fetchMore I can see next error:

Uncaught (in promise) Error: updateQuery option is required. This function defines how to update the query data with the new results.

**Comment by helfer** [comment]
Hi @seeden 👋

I think the naming that we chose is a bit unfortunate. For `fetchMore` you can continue using `updateQuery` just like before. Only for mutations we recommend using `update` instead of `updateQuery` (which is different from the `updateQuery` for `fetchMore`, but has the same name). Does that make sense? Is there any place in the docs where we could clarify this?

**Comment by stubailo** [comment]
FWIW, for mutations it's called "updateQueries" :)

**Comment by helfer** [comment]
I think I'll close this issue and make a note to point out explicitly in the docs that for mutations you should continue to use `updateQuery`.
