### ISSUE TITLE
Should ROOT_QUERY be initilized by myself ?

### ISSUE THREAD

**Issue by darkship** [apollographql/apollo-client#1804]
Hi,
I came across an issue like this https://github.com/apollographql/apollo-client/issues/1701. 

It appears that when I start my app I don't have any ROOT_QUERY. So that whatever is in my query,<code>store.readQuery({query});</code> throws "Can't find field <field> on object (ROOT_QUERY) undefined."
Running <code>store.writeQuery({query, data}})</code> creates ROOT_QUERY and the same <code>readQuery</code> call works afterwards.

Is this a bug or should I have used <code>initStore</code> ?

**Comment by helfer** [comment]
Hi @darkship If any of the data that `readStore` tries to read is not there, the function will throw an error. In your case there's nothing in the store at all, which is why it errors at ROOT_QUERY. You should protect the `readStore` call with a try/catch block if it's possible that the data might not be in the store yet.

**Comment by darkship** [comment]
OK, thanks

**Comment by zixia** [comment]
@helfer Why not just return `null` instead of throwing an `Exception`? I feel return null is more convenience.
