### ISSUE TITLE
Do we really need resetStore for signIn, signUp?

### ISSUE THREAD

**Issue by steida** [apollographql/apollo-client#1889]
Without Redux, I understand re-fetching is the must, but why user data has to be cleared after signIn? 

For signOut, resetStore seems to be not enough, because, with SSR, the app still can contain server initial state, so we need full reload.

Please correct me if I am wrong.

**Comment by kMeillet** [comment]
For the moment, i use a full refresh, because resetStore is really weird and can throw for some reason like in-flight request or new request incoming before full reset phase. I've try awaiting full cache reset before redirect on auth form, but it slowdown my logout :( ...

If resetStore doesn't clear cache, component will not be refresh when logout (like an AppBar with current authenticated user name and surname).

Why you need a full reload for SSR ? Only the Apollo cache is reset, and when using Redux, i don't understand why you need that because hydrated initial state seem to live in Redux, not in Apollo cache.

**Comment by steida** [comment]
> Why you need a full reload for SSR?

Because Next.js app can contain previously logged in user data in its initial props.

**Comment by jbaxleyiii** [comment]
@steida resetStore is the currently advised way to clear out data for signIn / signUp. In regards to SSR, a new client instance should be created for each request as to not leak user data between users.
