### ISSUE TITLE
How to get status code from failed request

### ISSUE THREAD

**Issue by kamrancode** [apollographql/apollo-client#1911]
How am I suppose to get network status code in my catch block?
I need to decide next step base on this status code

```
  const testClient = new ApolloClient({
    networkInterface: createNetworkInterface({
      uri: 'https://api.github.com/graphql'
    })
  })

  testClient.query({
    query: gql`query { viewer { login }}`
  })
  .then(data => console.error('TEST RES =>', data))
  .catch(error => {
    debugger // i need error.networkError.status
    console.error('TEST ERR =>', error)
  })
```

and I cannot use afterware because I'm using redux-saga and afterware doesn't accept generator.
or can't run generator in afterware.

**Comment by jbaxleyiii** [comment]
@KamranGhoochanian error handling is definitely a major weak point of Apollo that we are actively working on!

If you would be able / like to help with this specific problem, I can help point you (or anyone else) in the right direction.

Currently, if the server returns an invalid `ExecutionResult` (meaning `data` and `errors` are missing from the response data, AC throws a custom error saying that the server response was empty. [This](https://github.com/apollographql/apollo-client/blob/3b5045dfe74183fe060d2027e31317d890755b99/src/transport/networkInterface.ts#L241-L244) is where that happens.

To fix this, we need to pull the status code from the [response](https://github.com/github/fetch#caveats) and attach it to the error. We should also remove debugName here and replace it with operationName since debugName never was fully built out.

Would you be open to working on this PR? You could also start with a failing test based on this [test](https://github.com/apollographql/apollo-client/blob/master/test/networkInterface.ts#L477-L481). The change of the message could also include the status like the following tests show

**Comment by KamranGhoochanian** [comment]
I'll be happy to help
I will look at the test

**Comment by jbaxleyiii** [comment]
@KamranGhoochanian so great! Let me know if you have any questions!

**Comment by beardedpayton** [comment]
I can help with this @jbaxleyiii  if @KamranGhoochanian hasn't gotten far with it yet!

**Comment by samrae7** [comment]
Hy just wondering if someone is working on this as I need this too :)
