### ISSUE TITLE
Never sends cookie header to the server 

### ISSUE THREAD

**Issue by narayananramu** [apollographql/apollo-client#1946]
Apollo client doesn't send session cookie to Apollo server as a result I am getting empty session object on Apollo Server.

I have 3 Docker containers that run

1. Apollo Koa Server (kcors is enabled) at api.a.cloud
2. Koa (where I use Apollo Client with React) at qwerty.a.cloud
3. Nginx (for reverse proxy) at a.cloud

Apollo Koa Server Session Configuration & Koa. Also both (Apollo Server and Client) share same cookie and both work as excepted when normal browser request is sent.

```
sessionConfiguration : {
        key: '_a',
        maxAge: 86400000,
        overwrite: true,
        httpOnly: true,
        signed: true,
        domain: '.a.cloud',
        store: redisStore({
            host: "192.168.0.100",
            port: 32769
        })
}
```

Apollo Client React Snippet

```
const networkInterface = createNetworkInterface({
    uri: 'http://api.a.cloud/user',
    opts: {
        credentials: 'same-origin'
    },
});

const client = new ApolloClient({
    networkInterface: networkInterface
});

```

Thanks in advance 👍

**Comment by nihalgonsalves** [comment]
Apollo-Client uses `fetch` under the hood, so if you're looking for more information you should look into documentation about fetch instead.

That said, I don't think that making a request from `qwerty.a.cloud` to `api.a.cloud` with `credentials: 'same-origin'` will send cookies, regardless of the fact that you set the cookie with `.a.cloud`.

Try using `credentials: 'include'`, because you're making a cross-origin call.

**Comment by narayananramu** [comment]
@nihalgonsalves Thanks for the reply, I made a workaround using stateless cookie (JWT). I tried using `credentials: 'include'` there is any change in the request header.
