### ISSUE TITLE
Cache API design

### ISSUE THREAD

**Issue by jbaxleyiii** [apollographql/apollo-client#1971]
This issue is an umbrella issue for tracking discussions related to the new store API design and store's built with it!

cc @shadaj @nevir

**Comment by nevir** [comment]
Some scattered feedback as I dig into the code:

1. It would be nice if the cache was a pure interface, so we didn't have to set up a circular dependency on apollo-client.  I think there's a couple changes needed for this:

  * Reduce the surface area of the Cache's interface.  Probably: drop `readQuery`/`readFragment` (in favor of `read`) from the API, and instead make them pure functional helpers that AC uses internally.  Ditto `write`.

  * Can `diffQuery` be folded into `read`?  It overlaps with `returnPartialData` (and it's not great that we're using exceptions as control flow in that case).

2. I'm not entirely clear on when/why AC asks for non-optimistic data from the cache; have any clarity or pointers for me?

**Comment by stubailo** [comment]
Link to PR for context: #1921

**Comment by stubailo** [comment]
> I'm not entirely clear on when/why AC asks for non-optimistic (raw) data from the cache; have any clarity or pointers for me?

You want this if you are planning to update the non-optimistic data with a `readQuery`/`writeQuery` combo.

**Comment by nevir** [comment]
> You want this if you are planning to update the non-optimistic data with a readQuery/writeQuery combo.

Unless I'm missing something, there's no _public_ API from AC that allows someone to specify `optimistic: false`, right?

Locations in AC that I'm unclear on:

---

[`QueryManager#fetchQuery`](https://github.com/apollographql/apollo-client/blob/bdc715fec132e075938b259295fd4efb68a4d18e/src/core/QueryManager.ts#L445-L450) calls `diffQuery({ ... optimistic: false })`, which is surprising to me.  If the optimistic view of the data satisfies the query (and not `network-only`), wouldn't we want it to emit a value?  Also, it appears like the result from this call is passed [directly to the caller](https://github.com/apollographql/apollo-client/blob/bdc715fec132e075938b259295fd4efb68a4d18e/src/core/QueryManager.ts#L581) without having optimistic data layered on.  Similarly, it calls through to `QueryManager#fetchRequest`, which [follows suit]((https://github.com/apollographql/apollo-client/blob/bdc715fec132e075938b259295fd4efb68a4d18e/src/core/QueryManager.ts#L1368-L1375)).

I read that as `fetchQuery` being concerned with only the server's view of the data (makes sense), but does it seem to imply that AC has to then re-query for (or layer on) optimistic values before returning via its public API (which it does not seem [to](https://github.com/apollographql/apollo-client/blob/bdc715fec132e075938b259295fd4efb68a4d18e/src/core/ObservableQuery.ts#L232-L234) [do](https://github.com/apollographql/apollo-client/blob/bdc715fec132e075938b259295fd4efb68a4d18e/src/core/ObservableQuery.ts#L427-L435)).  I think I'm missing something.

---

[`DataStore#markMutationResult`](https://github.com/apollographql/apollo-client/blob/bdc715fec132e075938b259295fd4efb68a4d18e/src/data/store.ts#L190-L198)'s use of `optimistic: false` for `updateQueries` seems clear - check any `updateQueries` if present, and only write them to the cache if values have changed.  However, I'd like to argue that this is something that the cache should perform for _all_ writes (and that AC can skip this particular check)

**Comment by Fxlr8** [comment]
Ability to read/update instances in store using data id only would be highly useful

**Comment by nevir** [comment]
@Fxlr8 I believe you can do that today via [`readFragment`](http://dev.apollodata.com/core/read-and-write.html#readfragment)

**Comment by Fxlr8** [comment]
@nevir, `readFragment` as API reference says, requires me to:

1. write/import a fragment
2. add fragment name
3. add fragment-specific variables

it is unwanted stuff to do when I just want to read/change a single object in the store. data id is unique for the whole store and is enough to identify and get a single item

**Comment by Fxlr8** [comment]
Also, there is a problem when I want to `readQuery` on a query with pagination. For example, if I have the following data structure: 
`
`

**Comment by nevir** [comment]
Ah, yeah - that makes sense.  I can't speak to the pagination bit (I think it might get merged into a single list somewhere in the cace)

As for fetching state from Apollo's current cache without a fragment - unless you only want shallow values (e.g. no nested objects/arrays), it's a no-go.  The cache needs to know how far to walk (and reconstruct) your nodes to return them

**Comment by nevir** [comment]
Feedback on `recordOptimisticTransaction`:

The current behavior appears to be to capture the `transaction` callback, and (re-)call it each time the store wants to (re-)apply the optimistic update.  But for situations where the app must be shut down (and the cache needs to be marshalled/restored), that's not going to work (at least at this level).

What I'm thinking of doing is:

* Record all writes (as POJOs), which can be applied when replaying optimistic updates
* _Disallow_ reads from the transactional `Cache` - possibly entirely, or more likely only reads that occur after a write.  (So that we can reason more clearly about optimistic updates that are replayed way down the line)
  * Or, alternatively, reads could read from the state of the store prior to the transaction beginning (even after a write).  But that seems like it'd be pretty confusing

**Comment by nevir** [comment]
Another point:

* Transactions should probably be given a `DataProxy`, not an entire `Cache` object (hard to reason about calling `reset`, `watch`, etc within a transaction)

**Comment by stubailo** [comment]
@Fxlr8 you'll be interested to read about the `@connection` directive, which is exactly for that purpose - to make more predictable store keys for complex arguments: http://dev.apollodata.com/react/pagination.html#connection-directive

> Transactions should probably be given a DataProxy, not an entire Cache object

👍  - I agree that the methods should be limited to the ones that make sense

> The current behavior appears to be to capture the transaction callback, and (re-)call it each time the store wants to (re-)apply the optimistic update.

I think that is an implementation detail of `InMemoryCache` - other implementations could do it differently, like storing a set of patches on the data.

> it is unwanted stuff to do when I just want to read/change a single object in the store.

The problem here is field arguments. Since JS has no concept of a field with arguments, you kind of need the fragment to specify which arguments you're trying to read:

```
fragment Price on InventoryItem {
  price(location: USA)
}

# vs.
fragment Price on InventoryItem {
  price(location: AUS)
}
```

So it's not really clear what a "single object" in GraphQL should look like. Besides, different store implementations might store the objects in different ways.

I think this might be a place where store implementations can provide non-standard APIs like `getObject(id)`, which will do different things depending on the underlying implementation.

**Comment by nevir** [comment]
Looks like there's a couple straggling spots where `addTypename` is still managed outside of the cache (spotted by @vincecoppola).  Would be good to have consistent ownership for that config flag:

* https://github.com/apollographql/apollo-client/blob/2.0-alpha/packages/apollo-client/src/core/QueryManager.ts#L355
* https://github.com/apollographql/apollo-client/blob/2.0-alpha/packages/apollo-client/src/core/QueryManager.ts#L1093

**Comment by nevir** [comment]
Also, I'm definitely struggling to understand when the cache should throw exceptions vs not - for example https://github.com/convoyinc/apollo-cache-hermes/pull/32 - from reading the in memory cache code, it seems like diffQuery _should_ be throwing if `returnPartialData` is falsy (aka the default), but it doesn't appear to.  And things like query observers don't appear to expect it to throw

**Comment by jbaxleyiii** [comment]
@nevir I was just talking with @shadaj about the typename issue! Working on a solution for sure!

hmm, I'm not sure on throwing. We should set policies for sure there. Maybe even adjust to not throw anywhere and have error responses somehow?

What are your thoughts?

**Comment by nevir** [comment]
IMO the cache shouldn't throw at all - but instead return `isMissing` when
requested.  That way AC can choose what to do based on it

**Comment by nevir** [comment]
Aha, so I missed that `returnPartialData` _defaults_ to `true` (might want to flip that option around in the cache API to make it apparent)

**Comment by nevir** [comment]
Oof, more fire to douse on to the "don't expect + trap errors coming from the cache" fire: just lots a lot of time to a genuine bug in my cache that was being swallowed by AC, and treated as a partial result

**Comment by jvbianchi** [comment]
is there a design doc with the new planned Cache API?

**Comment by Fxlr8** [comment]
By the way, why do you guys want to drop the [query reducer](http://dev.apollodata.com/react/cache-updates.html#resultReducers) feature?

**Comment by shadaj** [comment]
@Fxlr8 Before, Apollo Client always had a single cache implementation that had a structure that could be updated with a reducer. With the new Cache API, there can be cache implementations that do not have an in-memory representation that can be updated with a reducer, so we decided to remove the feature so that Apollo Client could be more flexible.

**Comment by cport1** [comment]
Doesn't version 2.0 pretty much take care of this issue?

**Comment by jbaxleyiii** [comment]
I'm going to close this out in favor of a new issue to formally document the API. cc @shadaj would you be up for documenting it?
