### ISSUE TITLE
[docs] config.props passes ownProps for mutations, not the props themselves.

### ISSUE THREAD

**Issue by poyannabati** [apollographql/apollo-client#1986]
I think the docs are confusing / misleading as they are now. 

![image](https://user-images.githubusercontent.com/1499050/28916330-2ad14d72-7842-11e7-81fe-88caabf9beeb.png)

Whereas the part on mutations shows us;

![image](https://user-images.githubusercontent.com/1499050/28916356-3c8e01e0-7842-11e7-9f16-534b9d37af25.png)

**Comment by stubailo** [comment]
Would you mind reopening the exact same thing on https://github.com/apollographql/react-apollo?

However, it seems like it's a problem with the docs themselves, since I think it's always `ownProps` so it's probably just not clearly written: https://github.com/apollographql/react-apollo/blob/8ee56e94d90c1df6862b54073ed0cf3b99330ead/src/types.ts#L63

Mind sending a PR here to mention that parent props are passed as `ownProps`? https://github.com/apollographql/react-docs/blob/master/source/api-graphql.md#configprops
