### ISSUE TITLE
Apollo style cursor based pagination tradeoffs

### ISSUE THREAD

**Issue by rjdp** [apollographql/apollo-client#2058]
Is there any tradeoff with Apollo style approach as compared to relay style cursor pagination ? I am trying to understand the same, your insight will be greatly helpful.

**Comment by rjdp** [comment]
Any insight will be very helpful.

**Comment by n1ru4l** [comment]
There is not apollo style cursor approach. You could use relay cursors or offset based navigation depending on your use case.

I do not think that this question does belong here. IMHO it would be a better fit for stack overflow or the apollo stack since this is more of a schema design question then a "problem" related to apollo client.

**Comment by rjdp** [comment]
@n1ru4l Thanks, I will close the issue.
