### ISSUE TITLE
Throwing error when field is missing

### ISSUE THREAD

**Issue by sondremare** [apollographql/apollo-client#2148]
Our application is getting quite large, and tons of fragments.
We read and write fragments based on data received from a real time service.
Once in a while we mismatch the fields from the original query and the result is a "Missing field" warning. The end result for the user is that the data is not showing.

I created a fork an actually throw the error as you suggest in your own code:
/src/data/writeToStore.ts@master#L200

However, the error seems to be swallowed by the system, and I am unable to get any better error handling. Any suggestions to what I can do?

**Intended outcome:**
An error to be thrown when we write to store with missing fields

**Actual outcome:**
Nothing happens

**Version**
- apollo-client@1.4.2

**Comment by jbaxleyiii** [comment]
I think we should eventually change how error are handled by the store and maybe even loop it into the 2.0 since the swallowed errors make store issues hard to debug. I'll add it to the 2.0 milestone

**Comment by hwillson** [comment]
Error handling has changed quite a bit since this issue was created. See the [Error handling](https://www.apollographql.com/docs/react/features/error-handling.html) section of the docs for more info, looking at the [Error policies](https://www.apollographql.com/docs/react/features/error-handling.html#policies) section in particular. Thanks!
