### ISSUE TITLE
Warning on missing data for observable query

### ISSUE THREAD

**Issue by jay1337** [apollographql/apollo-client#2262]
When an observed query can't be updated because data is missing in the cache, there should be a `console.warn` because it means that:

1. Data are not consistent in the app
2. There is a mistake in the choice of the queries observed or in the choice of field selected in the response to some mutations/queries

For instance, if you call a mutation to add a new product to a shopping basket with only a table of product's ids selected in the response, and if you have an observed query on the basket with product's field "weight" selected, the query won't be updated and thus the user won't see the new product.

Ideally the warning should tell which data is missing.

**Comment by jbaxleyiii** [comment]
@jay1337 I'm all for improving the development warnings / guidance of Apollo! Do you have a sample app which showcases this behavior?

**Comment by jay1337** [comment]
@jbaxleyiii I don't have (time to provide) a full sample app but here are some code to make the example in my first message more concrete.

The schema could be:

```
type Query {
  user(id: ID!): User!
}

type User {
  id
  basket: [Product!]!
}

type Product {
  id
  name
  weight
}

type Mutation {
  addProductToBasket(user: ID!, product: ID!) User!
}
```

The query observed by a React component could be:

```
query {
  user(id: 123) {
    id
    basket {
      id
      name
      weight
    }
  }
}
```

The mutation triggered when the user adds a product to the basket could be:

```
mutation {
  addProductToBasket(user: 123, product: 456) {
    id
    basket {
      id
      name
    }
}
```

Since `weight` is not selected in `basket`, data will be missing to refetch the query from Apollo cache after the mutation, thus the basket React component won't get updated. A warning could easily be added in Apollo code to help the developer.

**Comment by jay1337** [comment]
@jbaxleyiii I updated to:

```
apollo-cache-inmemory@0.2.0-rc.0
apollo-client@2.0.0-rc.1
```

And now if data is missing, the partial data are passed to the wrapped component anyway !
So I can get `!this.props.data.error && !this.props.data.loading && this.props.myRequiredQueryField === undefined` !

**Comment by jay1337** [comment]
Hey !

**Comment by jbaxleyiii** [comment]
@jay1337 sorry about that! I forgot to add the label to keep this open as an area of improvement!

**Comment by jay1337** [comment]
Hey !

**Comment by msimulcik** [comment]
@jbaxleyiii any update on this? Lack of any warning caused nasty bug in our application. We are using `cache-only` query to get logged user from cache relying on data returned previously by login mutation. The problem was that mutation didn't return all data requested by `getLoggedUserQuery` which resulted in error during rendering caused by missing data in props.

I did a little bit of debugging of Apollo and ended up with adding following code to [`ObservableQuery.currentResult`](https://github.com/apollographql/apollo-client/blob/1c9cd5da282211d333fd7c8bfca2d984964987a4/packages/apollo-client/src/core/ObservableQuery.ts#L201). I also had to return caught `error` from [`QueryManager.getCurrentQueryResult`](https://github.com/apollographql/apollo-client/blob/c4a1ad63b4c9845f8cbaa9bb8a0b24cf2431443b/packages/apollo-client/src/core/QueryManager.ts#L990) as it contains information about missing field.
```js
const isLoading = isNetworkRequestInFlight(networkStatus);
if (!isLoading
    && !this.options.returnPartialData
    && partial
) {
    console.warn(error);
}
```
Logic behind this is that if there are no data being loaded it most likely means that partial data are caused by error in query. I'm not sure about `&& !this.options.returnPartialData` part of condition.

I can create PR for this but I wanted to discuss it first because there's a high chance that I'm missing something.

**Comment by derek-duncan** [comment]
We're having the same issue as @msimulcik. Sometimes partial data is returned from the cache while the data is first loading. Thus, sometimes `data` has incomplete data, which destroys our confidence in the object structure, forcing unnecessary null-checks. It'd be great if `data` could remain empty when `networkStatus` is `1`, even if partial cache data is found.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Warning%20on%20missing%20data%20for%20observable%20query&body=Migrated%20from:%20apollographql/apollo-client%232262) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
