### ISSUE TITLE
Unhandled GraphQL subscription error ObservableQuery.js 184

### ISSUE THREAD

**Issue by abubakkarbutt** [apollographql/apollo-client#2295]
**Error Message:**
Unhandled GraphQL subscription error ObservableQuery.js:184
[ 0: {message: "Cannot read property 'then' of undefined"} ]
**Version**
- apollo-client@1.9.3
- apollo-angular@0.13.2
- graphql-subscriptions@0.5.4
- graphql-redis-subscriptions@1.3.1
- subscriptions-transport-ws@0.8.2

**Comment by abubakkarbutt** [comment]
I can handle the error by adding onError to subscribeToMore but don't know what is causing this error

**Comment by kamilkisiela** [comment]
@abubakkarbutt Could you try out new version (beta) of `apollo-angular`? I think something in the integration is causing an error, worth to try.

All details here:
https://github.com/apollographql/apollo-angular/pull/377

You can find there Migration Guide since there are some breaking changes but not a lot, should be very easy to move on.
