### ISSUE TITLE
generateErrorMessage creates giant error messages (86KB)

### ISSUE THREAD

**Issue by riking** [apollographql/apollo-client#2310]
**Intended outcome:**

Error messages reported in the console are concise and comprehensible.

**Actual outcome:**

Simply joining error messages of an array together when a large array of identical errors is generated results in enormous error messages.

Error with HTML response (86KB): http://putco.de/NjkyMw.javascript

![image](https://pbs.twimg.com/media/DL5DcyuXkAAOBtc.jpg:large)

https://twitter.com/SirStendec/status/920056004821291013

**How to reproduce the issue:**

Error messages should be deduplicated before combining.

https://github.com/apollographql/apollo-client/blob/9b0a587b9d5d94016d6fcb27db8d6e8d0ae1ff93/packages/apollo-client/src/errors/ApolloError.ts#L15-L16

Also, the comment on the function is incorrect - the function always performs work and never nop-s.

**Version**
- apollo-client@1.8.1

**Comment by riking** [comment]
This is still an issue from what I can see.

**Comment by riking** [comment]
.

**Comment by hwillson** [comment]
While this can definitely be improved, the way it's currently handled is by design.

To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=generateErrorMessage%20creates%20giant%20error%20messages%20(86KB)&body=Migrated%20from:%20apollographql/apollo-client%232310) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
