### ISSUE TITLE
fetchMore after being offline

### ISSUE THREAD

**Issue by prybalko** [apollographql/apollo-client#2533]
This issue ticket branched off from #1413

**Intended outcome:**
`fetchMore` failing for follow up requests after encountering network errors

**Actual outcome:**
`fetchMore` should work after being offline

**How to reproduce the issue:**
https://github.com/sreucherand/react-apollo-error-template

1. Turn off network
1. Try to Fetch more. See the error
1. Turn on network
1. Try to Fetch more again

**Version**
- apollo-client@1.9.0

**Comment by jbaxleyiii** [comment]
@prybalko have you tried out the 2.0?

**Comment by prybalko** [comment]
@jbaxleyiii not really. `2.0` doesn't seem to be compatible with `1.*` versions, so in order to use it, I would have to rewrite my application. In any case, I think this bug worth fixing in `1.*` version.

**Comment by prybalko** [comment]
does that make sense?

**Comment by sondremare** [comment]
@jbaxleyiii I tested this on version 2.1.0 of apollo. Breaks aswell. 
Crashes when attempting to fetch more when offline, and then also crashes on all subsequent calls

**Comment by alewiahmed** [comment]
Any news on this.

**Comment by hwillson** [comment]
I've confirmed that this issue is no longer a problem using `apollo-client` 2.3.1, and other current day supporting libraries. I've updated the reproduction provided in https://github.com/apollographql/apollo-client/issues/2533#issue-272537449 to use the latest and greatest Apollo libs, and everything works properly (new reproduction: https://github.com/hwillson/apollo-client-issue-2533). If anyone is still encountering this issue, please post back and let us know. Thanks!
