### ISSUE TITLE
Apollo Cache with Relay Modern

### ISSUE THREAD

**Issue by tlvenn** [apollographql/apollo-client#2558]
Similarly on how apollo-link can be used with Relay Modern, I am wondering if apollo-cache could not be integrated in Relay Modern as well.

Contrary to what I had believed, Relay Modern does not ship with any cache at all but one can easily be added at the network level:

> https://github.com/felippepuhle/relay/blob/069c5af8c19132ccde29be5ffddc0be7c2d7dbfb/docs/modern/Caching.md

Relay Modern ships a very rudimentary in memory cache with `RelayQueryResponseCache` and it would be great if we could tap into apollo-cache and its plugins such as apollo-cache-hermes.

**Comment by jbaxleyiii** [comment]
@tlvenn are there any docs on what a relay cache would need?

**Comment by tlvenn** [comment]
Hi @jbaxleyiii,

First I should correct myself by saying that the default cache (named `store` in Relay Modern) provided by Relay Runtime (`RelayMarkSweepStore`) is not rudimentary at all. They just choose to have a pretty agressive GC strategy which purge any data that is not referenced in your view anymore.

The good news is the store is entirely pluggable, very similarly to Apollo Client 2.0 with its cache. And there is clear contract defined as an interface for the store itself:

> https://github.com/facebook/relay/blob/master/packages/relay-runtime/store/RelayStoreTypes.js#L96

**Comment by tlvenn** [comment]
@jbaxleyiii any chance to take this issue into some consideration ?

**Comment by hwillson** [comment]
While we're not opposed to this idea, this isn't something the Apollo team is planning on working on anytime soon. If someone in the community wants to dig into this further, and needs any specific changes made to `apollo-client` to make this happen, please let us know. We're always open to PR's that make `apollo-client` (and its supporting libraries) more re-usable with other libraries. Since there hasn't been much traction here though, I'll close this for now. If anyone is interested in championing this idea, please post back and let us know. Thanks!
