### ISSUE TITLE
[apollo-cache-inmemory] ESLint problems importing InMemoryCache

### ISSUE THREAD

**Issue by nabiltntn** [apollographql/apollo-client#2591]
**Intended outcome:**

After installing `apollo-cache-inmemory`, import and use `InMemoryCache`

**Actual outcome:**
 Errors in ESlint and when starting application.

```
Line 2:  Unable to resolve path to module 'apollo-cache-inmemory'  import/no-unresolved
Line 2:  Missing file extension for "apollo-cache-inmemory"        import/extensions
```

**How to reproduce the issue:**

Install the package and import `InMemoryCache` using 
```js
import { InMemoryCache } from 'apollo-cache-inmemory';
```
**Version**

- "apollo-cache-inmemory": "^1.1.1"
- "apollo-client": "^2.0.3"
- "apollo-link": "^1.0.3"
- "apollo-link-context": "^1.0.1"
- "apollo-link-http": "^1.2.0"

**Comment by stefanmaric** [comment]
Experiencing the same.

**Comment by nabiltntn** [comment]
It works when adding `/lib` :

```
import { InMemoryCache } from 'apollo-cache-inmemory/lib';
```
Is it the intended way ?

**Comment by stefanmaric** [comment]
> Is it the intended way ?

I don't think so. Probably has something to do with this PR: https://github.com/apollographql/apollo-client/pull/2466

**Comment by jbaxleyiii** [comment]
@kamilkisiela do you have any idea why this happened?

**Comment by kamilkisiela** [comment]
@jbaxleyiii I did some testing and it seems ESLint doesn't care about package.json's `main` field. If I set `main: "./lib/index.js"` ESLint warns that `apollo-cache-inmemory/index.js` is missing. Which is true but because there is no `./index.js` this is why we have `main` in package.json to point to the entry file.
I could set there any path, it still won't work.

We could publish `apollo-cache-inmemory` the same way we do with `apollo-client`, meaning all the files would be in root directory of a package. I checked and it solves the issue.

**Comment by kamilkisiela** [comment]
@jbaxleyiii About the publishing process. Since all packages share exact same file structure and have the same values for package.json's `main`, `jsnext:main`, `module` we could do in `apollo-client` the same thing I did in `apollo-angular`.

Lerna mono repo. Every package has the npm script called [`deploy`](https://github.com/apollographql/apollo-angular/blob/8440034ed8f1d8d3e55c2abb4561780f6574901b/packages/apollo-angular/package.json#L21) that is placed in [`scripts/deploy.sh`](https://github.com/apollographql/apollo-angular/blob/8440034ed8f1d8d3e55c2abb4561780f6574901b/scripts/deploy.sh). 
This way I run `npm run deploy` in root to publish all or `cd packages/<name> && npm run deploy` to publish just one.

We could create a repository to keep those scripts so we can use them in many places (apollo-angular, apollo-client, apollo-link etc).

**Comment by mechanical-turk** [comment]
For those who had this error start happening out of nowhere, it's probably because you're using `^` in your package json. Npm adds this by default when you install packages. It will make your package manager download the latest major version. For example, if your package version in your package.json is `{"apollo-cache-inmemory": "^1.1.1"}`, and the latest version is `1.9999.9999`, your package manager will download `1.9999.9999`. This won't happen in your local dev environment. You probably saw this error in a continuous integration environment while deploying. Its' because that environment *will* download the latest major version.

If you want a quick fix, just take out that nasty ol `^` out of the version string.

Steps:

1) "apollo-cache-inmemory": "^1.1.1" --> "apollo-cache-inmemory": "1.1.1"
2) delete node_modules
3) delete package-lock.json
4) run `npm install`

**Comment by jbaxleyiii** [comment]
@kamilkisiela thanks for the feedback! I'm working on making the repo easier to interact with so those are great things to know!

**Comment by niieani** [comment]
Actually, the reason for this issue is that path for `jsnext:main` is wrong in all the the packages, e.g.:

https://github.com/apollographql/apollo-client/blob/37e6f9b8adc1bf2fc12bb8c3cb5c2aa898702ce2/packages/apollo-cache-inmemory/package.json#L12-L15

You can see that it's missing a `.` in front. This causes the eslint rule to resolve it from the root instead of relative to the package.

The bugs were introduced in #2466. Another issue is that MapCache, which is not re-exported is now unusable from Node (only when building with Webpack) since it's not exposed in index (on purpose, I didn't want to add it to the bundle, since it would increase it's size).

**Comment by jbaxleyiii** [comment]
@niieani this is great information! I'll work on fixing this for the next build and if you have any other ideas on how to improve our bundlesize / this?

**Comment by niieani** [comment]
@jbaxleyiii Nothing more comes to my mind at this time, just the `sideEffects` tip I mentioned above. As for the fix, we can actually do without `./` in the `main`/`module`/`jsnext:main`/`typings` fields, because they're implicitly relative: i.e. `lib/index` or `lib/index.js` should be enough.

**Comment by WaldoJeffers** [comment]
Any updates on this?

**Comment by glennreyes** [comment]
@niieani @jbaxleyiii IIRC I think we can open a PR fixing the path of `jsnext:main`?

**Comment by niieani** [comment]
@glennblock I'm only a contributor (not a maintainer), but I say go for it! :)

**Comment by glennblock** [comment]
Wrong Glenn :-)

**Comment by glennreyes** [comment]
👋  @glennblock nvm ... all good 👉  https://github.com/apollographql/apollo-client/pull/2648

**Comment by niieani** [comment]
Sorry about that @glennblock, I blame GitHub's autocomplete 😂

PR looks good enough to fix for now @glennreyes.

**Comment by glennblock** [comment]
@niieani all good. I didn't think I had filed any issues against apollo, but still happy to here :-)
