### ISSUE TITLE
[API Request] -Expose `restore`, `extract` from underline cache to ApolloClient

### ISSUE THREAD

**Issue by yuit** [apollographql/apollo-client#2607]
While using new ApolloClient with Hermes cache, we end up have to directly access the cache to perform `restore`or `extract`

```typescript
const client = new ApolloClient(...);
...
client.cache.restore(...);
// or
client.cache.extract();
```

**Intended outcome:**
We would like to propose a slight change in the API and expose `restore` and `extract` method

```typescript
const client = new ApolloClient(...);
...
client.restore(...);
// or
client.extract();
```
**Version**
- apollo-client@2.0.0

ping @nevir

**Comment by jbaxleyiii** [comment]
@yuit this seems totally fine to me! I'm going to label this as a good first PR to see if anyone wants to grab it, if not I'll get it added!

**Comment by M-Zuber** [comment]
I'd like to give this a shot, where should I start?

**Comment by jbaxleyiii** [comment]
@M-Zuber so great!! What needs to be done is add two methods to the `ApolloClient.ts` file that wraps the underlying cache calls (`extract`, `restore`). We do this already for items like `readQuery` so that is a great starting point: https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/ApolloClient.ts#L278-L285

Then we need a test for both. You may be able to just replace some existing `cache.extract` with `client.extract` or model new tests where you check that `client.extract() === client.cache.extract()`.

After that, if you want, you can update the docs (the server side render recipe comes to mind) with the new easier way to use it!

Don't hesitate to ping me here or in the apollo slack if you run into anything!

**Comment by yuit** [comment]
@jbaxleyiii @M-Zuber  Thank you for this lighting fast respond ⚡️
