### ISSUE TITLE
Fragment Matcher warning when __typename is included for Union types

### ISSUE THREAD

**Issue by spypsy** [apollographql/apollo-client#2694]
**Intended outcome:**
I have created a mutation that can return one of two types, therefore described the return type as a Union of the 2. On the client I have described the mutation like this: 
```
    mutation(input: $input) {
      ... on Type1 {
        id
        field1
        field2
        field3
      }
      ... on Type2 {
        id
        another_field
        another_field2
        a_nested_field {
          id
        }
      }
    }
```

The graphql server (Apollo's server) returns a type with the correct `__typename` assigned thanks to a `__resolveType` that I have added. I expect that the fragment matcher would be able to determine which type I am sending back since the `__typename` is clearly stated in the object

**Actual outcome:**
However the client is still that the Fragment matcher cannot correctly match the types and I would have to use the `IntrospectionFragmentMatcher`. It tries to write the response to the store as both types. 

What I don't understand is why can't the fragment matcher simply understand which type we're sending and write that to the store since it __clearly__ defined in the object(s) that I receive from the GraphQL server

**How to reproduce the issue:**
Use any union type as a result to a mutation and then create a client mutation similar to the one described above

**Version**
- apollo-client@2.0.3

**Comment by helfer** [comment]
I think your app will still work, but Apollo is printing the error message because it can't tell for sure if the fragment that doesn't match should really not match. Here's what I think is happening.

You return a result with `__typename: 'Type1'`. The fragment matcher can match fragment 1, so your result will be okay. For the fragment on Type2 however, it can't tell whether it should match or not. It doesn't know that Type2 is not a union type per se. All it knows is that there's a type condition that doesn't match, so it warns you about it. If you're sure that you've done everything correctly, then your app will work just fine and you can ignore the error. If you just want the error to go away, you can use the IntrospectionFragmentMatcher and don't provide it any information about types. For more info, see the [comment in the source code](https://github.com/apollographql/apollo-client/blob/e7fb145cc730f6d299ff1de564b0acafe7d535ae/packages/apollo-cache-inmemory/src/fragmentMatcher.ts#L70).

I hope that helps!

**Comment by spypsy** [comment]
Right that makes sense, thanks a lot for taking the time to respond @helfer!
