### ISSUE TITLE
Feature idea: fetchPolicy to only fetch fields that are missing in cache.

### ISSUE THREAD

**Issue by jonaskello** [apollographql/apollo-client#2872]
It seems like the `fetchPolicy` = `cache-first` always fetch all fields of a query from the network, even if some fields are available directly from cache.

For example this query:

```
  query MeasurementEditorQuery($measurement_no: Int!) {
    measurementByNo(measurement_no: $measurement_no) {
      ...
    }
    parameterGroups {
     ...
    }
  }
```

If the `measurementByNo` field is already in cache for the given `$measurement_no` but the `parameterGroups` field is not in cache the whole query is fetched from the server, including all of it's fields.

Ideally the query would be stripped of fields available in cache first and then the stripped query is sent to the server. Then the server response is merged with the cache response to create a full response.

This is especially problematic since I'm trying to add a new record to the `measurementByNo` field on the client with measurement_no = -1 which is a placeholder for a new record. Since the parameterGroups field is not available from the store, whole query gets fetched from the server, and since measurement_no = -1 does not exist, my previously added new record is overwritten with `null`.

I could make several queries with different fetchPolicy but I don't think this should really be needed. Also the performance would be better if only missing fields are fetched.

So perhaps this could be added as a separate fetchPolicy like `cache-if-field-exists-otherwise-network`. Or maybe something less verbose :-):.

**Comment by Poincare** [comment]
This roughly feels like the query diffing logic that Apollo Client used to contain back in the day - maybe @jbaxleyiii can confirm whether I'm interpreting this correctly.

Although the "fill from cache and merge result" idea seems good at the outset, we realized that it is much more trouble than it is worth for the most part because it leads to very complicated situations with stale/new data. This makes the logic very difficult to reason about consistently.

The primary point of the cache in Apollo Client is actually UI consistency, not roundtrip reduction. Although the latter is accomplished to some degree by virtue of just having a caching mechanism, we shouldn't trade off ease of consistency in order to get fewer roundtrips.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Feature%20idea%3A%20fetchPolicy%20to%20only%20fetch%20fields%20that%20are%20missing%20in%20cache.&body=Migrated%20from:%20apollographql/apollo-client%232872) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
