### ISSUE TITLE
Stencil Integration

### ISSUE THREAD

**Issue by marcosfede** [apollographql/apollo-client#2908]
Are there any plans to make an integration with [Stencil](https://stenciljs.com/)?

**Comment by Poincare** [comment]
I haven't personally heard much about Stencil - it seems like a component library built on top of a virtual DOM. What would an integration between Apollo and Stencil look like? I imagine that a community supported integration would be quite welcome.

**Comment by marcosfede** [comment]
I think it could look quite similar to the react-apollo integration due to the similarities between react and stencil jsx syntax

**Comment by Poincare** [comment]
After digging into Stencil a bit more, it seems to me that it's meant as a *compiler* that produces web components that work with any frontend framework. Given this, I imagine that the way Apollo Client would work with Stencil would likely be pretty different because `react-apollo` is pretty tied to the way React does things.

Maybe I am misunderstanding the purpose behind Stencil - could you clarify what an integration would mean here? Maybe with an example or something?

**Comment by arjunyel** [comment]
Im trying to use Apollo with Stencil and its not compiling, any ideas? https://github.com/apollographql/apollo-client/issues/2901#issuecomment-379120657

**Comment by hwillson** [comment]
Thanks for the suggestion @marcosfede. This isn't something that's currently planned, so we'll close this for now. A community driven stencil + Apollo integration project would be awesome though, so if anyone is working on one please keep us posted!

**Comment by ardatan** [comment]
I just released Stencil-Apollo package for Stencil + Apollo integration;
Check out my blog post for details;
https://medium.com/the-guild/stencil-apollo-stencil-meets-graphql-6fec577ee615

**Comment by marcosfede** [comment]
@ardatan Awesome! thank you for this
