### ISSUE TITLE
query includes `id` field(same value) with weird behaviour

### ISSUE THREAD

**Issue by lonyele** [apollographql/apollo-client#2943]
I have in this very weird situation, I think It is related to #93 
From graphiql, there is no problem at all querying including id field with same value

```
[
      {
        "id": "123",
        "name": "John Smith"
      },
      {
        "id": "123",
        "name": "Sara Smith"
      },
      {
        "id": "123",
        "name": "Budd Deey"
      }
]
```
However with apollo-client, I get same amount of arrays but the values are same with the first array

```
[
      {
        "id": "123",
        "name": "John Smith"
      },
      {
        "id": "123",
        "name": "John Smith"
      },
      {
        "id": "123",
        "name": "John Smith"
      }
]
```
I'm now testing so I wouldn't use same value for id in real situation, though It gave me some frustrating time because of this weird behaviour. So this is intended right?

**Comment by Poincare** [comment]
This is intended behavior, assuming that you have some kind of `dataIdFromObject` function set up. This is because of the fact that the cache is normalized by the `id` value, meaning that it assumes that each piece of data with the same id represents the same object.

You can read [this post](https://dev-blog.apollodata.com/the-concepts-of-graphql-bc68bd819be3) to understand this point more clearly.
