### ISSUE TITLE
500 server status code?

### ISSUE THREAD

**Issue by oliviertassinari** [apollographql/apollo-client#3057]
Hi,

This is not a feature request nor a bug report. I don't know what's the best medium to provide this feedback so I'm gonna do it here.
[express-graphql recently moved](https://github.com/graphql/express-graphql/pull/419) from returning a 200 status code to a 500 status code when the `data` object is empty.
I don't know the codebase well enough to answer this question nor I can think of a testing process:

**Could it be an issue when a graphql endpoint returns an error with a status code 500 instead of 200 with apollo?**

Thanks.

**Comment by pleunv** [comment]
[apollo-link](https://github.com/apollographql/apollo-link) used to exit early on any error >= 300, however after a [recent change](https://github.com/apollographql/apollo-link/issues/208) this should not be the case anymore and the error should now trickle down to the component that caused it so that it can be handled there accordingly. 

So I _think_ the answer is **no, it should not be an issue**, but you might want to verify to be sure :)

**Comment by oliviertassinari** [comment]
@pleunv Thanks! We will see how the apps behave in production :).
