### ISSUE TITLE
Circular dependencies and fragment colocation

### ISSUE THREAD

**Issue by pulse14** [apollographql/apollo-client#3072]
The way fragment composition works (with tagged template literals) we can have circular dependencies between JS files even if there is no circular depedencies between fragments.

For example `ComponentA` use `fragmentA`. `fragmentA` is on `ComponentA.fragments.fragmentA` property.
This component use `mutationA` (stored in separate file). `mutationA` query use `fragmentA`

So, we have a circular dependency here (between component file and mutation file) even if there is no "real" circular dependencies between fragments/queries.

I see multiple solutions, but none of them really solve the issue :
- We don't colocate fragments, but it's what i'm trying to do ... :(
- Global namespace like relay but apollo use a completely different approach
- We use functions in tagged templates, but I think it's not an option...

And one more problem: if I don't colocate everything and want to use .graphql file,  I need to use `#import` and that's not in the spec I think.

I know I can colocate the mutation to fix the problem, but there is too much code in these files to handle store update, etc...

Maybe I'm missing something, is the way we organize the code uncommon ?

**Comment by hwillson** [comment]
The approach outlined in the [Reusing fragments](https://www.apollographql.com/docs/react/advanced/fragments.html#reusing-fragments) section of the docs is just a guideline. It works in a lot of cases, but isn't always a perfect fit. If you need to adjust your fragment approach to be more re-usable across a large number of components, then by all means use whatever solution makes the most sense in your case. Fragment colocation approaches like [`#import`](https://www.apollographql.com/docs/react/advanced/fragments.html#webpack-importing-fragments) (for webpack) or [`babel-plugin-import-graphql`](https://www.npmjs.com/package/babel-plugin-import-graphql) are great workarounds to the issues you've outlined.

**Comment by pulse14** [comment]
@hwillson Thanks for your answer. I don't think the issue is really solved. `#import` isn't official and has issues listed here https://github.com/facebook/graphql/issues/343

Could apollo add a way to use global namespace ?

**Comment by hwillson** [comment]
@pulse14 We're not currently planning any changes around using a global namespace (we're not big fans of the global namespace option due to the potential for naming conflicts - as mentioned in 
https://github.com/facebook/graphql/issues/343#issuecomment-322622003). The `#import` option isn't official, but does it need to be? Until (if?) an official approach is included in the graphql spec, the current `#import` options work quite well. We're definitely happy to consider any changes to Apollo Client, but in this case we don't see a large benefit that we'd gain from adopting a Relay approach, over the existing `#import` approaches. If people overwhelmingly want to see this though, we'll of course reconsider 🙂.
