### ISSUE TITLE
getMainDefinition has no TS definition for 'operation'

### ISSUE THREAD

**Issue by Falieson** [apollographql/apollo-client#3090]
I'm following this resource (I wish it were linked on the official docs related to apollo-link-ws omg, its what i've been looking for for days).

https://github.com/apollographql/apollo-client/blob/master/docs/source/features/subscriptions.md

**Intended outcome:**
I thought apollo stuff was all typed really well so I'm pointing out this issue with following the docs:
```
 const link = split(
    // split based on operation type
    ({ query }) => {
      const { kind, operation } = getMainDefinition(query)
      return kind === 'OperationDefinition' && operation === 'subscription'
    },
    wsLink,
    httpLink,
  )
```

**Actual outcome:**

Typescript Error
```
[ts] Type 'OperationDefinitionNode | FragmentDefinitionNode' has no property 'operation' and no string index signature.
const operation: any
```

**How to reproduce the issue:**
Follow the docs link

**Version**
- apollo-client@2.2.5

**Comment by ucanlendit** [comment]
same..

**Comment by sean-clayton** [comment]
@Falieson just curious: Are you using create-react-app-typescript?

**Comment by wiktor-golonka** [comment]
Same here. Using Angular 4. 
```
        "apollo-angular": "^1.0.1",
        "apollo-angular-link-http": "^1.0.2",
        "apollo-client": "^2.2.8",
        "apollo-link-ws": "^1.0.7",
```

**Comment by hwillson** [comment]
Thanks for pointing this out @Falieson. This is because `getMainDefinition` can return either a `OperationDefinitionNode` or `FragmentDefinitionNode`, but only `OperationDefinitionNode` has an `operation` property. 

The code samples in the docs are (for the most part) JS examples. To avoid the Typescript compilation error you could follow the approach listed in https://github.com/apollographql/apollo-client/issues/3090#issuecomment-379804727, or do something like:

```ts
interface Definintion {
  kind: string;
  operation?: string;
};

const link = split(
  ({ query }) => {
    const { kind, operation }: Definintion = getMainDefinition(query);
    return kind === 'OperationDefinition' && operation === 'subscription';
  },
  wsLink,
  httpLink,
);
```

Code samples are going to remain primarily JS based (at least for now). Thanks!
