### ISSUE TITLE
Misleading documentation with regards to `query`'s `fetchPolicy` allowed policies

### ISSUE THREAD

**Issue by shoooe** [apollographql/apollo-client#3130]
**Intended outcome:**
Set "cache-and-network" when querying directly from the ApolloClient.

**Actual outcome:**
Error message:

> Error: cache-and-network fetchPolicy can only be used with watchQuery

**How to reproduce the issue:**
Follow the documentation [here](https://www.apollographql.com/docs/react/reference/index.html#ApolloClient.query) and try to query via `client.query(...)` with fetch policy `"cache-and-network"`.

**Version**
- apollo-client@<version number>

**Comment by aldarund** [comment]
Yes, its not clear at all why u cant use cache-and-network with query....

**Comment by vegetablesalad** [comment]
I too have this problem.
[Official documentation](https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-config-options-fetchPolicy) even gives this example:

```
export default graphql(gql`query { ... }`, {
  options: { fetchPolicy: 'cache-and-network' },
})(MyComponent);
```

**Comment by macbutch** [comment]
I have this issue too. Is there any explanation for the restriction on using `cache-and-network` with queries? It seems especially strange given that the documentation describes this behaviour as the default (it isn't; the default is `no-cache`).

**Comment by hehoo** [comment]
Any update for this issue?

**Comment by audiolion** [comment]
wondering about this as well, or how to use watchQuery in tandem with query to manually fire a cache-and-network query.

**Comment by jlubeck** [comment]
Is there a workaround for this?

**Comment by theodorDiaconu** [comment]
Any update on this ? This is very strange!

**Comment by mikebm** [comment]
It appears "cache-and-network" policy does work with the new Query component, but not with client.query as everyone has found. I am not sure if this was the intended behavior or not but it is extremely frustrating given the incorrect documentation and lack of documentation around watchQuery.

**Comment by ack210** [comment]
@mikebm I was curious about this as well since cache-and-network was working fine with the Query component, but looking under the covers a bit it seems like the Query component actually does use watchQuery: https://github.com/apollographql/react-apollo/blob/1c666276b2206ae882fed3cc0bf6de38ab5432d8/src/Query.tsx#L167

I only looked briefly so I could be wrong, but maybe the Query component implementation could at least serve as an example of how to use the client "properly".

**Comment by cyberdude** [comment]
Is this still a thing?

**Comment by mikebm** [comment]
> Is this still a thing?

Yes. See the following code:
https://github.com/apollographql/apollo-client/blob/master/packages/apollo-client/src/ApolloClient.ts#L292-L296

**Comment by joelgetaction** [comment]
Hi,

Hey @hwillson or @peggyrayzis can we get some movement on this issue please?  This is impacting a large number of people and we really need a bug fix.  :-)

Thanks!

**Comment by cyberdude** [comment]
For those wondering how to use fetchPolicy with client.query, I did the following after digging in the source code.  I hope this helps.

```
  const { data } = await client.query({
    query: gql`
    ${fullRouteFragment}
      {
        cars(feature_id: "${id}", published_status: ALL) {
          ...fullRouteFields
          ${(additionalFields || []).join("\n")}
        }
      }
    `,
    fetchPolicy: "network-only"
  });
```

**Comment by mikebm** [comment]
@cyberdude this issue is specific to `network-and-cache`, your example uses network-only which was never an issue. There is code in the apollo client to throw an exception when using `client.query` with a fetchPolicy of `network-and-cache`, which is the opposite of what the documentation states.

**Comment by cyberdude** [comment]
Ahh right, sorry, I was confusing this with another one about missing documentation. Deleting original useless comment I made.

Thanks.

**Comment by saernz** [comment]
Oh man still not resolved 😭I've had soooo much problem with Apollo docs today regarding local state and thought I was finally on a roll until I tried to implement something that seemed like core functionality only to find it doesn't work :(

Is there a work around for this or do we just need to use `network-only` for now? 😭

**Comment by smolinari** [comment]
Related earlier reported bug: https://github.com/apollographql/apollo-client/issues/3880

Scott

**Comment by smolinari** [comment]
Duplicated.... https://github.com/apollographql/apollo-client/issues/3880

Scott

**Comment by PowerKiKi** [comment]
The current method signature is:

https://github.com/apollographql/apollo-client/blob/166f28f5ae9846cfb2ca863b3302f64a23731f54/packages/apollo-client/src/ApolloClient.ts#L331-L333

So because `query()` returns a `Promise` it can only ever resolve to a single value (on the contrary `watchQuery()` returns an `Observable` which can resolve to multiple values over time).

That means `cache-and-network` cannot be implemented for `query()` (without introducing a breaking change in the method signature). If you need `cache-and-network` behavior, then you must use `watchQuery()`.

However we can reduce friction for new users by enforcing this constraint by splitting up `FetchPolicy` into two distinct types, and updating the docs. Probably something like:

```ts
export type FetchPolicy =
  | 'cache-first'
  | 'network-only'
  | 'cache-only'
  | 'no-cache'
  | 'standby';

export type WatchFetchPolicy =
  | FetchPolicy
  | 'cache-and-network';
```

@hwillson would you accept a PR for this kind of fix ? or would there be a more appropriate approach ?

**Comment by hwillson** [comment]
@PowerKiKi Yes, we'd definitely accept a PR for this - thanks!

**Comment by sanchan** [comment]
Just in case somebody needs a workaround, I'm doing this:
```
const result = await client.watchQuery({
      query: MY_QUERY,
      fetchPolicy: 'cache-and-network'
}).result();
```

**Comment by DavidStummer** [comment]
Any workaround for this yet?

**Comment by benjamn** [comment]
While the error message could be improved, there is no logical bug to fix here.

As @PowerKiKi [explained above](https://github.com/apollographql/apollo-client/issues/3130#issuecomment-478409066), the `cache-and-network` policy only makes sense if you're prepared to receive multiple results. Since the `ApolloClient#query` method can only produce one result per call by returning a `Promise<ApolloQueryResult<T>>`, there's no way to get both a result from the cache and a result from the network when calling `ApolloClient#query`.

In other words, while this error doesn't do a great job of explaining itself (beyond the simple fact that `cache-and-network` should only be used with `watchQuery`, which is true), it does a fine job of preventing anyone from mistakenly using the `cache-and-network` policy in a situation where the client cannot obey that policy.

It's also worth noting that React Apollo uses `watchQuery` under the hood, which is why the `cache-and-network` policy makes perfect sense with React Apollo.

Given the misconceptions that have proliferated in this issue, it's very tempting to "solve" this issue by silently replacing `cache-and-network` with `cache-first` in `ApolloClient#query` (perhaps with a friendly warning), since that's almost certainly what folks really want here.

**Comment by PowerKiKi** [comment]
> silently replacing cache-and-network with cache-first in ApolloClient#query

I strongly disagree with that. It will only bring even more confusion to users as they specifically asked for a behavior that can never be valid, but the patch will _unexpectedly_ change the behavior. This patch make Apollo less predictable and more obscure.

The fetch policy is already hard enough to grasp not to introduce a `cache-and-network-but-sometimes-just-cache-first`.

Also it is very debatable what users actually want to do. In our case we replace `cache-and-network` with `network-only`, because we want to be sure to have the latest data from server. Assuming that everybody always want potentially stale data is a very slippery slope. The only person who can properly make the decision is the user by choosing the correct and valid fetch policy for his unique use-case.

Instead I believe we should teach users what is possible or not, and not allow them to have expectations that can never be full-filled.

@hwillson already [agreed](https://github.com/apollographql/apollo-client/issues/3130#issuecomment-480525196) on that alternative. Was it debated with him before implementing 70fdf25b2b2800a5cac41d12dddd4fefb4c3db20 ? Is there a chance to be reverted ?

**Comment by DavidStummer** [comment]
@benjamn it makes sense that given `ApolloClient#query` it returns a promise, it can't perform a cache query then a network query.

I will put my use-case here, maybe it will help clarify what I am trying to achieve. Apologies if it is the wrong place. I need to fetch from cache, then fetch from network if possible (what `cache-and-network` would do). So, I could query twice using `cache-only`, and again using `network-only`, _but_ the crucial thing here that `cache-and-network` does it that it updates the cache if fresh data comes down, whereas to my understanding querying via `ApolloClient#query` using `network-only` doesn't do that. Is there a way to manually update the cache in this situation?

Thanks.

**Comment by PowerKiKi** [comment]
@DavidStummer if you want `cache-and-network`, then you have to use `watchQuery`. Nothing more, nothing less. Anything else would be just re-inventing the wheel.

**Comment by DavidStummer** [comment]
@PowerKiKi thanks for the clarification. I think I got confused and now realise that `network-only` does indeed store the data in the cache for later use. Thanks.

**Comment by DavidStummer** [comment]
I think throwing an error which states something like 'It makes no sense to use cache-and-network with ApolloClient#query, as this function returns  promise' would educate new users quickly and avoid this confusion.

**Comment by PowerKiKi** [comment]
@benjamn your last commit is exactly what I had in mind.

This way TypeScript users are prevented to shoot themselves in the foot, thanks to the strong typing. And JS vanilla users would still get an error on runtime to inform very explicitly that they are doing something wrong.

Thank you for taking the time to implement it.

**Comment by timhwang21** [comment]
Hi @benjamn @PowerKiKi I'm a bit confused about this change. Now, `cache-and-network` is apparently no longer permitted for `react-apollo` `<Query/>`s. But reading this issue, this seems not to be the intention? As @ack210 mentions a year ago, `<Query/>` does in fact use `watchQuery`.

Do `react-apollo` types need to be updated such that `fetchPolicy` uses `WatchQueryFetchPolicy` instead of `FetchPolicy`? (I can also file a bug report and/or PR if needed.)

**Comment by benjamn** [comment]
@timhwang21 It might be a breaking change if you consider only the type system, but I think it better reflects what would actually happen if you tried to pass `fetchPolicy: "cache-and-network"` to the `query` method—it would thrown and exception at runtime. So I'm pretty sure there won't be any code that worked before this, but is now broken by this change… though of course there are always edge cases, and we welcome reports of unexpected surprises.

Longer term, I think the `watchQuery` behavior of subscribing to multiple query results should become the preferred/only way to fetch queries, since it's what React Apollo uses, and it's clearly more flexible than the single `Promise<ApolloQueryResult<T>>` returned by the `query` method. We have some good ideas about how to merge those APIs together without totally disregarding backwards compatibility, but that transition will probably happen in the Apollo Client 3.0 timeframe.

**Comment by timhwang21** [comment]
> So I'm pretty sure there won't be any code that worked before this, but is now broken by this change

Just to make sure my own code isn't broken, this is disregarding types right? Just want to make sure `<Query fetch policy="cache-and-network">` is valid!

**Comment by joelgetaction** [comment]
Hi @benjamn - thanks for your hard work on Apollo.

I've had several use cases where the declarative nature of `<Query ...>` just doesn't work and where we needed to use `query()` as a result.  I guess I don't understand why it's not allowed or supported to use `cache-and-network` for plain imperative `query()`?  I get that promises only allow a single value to be returned but couldn't this be achieved with some kind of callbacks or observables?  I just disagree with the decision to remove `cache-and-network` from the imperative `query` function.

I disagree because caching and coding style (declarative vs imperative) are orthogonal to each other and should remain so.  For example:

* `query()` vs `<Query>` is about imperative vs declarative coding style and both styles have valid use cases
* `cache-and-network` is about "make my app appear faster by first using a cached value but then refresh with a new network value if it comes back different to what was in my cache" 

These two points have nothing to do with each other and should not be connected.  One is about coding style, the other is about data staleness.   They are not and should not be related.

I really feel uncomfortable that in order to use `cache-and-network` we're being forced to use the declarative `<Query>` style.  That feels heavy-handed to me and is not a step in the right direction.

I really appreciate you all open-sourcing Apollo and I don't mean to sound like a whiner.  I appreciate all your hard work.  But I just don't understand why you can't add `cache-and-network` to the imperative `query()` function.  This PR feels like a step in the wrong direction IMHO ...

**Comment by benjamn** [comment]
@timhwang21 `<Query fetch policy="cache-and-network">` has always been valid, because that option gets passed through to the `watchQuery` method of `ApolloClient`, which has always accepted the `fetchPolicy: cache-and-network` option. That said, if you happened to try this in the short span of time between when `apollo-client@2.6.0` (last night) was released and `react-apollo@2.5.6` was released (this morning), please make sure to update `react-apollo` if you haven't already!

> I get that promises only allow a single value to be returned but couldn't this be achieved with some kind of callbacks or observables?

@joelgetaction That's what `watchQuery` is for. For what it's worth, if I were rewriting this API from scratch, the `watchQuery` behavior would be the only option, and that method would be called `query` instead of `watchQuery`. If/when that happens (perhaps in Apollo Client 3.0), I think most of what's bothering you will disappear.

> Or is the intention that we should use `watchQuery` in this case?

This is exactly the intention, and I don't think renaming the `<Query>` component to `<WatchQuery>` makes sense, not only because it would be a disruptive change for React Apollo users, but also because the component-ness of the `<Query>` component strongly suggests that it will be updated over time, rather than only ever rendering one result.

For anyone who didn't already know that `watchQuery` is for multiple results and `query` is for a single result, you now have both the type system and a runtime invariant to make sure you think about the distinction.

**Comment by PowerKiKi** [comment]
> the `watchQuery` behavior would be the only option, and that method would be called `query` instead of `watchQuery`

This would be a great improvement, albeit breaking a ton of code of course. As newcomers it took us a long time to figure out that the existing `query` method is mostly useless, and `watchQuery` is by far the superior choice in all cases.

Until that breaking change happen, it could be possible to emphasized in documentation that `query` should be avoided in most cases. That would be a sort of "soft-deprecation" ...

**Comment by fozzarelo** [comment]
watchQuery unhadled promises cannot be caught.

**Comment by zhuhang-jasper** [comment]
Its 2021 and what's the solution?
