### ISSUE TITLE
Add notes about immutability

### ISSUE THREAD

**Issue by lorensr** [apollographql/apollo-client#3199]
I couldn't find any place in the docs that talks about whether callback args should be mutated or not. Eg results from `read*` or the first arg to `updateQuery`. Some may be used to generally not mutating things given from libraries in React or Redux, but perhaps it's worth noting, either in the documentation for each function, or a blanket statement somewhere.

Somewhat related: #2597

**Comment by hwillson** [comment]
Flagging this as a feature request (since we'll have to work out an official stance on immutability).

To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Add%20notes%20about%20immutability&body=Migrated%20from:%20apollographql/apollo-client%233199) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!

**Comment by lorensr** [comment]
It's meant as a request for documentation on current practices. Does that fall under the new repo?

**Comment by hwillson** [comment]
Right, but the current practices go both ways right now. We definitely need more discussion on this, but I think we should move it for now (since it's not a bug). We're really trying to reduce the issue list in this repo to clear cut bugs only (as much as possible). Thanks!
