### ISSUE TITLE
apollo-boost => named import ApolloClient vs default import Error

### ISSUE THREAD

**Issue by ultrox** [apollographql/apollo-client#3368]
**Intended outcome:**

I was trying to create client by importing ApolloClient

`import { ApolloClient } from "apollo-boost";`

Following the documentation I did it like this:

```
const client = new ApolloClient({
  uri: "https://w5xlvm3vzz.lp.gql.zone/graphql",
});
```
I was expecting to send the query and get the console.log result
```
client
  .query({
    query: gql`
      {
        rates(currency: "USD") {
          currency
        }
      }
    `,
  })
  .then(result => console.log(result));
```
**Actual outcome:**

I got this error:
`In order to initialize Apollo Client, you must specify link & cache properties on the config object.
`

This happened because I followed one of the countless outdated tutorials out there, and didn't replaced named import.

I took a look in apollo-boost and notice there is no name export but only default, somehow when in browser this named import ApolloClient gets imported from another place. I

**How to reproduce the issue:**

Here, just visit the link: https://codesandbox.io/s/vpq7wm1wl 

**Version**
- apollo-client@^2.1.3

**Comment by hwillson** [comment]
Thanks for pointing this out @ultrox - I agree, this is definitely confusing. There is a backstory here, but long story short, the named `ApolloClient` export is in place for backwards compatibility reasons. It's coming [directly from the `apollo-client` package](https://github.com/apollographql/apollo-client/blob/493d9a787011b7e5524edafa97422144ad8d64d1/packages/apollo-boost/src/index.ts#L2).

We might be able to get rid of this now, but in the meantime we could at a minimum update the `In order to initialize Apollo Client, you must specify link & cache properties on the config object.` error message to mention the named import issue, for `apollo-boost` users.

**Comment by wzup** [comment]
Same here
https://github.com/apollographql/apollo-client/issues/3639

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=apollo-boost%20%3D%3E%20named%20import%20ApolloClient%20vs%20default%20import%20Error&body=Migrated%20from:%20apollographql/apollo-client%233368) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
