### ISSUE TITLE
update is not called in mutation when fetchPolicy set to 'no-cache'

### ISSUE THREAD

**Issue by aunz** [apollographql/apollo-client#3401]
**Intended outcome:**
`update` option should be called when executing `client.mutate({ ... })`

**Actual outcome:**
`update` is not called when executing `client.mutate({ fetchPolicy: 'no-cache' })` 

**How to reproduce the issue:**
https://codesandbox.io/s/o98ylor0m5

**Version**
- apollo-client@2.3.0

**Comment by reeceaw** [comment]
I'm getting this too

**Comment by hwillson** [comment]
`client.mutate`'s `update` option/callback is intended to be used only when you want to interact with the data store (cache). The `update` callback itself gets sent a proxy to access the data store, as well as the result of the mutation. When you're using `no-cache` you shouldn't be interacting with the data store at all. If you want to fire actions after the mutation has completed, use the Promise returned from the `client.mutate` call. 

I am marking this as a bug though, since the docs really aren't very clear about this. I'll get them updated. Thanks!

**Comment by hwillson** [comment]
Addressed in https://github.com/apollographql/apollo-client/pull/3774. Thanks!
