### ISSUE TITLE
Should docs for the react-apollo mutations utilize functional components?

### ISSUE THREAD

**Issue by chrisfosterelli** [apollographql/apollo-client#3414]
The react-apollo documentation for Mutations has the following example which uses functional components: 

```javascript
const AddTodo = () => {
  let input;

  return (
    <Mutation mutation={ADD_TODO}>
      {(addTodo, { data }) => (
        <div>
          <form
            onSubmit={e => {
              e.preventDefault();
              addTodo({ variables: { type: input.value } });
              input.value = "";
            }}
          >
            <input
              ref={node => {
                input = node;
              }}
            />
            <button type="submit">Add Todo</button>
          </form>
        </div>
      )}
    </Mutation>
  );
};
```

The documentation for Queries also only uses functional components, except for one case where they use a class for `ApolloConsumer` and then follow with a recommendation to not use that pattern. 

This suggested to me that classes where not encouraged anymore with apollo-react, and only building the app out of functional components was the recommended pattern. Is this correct?

I can understand how only using functional components might occur naturally for the Query examples as there isn't state for most of those. However, I thought the use of a functional component here in the Mutation docs was very strange, because this uses a `ref` to store/manipulate state on the DOM node directly which is [not an encouraged pattern by react](https://reactjs.org/docs/refs-and-the-dom.html). This made me think that this was maybe a pattern being encouraged by Apollo.

- [x] docs

**Comment by hwillson** [comment]
Hi @chrisfosterelli - the docs tend to prefer the use of stateless functional components where possible, for various reasons (performance, creates smaller / more concise examples, personal preference, etc.). A `React.Component` approach can definitely be used instead, so please use whichever you prefer. That being said, I see your point regarding some of the `<Mutate />` examples manipulating form `input` state via the DOM. Resetting form `input` values this way is kinda one of those things that a lot of people are doing (since it's relatively harmless), even though it's not really recommended. But again, I do agree that the docs should make sure best practices are followed as much as possible.

If we updated the [The Mutation component](https://www.apollographql.com/docs/react/essentials/mutations.html#basic) section (which includes the first `<Mutation />` example that uses `input.value = ''`) to show an alternative approach using `React.Component`, and mentioned that manipulating state is better handled using `Component`'s, do you think that would help? So we'd add a second example like:

```js
class AddTodo extends Component {
  constructor(props) {
    super(props);
    this.state = { todo: '' };
    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(e) {
    this.setState({ todo: e.target.value });
  }

  resetTodo() {
    this.setState({ todo: '' });
  }

  render() {
    return (
      <Mutation mutation={ADD_TODO}>
        {addTodo => (
          <form
            onSubmit={e => {
              e.preventDefault();
              addTodo({ variables: { type: this.state.todo } });
              this.resetTodo();
            }}
          >
            <input value={this.state.todo} onChange={this.handleChange} />
            <button type="submit">Add Todo</button>
          </form>
        )}
      </Mutation>
    );
  }
}
```

Let us know - thanks!

**Comment by chrisfosterelli** [comment]
@hwillson Yes, I think that's a great solution and removes any chance for confusion!

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Should%20docs%20for%20the%20react-apollo%20mutations%20utilize%20functional%20components%3F&body=Migrated%20from:%20apollographql/apollo-client%233414) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
