### ISSUE TITLE
api for debouncing: apply only optimistic update & rollback

### ISSUE THREAD

**Issue by jardakotesovec** [apollographql/apollo-client#3425]
Coming from relay, I miss possibility to delay sending of the mutation to the server and apply only optimistic update until there is good time to commit it to server. Typical use case is filling the form. Now its necessary to keep the input values in the component state (or apollo store, but separately from server schema). Idea of including debounce options within apollo was already [discouraged](https://github.com/apollographql/apollo-client/issues/1886). 

There was similar discussion in Relay, which also had similar direction that debouncing should not go to the core. But there [was](https://facebook.github.io/relay/docs/en/classic/classic-api-reference-relay-store.html#applyupdate-static-method) good api for it in relay classic and its also somewhat possible with [modern api](https://github.com/apollographql/apollo-client/issues/1886)

Using this api its possible to quickly updating UI changes (like writing in input) and commit or rollback at the end. With every input change I could basically apply new optimistic change and rollback the previous one and at the end just commit the last version.

To make more clear how the api could look like - having either option for `store.mutate` method or separate method (like `store.localMutate`) that would return object with `rollback` and `commit` methods. 

Have not spent time with apollo client internals yet, so any feedback on how this is desirable and feasible to implement with current code base are hugely welcomed.

Looking forward to discussion.

- [ ] has-reproduction
- [x] feature
- [ ] docs
- [ ] blocking
- [ ] good first issue

**Comment by Dattaya** [comment]
It would be nice to have this feature. Right now, if you modified two values consecutively and each of them was tied to a debounced patch, you'd experience a flicker; here's a sequence of events that leads to it:
* Modify value 1
* `writeFragment` is called, `patchItem` call is scheduled to run in 0.5s.
* Modify value 2
* `writeFragment` is called, `patchItem` call is scheduled to run in 0.5s.
* First `patchItem` is executed and optimistic response 1 is received that causes the flicker
* Second `patchItem` is executed and an optimistic response 2 is received that restores value 2

Adding updated value 2 to the optimistic response of value 1 does not solve the problem because server's response isn't aware about the new value 2 and would return outdated instead.

This is how it looks like:
![ezgif-2-2a4719353e](https://user-images.githubusercontent.com/387256/41708380-23ca4fba-7549-11e8-94c9-18a813969a26.gif)

There is a solution proposed in https://github.com/apollographql/apollo-client/issues/1886#issuecomment-366022558 —adding a re-render toggle flag to a component, waiting for all debounced promises to complete and then propagate values to the components or alternatively adding an 'isDisabledValuePropagation' flag to each component and activate it at the beginning and once all debounced promises finished but it's not pretty. For some, making fields completely uncontrollable is an acceptable solution, but for many—it's not.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=api%20for%20debouncing%3A%20apply%20only%20optimistic%20update%20%26%20rollback&body=Migrated%20from:%20apollographql/apollo-client%233425) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
