### ISSUE TITLE
Error message is cryptic when using @client

### ISSUE THREAD

**Issue by aunz** [apollographql/apollo-client#3478]
Using the directive `@client` when requesting a non-null type results in an unexpected error message should the server throws an error

Server
```graphql
type query { hello(shouldThrow: Boolean): Thing! } # Thing is non-null
type Thing { name: String }
```
```js
const resolvers = {
  Query: {
    hello: (_, { shouldThrow }) => {
      if (shouldThrow) throw new Error('Oops from server!')
      return { name: 'world' };
    },
}
```
Client
```js
const client = new ApolloClient({
  clientState: {
    resolvers: {
      Thing: { stuff: ()  => 'some stuff' }
    }
  }
})

client.query({
  query: gql`query ($shouldThrow: Boolean) { hello(shouldThrow: $shouldThrow) {
    name
    stuff @client
  } }`,
  variable: { shouldThrow: true }
})
```

**Intended outcome:**
An error message from server "Oops from server"

**Actual outcome:**
Network error: rootValue is null

**How to reproduce the issue:**
https://codesandbox.io/s/v327343203

**Version**
- apollo-client@2.3.1

**Comment by SilvanCodes** [comment]
I've experienced the same error, I think it's due to the empty data key on the network query response which the local resolver then tries to merge with. I think the desired behavior could be a partial response including the local data and the remote error message. I'm unsure if the problem still exists in apollo-client@2.5.x.

Relevant part of the docs (of 2.5):

> After the query has been handled by the remote resolvers and the result is passed back to Apollo Client from the API, the @client parts of the original query are then run against any defined local resolvers, their results are merged with the network results, and the final resulting data is returned as the response to the original operation.

**Comment by jbaxleyiii** [comment]
Thanks for reporting this. There hasn't been any activity here in quite some time, so we'll close this issue for now. If this is still a problem (using a modern version of Apollo Client), please let us know. Thanks!

**Comment by keeslinp** [comment]
We are experiencing behavior similar to this on `apolloclient: 2.6.8`. I tried removing our local resolvers and it made the problem go away.

Our situation ist hat we're getting a response with the shape:
```
{
data: null,
errors: [ { ... some error info }]
}
```
and then apollo-client crashes here (https://github.com/apollographql/apollo-client/blob/86bfff808ead3492883e1e31c10647818db8cfe5/src/core/LocalState.ts#L358) because `rootValue` is null. So instead of throwing the correct error it throws an unhelpful one about indexing on null.

**Comment by alex-vladut** [comment]
I am also facing this issue with the latest apollo client version `3.5.10`. As mentioned in the comment above, the error only happens when a local resolver is defined and, if I remove it, the problem goes away. But I would like to keep the local resolvers, is there any way to fix this issue in that case? Thanks
