### ISSUE TITLE
Question: Why is __typename property enumerable?

### ISSUE THREAD

**Issue by capaj** [apollographql/apollo-client#3533]
I am quite new to apollo client so this might be a question that has been answered, if it is I apologize. I understand apollo query results always carry the `__typename` prop to make it possible to cache them easily. My question is-wouldn't it be better if this prop would be added to the object as  non enumerable? Is there a reason why it needs to be enumerable?

There are quite a lot of people who have an issue with this and IMHO it would solve most of the problems if it was nonenumerable.

**Comment by KaySackey** [comment]
To me, having `__typename` as an enumerable is invaluable since when I copy graphql results to another object, the type information isn't lost. When debugging, its always obvious where the the data came from.

I am curious, what are a lot of issues people have with this?

**Comment by capaj** [comment]
@KaySackey having a property non enumerable does not mean you can't copy it. You just have to be explicit about it, which is IMHO preferable, because most people will run things like `Object.entries()` on their data and will be unpleasantly surprised as it currently is.

**Comment by KaySackey** [comment]
`__typename` is part of a valid GraphQL return though, and is returned by the query.

For those of us who use apollo-client directly, instead of via the React/Angular/etc. integration, this will likely be a major change. 

To me, that's the issue. 

The rest of my codebase predates usage of GraphQL, so very little of it is explicitly written to deal with Apollo itself. This includes most of the 'middleware' type transformations, which if `__typename` became non-enumerable, would no longer preserve it for further processing down the line.

`Object.assign` for instance only works on enumerable properties. So if you were using say MobX, and wanted to extend an existing observable, you may write code similar to` Object.assign({}, obj.myObservable, values);`. It would have been expected that the new object would have __typename in it, but now it wouldn't and any checks written for __typename would fail.

That's just off the top of my head.

**Comment by capaj** [comment]
@KaySackey I am not saying this is a minor change. This is certainly a change which would require a major version bump. Thanks for explaining how it could break existing code, but I don't think it was necessary. I'd rather hear all the usecases you have for it when using it in the real world apps. Because for me, it was causing just issues-I never really used this field for anything in my react apps. Hence why I opened this issue. It seems bad to force so many developers do weird hacks to omit this, when the javascript has this nifty property flag.

**Comment by anton-kabysh** [comment]
`__typename` is technical fields used by Apollo client internally and I was surprised why it's not an symbol in 2018.

For example, when I want to initialise form with data received from query I need to filter out `__typename`, because when I sent the same data back with mutation I will get and error because `__typename` is not defined on input type. 

Basically, it breaks workflow when I can't sent with mutation data that i've just received with a query.

**Comment by capaj** [comment]
@hwillson I've posed this as a question, because I didn't want to seem too aggressive, but really I should just change the title of this issue to be "Use a symbol to hide away the `__typename` property on a query result"

**Comment by anton-kabysh** [comment]
Basically, `__typename` is injected by Apollo into query to fetch a `type` of the queried entities. Those types is used by `apollo-client` to build `id` property (which is symbol) for caching purposes in `apollo-cache`. So, `__typename` is a valid property of query response and almost always ignored by developers and does not hurt anyone. 

But generally speaking it's a bad design decision to have `__typename` property in response because:  _it's not what i've requested_. I am not against `__typename` for caching purposes, but I don't want to have it in data received. 

I gave one example with form when I initialise form with query and can't submit it with the same data immediately.

Second example when `__typename` is a pain when I use result of GraphQL query to generate excel file. Of course, I don't want to see any `__typename` columns in my exported file. For this case I use second fetch-only `apollo-client` instance with `addTypename: false` property set for `cache` instance.

Best,
Anton.

**Comment by zimme** [comment]
The one problem I have with `__typename` is that it's added without someone explicitly stating that they want it in their query.

As it's something used by apollo internally and added without any interaction by the developer it should be removed/non-enumerable when the developer us using the result and if you as a developer want the `__typename` then you should just add it to your query and then it should be enumerable.

**Comment by clayne11** [comment]
The `__typename` is important when you're dealing with union and interface types though. We can't remove it. I agree with it not being enumerable though.

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Question%3A%20Why%20is%20__typename%20property%20enumerable%3F&body=Migrated%20from:%20apollographql/apollo-client%233533) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
