### ISSUE TITLE
refetchQueries only refetches a single query

### ISSUE THREAD

**Issue by wmertens** [apollographql/apollo-client#3540]
**Intended outcome:**

After a mutation, the `refetchQueries` prop is used and all queries that have matching names are refetched.

**Actual outcome:**

After a mutation, the `refetchQueries` prop is used and the first query for each matching name is refetched.

**How to reproduce the issue:**

I don't have time to create a reproduction right now, I'm hoping this rings a bell, if not I can create a repro.

Basically, we have several queries with the same name that have slightly different fields, eg. `query foo { foo { id bar } }` and `query foo { foo { id meep } }`. Since v2.1 of react-apollo, only one of those queries gets updated.

**Version**

* apollo-client@2.2.8
* react-apollo@2.1.2

It used to work before.

(This is a copy of https://github.com/apollographql/react-apollo/issues/1897 - apologies if that's bad form, but that one didn't get any replies and I thought that maybe it's more related to apollo-client anyway.)

**Comment by TSMMark** [comment]
I'm in the same boat. We have multiple instances of `<Query` react components, each loads the same query, but with different variables. When using `graphql` HOC with option `refetchQueries`, only the latest query is refetched.

**Comment by TSMMark** [comment]
Confirmed apollo has > 1 queries registered with different IDS, however, only the latest one gets refetched

![screen shot 2018-08-06 at 3 36 43 pm](https://user-images.githubusercontent.com/4197823/43737243-aba6235a-998e-11e8-96fe-51edc7d647a9.png)

The refetched query also appears to ignore the `skip` option when refetched by name; although, that is probably another issue.

**Comment by arist0tl3** [comment]
Spent a while on this one. 

@hwillson there is a repro here: https://github.com/arist0tl3/apollo-client-test

When `refetchQueries` is passed in as an array (`refetchQueries: ['Dates']` in the repro), then it looks like `refetchQueries` resolves to an actual query object (the first one it finds?)

When `refetchQueries` is passed in as a function that resolves to an array (`refetchQueries: () => ['Dates']` in the rero), then `refetchQueries` is an array of strings, and  `refetchQueryByName` seems to work as expected.

I know I've seen other `['Query']` vs `() => ['Query']` discussions around here, so I'm not sure what the expected behavior is, or if the docs need to be updated, etc.

**Comment by spyshower** [comment]
>  so I'm not sure what the expected behavior is, or if the docs need to be updated, etc.

Yeah like so many other things on Apollo that you expect to work like they should, or at least how it is explained in the docs. Sometimes the project feels abandoned.

**Comment by asselstine** [comment]
@TSMMark Thank you for the code.  I think it should really be part of Apollo core; being able to call refetchQueries outside of a mutation is pretty essential.

I might incorporate it as part of a library, and I'll be sure to include a link to this comment.

**Comment by asselstine** [comment]
@TSMMark I've created a package called [apollo-refetch-queries](https://github.com/DeltaCamp/apollo-refetch-queries) with your code.  I've added you as an author if you're comfortable with that.

**Comment by TSMMark** [comment]
@asselstine No problem! Hope it works for you, thanks for bundling it into a package. Have you had any issues with that code in the wild so far?

**Comment by asselstine** [comment]
@TSMMark Just the ordering of the functions; I had to reorder them to get it to work, and also force the casting of the queryManager to `any` so that we can pull out the private variables.  Also it didn't like the `import { type ApolloClient } from 'apollo-client'` so I changed it to `import { ApolloClient } from 'apollo-client'`.

**Comment by KeithGillette** [comment]
FWIW: I thought we were experiencing this issue (which surfaced with either the `refetchQueries: ['QueryName']` or `refetchQueries: () => ['QueryName']` syntax) but I think it's actually the case that ApolloClient is only refetching queries with active subscriptions, not all of those with matching names that still exist in the cache. In previous testing, I had not paid attention to the subscription status of the queries but realize now that only 1 was actively subscribed when `refetchQueries` was invoked. In further testing, if I do not unsubscribe from a `watchQuery` when the calling component is destroyed so that the subscription remains active, then `refetchQueries` does indeed refetch all the queries of the same name but different variables.

**Comment by wmertens** [comment]
Ok, great find! So the issue is really that non-active queries with the
same name need to be removed from cache?

**Comment by KeithGillette** [comment]
Well, I suppose if queries with no subscribers were removed from the cache, that would also force a fetch to occur, @wmertens, but then it wouldn't be much of a cache, as lots of queries will be fetched and re-read from the cache with a `query` instead of a `watchQuery` and never have any subscribers. I know cache invalidation is hard, but here must be another solution to this…

**Comment by wmertens** [comment]
Err, no - only refetchqueries should invalidate the cache entries.

**Comment by KeithGillette** [comment]
Yes, invalidating the cache entries of queries with matching names on a `refetchQueries` seems like an appropriate approach, @wmertens. Right now, it appears that when the [last subscriber to an `ObservableQuery` unsubscribes](https://github.com/apollographql/apollo-client/blob/eecaf222d2a882a8786d0c3711bb0fea079c873b/packages/apollo-client/src/core/ObservableQuery.ts#L555), the [`ObservableQuery.tearDownQuery` method](https://github.com/apollographql/apollo-client/blob/eecaf222d2a882a8786d0c3711bb0fea079c873b/packages/apollo-client/src/core/ObservableQuery.ts#L601) [removes the query](https://github.com/apollographql/apollo-client/blob/eecaf222d2a882a8786d0c3711bb0fea079c873b/packages/apollo-client/src/core/QueryManager.ts#L783) from the [`QueryManager.queryIdsByName` Map](https://github.com/apollographql/apollo-client/blob/eecaf222d2a882a8786d0c3711bb0fea079c873b/packages/apollo-client/src/core/QueryManager.ts#L95) so that when [`QueryManager.refetchQueryByName`](https://github.com/apollographql/apollo-client/blob/eecaf222d2a882a8786d0c3711bb0fea079c873b/packages/apollo-client/src/core/QueryManager.ts#L1157) is called, the given query is no longer in its Map and therefore not refetched, but also not referencable by name for invalidation…

**Comment by TSMMark** [comment]
The inconsistent behavior of refetching with apollo has resulted in a ton of extra `'network-only'` fetch-policies for important screens. It is probably one of the biggest pain points with apollo client, which is otherwise pretty seamless IMO.

I agree with @wmertens and @KeithGillette, an invalidation approach like that could work.

**Comment by Kisepro** [comment]
Same problem for me.
I will try to do my custom refetch.
Thanks @TSMMark for the code !

**Comment by ibash** [comment]
For posterity -- the other thing to check is the `queryDeduplication` option on the client.
If you set `queryDeduplication` to false and the bug goes away, then it's because you have inflight requests.

**Comment by elvisduru** [comment]
Thanks @ibash . Setting `queryDeduplication` to false worked for me!

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
