### ISSUE TITLE
Use ApolloConsumer Not handling error?

### ISSUE THREAD

**Issue by Adherentman** [apollographql/apollo-client#3666]
```javascript
<ApolloConsumer>
  {client => (
    <Form
       onSubmit={e => {
         e.preventDefault();
         validateFields(async (err, values) => {
         if (!err) {
           console.log('Received values of form: ', values);
           const { data, error } = await client.query({
           query: LOGIN_QL,
           variables: {
              username: values.username,
	      password: values.password
	   }
	});
	if (error) {
	  this.setState({ noLogin: false });
	  console.log(this.state.noLogin);
	}
	if (data) {
	  console.log(data);
	  localStorage.setItem('token', data.Login.token || '');
	  console.log(localStorage.getItem('token'));
	  // history.push('/dashboard');
	}
	  console.log(data);
	}
     });
  }}
  className="login-form"
>
{this.state.noLogin ? <div>password error</div> : null}
```

When I enter the wrong password, chrome gives the log：
I use `apollo-link-error`
```
[GraphQL error]: Message: username or password error, Location: [object Object], Path: Login
```
```javascript 
const errorlink = onError(({ graphQLErrors, networkError }) => {
  if (graphQLErrors) {
    graphQLErrors.map(({ message, locations, path }) =>
      console.log(
	`[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`
       )
  );
}
  if (networkError) {
    console.log(`[Network error]: ${networkError}`);
  }
});
```
**Intended outcome:**

I want to go to `setState` when I enter the wrong account password.

**Actual outcome:**

But when I lose the wrong way, he just passes me a log through `apollo-link-error`, and then doesn't deal with `setState`.

**Versions**

- "apollo-cache-inmemory": "^1.2.5"
- "apollo-client": "^2.3.5"
- "apollo-link-error": "^1.1.0"
- "apollo-link-http": "^1.5.4"
- "apollo-link-state": "^0.4.1"
-  "react-apollo": "^2.1.6",

**Comment by anderllr** [comment]
Hello I don't know if you solved this issue but I had the same error and I did a small adjustment of the documentation example, and I change the promise approach, like above:

onClick={() => client.query({
                                                       query: LOGIN_QL,
                                                            variables: {
                                                                username: values.username,
                                                                password: values.password
                                                            }
                                                        })
                                                            .then(({ data }) => {
                                                                let { login: { token } } = data;
                                                                localStorage.setItem('token', data.Login.token || '');
	  console.log(localStorage.getItem('token'));
                                                            })
                                                            .catch(({ graphQLErrors }) => {
                                                                //This variable returns an array of errors
                                                                console.log('Error: ', graphQLErrors[0].message );
                                                            })

                                                        }

**Comment by hwillson** [comment]
@Adherentman Any chance you can provide a small runnable reproduction that demonstrates this?

**Comment by vadistic** [comment]
I've just noticed the same thing.

@hwillson Here's repro: https://codesandbox.io/s/zr69row3o3

Steps:
- `Query` in `QueryComponent.js` loads invalid query on render and error are handled gracefully (returned)
- In `ConsumerComponent.js` you can fire a valid query to see that  this repro is configured correctly
- Then fire invalid query

Result:  Tthe sandbox crash

Expected result: The sandbox does not crash, errors are handled in the same manner as apollo's Query/Mutation components - preferably with similar error API

It looks, that there is no error handling in ApolloConsumer, and it seems for me like a bug since `client.query()` also should return errors in array `{errors: any[]}`.

Also the error API (and typescript typings) are slightly different than Query or Mutation components since it returns those `{errors: any[] | undefined}` instead of `{error: ApolloError | undefined}`, which I personally would like to see unified.

So - handling errors myself with try-catch or similar is not a challenge, but I find it annoying to handle both errors returned & errors thrown for one component.  My question is - is it a bug or design decision? 🙃

Btw: Placing ApolloConsumer directly under ApolloProvider resulted for me in sandbox crash and memory-leak. I needed to placed divs - can you try it, is it known behavior? To reproduce - try removing commented div & QueryComponent in `App.js`.

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!
