### ISSUE TITLE
Invalid peer dependencies with 2.3.7

### ISSUE THREAD

**Issue by mikl** [apollographql/apollo-client#3737]
After upgrading to apollo-client, and using graphql@0.13, Yarn now will yield the following warning:

```
apollo-client@2.3.7" has incorrect peer dependency "graphql@^0.11.0 || ^14.0.0"
```

Since GraphQL 14 is not released yet, this means that users will have to either use a pre-release version or downgrade to graphql v0.11 to avoid getting this error.

Presumably, this error message is mostly cosmetical, and can safely be ignored.

The problem was introduced in commit 46f0fe661ed3c0e8805228dc8cb7032d60050b21, presumably as a solution to #3562.

- [x] good first issue

**Comment by joealden** [comment]
Is this not just as simple as reverting the referenced commit? Should the referenced commit not just be deferred until v14 is out of rc?

**Comment by hwillson** [comment]
This change was submitted via https://github.com/apollographql/apollo-client/pull/3598. The side benefit of that PR was to cleanup the existing `graphql` peer dep range, which seemed unnecessary. Unfortunately, when I merged that PR I forgot that the ^ operator only covers any minor version IF the major version is not 0 (since a 0 major version is technically considered development by semver 2). Fix coming - thanks!

**Comment by divyenduz** [comment]
@hwillson  When will this be released?
