### ISSUE TITLE
Network Error fallback on cache

### ISSUE THREAD

**Issue by audiolion** [apollographql/apollo-client#3755]
Hey guys 👋 ,

There was a previous issue on this topic #1653 but there wasn't a resolution and it was autoclosed.

What I am wondering is how you can fallback on the cache when an apollo query fails due to a network error. Specifically I am working in the mobile realm where connections can be much more flakey and I am finding that if a user goes offline temporarily, I want to fallback on cached data. As far as I can tell the only option I have is to check `data.error` for a `networkError` and if so query my own cache and return that data to the children of my query component.

While this is possible, I am wondering if this is the best solution?

**Comment by mbaranovski** [comment]
How about doing it the opposite way? First display result from a cache and then fetch from network in the background? `cache-and-network` fetchPolicy.
https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-config-options-fetchPolicy

**Comment by justinmakaila** [comment]
I think I'm gonna take this on... my idea is to modify this method: https://github.com/apollographql/apollo-client/blob/ebf52974e710dc7710470ecbf61ea01d0d2b866f/packages/apollo-client/src/core/QueryManager.ts#L311-L442

More specifically: https://github.com/apollographql/apollo-client/blob/ebf52974e710dc7710470ecbf61ea01d0d2b866f/packages/apollo-client/src/core/QueryManager.ts#L410-L425

I'm thinking I can add a helper which checks for that error message, and if the message matches and it's `fetchPolicy` is `cache-and-network`, we just return the cache data that was already queried (here)[https://github.com/apollographql/apollo-client/blob/ebf52974e710dc7710470ecbf61ea01d0d2b866f/packages/apollo-client/src/core/QueryManager.ts#L350]

**Comment by audiolion** [comment]
relying on the text of an error mesaage seems super flakey to me, I dislike that my own patched code is relying on it

**Comment by wzup** [comment]
@mbaranovski 
> _How about doing it the opposite way? First display result from a cache and then fetch from network in the background?_

How about tell us how we should find where in our code this error is thrown? Line number? file name?
Current cryptic error message is absolutely uninformative.

![screen shot 2018-09-27 at 9 46 10 am](https://user-images.githubusercontent.com/3880497/46136550-8b988180-c250-11e8-89d1-bca3cfd8b374.png)

**Comment by mbaranovski** [comment]
I don't know why you want me to tell you this but I would put a breakpoint at `XMLHttpRequest.js:259:16` and check the request data to identify which request is in fact failing.

**Comment by sakettawde** [comment]
As far as I understand, while the fetch policy is "cache-and-network" the sequence of values for loading, data and error is as follows when different events are fired:
On first load of Query component:
loading - false
error- undefined
data - (if data is present in cache it will be a populated object) 

Subsequently, network request is made:
loading - true
error - undefined
data - (remains the same as before)

On success of retrieving data:
loading - false
error - undefined
data - new data (if there was any)

On failure of retrieving data (or user being offline in our case) there are 2 possibilities:
1. loading stays true due to the error mentioned, apollo is unable to detect when user intermittently drops out of network. In my experience there wasn't even a timeout in this case, it just stayed this way quite a few times.
2. loading becomes false, error is now populated with 'Network Error: Network Request Failed'

Now just one case we haven't handled is the first time ever you fetch data, i.e. no data in the cache, then your data response object remains empty the whole time the network error is being responded. So you have to handle that separately too.

This is what my query component looks like when I need to handle the load cache if not connected to internet or user offline scenario:

`<Query query={GET_SOMETHING} fetchPolicy="cache-and-network">
                  {({ loading, error, data }) => {
                    
                    if (!loading && error) {
                      return <Text>{error.message}</Text>
                    } else if( !loading || data) {
                      return (
                        <ActualComponentwithData data={data} />
                      )
                    } else if (loading || error) {
                      return <LoadingIndicator/>
                    } else {
                      return <Text>There is no data to show at the moment</Text>
                    }
                  }}
                </Query>`

This takes care for me of all the unexplained issues I face, and I have got used to writing things this way. Any advice of if this is alright or not would be helpful.
There isn't enough information about this anywhere online. Request that when we use the cache-and-network fetch policy in React Native, it is able to handle the user being offline in the future. Till then above is my current fix.

**Comment by campie** [comment]
Hey @audiolion, I found this issue and I think I came up with a slightly different workaround. I would really appreciate to know what you guys think about it.

I'm using Vue js, but I think my problem similar to yours: when using cache-and-network in a Vue-Apollo smart query, as soon as the component is mounted, the UI is instantly updated with the results from the cache and then a network request is dispatched. If the request fails, the query result data is an empty object and the data in the UI becomes undefined and disappears.

At first, I tried to tackle this problem by hooking at the error callback Vue-Apollo provides. But Vue-Apollo also provides a update callback which is fired twice when using cache-and-network: first with the result from cache and then with the result from the network request.

This is my workaround:

```
query: {
    users: gql'{
        users: {
            id
            name
        }
    }',
    update(data){
        if(Object.keys(data).includes('users')){
            // First time: data.users = result from cache
            // Second time: data.users = result from the network request
            return data.users
        }
        // First time: data.users was not found in the cache; this.users = initial vue data value (possibly null)
        // Second time: network request failed; this.users = data in the cache or initial vue data value
        // Show toast to inform user. Display update button.
        return this.users
    }
}
```

**Comment by ajaysinghj8** [comment]
Hi @audiolion, thanks for raising this issue. I am also looking for a similar solution. any solution so far? Please let us know. thanks

**Comment by futantan** [comment]
@audiolion We are trying to solve this issue using apollo-link.
One of my colleagues shared this on github https://github.com/hollyoops/apollo-link-network-error

**Comment by audiolion** [comment]
@futantan nice! seems like a great way to go about it

**Comment by GabrielGalatti** [comment]
Has there been any progress?

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!

**Comment by darrylyoung** [comment]
> A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!

Yeah, I'd like to upgrade to version 3 but unfortunately don't have the capacity right now. As a result, I'm _stuck_ on `2.6.10` – at least for a little while – and have this exact issue with `cache-and-network`.

What did you end up doing, @GabrielGalatti?
