### ISSUE TITLE
Support for Apollo Client Developer Tools in Apollo Boost

### ISSUE THREAD

**Issue by 27percent** [apollographql/apollo-client#3778]
I'd love to start using the Apollo client dev tools, they look pretty powerful and are one of the things that attracted me to Apollo. I've read over the docs and its unclear to me if Boost supports them. Apologies in advance if this is actually covered in the docs, I can miss the most obvious things sometimes!

The lack of 'connectToDevTools' in the configuration options seems to indicate it isn't supported yet as a config option, I get a warning in the console if I set it too, and the dev tools aren't detecting a suitable connection when on my Apollo project so I'm guessing its not turned on by default.

Is this something supported that I'm missing, in which case I owe you all a beer for wasting your time, or is it unsupported? If the latter, is it on the roadmap to be supported or is it a deliberate decision to omit?

**Comment by hwillson** [comment]
No, the `connectToDevTools` config option is not currently supported with Apollo Boost. Your best bet is to use the full blown version of Apollo Client (see [here](https://www.apollographql.com/docs/react/advanced/boost-migration.html) for help migrating from Apollo Boost to Apollo Client). At this point I would normally recommend opening a feature request for this over in http://github.com/apollographql/apollo-feature-requests/issues, but we're going to be deprecating Apollo Boost when we release Apollo Client 3. Apollo Client 3 will continue to provide `connectToDevTools` functionality. Thanks!

**Comment by hdra** [comment]
Hi @hwillson , 

I just got started working with Apollo and landed here while trying to figure out whats wrong with my dev tool setup with apollo-boost, so thanks for clarifying that its not fully supported to work with the Apollo client dev tool. 

But then I'm quite surprised to read that apollo-boost will be deprecated when Apollo Client 3 is released? I find this quite surprising as apollo-boost is pretty much in every getting started material I can find on working with Apollo, including the readme of this very project. Is there anything that I can read to see whats planned for the v3 (timeline/roadmap/etc)?

**Comment by hwillson** [comment]
@hdra The Apollo Client 3 roadmap details will be posted shortly. Apollo Boost functionality isn't going to disappear entirely, it's just that we're intending to reduce the confusion around there being effectively 2 versions of Apollo Client - the fully configurable `apollo-client` version, and the pre-configured `apollo-boost` version. Instead of promoting and publishing 2 separate approaches, we're going to move back to a single `apollo-client` package, that provides the same Apollo Boost defaults out of the box. So instead of:

```js
import ApolloClient from "apollo-boost";

const client = new ApolloClient({
  uri: "https://w5xlvm3vzz.lp.gql.zone/graphql"
});
```

you'll be able to:

```js
import { ApolloClient } from "apollo-client";

const client = new ApolloClient({
  uri: "https://w5xlvm3vzz.lp.gql.zone/graphql"
});
```

without having to specify your `cache` or `link` (unless you want to).

We'll probably also provide an `apollo-boost` wrapper package that just re-exports the updated `ApolloClient` class, so `import ApolloClient from "apollo-boost";` will still work (and existing codebases won't need to be updated). That being said, Apollo Client 3 is going to be introducing (hopefully very minor) breaking changes, so people might need to update certain parts of their code regardless. 

More details coming soon for sure - when they're ready, they'll be posted in https://github.com/apollographql/apollo-feature-requests/issues/33. Thanks!

**Comment by hdra** [comment]
I see. Thank you for the clarification. Glad to see the direction it is going, gotta admit the distinction between the client from `apollo-boost` and the one from `apollo-client` is a source of quite a bit of confusion while I was starting out.
