### ISSUE TITLE
Document client.writeData

### ISSUE THREAD

**Issue by lorensr** [apollographql/apollo-client#3783]
It doesn't appear here:

https://github.com/apollographql/apollo-client/blob/master/docs/source/api/apollo-client.md
https://www.apollographql.com/docs/react/api/apollo-client.html

**Comment by jack-sf** [comment]
The issue is that `writeData` is mentioned in the client and cache API, is available for public use, but there are little docs on how to use it.

Also there's a few quirks about it, you can't just do `client.writeData({ _object in store you want to modified_ })`, because of https://github.com/apollographql/apollo-link-state/issues/242#issuecomment-488066433 , https://github.com/apollographql/apollo-client/issues/4785#issuecomment-493061107 , https://github.com/apollographql/apollo-client/issues/4554 . 

Also there's this `id` param that probably should be constructed with `client.cache['config'].dataIdFromObject` (another quirk here: `config` is currently private property, thus it's difficult to reach `dataIdFromObject`) .

**Comment by sangdth** [comment]
I've followed the documentation and it just simply does not work. The cache is empty. It took me 3 days and I still can not make the local state works. Why does using Apollo require so much works?

**Comment by lorensr** [comment]
This function is gone as of `3.0.0`:

![image](https://user-images.githubusercontent.com/251288/97816906-e4744880-1c66-11eb-9f77-18ffea846f8c.png)

https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#apollo-client-300
