### ISSUE TITLE
Why are inline function advocated? ie. <Mutation mutation={()=>{})> 

### ISSUE THREAD

**Issue by pak11273** [apollographql/apollo-client#3991]
From the docs: https://www.apollographql.com/docs/react/essentials/mutations.html

```
        <form
            onSubmit={e => {
              e.preventDefault();
              addTodo({ variables: { type: input.value } });
              input.value = "";
            }}
          >
```

Aren't inline functions an anti-pattern and have performance problems due to creating a new function on every render?  I see this all over the docs for component prop values.  Why can't the functions be put inside the class constructor?

**Comment by JoviDeCroock** [comment]
There's no problem to put it in class constructor but doc examples are most of the time kept short. In theory it's an anti-pattern, because on every rerender the function gets reassigned.

You can use `arrows` or the `constructor` to bind efficiently. The constructor is most efficient if the Component is commonly used. Arrows are good to avoid unneeded constructors when the component isn't used a lot.

**Comment by pak11273** [comment]
I see a lot of inline functions looking used in the apollographql code like react apollo so I'm guessing it really isn't that big of a performance hit.  Even if there are no perf issues it leaves the render function a little bloated.  Thanks for the reply.
