### ISSUE TITLE
if a Query is stopped using AbortController, it cannot be executed again.

### ISSUE THREAD

**Issue by gabor** [apollographql/apollo-client#4150]
**Intended outcome:**

i use react with apollo.
i want to cancel a running graphql query using the `AbortController` approach to stop the `fetch` request. later i want to run the query again.

**Actual outcome:**

i can cancel the query using an `AbortController`.but, if i execute the query again, no http-request is sent. maybe some cleanup did not happen and apollo still considers the query running? no idea. i can start other queries. so for example, if this graphql query has a parameter, i can start the query with param1, cancel it, then start it with param2 and it works. but if i start it again with param1, no http request is sent.

**How to reproduce the issue:**

- create a react-component
- wrap it in `withApollo`
- somewhere in the component do a handler to a button-click or something that you can do multiple times:
```
handleButtonClicked() {
    const abortController = new AbortController();
    const { signal } = abortController;

    this.props.client
      .query({
        query: QUERY,
        variables: {
          .
          .
          .
        },
        context: {
          fetchOptions: {
            signal,
          },
        },
        fetchPolicy: 'network-only',
      })
      .then(() => {console.log('done');});

    setTimeout(() => {
        abortController.abort();
    }, 3000);
}
```
- the `QUERY` should go to something slow (like, response in 20seconds)
- open the network-tab in the browser (i tried in google-chrome)
- click the button, and verify that the query is first `pending` and then later `canceled`
- click the button again, and there will be no new line in the network-tab

- 
**Versions**

```
  System:
    OS: macOS 10.14.1
  Binaries:
    Node: 8.12.0 - /usr/local/opt/node@8/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
  Browsers:
    Chrome: 70.0.3538.102
    Firefox: 63.0.1
    Safari: 12.0.1
```

**Comment by Phaster911** [comment]
any updates on this?

**Comment by charan432** [comment]
I am also facing the same issue.. Does anyone have an update on this??

**Comment by AW-TaylorBett** [comment]
You need to recreate a new AbortController for the second instance of the request. A single AbortController is associated with a single request via its AbortSignal. Hence your AbortController is still associated with the original request instance. 

See https://developer.mozilla.org/en-US/docs/Web/API/AbortController

**Comment by gabor** [comment]
@AW-TaylorBett thank you for the info. unfortunately the situation is somewhat different. the problem-scenario is this:

1. start request
2. abort request
3. start request

and the request in [3] does not happen.

**Comment by Peterabsolon** [comment]
Same issue here. The third request never fires, even despite executing with a new, unaborted AbortController

**Comment by helfer** [comment]
@gabor where did you read about the AbortController approach? I think it's the wrong way to do this, because reaching into the link/fetch and cancelling the request breaks all the abstractions that ApolloClient and apollo link set up for you. If you ask ApolloClient to run a query, then you should tell ApolloClient if you no longer wish to run that query, so the stack can be unwound in an orderly fashion. If you called `client.query` to run it, you should use that same interface to cancel the query. Unfortunately that's not possible at the moment, but it should be possible by making the promise cancellable.

Under the hood `client.query` calls `watchQuery`, which supports unsubscribing. If I'm not mistaken, unsubscribing from a watch query will propagate through the link stack and abort the `fetch` request in browsers that support it, so this is the proper way to go.

If you want to make `query` cancellable, you could consider making a PR to apollo client that adds a `cancel` function to the promise returned.

As a workaround for the time being, here are two other options:
1. Use `watchQuery` and unsubscribe from it when you want to cancel the request. You can turn an observable into a promise pretty easily. I'm not 100% sure if this will work, but it should work.
2. If #1 doesn't work or if you don't really need the query to go through ApolloClient's cache, you can use `client.link` directly to make the request by calling `execute(link, operation)`, as described here: https://www.apollographql.com/docs/link/#standalone If you unsubscribe from the observable there (by calling the function returned from `observable.subscribe`), the link stack should be properly unwound, and your fetch request will get cancelled if it's still pending.


PS: The reason the second request hangs if the first one was aborted is precisely because assumptions were violated by breaking the abstraction. As you can see [here](https://github.com/apollographql/apollo-link/blob/a7a6cf0697177afdf537e4dfa568ebc271ab09e2/packages/apollo-link-http/src/httpLink.ts#L148), the authors originally assumed that the only way a request would get aborted is via unsubscribing. If you're aborting it directly, that assumption is obviously violated, and the error doesn't propagate through the stack. This leaves other links and subscribers in the stack hanging, because they received neither an error, nor were they unsubscribed from. In your specific case, the dedup link is left hanging, so when a second identical request comes in, it ends up being deduplicated and your second requests waits for the first one to complete, not knowing that it was aborted. The simplest workaround in that case is to just passing `queryDeduplication: false` when you initially instantiate ApolloClient. Keep in mind however that this might now result in multiple identical queries being in flight at the same time if your client makes the same query more than once in a short interval.

PPS: Looking at your code, it seems what you really want is just a query timeout. If so, then the right solution would be to use a timeout link (eg. apollo-link-timeout. Although that particular implementation issues and also breaks assumptions, it should fix your problem for now).

**Comment by gabor** [comment]
@helfer thanks for the response. there is a lot of info in your comment, so i will try to react to it's parts:

- generally, what i want to achieve is to cancel the query. it does not really matter for me how it is achieved as long as it works
- it is not a timeout-based situation. (if we want to go with an example-situation, imagine i start a long-running search-query, but in the middle i reconsider and i want to search for something else).
- the reason i went with the `AbortController` approach is because:
  - i could not find any documentation about how to cancel a running apollo-query.
  - `fetch` requests are cancelled using an `AbortController`
  - and, because apollo allows passing extra options to the fetch call using `fetchOptions` (https://www.apollographql.com/docs/link/links/http)
- i am totally ok with doing it a different way, but please note apollo should probably reject overrides to the abortController in fetch, or at least document that it should not be overridden, because currently it is not obvious that this breaks any abstractions.
- the `watchQuery` approach should be fine for my use-case, i will try it if it works,  and get back to you with the result

**Comment by gabor** [comment]
@helfer i tried it out, and the `watchQuery` + `unsubscribe` approach does work, thanks a lot!
would be nice to have this mentioned somewhere in the documentation.

**Comment by francoisromain** [comment]
@gabor could you show a code example of how to implement this please?

**Comment by gabor** [comment]
sorry @francoisromain , i do not have access to that code anymore. it went roughly like this:
- you have the code that does `client.query(params).then(...)`
- you switch to `const thing = client.watchQuery(params)`
- somewhere on `thing` there is a way to subscribe a callback-function to it. you will get the query-result that way
-  if, during the execution of the query, you unsubscribe the callback-function from the `thing`, the ajax-request will stop.

unfortunately i do not remember the exact api-calls, but there is some way to go from that `thing` to something that has the api like zen-observable ( https://github.com/zenparsing/zen-observable ). perhaps, if you use typescript the auto-complete can navigate you to it. or maybe someone else can link to a code-example.

**Comment by dylanwulf** [comment]
@helfer Do you know of any way to cancel a `fetchMore` request? The unsubscribe method doesn't seem to work on requests initiated through `fetchMore`

**Comment by leebenson** [comment]
I spent some time this weekend debugging this problem, and I found it was necessary to set _both_ `queryDeduplication: false` on the ApolloClient _and_ use `.watchQuery` instead of `.query` + an explicit `AbortController.signal`.

I wound up with something like...

**Creating the Apollo client**:

```ts
const client = new ApolloClient({
  // Regular options here, such as...
  cache,
  links: ApolloLink.from([links,go,here]),

  // This is what enables cancelation
  queryDeduplication: false
})
```

**Then to issue/cancel a query...**

```ts
// Issue the query
const query = client.watchQuery<SomeQuery, SomeQueryVariables>({
  // Usual stuff, no need for a custom `AbortController.signal`
  query: SomeQueryDocument,
  fetchPolicy: "network-only",
  variables,
});

// Subscribe to it, and do something with the data
const observable = query.subscribe(({ data }) => {
  // do something with `data`
  // ...
})

// Then somewhere you want to cancel it...
observable.unsubscribe(); // <-- will implicitly cancel the fetch
```

That should successfully cancel a query, and enable re-sending, e.g. in this case where I canceled a query twice, and let it succeed the third time:

<img width="580" alt="Screenshot 2019-06-08 at 15 17 48" src="https://user-images.githubusercontent.com/719722/59148413-aedf1780-8a00-11e9-8c35-74799dadc6ac.png">

**Comment by hwillson** [comment]
https://github.com/apollographql/apollo-client/issues/4150#issuecomment-500127694 should help answer this. Thanks!

**Comment by javier-garcia-meteologica** [comment]
I used the solution proposed by @leebenson and worked fine in apollo client 2. But it is not working in apollo client 3.

I am using `queryDeduplication: false`, `fetchPolicy: 'network-only'` and I've checked that `unsubscribe` tears down the query, but somehow the query is not aborted.

**Comment by javier-garcia-meteologica** [comment]
I found in #6985 why it doesn't work in apollo client 3.

**Comment by wordwords** [comment]
I had the same problem. And I solved it.
I am wondering if my method is correct.
* I don't speak English, so I use Google Translate.

![스크린샷 2020-10-16 오후 3 29 10](https://user-images.githubusercontent.com/33927558/96224046-e503b280-0fc9-11eb-8578-506c615dd9d9.png)


[Cause of the problem]
- abortController.abort() only worked the first time.
- because abortController only looks at the 'first called API'.
- So, every time I call the API, I allocate abortController again.


[Resolution process]
A. Whenever a new event occurs, cancel the previous abortController.
B. Reassign a new abortController.


[logic1]
```
   const [_controller, set_controller] = useState(new AbortController());   // state
```


[logic2]
```
      const { GET_MY_NAME } = query;
      const [getMyData] = useLazyQuery(GET_MY_NAME, {
        fetchPolicy: "no-cache",
        variables: { myword: myword },
        context: {
          fetchOptions: {
            signal: _controller.signal
          }
        },
         
        onCompleted: (data) => {
         
        }
     });
```

[logic3]
```
  const onChange = (e) => {
          _controller.abort()

      setTimeout(async (_) => {
          await set_controller(new AbortController());   // state update
          await getMyData();
      }, 500);
  }

```

[logic4]
```
          <input
            onChange={onChange}
          />
```



If I use this method, it works normally. But I am not sure if this is the correct way.

**Comment by Covmon** [comment]
Anyone come up with a solution in Apollo 3?

**Comment by Morphexe** [comment]
Also in dire need of being able to cancel a long running query based on user input using Apollo 3.

**Comment by brendanmoore** [comment]
I believe that part of the issue will be fixed in `3.3+`. If you use your own `watchQuery` and manually unsubscribe. I am using this approach: https://gist.github.com/brendanmoore/8cd239c5b35983936581b61922b09b2e and it works flawlessly in  `3.3.0-beta.16` as Apollo does use its own `AbortController` internally when you unsubscribe - (when using `HttpLink`).

**Comment by donegjookim** [comment]
I was able to work around this issue by integrating `AbortController` with `fetchMore` method. 

> This function is a member of the ObservableQuery object returned by client.watchQuery, and it's also included in the object returned by the useQuery hook ([fetchMore Doc Link](https://www.apollographql.com/docs/react/pagination/core-api/#the-fetchmore-function))

**Comment by robert-king** [comment]
problematic scenarios:
if user turns off their wifi and then turns their wifi on, or if you're testing offline mode using chrome devtools network throttling, and then when you come back online and refresh buttons are broken.

**Comment by LiamKarlMitchell** [comment]
createHttpLink has an unhandled TypeError for me when in offline mode and retry-link doesn't get the event.

**Comment by claycoleman** [comment]
> I spent some time this weekend debugging this problem, and I found it was necessary to set _both_ `queryDeduplication: false` on the ApolloClient _and_ use `.watchQuery` instead of `.query` + an explicit `AbortController.signal`.
> 
> I wound up with something like...
> 
> **Creating the Apollo client**:
> 
> ```ts
> const client = new ApolloClient({
>   // Regular options here, such as...
>   cache,
>   links: ApolloLink.from([links,go,here]),
> 
>   // This is what enables cancelation
>   queryDeduplication: false
> })
> ```
> 
> **Then to issue/cancel a query...**
> 
> ```ts
> // Issue the query
> const query = client.watchQuery<SomeQuery, SomeQueryVariables>({
>   // Usual stuff, no need for a custom `AbortController.signal`
>   query: SomeQueryDocument,
>   fetchPolicy: "network-only",
>   variables,
> });
> 
> // Subscribe to it, and do something with the data
> const observable = query.subscribe(({ data }) => {
>   // do something with `data`
>   // ...
> })
> 
> // Then somewhere you want to cancel it...
> observable.unsubscribe(); // <-- will implicitly cancel the fetch
> ```
> 
> That should successfully cancel a query, and enable re-sending, e.g. in this case where I canceled a query twice, and let it succeed the third time:
> 
> <img alt="Screenshot 2019-06-08 at 15 17 48" width="580" src="https://user-images.githubusercontent.com/719722/59148413-aedf1780-8a00-11e9-8c35-74799dadc6ac.png">

@leebenson 's answer still works for me using ApolloClient `3.4.11`. For my use case, queries could still be cancelled without using `queryDeduplication: false`, which I wanted to avoid.
