### ISSUE TITLE
[typescript] `ApolloClient.mutate()` type is not consistent and not usable

### ISSUE THREAD

**Issue by samuela** [apollographql/apollo-client#4170]
The type of `ApolloClient.mutate()` is not consistent with other methods like `query()` and offers no way to deal with mutations in a type safe way. Here's the type of `mutate<T, TVariables>()`:
```typescript
export default class ApolloClient<TCacheShape> implements DataProxy {
    mutate<T, TVariables = OperationVariables>(options: MutationOptions<T, TVariables>): Promise<FetchResult<T>>;
}
```
Here's `FetchResult<T>`:
```typescript
export declare type FetchResult<C = Record<string, any>, E = Record<string, any>> = ExecutionResult & {
    extensions?: E;
    context?: C;
};
```
Note that the `T` in `mutate<T>()` corresponds to `C` in `FetchResult<C = Record<string, any>, E = Record<string, any>>`. In other words `mutate<T>(...).context : T` which doesn't match `ApolloClient.query()`. 

Moreover there's no way to type the resulting data that comes out of the mutation: Because no type parameters are passed to `ExecutionResult` there's no way to type `mutate(...).data`!

And for reference, here's `ExecutionResult` from `@types/graphql`:
```typescript
export interface ExecutionResult<TData = ExecutionResultDataDefault> {
    errors?: ReadonlyArray<GraphQLError>;
    data?: TData;
}
```

See also https://github.com/apollographql/apollo-client/issues/4153.

**Intended outcome:**
A consistent, clean way to type graphql queries and mutations.

**Actual outcome:**
Unhelpful and inconsistent types on `ApolloClient.mutate()` relative to the other methods, `query()` etc.

**How to reproduce the issue:**
Look at the code.

**Versions**
"apollo-boost": "0.1.22"

**Comment by ekron** [comment]
The problem is the `ApolloClient.mutate` function can return `Promise<any>` even if the correct types are provided as generics.

Example:

```typescript
interface SampleMutationResult {
  id: string;
}

interface SampleMutationVariables {
  someVariable: string;
}

const result = await client.mutate<SampleMutationResult, SampleMutationVariables>({
  mutation: TaskByIdDocument,
  variables: { someVariable: "test" }
});

// Expect: result to be FetchResult<SampleMutationResult, Record<string, any>>

// Actual: result is type any.
```

**The fix is to add the typings for graphql module:**

```bash
yarn add @types/graphql
```

**What's the problem?**

I'll take a quick guess. The ApolloClient type returns a `FetchResult` for mutate:

```typescript
mutate<T = any, TVariables = OperationVariables>(options: MutationOptions<T, TVariables>): Promise<FetchResult<T>>;
```

FetchResult relies on a typing being present for `ExecutionResult` from the `graphql` package:
```typescript
export declare type FetchResult<TData = {
    [key: string]: any;
}, C = Record<string, any>, E = Record<string, any>> = ExecutionResult<TData> & {
    extensions?: E;
    context?: C;
};
```

**Possibly if the @types/graphql typings are not available then you'll get the unexpected `Promise<any>` returned from `mutate`?**

**Comment by Harmonickey** [comment]
Excellent, thanks for the solution @ekron

**Comment by sseppola** [comment]
Good reasoning @ekron, however my type for `FetchResult` from the apollo-link@1.2.11 package is different than yours:
```ts
export declare type FetchResult<C = Record<string, any>, E = Record<string, any>> = ExecutionResult & {
    extensions?: E;
    context?: C;
};
```
Notice the missing type argument missing from `ExecutionResult` as well as TData missing entirely from the FetchResult type arguments.

**Comment by ekron** [comment]
@sseppola -- does your project contain the latest @types/graphql package?

If not, trying updating.

Just a quick guess: you might have an outdated version of `ExecutionResult`?

See this commit and related code:

- https://github.com/DefinitelyTyped/DefinitelyTyped/commit/deb7d8beaff5d43da749c5bc0f2020cdcaaabb6b
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/graphql/execution/execute.d.ts#L43

**Comment by sseppola** [comment]
Was able to solve the problem while responding to your comment @ekron, the following is my process in case someone else has the same problem.

We're using @types/graphql version: 14.2.0, which has the correct ExecutionResult type:
```ts
export interface ExecutionResult<TData = ExecutionResultDataDefault> {
    errors?: ReadonlyArray<GraphQLError>;
    data?: TData;
}
```
like I said above, the problem is that `FetchResult` does not pass the `TData` generic to `ExecutionResult`. When I dig a little deeper in my dependencies it seems like apollo-client is using its apollo-link@v1.2.2 instead of v1.2.11 which my package.json specifies.

```bash
$ yarn why apollo-link
yarn why v1.10.1
[1/4] 🤔  Why do we have the module "apollo-link"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "apollo-link@1.2.11"
info Has been hoisted to "apollo-link"
info Reasons this module exists
   - Specified in "dependencies"
   - Hoisted from "apollo-link-error#apollo-link"
   - Hoisted from "apollo-link-batch-http#apollo-link"
   - Hoisted from "apollo-link-http#apollo-link"
   - Hoisted from "apollo-link-batch-http#apollo-link-batch#apollo-link"
   - Hoisted from "apollo-link-http#apollo-link-http-common#apollo-link"
   - Hoisted from "apollo#apollo-language-server#apollo-link"
   - Hoisted from "apollo#apollo-language-server#apollo-link-ws#apollo-link"
   - Hoisted from "apollo#apollo-language-server#apollo-link-context#apollo-link"
info Disk size without dependencies: "320MB"
info Disk size with unique dependencies: "996MB"
info Disk size with transitive dependencies: "1.21GB"
info Number of shared dependencies: 6
=> Found "apollo-client#apollo-link@1.2.2"
info This module exists because "apollo-client" depends on it.
info Disk size without dependencies: "576MB"
info Disk size with unique dependencies: "1.51GB"
info Disk size with transitive dependencies: "1.86GB"
info Number of shared dependencies: 7
=> Found "apollo-link-dedup#apollo-link@1.2.2"
info This module exists because "apollo-client#apollo-link-dedup" depends on it.
info Disk size without dependencies: "232MB"
info Disk size with unique dependencies: "1.18GB"
info Disk size with transitive dependencies: "1.52GB"
info Number of shared dependencies: 7
✨  Done in 1.60s.
```

I'm using `apollo-client@2.5.1` (latest), and it depends on `apollo-link: "^1.0.0", so it has to be something in the dependency resolution that's gone bad.

Inspecting `yarn.lock` I find this entry:
![Screen Shot 2019-04-25 at 14 07 10](https://user-images.githubusercontent.com/4065840/56734642-b655a480-6763-11e9-983b-709811c70d2b.png)
which forces `apollo-link@^1.0.0` and `apollo-link@^1.2.2` to be resolved to 1.2.2 instead of 1.2.11 (latest).

Furthermore, upgrading indirect dependencies like this is an ongoing issue in yarn according to this issue: https://github.com/yarnpkg/yarn/issues/4986. So following the advice in the issue I deleted the related apollo-link entry pictured above and re-ran `yarn`, which produced the following yarn.lock diff:
![Screen Shot 2019-04-25 at 14 20 09](https://user-images.githubusercontent.com/4065840/56735433-beaedf00-6765-11e9-92cf-fedbfbc577ff.png)

After that I had no `@types/graphql` dependency any more, and had to add it myself. Finally it all worked as expected.

**Comment by MonsieurMan** [comment]
Just got this error and solved it adding @types/graphql, shouldn't this issue be closed ? 🙂

**Comment by Fxlr8** [comment]
@MonsieurMan, this is what I get when try to install `@types/graphql`

> deprecated @types/graphql@14.5.0: This is a stub types definition. graphql provides its own type definitions, so you do not need this installed.

Are we doomed?

By the way, I am using `"apollo-client": "^2.6.8"` and `"apollo-link": "^1.2.13"` and I still get the same annoying error.

**Comment by MonsieurMan** [comment]
@Fxlr8, then you're probably missing the whole `graphql` package ? It is stated it now provides its own typing, so you should have them otherwise.

**Comment by Fxlr8** [comment]
nope, I have `"graphql": "^15.0.0"` installed.

Here is how the `ExecutionResult`'s types look like right now:
https://github.com/graphql/graphql-js/blob/278bde0a5cd71008452b555065f19dcd1160270a/src/execution/execute.d.ts#L40-L49

Unfortunately, the error is still here

**Comment by MonsieurMan** [comment]
https://github.com/apollographql/apollo-client/blob/3d7bc8e8a7c03fcd4fa2a8dcc94df80205af388e/package.json#L58  
You shouldn't use the 14.x that's all.

**Comment by Fxlr8** [comment]
with `"graphql": "^14.5.4"` the error is gone, but `ApolloClient.mutate()` still returns `Promise<any>`

**Comment by hwillson** [comment]
This should no longer be an issue in `@apollo/client@latest` - let us know otherwise, thanks!
