### ISSUE TITLE
Naming the default export `ApolloClient` for both `apollo-boost` and `apollo-client` is confusing

### ISSUE THREAD

**Issue by vjpr** [apollographql/apollo-client#4374]
In the docs this is done often, but the apis are completely different.

You should not refer to ApolloBoost and ApolloClient.

```
import ApolloClient from 'apollo-client'
import ApolloClient from 'apollo-boost' // bad
```

**Comment by smolinari** [comment]
@vjpr - do you mean like here in the "essentials" section of the docs? 

https://github.com/apollographql/apollo-client/blob/master/docs/source/essentials/get-started.md

There they use Apollo Boost, because is the simplified, "essential" and easier to use then using the singular packages (and getting it right). 

If you go into the _advanced section_ of the docs, [like for caching](https://github.com/apollographql/apollo-client/blob/master/docs/source/advanced/network-layer.md), the "apollo-client" package is referenced, which you can still use, if you want to do more _advanced_ things.  

I'll also agree: The concepts between Apollo Boost and using the singular packages for more advanced setup could be much better explained here: https://github.com/apollographql/apollo-client/blob/master/docs/source/basics/setup.md 

I'll add a PR. 

Scott

**Comment by vjpr** [comment]
In the API reference here https://github.com/apollographql/apollo-client/blob/master/docs/source/api/apollo-client.md, it shows what options you can pass to `ApolloClient`.

But then you use `import ApolloClient from "apollo-boost";` in the essentials page.

But `apollo-boost` has less options and shows a little error message (that is easy to miss) that you cannot use `link`, etc, etc.

So using `ApolloClient` to refer to two different things is really confusing.

**Comment by JoviDeCroock** [comment]
I don't really see why `apollo-boost-migration` is a bad name since migration means moving away from something. The only other way is to make a really long title in your ToC which isn't really common since a ToC needs to be scannable.

**Comment by vjpr** [comment]
Good point - I think it's fine then.

**Comment by danilobuerger** [comment]
Closing as this seems resolved.
