### ISSUE TITLE
Initializing local state with an array stores incorrect value in the cache

### ISSUE THREAD

**Issue by justinanastos** [apollographql/apollo-client#4498]
When writing data to the cache directly via `cache.writeData`, empty arrays are stored as follows:

```
cartItems: {"type":"json","json":[]}
```

This can be seen with [Apollo's Full Stack Tutorial in Section 8: Managing Local State](https://www.apollographql.com/docs/tutorial/local-state.html#store-initialization).

# Cause

This appears to be caused by `apollo-client-inmemory`'s behavior in [writeFieldToStore](https://github.com/apollographql/apollo-client/blob/dea8b34f722175871235bb424ac4d37cb28ec018/packages/apollo-cache-inmemory/src/writeToStore.ts#L273-L282):

https://github.com/apollographql/apollo-client/blob/dea8b34f722175871235bb424ac4d37cb28ec018/packages/apollo-cache-inmemory/src/writeToStore.ts#L273-L282

For local state, there will be no `selectionSet` and `typeof [] === "object"`. Perhaps the `Array.isArray()` check should preceed `!field.selectionSet || value === null`?

# Reproduction

- Check out Apollo's full stack tutorial from [GitHub](https://github.com/apollographql/fullstack-tutorial)
- `cd` to `final/server`
    - Install dependencies via `npm ci` and run the project `npm start`
- In a second terminal, `cd` to `final/client`
    - Install dependencies via `npm ci` and run the project `npm start`
- Load the browser, check the cache with Apollo Client DevTools 

    ![image](https://user-images.githubusercontent.com/5224118/53367712-d9efa080-3914-11e9-959f-49a813b9cf3f.png)

# Versions

This can be reproduced both with the latest stable releases and with the latest v2.5 release candidate (rc2, February 25th)

**Comment by veddermatic** [comment]
This behavior is especially troubling if the empty array is a child of an object in a collection. If the first child array is empty, objects in other children are stored a `json`, not as objects. This causes queries that reference those children to error.

Example: 

If I have this schema:

```
type Parent {
  name: String!
  kids: [Child]!
}
type Child {
  name: String!
}
```

And I fetch all the parents, and store them in a `stuff @client` cache, it will look like this if the first parent returned has no children:

```
ROOT_QUERY
  stuff: [Parent]
    0: Parent: abc-123
      name: "A name"
      kids: {"type":"json","json":[]}
    1: Parent: def-456
      name: "Uh Oh:
      kids: {"type":"json","json":[{"id":"xyz-789","name":"A child","__typename":"Child"}]}
```

Any query that includes:

```
stuff @client {
  name
  kids {
    id
   name
 }
}
```

will error with `Error: Network error: Can't find field name on object undefined.`  This is causing some serious issues in our app.

**Comment by amie-wilt** [comment]
@veddermatic Did you figure this out? I just came across this and am a little confused as to why this issue is still open and why there aren't more complaints.. makes me wonder if I have some weird configuration or something.

**Comment by veddermatic** [comment]
@amie-wilt : Thanks to a well-timed trip, I haven't had a chance to try any solutions / workarounds yet, but I have a couple ideas. Will dig into it sometime in the coming week. Should I figure anything out, I'll make sure to post here.

**Comment by Adam-Beno** [comment]
I've run into the same issue on my project with react-native. My case is very similar to what @veddermatic described above. 

### The issue
If I take the same schema above which is somewhat the same what i have.
```
type Parent {
  id: String!
  name: String!
  kids: [Child]!
}
type Child {
  id: String!
  name: String!
}
```

And proceed to add parents with empty children it actually still works. So I end up having this structure.
```
{
  parents: [
    {
      id: 'someId',
      name: 'somename',
      kids: [],
    },
  ],
}
```
Now when I add children to this parent it also still works. I do this via `cache.writeFragment` and extending the existing array which leaves me with following structure:
```
{
  parents: [
    {
      id: 'someParentId',
      name: 'someParentName',
      kids: [
        {
          id: 'someChildId',
          name: 'someChildName',
        },
      ],
    },
  ],
}
```

If I now try to add another `Parent` object with empty children it will fail.
Expected structure:
```
{
  parents: [
    {
      id: 'someParentId',
      name: 'someParentName',
      kids: [
        {
          id: 'someChildId',
          name: 'someChildName',
        },
      ],
    },
    {
      id: 'someParentId2',
      name: 'someParentName2',
      kids: [],
    },
  ],
}
```
What i get instead
`null`

What is interesting tho, is if I create two parent objects first like this:
```
{
  parents: [
    {
      id: 'someParentId',
      name: 'someParentName',
      kids: [],
    },
    {
      id: 'someParentId2',
      name: 'someParentName2',
      kids: [],
    },
  ],
}
```
And then start adding children to each of them, it actually works. However, this breaks again when I try to add another parent object after adding children.

The error message i get is always the same:
**`Error: Network error: Can't find field id on object undefined.`**

Also an interesting fact, since I'm running `apollo-cache-persist` I can actually see the data there added correctly, just for some reason it's being returned as `null`.

### Workarounds?
- I tried digging around in the `apollo-cache-inmemory` module itself and basically changing what @justinanastos suggested but unfortunately no matter where i put the `Array.isArray()` check it would break the app even more.
- Initiating the `Parent` array with dummy data doesn't work either

What I have not tried yet
- Perhaps initiating `Parent` with `null` value on `kids` attribute would work instead of `[]`?
- The last resort would probably be separating the `Child` from `Parent` and turning it into following structure:
```
{
  parents: [
    {
      id: 'someParentId',
      name: 'someParentName',
    },
  ],
  kids: [
    {
      id: 'someChildId',
      name: 'someChildName',
      parentId: 'someParentId',
    },
  ],
}
```
But obviously this is far from ideal.

### Stack
```
"react-native": "0.59.10",
"react-apollo": "2.5.8",
"apollo-client": "2.6.3",
"apollo-cache-inmemory": "1.6.2",
"apollo-cache-persist": "0.1.1",
"apollo-link": "1.2.12",
"apollo-link-error": "1.1.11",
"apollo-link-http": "1.5.15",
"apollo-link-state": "0.4.2",
```

**Comment by Adam-Beno** [comment]
After some digging I found out how to solve half of the problem. Since I'm using `writeQuery` to initialize the `Parent` object I had to pass along a `gql` which is where the problem was for the children array.

I was using this query to write in cache
```
gql`
  query InitParent{
    parents @client {
      id
      ...
      children
    }
  }
`;
```
to store following data:
```
{
  parents: [
    {
      id: 'someParentId',
      ...,
      kids: [],
    },
  ],
}
```
This as we already know from the posts above results in an error because the array is stored in cache like this:
```
kids: {"type":"json","json":[]}
```

**However if you modify the query to include all the fields on the children object like this:**
```
gql`
  query InitParent{
    parents @client {
      id
      ...
      children {
        id
        ...
        name
      }
    }
  }
`;
```

and use it with `.writeQuery` it will actually create an empty array instead of json:
```
kids: []
```

**This is because apollo needs a `selectionSet` to be able to save it as an `array` rather than `json`.**

But as I mentioned, this covers only half of the problem, because simple arrays such as:
```
kidNames: ['john', 'eva']
```
will still get stored as json:
```
kidNames: {
  type: json
  json: ['john', 'eva']
}
```

**Comment by tresdev** [comment]
This is very troubling and time consuming problem you likely have to deal with when you use local state. 
I hope I could set (actual) typeDefs so I can let the apollo client understand the local schema.
It seems it needs some working on dealing with null values and empty arrays.

**Comment by hwillson** [comment]
👋 @justinanastos this should no longer be an issue in `@apollo/client@latest` - let us know otherwise, thanks!
