### ISSUE TITLE
local queries not mockable with addMockFunctionsToSchema

### ISSUE THREAD

**Issue by jrr** [apollographql/apollo-client#4513]
(follow up from https://github.com/apollographql/apollo-client/issues/4325#issuecomment-467873190 )

**Intended outcome:**
Local queries can be mocked with `addMockFunctionsToSchema` and `SchemaLink`.

**Actual outcome:**
The mocks do not take effect.

**How to reproduce the issue:**

I'll try to build a repro soon, but for now here are a couple select snippets. I'm constructing an apollo client like this:

```ts
  const serverSchema = makeExecutableSchema({ typeDefs: rawSchema });
  addMockFunctionsToSchema({
    schema: serverSchema,
    mocks: mocks as any,
  });

  const clientSchema = makeExecutableSchema({
    typeDefs: require("client/graphql/schema.graphql"),
  });
  addMockFunctionsToSchema({
    schema: clientSchema,
    mocks: mocks as any,
  });

  const exSchema = mergeSchemas({
    schemas: [serverSchema, clientSchema],
  });

  const client = new ApolloClient({
    cache: new InMemoryCache(),
    link: new SchemaLink({
      schema: exSchema,
    }),
    resolvers: ClientSideResolvers,
    defaultOptions: {
      watchQuery: {
        fetchPolicy: "cache-and-network",
      },
    },
  });
```

My mocks look like this:

```
  mocks: {
    Query: () => ({
      localThing: () => "fooBar", // <- this stopped working with the move from apollo-link-state to apollo-client 2.5
      remoteThing: () => "qwerty"
    }),
  },
```

**Versions**
```
  System:
    OS: macOS 10.14.3
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: 1.13.0 - ~/repos/edustaff/placement/node_modules/.bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
  Browsers:
    Chrome: 72.0.3626.119
    Firefox: 65.0.1
    Safari: 12.0.3
  npmPackages:
    apollo: ^2.5.3 => 2.5.3
    apollo-cache-inmemory: ^1.5.0 => 1.5.0
    apollo-client: ^2.5.0 => 2.5.0
    apollo-link-batch-http: ^1.2.8 => 1.2.8
    apollo-link-schema: ^1.1.6 => 1.1.6
    graphql-codegen-typescript-react-apollo-template: ^0.17.0 => 0.17.0
    react-apollo: ^2.5.0 => 2.5.0
    react-apollo-hooks: ^0.4.1 => 0.4.1
```

**Comment by hwillson** [comment]
Thanks for reporting this @jrr. When using Apollo Client 2.5's newer local state management features, `@client` based fields are no longer sent through the Link chain. This is by design as we want to avoid leaking local fields through Link's, since Link's were originally designed to be network oriented. We're working on new best practices for testing local resolvers (and will be publishing more info about this soon), but in the meantime there are a few approaches you can take.

**1) Keep using `apollo-link-state`**

You can continue to use `apollo-link-state` with Apollo Client 2.5, as long as you don't pass `resolvers` into the `ApolloClient` constructor. As soon as `resolvers` are configured in the constructor, AC 2.5's integrated local state features kick in and will strip all `@client` fields before they hit the Link chain.

**2) Mock your local resolvers separately**

Instead of mocking local and remote resolvers together in a `SchemaLink`, you can split things up so your local resolvers are mocked separately. Here's a quick example following the `addMockFunctionsToSchema` approach for the server schema, with separate `@client` field mocking:

```js
import { ApolloClient } from 'apollo-client';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { makeExecutableSchema, addMockFunctionsToSchema } from 'graphql-tools';
import { SchemaLink } from 'apollo-link-schema';
import gql from 'graphql-tag';

const typeDefs = `
  type Car {
    make: String!
    model: String!
    year: Int!
  }

  type Query {
    cars: [Car]
  }
`;

const schema = makeExecutableSchema({ typeDefs });
addMockFunctionsToSchema({ schema });

const mockResolvers = {
  Car: {
    inCart() {
      return false;
    },
  },
};

const client = new ApolloClient({
  cache: new InMemoryCache(),
  link: new SchemaLink({ schema }),
  resolvers: mockResolvers,
});

const query = gql`
  query {
    cars {
      make
      model
      year
      inCart @client
    }
  }
`;

client.query({ query }).then((result) => {
  console.log(result);
});
```

Using the above, Apollo Client takes care of combining the results from the mocked remote and local resolvers.

We'll definitely have more info published about all of this soon. Thanks!
