### ISSUE TITLE
Error being returned in result.error and not result.errors

### ISSUE THREAD

**Issue by sreejithr** [apollographql/apollo-client#4621]
According to the [documentation](https://www.apollographql.com/docs/react/api/apollo-client.html#ApolloQueryResult) for `query()` method in ApolloClient, it should return a `Promise<ApolloQueryResult>`. In `ApolloQueryResult`, I see a key `errors`. Yet I don't find this key (rather I find the keyy `error`) in my result when my query is failing.

Is this expected?

**Intended outcome:**
I expect `errors` to be defined here:

```
 <Query
  query={GetTasksQuery}
  variables={getTasksVariables}
>
  {({ data, errors, error }) => {
      console.log(`The key errors is present: ${ !!errors }`);
      console.log(`The key error is present: ${ !!error }`);
```

**Actual outcome:**
I can see that `error` is present and not `errors`. As I have Typescript in my project, I can't extract out `error` since the Typescript type for query result has `errors` in it.

**How to reproduce**
In a working Apollo setup, have a `<Query>` similar to above. Now go to `Network` tab in your Chrome devtools and block the request which corresponds to the query (right-click on the request and click `Block request URL`).

**Versions**
  System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 8.11.2 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 3.10.10 - /usr/local/bin/npm
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 66.0
    Safari: 11.1.2
  npmPackages:
    apollo-boost: ^0.3.1 => 0.3.1
    apollo-client: ^2.5.1 => 2.5.1
    apollo-link-state: ^0.4.2 => 0.4.2
    react-apollo: ^2.5.2 => 2.5.2

**Comment by hwillson** [comment]
@sreejithr `ApolloQueryResult` (which has an `errors` property) is the type of the result that comes back when using Apollo Client's `query` method directly. In your example however, you're using a React Apollo `Query` component (instead of calling `client.query` directly). React Apollo's `Query` component passes slightly different props to its render prop function, which you can see [here](https://github.com/apollographql/react-apollo/blob/b72a2ba5732d29e0dc151143c3d8946fd8b8bb19/src/Query.tsx#L53-L68). This is all functioning as expected.
