### ISSUE TITLE
Doc pages are very slow to scroll and can't be scrolled with the keyboard

### ISSUE THREAD

**Issue by slikts** [apollographql/apollo-client#4629]
For example: https://www.apollographql.com/docs/react/api/react-apollo

The page is very choppy to scroll (less so in the shorter documents) and none of the default navigation hotkeys like Page Up/Down, Space, or arrow keys work unless focus is manually brought to the `main` element that's set as scrollable. This is really not good for usability or accessibility.

**Comment by tanaypratap** [comment]
I think we need to do two things to fix this issue:
1. Skip sidebar navigation items: currently tabs go through all sidebar items before coming to the page
2. Assign a tabIndex=-1 to the main article div.

@hwillson if this seems right, I can send a PR. Please help me to run the gatsby site locally so that I can fix this.

I quickly ran an Accessibility Audit on the doc site. I can send smaller PRs or create issues for from this thread to track and fix all of these. Let me know if I should go ahead with this.
![image](https://user-images.githubusercontent.com/10216863/55507163-b25ac900-5674-11e9-8eb6-83c01397adf8.png)

**Comment by slikts** [comment]
`tabindex` could fix the keyboard shortcuts, but the sluggishness seems to be due to it doing something with `scroll` events, although I didn't look more closely.

**Comment by hwillson** [comment]
Thanks @slikts @tanaypratap! @trevorblades has been working on the new docs infrastructure, so I'll bring him into this discussion.

**Comment by abernix** [comment]
This is no longer a problem after https://github.com/apollographql/gatsby-theme-apollo/issues/23.  Thanks for reporting this originally.  In the future, all documentation theme related issues (which, as they are shared across all of our various documentation properties, are managed in a central location), can be opened in the https://github.com/apollographql/gatsby-theme-apollo repository.
