### ISSUE TITLE
How to (SSR): modify store (cache) before cache.extract() ? 

### ISSUE THREAD

**Issue by yxwu** [apollographql/apollo-client#4678]
For SSR, getDataFromTree() is used to trigger all Queries. 
However, I'd like to modify cache store on server side before executing cache.extract(), for example, if my GraphQL Server can only provide languageA, I'd like to add languageB to my query result on SSR side.

I can think of two options:

Use "virtual field" to add languageB to query result, but will cache.extract() also include "virtual field" ?

Use Query onCompleted() callback to modify cache, but I find on server side this callback not triggered.

Any suggestions?

Thanks in advance!

**Comment by baldurh** [comment]
I’m wondering about something similar. In our case we have an SSR react application but some parts of the application are not hydrated on the client side (static content, articles, etc) and we therefore do not need the data on the client. I would love it if you could somehow configure the query so that it is not extracted. That way we could get a hydration blob which only contains the data we need on the client.
