### ISSUE TITLE
Ignore results for server redirects

### ISSUE THREAD

**Issue by hehoo** [apollographql/apollo-client#4680]
I got a problem for server redirects. The problem is when graphql server returns 3xx status code, the apollo client would throws an exception "Unexpected token < in JSON at position 0". The reason behind it is that the apollo client is trying to handle the response that returned from the redirected url. And the returned response is actually a HTML, not a JSON. 

So my question is that for server redirects, is apollo client able to detect it and then ignore the results returned from the redirected url?

**Comment by abernix** [comment]
Since obeying redirects isn't always a desirable behavior (e.g. even `curl` requires an additional flag in order to follow the redirect!), the `fetch` implementation requires passing a `redirects: 'follow'` option which permits it.  For more information on passing a custom `fetch` implementation with options, see [the `apollo-link-http`](  https://www.apollographql.com/docs/link/links/http/) documentation and [the `fetch()` API options](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#Parameters).
