### ISSUE TITLE
local state not working

### ISSUE THREAD

**Issue by JonathanLehner** [apollographql/apollo-client#4734]
I followed the tutorial at https://www.apollographql.com/docs/tutorial/local-state/
Whenever I include the local state as in `export const LAUNCH_TILE_DATA = gql'
  fragment LaunchTile on Launch {
    id
    isInCart @client
    isBooked
    rocket {
      id
      name
    }
    mission {
      name
      missionPatch
    }
  }
';`
then the Query only returns {} . If I remove isInCart @client, then the query is successful and gives the launch information. What's wrong with the local state?

**Comment by OurMajesty** [comment]
I did encountered this too.  
When any error is thrown out in client resolver, then all result is becoming empty.  
And there's no indication about this in console.  
So, you should check `data.error` for your problem.

**Comment by lifeiscontent** [comment]
CC: @hwillson @benjamn

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!

**Comment by lifeiscontent** [comment]
@hwillson, any chance the apollo team would be willing to create a Next.js Example app? It seems like Next.js is the major SSR React Framework, but most examples that I've seen don't use the recommended SSR Patterns established by the apollo team. There are also weird things that happen. For example, if a query has an error on the server and the cache has been extracted for the client-side to use, apollo will no longer see the error because the error is not a part of the cache.

It would be great to see a developer from Apollo uncover a few of these common gotchas during SSR.

**Comment by lifeiscontent** [comment]
Based on my experience with Next.js and Apollo Client, Both technologies are good, but they're not good together due to how they are expected to be used. But maybe I just don't understand something and if possible, it would be great to have some of this confusion uncovered.

**Comment by hwillson** [comment]
@lifeiscontent this is something we might consider. Out of curiosity, what do you think https://github.com/vercel/next.js/tree/canary/examples/with-apollo is lacking?

**Comment by lifeiscontent** [comment]
@hwillson Thanks for asking. with-apollo requires you to have a root query for each individual page. getDataFromTree allows you to not have to expose a root query. There are also issues with the ergonomics of next.js e.g. if you have a query that depends on query parameters, the react context for the next.js router I don't believe is populated so using getDataFromTree is pointless in that case.

Also, it would be nice to see how to handle the case that I mentioned, e.g. theirs an error via SSR in graphql but then cleared out due to the data of the query being cleared out because the Apollo cache doesn't store errors in it. But in production environments it's very important to not drop errors. There is currently not a defined practice on how to handle these kinds of cases. Feel free to message me directly if you want more details. Happy to chat!
