### ISSUE TITLE
2.6.0 @client @export directive fix has caching issues

### ISSUE THREAD

**Issue by jwld** [apollographql/apollo-client#4826]
Relates to #4530 

**Intended outcome:**

Using the `@export` directive in a query should also fetch from the cache when possible.

**Actual outcome:**

Currently it seems to do a full refetch every time.

**How to reproduce the issue:**

The issue can be seen [here](https://codesandbox.io/s/012rnvnrrw). Moving between the ids sets `loading` to true every time.

**Versions**

Can see in the sandbox above ^

**Comment by benjamn** [comment]
Thanks for helping test the release candidate, noticing this issue, and providing a clear reproduction @jwld!

My conclusion after playing with the example is that this is working as designed, though the exact behavior is certainly open to discussion. This [commit](https://github.com/apollographql/apollo-client/commit/036c55be123d295ddda7b2b78275b907e619b9de) introduced the behavior of forcing a `refetch` whenever variables change and the query has some non-`@client` parts and the `fetchPolicy` is not `cache-only` (in this case it's `cache-first`, the default policy). [Here](https://github.com/apollographql/apollo-client/blob/0a4325b6a029174af922678a12505f1c84004f73/packages/apollo-client/src/core/ObservableQuery.ts#L631-L641)'s the latest version of the code, with the same logic.

One thing we've improved in 2.6.0 is that the `networkStatus` received by the React component is no longer always `NetworkStatus.loading` (see #4765), so in this case you could at least distinguish between the initial load and subsequent loads, even though `loading === true` in both cases. Specifically, the `networkStatus` ends up as `NetworkStatus.setVariables === 2` after you click one of the buttons, even though it was initiated by a `refetch`, because the variables are changing, which overrides the `NetworkStatus.refetch` status [here](https://github.com/apollographql/apollo-client/blob/0a4325b6a029174af922678a12505f1c84004f73/packages/apollo-client/src/data/queries.ts#L59-L68).

Looping in @hwillson in case he has any additional thoughts.

**Comment by jwld** [comment]
Thanks for the info! This behaviour does seem pretty odd to me.

If you pass the variable as an actual variable (by nesting `Query` components, rather than exposing it via `@export`) then the cache behaves as I'd expect it to - only showing loading state when it's unable to fetch from the cache. If this `@export` directive is intended to negate having to nest queries like this then I'd expect the behaviour to be identical.

Also, on a slight tangent (maybe something for another issue) - is there a way to skip a query based on a variable exposed via `@export`? Seems like quite an important use case, and is again something that can be done when nesting `Query` components (by using the `skip` prop).
