### ISSUE TITLE
unable to compile with TS as of 2.6.0

### ISSUE THREAD

**Issue by JacobPozaic** [apollographql/apollo-client#4851]
**Intended outcome:**

React app using apollo-boost version 0.3.1 depends on apollo-client version ^2.5.1 fails to compile with typescript version 3.4.5 with error, notable react-apollo is also locked to version 2.5.2 as any newer version fails to pass client through HOC's:
`Type '"cache-and-network"' is not assignable to type '"cache-first" | "network-only" | "cache-only" | "no-cache" | "standby" | undefined'.  TS2322`

`<Query query={query} variables={var} fetchPolicy={"cache-and-network"}>`

This is with a fresh package-lock.json, cleared node_modules and npm cache cleared followed by an npm install

**Actual outcome:**

React app using apollo-boost version 0.3.1 depends on apollo-client version ^2.5.1 fails to compile with typescript version 3.4.5 with error:
`Type '"cache-and-network"' is not assignable to type '"cache-first" | "network-only" | "cache-only" | "no-cache" | "standby" | undefined'.  TS2322`

`<Query query={query} variables={var} fetchPolicy={"cache-and-network"}>`

This is with a fresh package-lock.json, cleared node_modules and npm cache cleared followed by an npm install

apollo-client version 2.6.0 is installed and the App fails to run with the error described above.

this appears to be some change in apollo-client/core/watchQueryOptions.ts from version 2.5.1:
`export declare type FetchPolicy = 'cache-first' | 'cache-and-network' | 'network-only' | 'cache-only' | 'no-cache' | 'standby';`

changed to in version 2.6.0:
`export type FetchPolicy = 'cache-first' | 'network-only' | 'cache-only' | 'no-cache' | 'standby';
export type WatchQueryFetchPolicy = FetchPolicy | 'cache-and-network';`

**How to reproduce the issue:**

create a react app with typescript version 3.4.5 and apollo-boost 0.3.1 or apollo-client 2.6.0 and use a query component with the fetch policy "cache-and-network"

**Versions**

  System:
    OS: Windows 10
  Binaries:
    Node: 8.11.3 - C:\Program Files\nodejs\node.EXE
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    apollo-boost: ^0.3.1 => 0.3.1
    apollo-client: 2.5.1 => 2.5.1
    react-apollo: 2.5.2 => 2.5.6

**Comment by benjamn** [comment]
This was an intentional change in Apollo Client 2.6.0, discussed in https://github.com/apollographql/apollo-client/issues/3130, and [documented in `CHANGELOG.md`](https://github.com/apollographql/apollo-client/blob/master/CHANGELOG.md#apollo-client-260-1):

- The `FetchPolicy` type has been split into two types, so that passing `cache-and-network` to `ApolloClient#query` is now forbidden at the type level, whereas previously it was forbidden by a runtime `invariant` assertion:
  ```ts
  export type FetchPolicy =
    | 'cache-first'
    | 'network-only'
    | 'cache-only'
    | 'no-cache'
    | 'standby';

  export type WatchQueryFetchPolicy =
    | FetchPolicy
    | 'cache-and-network';
  ```
  The exception thrown if you ignore the type error has also been improved to explain the motivation behind this restriction. <br/>
  [Issue #3130 (comment)](https://github.com/apollographql/apollo-client/issues/3130#issuecomment-478409066) and commit [cf069bc7](github.com/apollographql/apollo-client/commit/cf069bc7ee6577092234b0eb0ac32e05d50f5a1c)

**Note:** it's important to use `react-apollo@2.5.6` together with `apollo-client@2.6.0`.

**Comment by JacobPozaic** [comment]
ok, thanks for the clarification!
