### ISSUE TITLE
watchQuery().valueChanges is triggered every time a query is performed (Maximum call stack size exceeded error)

### ISSUE THREAD

**Issue by alinmateut** [apollographql/apollo-client#4858]
I fetch a list of users
```
    this.apollo.watchQuery<any>({ query: this.getAllQuery })
        .valueChanges.subscribe(users => this.users = users);
```
then the list is rendered somewhere. When I click a user I can see more details about that user. So I do the following
```
this.apollo.query<any>({query: this.getUserQuery, variables: {id}})
    .subscribe(selectedUser => this.selectedUser = selectedUser)
```
First time I click a user everything works fine, but the second time I select a user I get the following message

> ApolloError {originalStack: "Error↵    at ApolloError.ZoneAwareError
> ...
> 
> graphQLErrors: [] 
> 
> message: "Network error: Maximum call stack size
> 
> networkError: RangeError: Maximum call stack size exceeded at
> Object.hasOwnProperty (<anonymous>)
> exceeded" ...
> 
> stack: "Error↵    at ApolloError.ZoneAwareError
> (http://localhost:4200/vendor.js:223157:33)↵    at new ApolloError
> (http://localhost:4200/vendor.js:148466:28)↵    at
> QueryManager.<anonymous>
> 
> [etc]

I read in the [docs](https://www.apollographql.com/docs/angular/basics/queries) and found the following:

> As you know, Apollo.query method returns an Observable that emits a
> result, just once. Apollo.watchQuery also does the same, except it can
> emit multiple results. (The GraphQL query itself is still only sent
> once, but the watchQuery observable can also update if, for example,
> another query causes the **object** to be updated within Apollo Client's
> global cache.)

I can't understand why  `users => this.users = users` is called when I select a user. It supposed to be called just when I update the list of users (when I add, edit or delete it from the list).

So, when exactly `watchQuery().valueChanges` callback is triggered? When I update the cache in general or when I update a certain object (in my case, the list of users) from the cache?

**Comment by svstartuplab** [comment]
I'm having a similar problem although not the error mentioned by the OP.  

I use a watchQuery to display a list of members from a db on a component's html table.  Works fine.

If I click a button to view an individual member's profile details in a modal window, another component, and pass that individual's id then I receive an object from the db that contains more properties than the member list in the table.  I'm not using in memory caching.

The problem is that the modal window watchQuery is causing the list component's query to run again and I don't want a needless hit to the server.  If I use apollo.query on the list component then there is no additional hit to the server.  However, I want to use watchQuery for the list but without this side effect.  Unlike the OP I get this side effect with only the first modal window and not subsequent ones.

The list component query:

`this.apollo
      .watchQuery({
        query: getAllMembers,
      })
      .valueChanges
      .pipe(
          tap(returnedData => {
            ... does some stuff to one of the returned properties...
          })
        )
      .subscribe(result => {
          this.dataSource.data = result.data['getMembers'];
          console.log('errors in getAllRecords', result.errors)
        });
`

The modal window query:

`this.apollo
      .watchQuery({
        query: getMemberByID,  // Run the query above.
        variables: {
          member_id: member_id,
        },
      })
      .valueChanges
      .subscribe(result => {
          let data = result.data['getMember'];
          this.addData(data, skillNames);  // Call function below to populate modal.
          console.log('errors in view-member', result.errors);
        });
`

**Comment by michelepatrassi** [comment]
I had something similar but then I started to trace the issue: after using valueChanges, I was mutating the returned data with a sort and this triggered cache changes and then valueChanges again. Making the sorting without mutating the data solved the issue for me.

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
