### ISSUE TITLE
Query deduplication doesn't work when queries include different fields

### ISSUE THREAD

**Issue by nsams** [apollographql/apollo-client#4920]
**How to reproduce the issue:**
https://codesandbox.io/s/apollo-query-deduplication-lc9l5

**Intended outcome:**
Query deduplication should avoid the second query ("Queries: 1")

**Actual outcome:**
Two queries are fired ("Queries: 2")

**Additional findings**
Deduplication works correctly when queries the same fields in both queries.

Modify the query2 to include `title` (so both queries include the same fields) and you'll see "Queries: 1"

**Versions**
    "apollo-cache-inmemory": "1.6.1",
    "apollo-client": "2.6.1",
    "apollo-link": "1.2.11",
    "apollo-link-http": "1.5.14",
    "graphql": "14.3.1",
    "graphql-tag": "2.10.1",
    "react-apollo": "2.5.6",

**Comment by benjamn** [comment]
This is working as designed. The two queries are not the same, so they cannot be deduplicated:
```ts
const query1 = gql`
  query {
    allFilms {
      id
      title
    }
  }
`;

const query2 = gql`
  query {
    allFilms {
      id
    }
  }
`;
```
It would be an interesting area for future research to deduplicate similar (subset/superset) queries, but it would always be somewhat flaky, because the smaller query could fire first, and then the larger query would still need to be requested.
