### ISSUE TITLE
[ Module not found ] apollo-cache-inmemory

### ISSUE THREAD

**Issue by LakshanKarunathilake** [apollographql/apollo-client#4945]
**Intended outcome:**
Import the InMemeoryCache class without any ts error

**Actual outcome:**

I was unable to import InMemoryCache class 

`import { InMemoryCache } from "apollo-cache-inmemory";`

This produces a tslint issue 

Module not found: Can't resolve 'apollo-cache-inmemory' in 'C:\Users\lakshan\Documents\ionic-offline\src'

**How to reproduce the issue:**

Import the InMemoryCache class

**Versions**

System:
    OS: Windows 10
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 40.15063.0.0
  npmPackages:
    apollo-cache-inmemory: ^1.6.2 => 1.6.2
    apollo-client: ^2.6.2 => 2.6.2
    apollo-link-http: ^1.5.14 => 1.5.14
    react-apollo: ^2.5.6 => 2.5.6

**Comment by LakshanKarunathilake** [comment]
When i try with apollo-cache-inmemory 1.4.2 it is not throwing any error

**Comment by benjamn** [comment]
If this was a common error, Apollo Client would be unusable for almost anyone. Since you're the first person to have this problem, I would encourage you to dig into it a bit further on your machine (does the `node_modules/apollo-cache-inmemory` directory exist, for example?), and/or provide as much information about your application as you can, since there's not enough information here for us to diagnose the problem effectively.

**Comment by LakshanKarunathilake** [comment]
I think it happened due to a crash in the npm installation 

I could fix that after downgrading and again upgrading the version

Thanks for help

**Comment by abul2285** [comment]
I can see update cache in apollo developer tool but browser doesn't update.. What shuld I do ??
