### ISSUE TITLE
Cannot read queryManager of undefined in Apollo.clearStore

### ISSUE THREAD

**Issue by sampsonjoliver** [apollographql/apollo-client#4970]
**Intended outcome:**
Clearing the apollo store, without refetching active queries,
```
return persistor
          .purge()
          .then(apolloClient.clearStore)
          .then(persistor.resume)
```

**Actual outcome:**

```
Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'queryManager' of undefined
```

**How to reproduce the issue:**
The issue is solved by binding the `clearStore` method in `ApolloClient.js`
```
    this.resetStore = this.resetStore.bind(this);
    this.clearStore = this.clearStore.bind(this);
```

It is also solved if I rewrite my calling function as
```
await persistor.purge();
await apolloClient.clearStore();
persistore.resume();
```

So I believe this problem comes about from invoking the function from a particular outer scope where the `this` reference is undefined. The fix should therefore be to bind the function to the ApolloClient instance.

**Versions**
```
System:
    OS: Windows 10
  Binaries:
    Node: 8.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.10.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    apollo-cache-inmemory: ^1.5.1 => 1.5.1
    apollo-cache-persist: ^0.1.1 => 0.1.1
    apollo-client: ^2.5.1 => 2.5.1
    apollo-link: ^1.2.11 => 1.2.11
    apollo-link-context: ^1.0.17 => 1.0.17
    apollo-link-error: ^1.1.10 => 1.1.10
    apollo-link-http: ^1.5.14 => 1.5.14
    apollo-link-logger: ^1.2.3 => 1.2.3
    apollo-link-offline: ^0.0.3 => 0.0.3
    apollo-link-retry: ^2.2.13 => 2.2.13
    apollo-utilities: ^1.2.1 => 1.2.1
    react-apollo: 2.1.3 => 2.1.3
```

Note I'm also on react-native 0.57.5

**Comment by hwillson** [comment]
Please try a recent version of `@apollo/client` and let us know if this issue is still happening. Thanks!

**Comment by chidimo** [comment]
I'm still experiencing this issue. I'm using apollo-client 3.1.4

The error is thrown on the `await clearStore()` line in the below hook

```javascript
export const useLogout = () => {
  const history = useHistory();
  const { clearStore, cache } = useApolloClient();

  const _logout = async () => {
    localStorage.clear();

    clearStore();
    cache.modify({
      fields: {
        isLoggedIn: () => false,
      },
    });
    history.push('/login');
  };

  return { _logout };
};
```

**Comment by helderjbe** [comment]
Also having this error. resetStore seems to work, but clearStore gives me this error:

```
Unhandled Rejection (TypeError): Cannot read property 'queryManager' of undefined
(anonymous function)
src/core/ApolloClient.ts:473
  470 |  */
  471 | public clearStore(): Promise<any[]> {
  472 |   return Promise.resolve()
> 473 |     .then(() => this.queryManager.clearStore())
      | ^  474 |     .then(() => Promise.all(this.clearStoreCallbacks.map(fn => fn())));
  475 | }
  476 | 
```

**Comment by winghouchan** [comment]
The functions lose their `this` context when you destructure functions from the instantiated Apollo Client because the functions are currently written as class methods: https://github.com/apollographql/apollo-client/blob/29cae08eb0f21cb1864ffcd4e7125e8f6d0eaa1b/src/core/ApolloClient.ts#L484-L490

To resolve, they could be re-written as arrow functions (which keep their `this` context) and assigned to class fields:

```typescript
export class ApolloClient<TCacheShape> implements DataProxy {
  ...
  public clearStore = (): Promise<any[]> => {
    return Promise.resolve()
      .then(() => this.queryManager.clearStore({
        discardWatches: true,
      }))
      .then(() => Promise.all(this.clearStoreCallbacks.map(fn => fn())));
  }
  ...
}
```

Or `this` can be bound in the constructor:

```typescript
export class ApolloClient<TCacheShape> implements DataProxy {
  ...
  constructor() {
    this.clearStore = this.clearStore.bind(this);
  }

  public clearStore(): Promise<any[]> {
    return Promise.resolve()
      .then(() => this.queryManager.clearStore({
        discardWatches: true,
      }))
      .then(() => Promise.all(this.clearStoreCallbacks.map(fn => fn())));
  }
  ...
}
```

See this [TypeScript Playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ1oDswFsCm0AvNAEQBmiJA3KutMPJhAC4BOArsM-KwBQCUKOhmYALAJYQAdGUwAheO0wATItDGSZ8xSqkAjcSt4aI-GhgC+tDLIFCMGBk3gg8UkPADmvcphIAadQlTc2grOlkAQVZWeAB3NTtCAD57BycIFzcPb19o2LiAoMkzOnCbbSVlOzQHekZM13cvH1kFKqKTUstUcIzmaAokYkw8BIR4ARpUIa0p6AB6BbhEAC4ULFw8dfJKMJnELXz4+aWV+HXkTfwdoZJ92badarNF5YnL6+3SO-3Ufo2skCURi8WBlRUYTUQ2mtleZyqeDIhjwyhmmGOcVO7zWG2wNx+eysTyq2POn3x3128HuFiAA) and hit <kbd>Run</kbd> to see a demo.

In the meantime, don't destructure.
