### ISSUE TITLE
Disable console.warn by default

### ISSUE THREAD

**Issue by olalonde** [apollographql/apollo-client#5214]
As a library, it's a bad practice to use `console.warn` or writing anything to the console by default. It should be possible to disable this behavior. 

Use case: I'm using apollo-client to test a graphql API in Node.js and it pollutes my test outputs with unnecessary text.

**Comment by rdsedmundo** [comment]
You can set `process.env.NODE_ENV` to `production`, which will suppress all development warnings.

**Comment by olalonde** [comment]
That's not an option as it would break code which assumes `process.env.NODE_ENV == "test"`.

**Comment by hwillson** [comment]
Please open a feature request for this in https://github.com/apollographql/apollo-feature-requests. Thanks!

**Comment by matthandlersux** [comment]
@olalonde fyi, you can avoid this issue if your project resolves to the latest version of `ts-invariant` (readme [here](https://github.com/apollographql/invariant-packages/tree/ts-invariant%400.7.3/packages/ts-invariant)), which defines a method to globally set the log level (`setVerbosity`).

in case it's useful: some of my dependencies in the apollo toolchain were still resolving to `ts-invariant:^0.4.0`... since the surface area of this library is pretty small, however, it worked out ok for me to force resolution to a more recent version by adding the following to `package.json` (this might be a yarn-only feature, so YMMV):
```json
  "resolutions": {
    "ts-invariant": "^0.7.3"
  }
```
