### ISSUE TITLE
docs: network-only documentation is unclear

### ISSUE THREAD

**Issue by lifeiscontent** [apollographql/apollo-client#5220]
https://github.com/apollographql/apollo-client/blob/0fd1b2c26aabb683262298ca0c8ac3c6f324d01b/docs/source/api/react-apollo.md#L922

> but at the cost of an instant response to the user when one is available

Does that mean cache will be returned? At which point does it get data from the cache?

**Comment by chaunceyau** [comment]
@lifeiscontent 'network-only' fetch policy means the query will never hit the cache on your request.

Take a look at this gif: https://imgur.com/AqT0R5u

Notice how the user profile information takes a second to load on first request. This is because the request is fetching from the server, as it does not have a cached version of the request. 

Also take note that when a user whose profile has been previously loaded, the profile updates instantly. This is because the request has been made and is now cached. If we want to avoid this from happening and force our query to hit the server every time, we can pass the 'network-only' fetch policy. 

I hope this helps.

**Comment by lifeiscontent** [comment]
@chaunceyau that's not true, if `disableNetworkFetches` is set to true, it becomes `cache-first`

**Comment by lifeiscontent** [comment]
to add more context, I'm using next.js and in SSR apollo behaves oddly in several places, when using a <Query> data is undefined when it shouldn't be, loading is true, when it should be false, all kinds of weird situations and there isn't a very clear explanation on how to setup apollo for a solid experience.

**Comment by dylanwulf** [comment]
I think the key word is "initial". The initial data will not be returned from the cache. But once you have initial data, updating the cache will update your query results.

**Comment by lifeiscontent** [comment]
@benjamn do you know how I could properly setup next.js to use a `<Query>` component to fetch data on the server, use the fetched data on the client (without loading triggered to true) because I'm currently running into issues of using getDataFromTree saying data is undefined, or loading is set to true on a `<Query>` component, and I'd like to stop playing wack-a-mole with the cache and just continue working on features.
