### ISSUE TITLE
Nullable Fields Not Working For Queries To Local State

### ISSUE THREAD

**Issue by devinsm** [apollographql/apollo-client#5253]
**Intended outcome:**
When querying the cache, fields should be nullable. That is if the return value of a local resolver does not have a property that the query asked for, that property should have a value of null in the query's result. Similarly, if the \@client field is pulled directly from the cache, and it lacks that property, that property should be replaced with null. Please see the reproduction, because the code will be clearer than what I've written here.

**Actual outcome:**
If a local query asks for a field, and the object the resolver returns does not have that field, then the query fails

**How to reproduce the issue:**
Please see this repo I made to demonstrate the issue: [https://github.com/devinsm/apollo-local-query-bug](https://github.com/devinsm/apollo-local-query-bug)

**Versions**
  System:
    OS: macOS 10.14.6
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Safari: 12.1.2
  npmPackages:
    apollo-boost: ^0.4.4 => 0.4.4

**Comment by linfan68** [comment]
We're facing the same problem. We're building react-native app and using a client-side resolvers backed by a local SQLite database. Doing this provides very low latency UI updates and saves whole lot of network requests. And because we're using same data structure for local/server database, we can move certain logic/data between server/client freely, and it also makes testing a lot easier.

**Comment by zcramos** [comment]
I'm also running into this problem. Any other workarounds? My use case:

```
query Stuff($id1: String, $id2: String) {
  foo(id: $id1) {
    ...thingFields
  }
  bar(id: $id2) @client  {
    ...otherThingFields
  }
}
```
`foo` is always a record that has been cached from a previous query and I'm using a cacheRedirect to fetch that record. `bar` may or may not exist (and would also be fetched via a cacheRedirect if available).

When ApolloClient tries to fetch bar and fails (because no record exists in the cache), it seems to send the entire query to the server, which fails because foo isn't a top level type in our graphql schema (and obviously bar fails on the server as well).

If I annotate foo `@client` as well, the query is never sent to our server but the resulting `data` is an empty object. I would expect the return value to be
```
{
  foo: { ...thingsOnFoo },
  bar: undefined,
}
```

I also tried changing the errorPolicy to `all`, but no luck there either.

Is the solution to write a custom resolver for `bar` instead of relying on cacheRedirects?

**Comment by linfan68** [comment]
> I'm also running into this problem. Any other workarounds? My use case:
> 
> ```
> query Stuff($id1: String, $id2: String) {
>   foo(id: $id1) {
>     ...thingFields
>   }
>   bar(id: $id2) @client  {
>     ...otherThingFields
>   }
> }
> ```
> 
> `foo` is always a record that has been cached from a previous query and I'm using a cacheRedirect to fetch that record. `bar` may or may not exist (and would also be fetched via a cacheRedirect if available).
> 
> When ApolloClient tries to fetch bar and fails (because no record exists in the cache), it seems to send the entire query to the server, which fails because foo isn't a top level type in our graphql schema (and obviously bar fails on the server as well).
> 
> If I annotate foo `@client` as well, the query is never sent to our server but the resulting `data` is an empty object. I would expect the return value to be
> 
> ```
> {
>   foo: { ...thingsOnFoo },
>   bar: undefined,
> }
> ```
> 
> I also tried changing the errorPolicy to `all`, but no luck there either.
> 
> Is the solution to write a custom resolver for `bar` instead of relying on cacheRedirects?

Not sure if I understand your problem correctly. But if you’re using the @client directive, you’ll need to write a resolver on client side. And then the query will never go to server but hit the resolver code on client, where you can do the cache handling. Unfortunately in that case you’ll hit this issue and cannot return null/undefined from that resolver.

On the other hand, if you just want to “return data if it exists on cache, and null if cache misses, but never ask server”, have you tried to set fetchPolicy to “cache-only”?

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!
