### ISSUE TITLE
use two identical @client fields nested in a query

### ISSUE THREAD

**Issue by mikestaub** [apollographql/apollo-client#5345]
When I use @apollo/react-hooks with a query with multiple instances of the same @client field nested, the data object is never populated. ( although the query completes ) Is this expected?

Note: If the 2nd @client field is not nested the query works.

sample query:

```
query myQuery {
  user {
    id
    # if we comment out the next line, the query works
    customField @client 
    friends {
      id
      customField @client 
    }
  }
}
```

**Comment by rdsedmundo** [comment]
Could you provide a working example of this not working? I set up a structure similar to yours locally and it worked perfectly for me. 

My hunch is that you may have a problem with your customField resolver. Would you mind sharing its definition? That's the only thing that I can think of, as otherwise, it's perfectly fine to have the same field multiple times.

**Comment by mikestaub** [comment]
You were correct, there was a bug in my resolver function. I would have expected apollo to throw an error.

Also, I accidentally added a client field to a type that did not have a resolver. The data was just never returned, I would have also expected an apollo error to be thrown.

**Comment by hwillson** [comment]
Sounds like this is working as designed - thanks!
