### ISSUE TITLE
Missing field in cache causes cache read to fail

### ISSUE THREAD

**Issue by haoyangnz** [apollographql/apollo-client#5403]
After I write to cache with missing fields, when I try to read the cache the cache read causes an error.

If the field is optional, shouldn't it just assume it's `null` and allow me to get the remaining of the data?

**Comment by timothyarmes** [comment]
I'm having the same problem. It's broken loads of my code.

When I look in the cache using the devtools, Apollo seems to insert null for optional fields.  If I insert an objet into the cache that doesn't have an optional field (such as an object returned by the server), then an exception is throw the next time the cache is read because the field is missing.

To work around the issue, I'm having to add the fields with a null value.
