### ISSUE TITLE
using apollo-link-batch with automatic persisted queries

### ISSUE THREAD

**Issue by khaledosman** [apollographql/apollo-client#5523]
The recommended way to setup Automatic Persisted Queries according to the documentation is by adding 
`createPersistedQueryLink({useGETForHashedQueries: true})`

Another best practice is to batch http request via `apollo-link-batch-http`. However apollo-link-batch-http does not support GET requests, so combining the two methods above doesn't work and throwns an error about GET requests not supported via batch http, so I have to remove `useGETForHashedQueries: true`.

What is the reason its not supported and What is the recommended way to go about this?

**Comment by macrozone** [comment]
run into the same problem, @khaledosman did you find any workaround?

**Comment by khaledosman** [comment]
I removed `useGETForHashedQueries`  some queries do still get persisted/cached as far as I can see in redis

**Comment by hwillson** [comment]
A lot of the Apollo Client internals have changed since v3 was launched. We recommend trying a more modern version of `@apollo/client`. Let us know if you're still encountering this issue. Thanks!

**Comment by eliw00d** [comment]
I just came across this after encountering `Error: apollo-link-batch-http does not support GET requests`. The documentation does point out:

> GET requests are not compatible with @apollo/client/link/batch-http.

and [there is a comment in the code](https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-batch-http/src/batchHttpLink.ts#L122) that says:

> There's no spec for using GET with batches.

which makes it sound like it will not be a thing - and is not with v3.

That being said, are there any plans to support some combination of the two? Something like use GET (and unbatched) where possible and POST (and batched) otherwise?

As of right now, if you set useGETForHashedQueries to true it just crashes and burns, even if you only have one request to send (which could be a GET).

**Comment by jeremypress** [comment]
hey @hwillson , we're still encountering this on apollo 3.x. using @apollo/client. Is there a required ordering to make this supported? We found no mention in the docs, and the error message makes it seem unsupported
