### ISSUE TITLE
[v3] React dependency is hard coded

### ISSUE THREAD

**Issue by kamilkisiela** [apollographql/apollo-client#5532]
Hi, I'm the author of [Apollo Angular](https://github.com/apollographql/apollo-angular) and I noticed that `@apollo/client` has now an optional dependency of `react`.

It's not a big problem in tools like `npm` or `yarn` but it breaks every single integration with other frameworks, even `vue-apollo`.

Vue and Angular people (or even folks from Svelte, Web Components, Polymer and so on) will see an error at build time that `react` module is missing or even at type checking phase when compiling with TypeScript.

I know that Vue, Angular or any framework other than React is not considered when planning new versions and not even listed in docs but we do our best to support our customers working day-to-day with those frameworks, in my case it's Angular.

I would be happy to help solving that issue.

Splitting core logic into `@apollo/core` and putting that in `@apollo/client` with react code sounds like a good option to me. Without that, I need to maintain a fork.

**Comment by kamilkisiela** [comment]
Not ideal proposal, but at least non-react people can use new Apollo v3 #5541

**Comment by abdonrd** [comment]
What about a React package? Something like `@apollo/react`?

**Comment by hwillson** [comment]
This is definitely something we've had in mind since we started working on AC 3. Our original design had specific features broken out into separate bundles, like `@apollo/client/core`, `@apollo/client/react`, `@apollo/client/link`, etc. After doing a bunch of planning and testing around that approach however, we've decided to head in different direction, and let modern build/bundle tooling tree-shake / dead code eliminate the parts of AC 3 that aren't being used. So if you're not using React for example, all React related code is sliced from the final bundle. Along these lines, `react` is a fully optional dependency using [NPM's new `peerDependenciesMeta` feature](https://github.com/npm/cli/pull/224). Package authors that are integrating with `@apollo/client` shouldn't have to worry about installing `react`. If this is an issue though, I'd love to hear more about it (with a specific example of the error you're seeing). We aren't against splitting `@apollo/client` up into multiple bundles if people prefer (and have a preliminary branch that does this), but if we can keep things simpler for both code maintenance and usability by relying on modern build/bundle tools, that's definitely the approach we'd prefer.

**Comment by abdonrd** [comment]
An example of the `npm init @open-wc` application with `@apollo/client@beta`.
Thanks to ES Modules, this application runs directly in the browser, without any build/bundle step.

- https://github.com/abdonrd/open-wc-application-apollo-client/compare/master...apollo-client-3#diff-4de87872859ee66b051ba259f0375644

<img width="1212" alt="Screenshot 2019-11-02 at 11 08 13" src="https://user-images.githubusercontent.com/1007051/68065245-78b08480-fd61-11e9-9d5e-f6cfb821934c.png">


And now working just patching `@apollo/client@beta` to remove the React exports.

- https://github.com/abdonrd/open-wc-application-apollo-client/compare/apollo-client-3...apollo-client-3-no-react

<img width="1212" alt="Screenshot 2019-11-02 at 11 11 39" src="https://user-images.githubusercontent.com/1007051/68065252-97af1680-fd61-11e9-93f6-6cb4a32cfb6c.png">


Note: The Apollo Client implementation is really simple and hardcoded to make the example easier.

**Comment by kamilkisiela** [comment]
Do you imagine asking users to add a postinstall script or even do it automatically for them? It's a workaround and not long term solution. 

@hwillson tree-shaking doesn't work like that, it includes all the code, marks some imports as unused and then on minifying the unused code is removed. That means TypeScript still sees react import.
Look at my PR. It keeps things fairly simple and we don't get multiple packages, just a nested package.json so all the tools can take advantage of it. We still reuse esm modules but we gain es5 bundle without react.

**Comment by kamilkisiela** [comment]
An extra thing to think about. Including `react` in `@apollo/client` means that whenever someone uses `@apollo/client` directly, in any 3rd-party library then all non-react codebases are broken.

Would be so easier if there would be `@apollo/react` (which sounds even better then `@apollo/client`)  that includes everything + react related code and `@apollo/client` that is a base for `@apollo/react` and other integrations.

**Comment by bennypowers** [comment]
Fully agree. Forcing react for everyone is counterproductive.

**Comment by hwillson** [comment]
Thanks all, and please don't worry - we'll make sure everyone is happy with the bundling approach before we push out the final AC3 release (we definitely don't want to break other UI integrations). @kamilkisiela your PR lines up exactly with how we had this setup before, so that's likely the direction we'll head in. We've received a tonne of great feedback from `beta` testers and will be reviewing/acting on all of it shortly.

**Comment by benjamn** [comment]
@hwillson Can we close this now that we have the `@apollo/client/core` entry point?

**Comment by hwillson** [comment]
For sure @benjamn - thanks!
