### ISSUE TITLE
watchQuery errorPolicy overrides the query errorPolicy in defaultOptions

### ISSUE THREAD

**Issue by capaj** [apollographql/apollo-client#5551]
This causes errors in the hook/component to be `undefined` and it's very frustrating for the apollo-client user to determine why this is.

**Intended outcome:**
query errors are not ignored
![image](https://user-images.githubusercontent.com/1305378/68252830-c7db0b80-0026-11ea-8a31-7f9e5ce5efbe.png)

Note: In order to take above screenshot I had to remove this line:
![image](https://user-images.githubusercontent.com/1305378/68252876-e2ad8000-0026-11ea-945e-634174daa157.png)

**Actual outcome:**
query errors are ignored
![image](https://user-images.githubusercontent.com/1305378/68252790-b42fa500-0026-11ea-9ddd-4785631f641b.png)

**How to reproduce the issue:**
1. instantiate your  `defaultOptions` like this: 
```ts
new ApolloClient({
    cache: new InMemoryCache({
      addTypename: true
    }),
    defaultOptions: {
      watchQuery: {
        fetchPolicy: 'cache-and-network' as FetchPolicy,
        errorPolicy: 'ignore' as ErrorPolicy
      },
      query: {
        fetchPolicy: 'network-only' as FetchPolicy,
        errorPolicy: 'all' as ErrorPolicy
      }
    },
    queryDeduplication: true
  })
```
This is similar to: https://www.apollographql.com/docs/react/api/apollo-client/#example-defaultoptions-object 

2. call `useQuery` in a component such as this ensuring that the resolver throws an error:
```ts
import { useQuery } from 'react-apollo'
import gql from 'graphql-tag'

export const TestApollo: React.FC<{}> = () => {
  const uqRes = useQuery(gql`
    {
      throwing
    }
  `)
  console.log('useQuery hook result:', uqRes)
  return <div>AA</div>
}
```
3. bug happens on the frontend 

**Versions**
```
  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.15.2 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Browsers:
    Chrome: 78.0.3904.70
    Firefox: 70.0
  npmPackages:
    apollo-cache-inmemory: ^1.6.3 => 1.6.3 
    apollo-client: ^2.6.4 => 2.6.4 
    apollo-link: ^1.2.13 => 1.2.13 
    apollo-link-batch-http: ^1.2.13 => 1.2.13 
    apollo-link-context: ^1.0.19 => 1.0.19 
    apollo-link-error: ^1.1.12 => 1.1.12 
    apollo-link-http: ^1.5.16 => 1.5.16 
    apollo-link-schema: ^1.2.4 => 1.2.4 
    apollo-server: ^2.9.7 => 2.9.7 
    apollo-server-express: ^2.9.7 => 2.9.7 
    react-apollo: ^3.1.3 => 3.1.3 
```

**Comment by hwillson** [comment]
This should no longer be an issue in `@apollo/client@latest` - let us know otherwise, thanks!

**Comment by omgaz** [comment]
@hwillson I've noticed the same behavior but the docs suggest that this isn't a bug but expected behavior:

https://www.apollographql.com/docs/react/api/core/ApolloClient/#example-defaultoptions-object

> Note: The useQuery hook uses Apollo Client's watchQuery function. To set defaultOptions when using the useQuery hook, make sure to set them under the defaultOptions.watchQuery property.

Am I misunderstanding something, should defaultOptions.query override the default behaviour of defaultOptions.watchQuery when using `useQuery`?

**Comment by hwillson** [comment]
@omgaz `defaultOptions.watchQuery` is used for `useQuery`, since `useQuery` uses `client.watchQuery()` internally. Setting `defaultOptions.query` options shouldn't impact `useQuery`. This being said we've made some adjustments to how default options are passed through the internals in AC3, so if you're able to try the latest version and notice any issues, definitely let us know. Thanks!
