### ISSUE TITLE
HttpLink is not replacing the authorization header 

### ISSUE THREAD

**Issue by HerlinMatos** [apollographql/apollo-client#5705]
I'm adding an authorization header to HttpLink with my token, and it's keeping the previous one, I am wondering if apollo client have some type of cache with the headers and how to avoid it 

**Code:**
const authorization = token ? `Bearer ${token}` : "";
const httpLink = new HttpLink({
    uri: GRAPHQL_SERVER_URL,
    headers: {'authorization': authorization} 
});
const client = new ApolloClient({
      link: httpLink,
      cache: new InMemoryCache()
});
client.query(q);

**Comment by dylanwulf** [comment]
The reason it appears to be "cached" is because the `new HttpLink()` code only runs _once_ when the application initializes. It has no way of knowing that the token changed. Instead of passing the token into the `HttpLink` constructor, consider using the `apollo-link-context` package to dynamically set the auth header: https://www.apollographql.com/docs/react/networking/authentication/#header

**Comment by HerlinMatos** [comment]
Thanks @dylanwulf , HttpLink was working fine as you mentioned, the issue was related with a request interceptor that I had in my system and broke all my graphql request authorization headers.
