### ISSUE TITLE
graphql-anywhere: replace `JSON.stringify` call on very hot code path

### ISSUE THREAD

**Issue by spencer-brown** [apollographql/apollo-client#5744]
Hey, folks! We use the `propType` module from `graphql-anywhere` in quite a few places in our app & we're finding that the `JSON.stringify` call [here](https://github.com/apollographql/apollo-client/blob/master/packages/graphql-anywhere/src/utilities.ts#L54) causes a noticeable slowdown when we make a particularly large data request during local development (ie, when prop-type checking is performed).

The size of our returned data is relatively large and contains many nested types in its query, which I suppose is what's causing this code path to be so hot.

Here's what I see when using Chrome's performance profiling feature after making a couple of these large network requests:
<img width="986" alt="Screen Shot 2020-01-02 at 2 20 28 PM" src="https://user-images.githubusercontent.com/5354793/71699870-7f19a780-2d76-11ea-8c6b-a38977ef5152.png">

I replaced this `JSON.stringify` call with a hard-coded string for comparison, which drove this line's execution time to 10s of ms.

Using `JSON.stringify` is nice for the level of detail it gives in the error, but would you accept an alternative that makes this line run faster? Using `JSON.stringify` causes such a large slowdown during local development that I think we'll have to remove this package from our app if a change isn't possible.

A simple solution might be to just make the error `${info.resultKey} missing`.

Happy to make a PR if you'd be open to it!

**Comment by thefliik** [comment]
> A simple solution might be to just make the error `${info.resultKey} missing`.

If I'm reading this correctly, the error message is currently always constructed, even when there is no error. Wouldn't a better solution be refactoring this code so that the error is only built if it's needed?

**Comment by spencer-brown** [comment]
@thefliik yes, that is a better solution :)

**Comment by benjamn** [comment]
I'm open to improving this, but I would just point out that we (the Apollo Client team) thought we _had_ written the code such that `JSON.stringify` would not be called in production, where performance matters most, thanks to [`ts-invariant`](https://www.npmjs.com/package/ts-invariant) and [`rollup-plugin-invariant`](https://www.npmjs.com/package/rollup-plugin-invariant).

This issue is specifically pointing out that `JSON.stringify` is called unnecessarily in _development_, which is true, but your stringification payload needs to be pretty huge before that becomes a noticeable problem, and there's no performance penalty in production, because long error messages are stripped in production builds.

Also, just in case anyone who reads this is new to JavaScript performance, `JSON.stringify` is one of the most obsessively optimized tools we have available as web developers, so in general there's no way to do what it does any faster using non-native JS. You can only pass less data to it, or stop calling it unnecessarily, which is what we're considering doing here.

**Comment by hwillson** [comment]
Just to add to the above, `graphql-anywhere` has been removed from Apollo Client 3. You'll still be able to use the current version as is, but we're not planning on making many future changes to it. If anyone is interested in maintaining it after Apollo Client 3 is live, let us know.

**Comment by HosseinAgha** [comment]
@hwillson did you move `graphql-anywhere` to any other github repository. I cannot find its original github repo when google it. Apollo documentation has so dead links to `graphql-anywhere`. Its npm package still points to apollo-client repo.  
You could have at list put it in an archived repository until someone volunteered for its maintenance.

**Comment by hwillson** [comment]
@HosseinAgha it's available here: https://github.com/apollographql/apollo-client/tree/release-2.x
It will find a new home before we launch AC 3.

**Comment by hwillson** [comment]
Closing since `graphql-anywhere` is no longer something we're supporting (details: https://github.com/apollographql/apollo-client/issues/5744#issuecomment-571988792). Thanks!
