### ISSUE TITLE
useQuery updating cache wrongly automatically

### ISSUE THREAD

**Issue by jordisantamaria** [apollographql/apollo-client#5807]
I'm having a problem getting data with useQuery, I have 2 calls with useQuery for the same query using a different variable, the problem is that if when returning data, some values of the returning array of the 2 calls are identically, the first call is getting updated with the values of the second call automatically, losing the data it should have.

As you can see on the image, at first it return an array of 6 values and other of 36 values "6 of them are same values of the array of 6 values", but it get updated automatically for no reason, getting both calls with array of 6 same values.

<img width="577" alt="スクリーンショット 2020-01-18 20 06 14" src="https://user-images.githubusercontent.com/6263700/72662791-bfdc1680-3a2e-11ea-9d5e-8e5b04e5a35a.png">

The 2 useQuery calls are:

const listFront = useQuery(GET_LIST_ITEMS_BY_LISTNAME_QUERY, {
    variables: {listName: props.router.query.listName, **isReverse: false**}
  });
  const listReverse = useQuery(GET_LIST_ITEMS_BY_LISTNAME_QUERY, {
    variables: {listName: props.router.query.listName, **isReverse: true**}
  });

I guess I will solve it by just calling graphql for only 1 list and separating it on front end... but still, its so weird graphql just update your query to make it same as other query because values of 1 query are included on the other query.

**Comment by benjamn** [comment]
Can you show the query, or ideally provide a simple [reproduction](https://github.com/apollographql/react-apollo-error-template#reproduction-creation-steps) (note the `ac3` branch)? I suspect you need a custom `merge` function for the array-valued field, since the cache can't automatically reconcile conflicting arrays for you. A custom `read` function could handle the `args.isReverse` boolean for you, too, so the second query might not need to trigger a network request at all.

**Comment by hwillson** [comment]
We'll need a reproduction (using `@apollo/client@latest`) to be able to troubleshoot this further. Thanks!
