### ISSUE TITLE
Error: Network error: fetcher is not a function

### ISSUE THREAD

**Issue by kuldip9060** [apollographql/apollo-client#5886]
Getting this "Error: Network error: fetcher is not a function" in both ios and android while try to debug with put some break points. 

Already, I have spend 3 days to resolve this issue but can't found the any solution. Please help me :(

**Comment by benjamn** [comment]
This repository is not used on iOS or Android. Try https://github.com/apollographql/apollo-ios or https://github.com/apollographql/apollo-android instead, and please provide as much additional information as possible when you do, like what version of the library you're using, and examples of the code you've written), so that we can actually help you. Your lost time investment may feel very real to you, but complaining about it is no substitute for providing actionable information.
