### ISSUE TITLE
fetchMore with infinite scrolling duplicates items

### ISSUE THREAD

**Issue by saschametz** [apollographql/apollo-client#5901]
**Intended outcome:**
The data shouldn't contain duplicated items

**Actual outcome:**
The data contains duplicated items

**How to reproduce the issue:**
I've added the example code that reproduces the issue.
I'm loading the data very fast by using a combination infinite scrolling and fetchMore.

If I set the fetchPolicy to "cache-and-network" the data contains many duplicated items.
After switching to "network-only" it works.

https://codesandbox.io/s/cool-sky-3spv4

Does someone know the reason for this?

**Comment by alexpermyakov** [comment]
Fixed: https://codesandbox.io/s/small-rgb-7q6lk

The "cache-and-network" policy always makes a request, it means `updateQuery` will be called twice during a single `handleLoadMore` call. 

You have to filter out the duplication or add a new _item_ only if it's hasn't been added before.

**Comment by saschametz** [comment]
Thanks @alexpermyakov, your version works great. However I'm struggling to fully understand why `updateQuery` is called twice.

So the "cache-and-network" policy first tries to read the data from the cache and besides that it always makes a request to the server and updates the cache with the current data.

The `fetchMore` function gets called once the `handleLoadMore` is called but why is `updateQuery` called twice?

**Comment by alexpermyakov** [comment]
Looks like it's current behavior: `updateQuery` always has been called despite the cache first policy.

**Comment by alexpermyakov** [comment]
@saschametz The problem is not in `updateQuery`, in fact it's better not to change it - it's fine.
Take a look [here](https://codesandbox.io/s/nervous-shadow-fvnn9) - you call `handleLoadMore` with the same `cursor` twice.

Explanation: the `cache-and-network` policy makes an extra render for the component (just try to console.log('render') inside Countries component). It's a correct and documented behaviour, however it's InfiniteScroll which makes an another handleLoadMore call with the same `cursor` after each render...

I think [updateQuery](url) should stay the same for all policies, it's not an apollo issue.
One solution might be just to control when you want to call `handleLoadMore`, check [this](https://codesandbox.io/s/interesting-carson-4fmgq).

**Comment by saschametz** [comment]
@alexpermyakov Thank you for the detailed explanation.
