### ISSUE TITLE
Argument of type '{ connectToDevTools: true; link: ApolloLink; cache: InMemoryCache; request: (operation: any) => Promise<void>; }' is not assignable to parameter of type 'ApolloClientOptions<NormalizedCacheObject>'.   Object literal may only specify known properties, and 'request' does not exist in type 'ApolloClientOptions<NormalizedCacheObject>

### ISSUE THREAD

**Issue by MichaelPopeDeveloper** [apollographql/apollo-client#6025]
Good afternoon! 

I recently switched React project to Typescript and am recieving the following error: 

```
Argument of type '{ connectToDevTools: true; link: ApolloLink; cache: InMemoryCache; request: (operation: any) => Promise<void>; }' is not assignable to parameter of type 'ApolloClientOptions<NormalizedCacheObject>'.
  Object literal may only specify known properties, and 'request' does not exist in type 'ApolloClientOptions<NormalizedCacheObject>
```

The code snippet looks like this: 
```
import ApolloClient from 'apollo-client';

export const Client = new ApolloClient({
  link: espoLink,
  cache,
  //uri: "http://localhost:8080/graphql",
  request: async operation => {
    //Get any tokens and send them to the server
    operation.setContext({
      headers: {
        "x-token": localStorage.getItem("token"),
        "x-refresh-token": localStorage.getItem("refreshToken")
      }
    });
  }
});
```

I looked into the type file, and it appears that the type ApolloClientOptions does not contains the 'request' property: 

```
export declare type ApolloClientOptions<TCacheShape> = {
    link?: ApolloLink;
    cache: ApolloCache<TCacheShape>;
    ssrForceFetchDelay?: number;
    ssrMode?: boolean;
    connectToDevTools?: boolean;
    queryDeduplication?: boolean;
    defaultOptions?: DefaultOptions;
    assumeImmutableResults?: boolean;
    resolvers?: Resolvers | Resolvers[];
    typeDefs?: string | string[] | DocumentNode | DocumentNode[];
    fragmentMatcher?: FragmentMatcher;
    name?: string;
    version?: string;
};
```

Although, the 'request' property is on Apollo Client in the [docs](https://www.apollographql.com/docs/react/get-started/)

Is this a problem with outdated typescript declarations?

**Comment by patomation** [comment]
I'm also facing the same issue.

**Comment by patomation** [comment]
Maybe the documentation is wrong. It must be hell to update the "Catacombs" of Apollo Documentation.

After reading other documentation.. er tutorials I found a different way to handle headers in the "Maze" that is the Apollo Documentation.

You would simply have to concat an authLink to espoLink

For your case it would be like this
`
import { setContext } from 'apollo-link-context'

const authLink = setContext((_, { headers }) => {
  // get the authentication token from local storage if it exists
  const token = localStorage.getItem('token')

  // return the headers to the context so httpLink can read them
  return {
    headers: {
      ...headers,
      "x-token": localStorage.getItem("token"),
       "x-refresh-token": localStorage.getItem("refreshToken")
    }
  }
})

const client: ApolloClient<NormalizedCacheObject> = new ApolloClient({
  cache,
  link: authLink.concat(espoLink)
})
`
I found this method here: https://www.apollographql.com/docs/react/networking/authentication/

Now that I'm reading the documentation I think apollo-boost comes with requests. I wish apollo boost wasn't a thing it really fractures learning instead of making easier for first timers to start.

**Comment by indralukmana** [comment]
I was trying out graphql with Next.js (using TypeScript). I also found this problem when trying to add `authorization` to the header by modifying `request` in `ApolloClient`

```
Object literal may only specify known properties, and 'request' does not exist in type 'ApolloClientOptions<NormalizedCacheObject>
```

After taking a closer look into this documentation the https://www.apollographql.com/docs/react/networking/authentication/#header I figure out there are two different `ApolloClient` available in `apollo-boost` package.

- `import { ApolloClient } from 'apollo-boost'` => this one is using `ApolloClient` from `apollo-client` package included with the `apollo-boost`. To modify the header we can use `setContext` from `apollo-link-context` to set the header with `HttpLink` instance.

- `import ApolloClient from 'apollo-boost'` => this one we need to configure the `request`

I'm not sure what their differences are but I use the first one because I was modifying the Next.js with apollo example.

**Comment by hwillson** [comment]
Apollo Boost has been deprecated, so this should no longer be an issue. Thanks!
