### ISSUE TITLE
Query from client in a local state field

### ISSUE THREAD

**Issue by dmitry** [apollographql/apollo-client#6047]
Is it somehow possible to query the client from the local state field?

```
resolvers: {
    Mutation: {
      filteredItems: (_root, variables, { cache, client }) => {
        const id = client.query({
          query: ITEMS
        });
```

Use case: I would like to filter the data, but before I do that, I would like to fetch all the data from `ITEMS` query (if it's still not added to cache), and only then filter this received data and return filtered data from the `filteredItems`.

Currently it goes into the endless loop if I call client query from the `filteredItems`

**Comment by 3nvi** [comment]
If it's in the cache, a simple `proxy.readQuery` would suffice. If it's not, I believe this is an `async` operation so you should `await` for it.

Not, 100% sure

**Comment by dmitry** [comment]
@3nvi I tried to use `await` on `client.query`, but it recursively loops without ending. Query default `fetchPolicy` option is `'network-only'`. Any idea how to run network query in the cache?

**Comment by 3nvi** [comment]
Hmmm.. I've never had to do it personally. Is there a chance to give us a reproduction environment (e.g. codesandbox)?

In any case, I would **personally** feel that logic like this could also exist in a link. You could chain this link and have it run & await your query before any `filteredItems ` operation. Adding this logic in a link will most likely resolve your problem. I understand though, that this doesn't mean that this issue should be closed, since it's unrelated to my suggestion
