### ISSUE TITLE
Running Mutation and Query in parallel and handling error and response

### ISSUE THREAD

**Issue by raghavgujjar** [apollographql/apollo-client#6049]
Have a query and mutation like this in my component,
```
const MUTATION1 = gql`mutation...`;
const QUERY1 = gql`query...`;
const [mutation, {loading: mutationLoading, error: mutationError, data: mutationData] = useMutation(MUTATION1);
useEffect(() => {
  const {loading: queryLoading, error: queryError, data: queryData} = useQuery(QUERY1, {variables: {}});
mutation({
   variables: {}
});
if (queryError) {
   console.log(queryError);
}
if (mutationError) {
   console.log(mutationError);
}
}, []);

```
I have to run them both in parallel when the component loads. My questions:
1. What is the best way?
2. When the component loads, I show a progress. The progress has to be removed once both completes. How can I do that? How do I know when both complete?
3. Even though the query/mutation returns an error, the `console.log` is not printing?

P.S. Little difficult to share entire code details. Hopefully, pseudo code would suffice.

**Comment by williamboman** [comment]
I'd recommend reading https://reactjs.org/docs/hooks-rules.html

So, first thing I wouldn't do is call `useQuery` inside the `useEffect` - this is probably what's causing most of your problems (read [rule of hooks](https://reactjs.org/docs/hooks-rules.html)).

What happens in my example👇 is that the both the mutation and query is executed once the component is mounted:
 - `useQuery()` - executes the query on mount by default, you can pass `{skip:true}` to disable this behaviour
 - `useMutation()` - by default returns a callback which, once called, will execute the mutation

We also set up different `useEffect` callbacks to be called whenever the hook dependencies change - we leverage this to a) decouple things, and b) make sure we `console.log` any errors as soon as they change.

```tsx
const MUTATION1 = gql`mutation...`;
const QUERY1 = gql`query...`;

const MyComponent = () => {
  const [mutation, {loading: mutationLoading, error: mutationError, data: mutationData}] = useMutation(MUTATION1);
  const {loading: queryLoading, error: queryError, data: queryData} = useQuery(QUERY1, {variables: {}});

  useEffect(() => {
    mutation({
       variables: {}
    });
  }, []);

  useEffect(() => {
    if (queryError) {
       console.log(queryError);
    }
  }, [queryError);

  useEffect(() => {
    if (mutationError) {
       console.log(mutationError);
    }
  }, [mutationError]);

  if (mutationLoading || queryLoading) { // to answer your 2. question
    return <Loading />
  }

  return <Something />
}
```

To answer 1) neither your mutation or query would have had time to resolve by the time your `if (queryError)` and `if (mutationError)` is executed because this effect is called as soon as the component is mounted. In my example above we instead set up two effects (pretty much callbacks) that will be executed whenever `queryError` or `mutationError` changes - this way we can decouple the actual execution of a query/mutation with its error handling.

**Comment by raghavgujjar** [comment]
@williamboman thank you so much for your response.  But, if I call the query outside of use effect at the top of the component,  and the component reren

**Comment by williamboman** [comment]
Nope! By default it will only run the query on mount. `useQuery()` returns a `const { refetch }` function which you can manually call to refetch it.

I believe the query will however be re-exexuted if `variables` change

**Comment by hwillson** [comment]
This was resolved by https://github.com/apollographql/apollo-client/issues/6049#issuecomment-598875690 - thanks!
