### ISSUE TITLE
MockedProvider with Enzyme shallow

### ISSUE THREAD

**Issue by jvanbaarsen** [apollographql/apollo-client#6129]
After spending a couple of days and looking all over the internet I'm starting to doubt what I'm doing wrong 🙈 

I'm trying to test a component that uses useQuery with Enzyme's Shallow rendering method:  https://github.com/jvanbaarsen/apollo-enzyme-test/blob/master/src/App.js#L17.

Somehow, whatever I try I keep getting the error that a client is not available and that I need to wrap my component in a ApolloProvider. I tried solving this by using a MockedProvider: https://github.com/jvanbaarsen/apollo-enzyme-test/blob/master/src/App.test.js#L19.

But no matter what I try, it just doesn't work with Shallow. When I try to use Mount it works, but I'd like to test a component in isolation as much as possible.

Is this something I'm doing wrong? Or just not support by apollo/react-hooks?

A full test repo can be found here: https://github.com/jvanbaarsen/apollo-enzyme-test

**Comment by freshollie** [comment]
Though it's not a solution to your problem (all the code looks correct to me, though I would probably say this is an enzyme issue), you should consider moving away from using shallow rendering: https://kentcdodds.com/blog/why-i-never-use-shallow-rendering

This will probably require a restructure of your app in order to modularise the pieces so that they can all be tested independently.

A good way to do this is to see your final "App" as a composition of different container components which each take their data from the Apollo state and represent it independently of each other, instead of having all your state funnelled down from a root component which becomes very problematic to test.
