### ISSUE TITLE
BUG: useLazyQuery will cancel previous inflight calls even in variables change

### ISSUE THREAD

**Issue by wuweiweiwu** [apollographql/apollo-client#6133]
**Intended outcome:**

- expected lazy queries in parallel with different variables will each trigger an `onComplete` or `onError`

**Actual outcome:**

- firing off lazy queries in parallel with different variables. found that only the last one trigged the `onCompleted` or `onError` callback

**How to reproduce the issue:**

https://codesandbox.io/s/jovial-darkness-11e5h?file=/src/App.js

you can see that `calling` is printed 3 times while `completed` is only called 1 time

**Versions**

```
 System:
    OS: macOS 10.15.4
  Binaries:
    Node: 12.15.0 - ~/.nvm/versions/node/v12.15.0/bin/node
    Yarn: 1.22.4 - ~/Desktop/nashi-client/node_modules/.bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.15.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 73.0.1
    Safari: 13.1
  npmPackages:
    @apollo/client: ^3.0.0-beta.41 => 3.0.0-beta.41
    @apollo/link-context: ^2.0.0-beta.3 => 2.0.0-beta.3
    @apollo/link-error: ^2.0.0-beta.3 => 2.0.0-beta.3
    apollo: ^2.25.0 => 2.25.0
```

**Comment by wuweiweiwu** [comment]
workaround is use `client.query` directly

**Comment by freshollie** [comment]
This is definitely not how `useLazyQuery` or any react hooks are supposed to be used. React hooks are always designed to have single input single output. The input state maps to the final output, so if the input changes, the previous output will never be emitted.

The whole point in react hooks is to prevent race conditions caused by doing stuff like this, using `client.query` is the correct and only way to achieve what you would like :)

**Comment by hwillson** [comment]
Answered by https://github.com/apollographql/apollo-client/issues/6133#issuecomment-611761188 and https://github.com/apollographql/apollo-client/issues/6133#issuecomment-611793980. Thanks!
