### ISSUE TITLE
ApolloClient setContext adding to Access-Control-Request-Headers

### ISSUE THREAD

**Issue by crimson-med** [apollographql/apollo-client#6171]
**Intended outcome:**
When setting authorization I should be able to see the authorization param filled in

**Actual outcome:**
it adds the key of my value to the `Access-Control-Request-Headers` instead

**How to reproduce the issue:**
```ts
import ApolloClient from 'apollo-boost';
import { ApolloProvider } from '@apollo/react-hooks';
import { ApolloProvider as ApolloHooksProvider } from 'react-apollo-hooks';
import App from './App';
import ReactDOM from 'react-dom';

const client = new ApolloClient({
    uri: process.env.REACT_APP_GRAPHQL,
    request: (operation) => {
        const token = localStorage.getItem('token')
        console.log(token);
        operation.setContext({
          headers: {
            authorization: token ? `Bearer ${token}` : ""
          }
        })
      }
  });

ReactDOM.render(
    <ApolloProvider client={client}>
    <ApolloHooksProvider client={client}>
            <App />
    </ApolloHooksProvider>
  </ApolloProvider>,
  document.getElementById('root'),
);
```

**Versions**
  System:
    OS: macOS Mojave 10.14
  Binaries:
    Node: 12.9.1 - /usr/local/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.13.0 - ~/.config/yarn/global/node_modules/.bin/npm
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 75.0
    Safari: 12.0
  apollo-boost: 0.4.7

**Screenshots:**
![Screenshot 2020-04-20 at 7 19 00 PM](https://user-images.githubusercontent.com/28290546/79746065-f54d1480-833b-11ea-857e-89c2ffcd386e.png)

**Additional Steps:** 
I have tried to change:
`authorization` to `test` and this just gives: `Access-Control-Request-Headers: test,content-type`

**Comment by AndTheDaysGoBy** [comment]
I'm just going to take a stab in the dark and assume you had the same issue as me. Is it possible that your issue is related to the following?:
The above is an OPTIONS request method, per https://www.w3.org/TR/cors/#preflight-request we see that the user credentials will be stripped. Thus, what's necessary is for OPTIONS requests to be able to be performed without authorization.
This would explain why it's in your `Access-Control-Request-Headers` because the implementation first populates that, and then, upon finding that it's an OPTIONs request, strips out the actual authorization header--thus the fragment.

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
