### ISSUE TITLE
Broken links to Error Policy

### ISSUE THREAD

**Issue by dandv** [apollographql/apollo-client#6234]
At https://www.apollographql.com/docs/react/api/apollo-client/, all 3 anchor links to [ErrorPolicy](https://www.apollographql.com/docs/react/api/apollo-client/#ErrorPolicy) are broken, and `ErrorPolicy` is not ultimately explained on the page.

**Comment by lexanth** [comment]
Same for `FetchPolicy` too

**Comment by lorensr** [comment]
Yes, FetchPolicy link here is broken:

![image](https://user-images.githubusercontent.com/251288/91111848-8c5e0c00-e64f-11ea-90d4-0e2ad666d288.png)

https://www.apollographql.com/docs/react/api/core/ApolloClient/#FetchPolicy

Also can't find definition by search: 

![image](https://user-images.githubusercontent.com/251288/91111821-78b2a580-e64f-11ea-99f5-bd840215522d.png)

**Comment by MrDoomBringer** [comment]
Hey all! 

Thanks for opening this issue. Looks like we've since removed those broken links. And just for posterity, here's the definitions for [FetchPolicy](https://www.apollographql.com/docs/react/data/queries/#setting-a-fetch-policy) and [ErrorPolicy](https://www.apollographql.com/docs/react/v2/data/error-handling/#error-policies).

I'll be closing this issue shortly - let me know if there are any other questions or if we should keep this open. Thanks!

All the best,
Emmanuel, Intern :)
