### ISSUE TITLE
Expose jsdocs on final bundle

### ISSUE THREAD

**Issue by weslleyaraujo** [apollographql/apollo-client#6267]
Hi there 👋

I noticed that some of the jsdocs are getting lost on the final bundle (Eg. `apollo-client/core/networkStatus.d.ts`)

I see that there are very well explained jsdocs on this file here: https://github.com/apollographql/apollo-client/blob/master/src/core/networkStatus.ts

Would expect that to show up on VSCode as shown below:
<img width="1155" alt="Screenshot 2020-05-11 at 17 11 27" src="https://user-images.githubusercontent.com/2286385/81578480-2785eb00-93ab-11ea-99a7-b8bce74692e9.png">

I am on version 2.6.8, not sure if this was already fixed

**Comment by hwillson** [comment]
Thanks for letting us know - we'll look into this post the 3.0 launch.

**Comment by manindr** [comment]
@weslleyaraujo I debugged it a bit and found out that jsdocs are being stripped because the `removeComments` option is set to true in `tsconfig.json`. 
Check here: https://github.com/apollographql/apollo-client/blob/ed7c5bb67129dbb2db693f9c3dbf582804a14bb3/tsconfig.json#L10

Now i don't think there's a way to remove comments in final bundle and keep the jsdocs in declaration file at same time.
See this issue on typescript: https://github.com/microsoft/TypeScript/issues/14619

@hwillson One way i can think of doing this is to don't remove comments in typescript build process but instead do the same in minify/uglify step. Not sure if that's a good solution but i could think of just this approach for now.

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
