### ISSUE TITLE
fetchMore doesn't set loading to true (beta.52)

### ISSUE THREAD

**Issue by mschipperheyn** [apollographql/apollo-client#6354]
**Intended outcome:**

When calling `fetchMore`, loading should be set to true.

**Actual outcome:**

It remains false and the data loads without this status ever changing, even though `notifyOnNetworkStatusChange: true` has been set on the `useQuery`

**How to reproduce the issue:**

Nothing special here:

```
const { loading, refetch, fetchMore, error, data } = useQuery(qry, {
    key: dataKey,
    variables,
    partialRefetch,
    notifyOnNetworkStatusChange: true,
    onCompleted: data => {
        if (data[dataKey].totalCount) {
            setTotalCount(data[dataKey].totalCount);
        }
    },
});
const loadMore = React.useCallback(
    (options = {}, loadOnTop = false) =>
        fetchMore({
            updateQuery: (previousResult, { fetchMoreResult, variables }) => {
                onUpdateQuery(loadOnTop);
                [...]
                return {
                    ...first,
                    ...last[dataKey],
                };
            },
            ...options,
        })
            .then(onLoadMore)
            .catch(onLoadMoreError),
    [onLoadMore, onLoadMoreError],
);
```
**Versions**
  Apollo client beta.52
  System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.1/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Safari: 13.1.1

**Comment by SeyedAlirezaFatemi** [comment]
I'm experiencing the same problem with Apollo client 3.0.0-rc.1. Calling refetch when using lazy query, doesn't set loading to true.

**Comment by tpict** [comment]
Also happening in `rc.4`

**Comment by damien-monni** [comment]
Happening in rc.6

**Comment by mschipperheyn** [comment]
I'm noting as well that https://github.com/apollographql/apollo-client/blob/master/src/__tests__/fetchMore.ts does not contain a test for `loading` being set to `true` when `fetchMore` is called.

**Comment by danifujii** [comment]
Happening in `rc.9`

**Comment by hatchli** [comment]
Happening in rc.10

**Comment by benjamn** [comment]
Fix incoming: #6583

**Comment by DanielMarkiel** [comment]
@benjamn I'm experiencing this issue  using `"@apollo/client": "3.0.2"`. Is it fixed for good?

**Comment by benjamn** [comment]
@DanielMarkiel Are you setting `notifyOnNetworkStatusChange: true`?

**Comment by DanielMarkiel** [comment]
@benjamn Yes sir. It worked perfectly before migration to v3. Downgrade to v`3.0.0` didn't help. 
I keep investigating what might be happening.

**Comment by DanielMarkiel** [comment]
@benjamn FYI, I found the reason for my problem.
In our app we've been calling fetchMore like this: 
```
      fetchMore({
        query: GQL_QUERY,
        variables: {
          ...variables,
          cursor,
        },
      });
```
When I removed `query: GQL_QUERY,` the loading state started to update correctly.
I believe the reason is the line (condition) below:
`...(fetchMoreOptions.query ? fetchMoreOptions : {` (src/core/ObservableQuery.ts)

Of course we were unnecessarily setting the `query` option, but since it worked in v2 I think it's an undescribed breaking change that is worth adding to the migration guide.

**Comment by onderonur** [comment]
> @benjamn FYI, I found the reason for my problem.
> In our app we've been calling fetchMore like this:
> 
> ```
>       fetchMore({
>         query: GQL_QUERY,
>         variables: {
>           ...variables,
>           cursor,
>         },
>       });
> ```
> 
> When I removed `query: GQL_QUERY,` the loading state started to update correctly.
> I believe the reason is the line (condition) below:
> `...(fetchMoreOptions.query ? fetchMoreOptions : {` (src/core/ObservableQuery.ts)
> 
> Of course we were unnecessarily setting the `query` option, but since it worked in v2 I think it's an undescribed breaking change that is worth adding to the migration guide.

This! I was looking for what is wrong with my infinite loaders and you saved my day!
And yes, settings that `query` is unnecessary. But I think, if we shouldn't add it and if it breaks things, it would be better that it's documented and removed from the TypeScript definitions etc. But if there are any use cases for it, it depends of course.

Apollo is a great tool and I know they put a lot of work into version 3. I hope these kind of little bugs will be fixed in near future and we will be amazed by the quality of Apollo. 

Thanks!

**Comment by kelly-tock** [comment]
> @DanielMarkiel Are you setting `notifyOnNetworkStatusChange: true`?

Setting this in my query worked when I did fetchMore, but not without this set.
