### ISSUE TITLE
relayStylePagination pageInfo not overwritten

### ISSUE THREAD

**Issue by Boshen** [apollographql/apollo-client#6649]
@benjamn benjamn

https://github.com/apollographql/apollo-client/blob/master/src/utilities/policies/pagination.ts#L115-L120

```js
      const pageInfo = {
        ...incoming.pageInfo,
        ...existing.pageInfo,
        startCursor: cursorFromEdge(edges, 0),
        endCursor: cursorFromEdge(edges, -1),
      };
```

I believe you meant

```js
      const pageInfo = {
        ...existing.pageInfo,
        ...incoming.pageInfo, // incoming should override existing
        startCursor: cursorFromEdge(edges, 0),
        endCursor: cursorFromEdge(edges, -1),
      };
```

**Comment by Boshen** [comment]
ping @benjamn

**Comment by benjamn** [comment]
I agree this logic is faulty, but my original reasoning for the counter-intuitive ordering of the `...spread`s was that `incoming.pageInfo.has{Next,Previous}Page` should _not_ overwrite the existing values, since the existing data represents the whole range of data received so far, whereas the incoming data is just a single page.

For example, in many cases (forward-only pagination from the beginning of the list), `existing.pageInfo.hasPreviousPage` will start out `false` and should remain `false` forever, even though `incoming.pageInfo.hasPreviousPage` will be `true` whenever fetching subsequent pages. Simply inverting the order of the `...spread`s gets this wrong, so I think we need a more sophisticated solution here.

**Comment by benjamn** [comment]
@Boshen Can you clarify what problems you observed due to the way this was written? Are you using any non-standard fields in your `pageInfo` objects?

**Comment by Boshen** [comment]
> Are you using any non-standard fields in your pageInfo objects?

Ahh ... I just took a look at the relay spec and your code again, 
I was returning `hasPrevPage` instead of `hasPreviousPage`, since some blogs used `hasPrevPage`.

And you corrected `hasPreviousPage` with `updatePageInfo("hasPreviousPage")` a few lines below.

Thanks for the help, cheers.
