### ISSUE TITLE
Integrate apollo-link-logger in @apollo/client package

### ISSUE THREAD

**Issue by saadaouad** [apollographql/apollo-client#6667]
First I want to thank you for this great package. 

I'm using [apollo-link-logger](https://github.com/blackxored/apollo-link-logger) and this requires [apollo-link](https://github.com/apollographql/apollo-link) package:
```shell
6:44:18 PM: ./node_modules/apollo-link-logger/es/index.js
6:44:18 PM: Cannot find module: 'apollo-link'. Make sure this package is installed.
6:44:18 PM: You can install this package by running: yarn add apollo-link.
6:44:18 PM: error Command failed with exit code 1.
``` 

I'd like to know if it's possible to integrate `apollo-link-logger` in `@apollo/client` package?

**Comment by benjamn** [comment]
My other comment mostly applies here as well: https://github.com/apollographql/apollo-client/issues/6671#issuecomment-662502335

In this case, I believe `apollo-link-logger` should release a new minor (or possibly major) version that requires `@apollo/client` v3, and imports `ApolloLink` from `@apollo/client`. As a technical note, I would suggest waiting for `@apollo/client@3.1.0` and requiring that version, because of #6656.

**Comment by saadaouad** [comment]
You're right @benjamn, `apollo-link-logger` core team should create a new release that requires `@apollo/client` v3.
I think it will be a minor changes, since `ApolloLink ` is only imported on this file https://github.com/blackxored/apollo-link-logger/blob/master/src/index.js

**Comment by acomito** [comment]
Not sure they're going to take that up: https://github.com/blackxored/apollo-link-logger/issues/54

**Comment by saadaouad** [comment]
This should resolve the problem https://github.com/blackxored/apollo-link-logger/pull/55 @acomito
