### ISSUE TITLE
Integrate apollo-upload-client in @apollo/client package

### ISSUE THREAD

**Issue by saadaouad** [apollographql/apollo-client#6671]
I'd like to know if it's possible to integrate [apollo-upload-client](https://github.com/jaydenseric/apollo-upload-client) in @apollo/client package?

**Comment by benjamn** [comment]
I really don't think this is something the maintainers of `apollo-upload-client` would want, since it would tie their release schedule and versioning to that of `@apollo/client`, and require PRs against this repo to make any changes. Additionally, the Apollo Client core team is just three people, so we don't currently have bandwidth to support more `@apollo/client/*` sub-packages than we already do. The `@apollo/client/react/*` and `@apollo/client/link/*` packages are already pushing it (though I appreciate your implied confidence in our abilities!), so we will need to let the dust settle on those (see #6656) before we consider adding any more.

**Comment by mschipperheyn** [comment]
Also, this adds packages size for people who might not even use it. I would personally recommend avoiding server uploads and instead use direct to S3 / Azure style uploads using your server only as an intermediary to get an upload token. So you can upload directly and not deal with all the challenges associated with processing upload streams. And your Graphql can just provide you with a standard mutation to get the upload token.

**Comment by saadaouad** [comment]
> I really don't think this is something the maintainers of `apollo-upload-client` would want, since it would tie their release schedule and versioning to that of `@apollo/client`, and require PRs against this repo to make any changes. Additionally, the Apollo Client core team is just three people, so we don't currently have bandwidth to support more `@apollo/client/*` sub-packages than we already do. The `@apollo/client/react/*` and `@apollo/client/link/*` packages are already pushing it (though I appreciate your implied confidence in our abilities!). I think we need to let the dust settle on those (see #6656) before we consider adding any more.

I see what do you mean @benjamn. 
To be honest I think it would be great to handle `multipart/form-data` request sending using `@apollo/client` in the future... happy to help on that.

**Comment by acomito** [comment]
Also bummed out to hear we can't handle files in 3.0...
