### ISSUE TITLE
TypeError: Cannot set property 'getFragmentDoc' of undefined

### ISSUE THREAD

**Issue by theneshofficial** [apollographql/apollo-client#6678]
I'm trying out Apollo Client 3 with create-react-app. I'm getting the error below. Not sure what am I doing wrong.

### Index.js
![Screenshot 2020-07-23 at 4 28 37 PM](https://user-images.githubusercontent.com/45613977/88267754-dd52ab80-cd03-11ea-8007-660198b8d6c1.png)

### App.js
![Screenshot 2020-07-23 at 4 28 11 PM](https://user-images.githubusercontent.com/45613977/88267798-ee9bb800-cd03-11ea-9df9-293720a3b27f.png)

**Actual outcome:**
<img width="1047" alt="Screenshot 2020-07-23 at 4 27 30 PM" src="https://user-images.githubusercontent.com/45613977/88267819-f9eee380-cd03-11ea-86b6-7eb943bd7361.png">

**Versions**

```  
System:
    OS: macOS 10.15.6
Binaries:
    Node: 14.5.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
Browsers:
    Chrome: 81.0.4044.138
    Safari: 13.1.2
npmPackages:
    @apollo/client: ^3.0.2 => 3.0.2 
```

**Comment by phvinayak017** [comment]
Can someone tell me what is the reason for this error?

**Comment by invilliaanajacobsen** [comment]
Same problem here

**Comment by theneshofficial** [comment]
> Can someone tell me what is the reason for this error?

The inmemorycache should be instantiated with "new" keyword.

**Comment by benjamn** [comment]
Confirming @theneshofficial's answer (use `new InMemoryCache()`).

In strict mode, if you call a constructor function without `new`, `this` will be undefined. If you're using native `class` syntax rather than transpiling, constructor functions will throw an exception if you call them without using `new`, which helps prevent this problem, but most people are still transpiling `class` to `function` to support older browsers.

**Comment by Tommy15101** [comment]
> > Can someone tell me what is the reason for this error?
> 
> The inmemorycache should be instantiated with "new" keyword.

Legend! Something so simple lol.. Thanks bro

**Comment by tromesh-chalodiya** [comment]
Hey Folks, I've recently ran into this error and I checked the react and react-dom version I have installed which are respectively ^18.1.0 for both. Since creating a root for our document through reactdom and separate it out from strict mode can create a difference. 

I was new to configure the apolloclient with react and faced below error 

**cache.ts:141 Uncaught TypeError: Cannot set properties of undefined (setting 'getFragmentDoc')
    at ApolloCache (cache.ts:141:1)
    at InMemoryCache (inMemoryCache.ts:58:1)
    at Module../src/index.js (index.js:10:1)
    at Module.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at startup:7:1
    at startup:7:1**
    
    and I have updated index.js with below 
    
 const client = new ApolloClient({
  uri: '',
  cache: new InMemoryCache(),
});

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <ApolloProvider client={client}>
      <App />
    </ApolloProvider>
  </React.StrictMode>
);
