### ISSUE TITLE
Fetch more with merge policy existing data comes undefined or previous incoming data with duplicates.

### ISSUE THREAD

**Issue by ErkinKurt** [apollographql/apollo-client#6729]
**Intended outcome:**
I'm not sure that I totally understood the merge vs updateQuery but here is the case:
When I use merge  field policy and fetch more in the same time, I expected to see that data populates with new ones. 

**Actual outcome:**
I have the people array as I do the first request via useQuery and the data populates with the expected data. However when I do fetchMore, here is what happens: 
I do fetch more, new data comes as incoming, however my existing data is undefined which is I think odd because I already have the data and showing in the UI. As you can see:

![image](https://user-images.githubusercontent.com/26188297/88803043-9279dd80-d1b4-11ea-9936-d2c537710bad.png)
![image](https://user-images.githubusercontent.com/26188297/88803355-ff8d7300-d1b4-11ea-8bac-95fe73c30fdd.png)

If I do fetchMore one more time, this time the existing will be filled with the previous incoming data but not the one that is already showing. And it will concatenate the prev with the incoming and the duplicate data will populate forever. But there will be no change in the UI at all. 
![image](https://user-images.githubusercontent.com/26188297/88803282-e8e71c00-d1b4-11ea-9ea7-111990e66ec9.png)

When I provide read field policy it will fetchMore as expected and I can see existing data in merge but then when the filterType changes, I can't even get the new data and only read is triggered with the existing data. By using updateQuery inside fetchMore I don't see any of the issues and it works as expected. 

**How to reproduce the issue:**

Reporduce repo: 
https://github.com/ErkinKurt/react-apollo-error-template

You can change status type and it will change the data that's shown but when you press load more you will get nothing. As I tried to explain above, you can uncomment read field policy and see what happens. Thanks for your hard work. 

**Versions**
```
System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 12.16.2
    Yarn: 1.22.4 
    npm: 6.14.4
  Browsers:
    Chrome: 84.0.4147.105
    Edge: Spartan (44.18362.449.0)
```

**Comment by benjamn** [comment]
You're very close to the solution, but there's one more piece that's worth understanding.

The cache can't make any assumptions about the meaning of your field arguments (`filterType` and `pageNumber`), so by default it stores data received for the `people` field separately whenever the arguments are different. Since your `fetchMore` query has different argument values than the original query, those two `people` results get stored separately, which is why `existing` is undefined in the `merge` function—no data exists for those new arguments.

While this is reasonable default strategy (in the absence of better information), it's often not a very good strategy, especially since `fetchMore` is intended to grow the original array, rather than storing its result separately. For cases like this, you can control which arguments the cache considers relevant for storage using the [`keyArgs`](https://www.apollographql.com/docs/react/caching/cache-field-behavior/#specifying-key-arguments) configuration. Options include `keyArgs: ["filterType"]`, `keyArgs: ["pageNumber"]`, `keyArgs: ["filterType", "pageNumber"]` (this is the default behavior), and `keyArgs: false`.

Since you probably want there to be only one array, regardless of the arguments, the most appropriate setting is `keyFields: false`, which tells the cache to store the `people` data using a property like `people: [...]`, rather than something like `'people:({"filterType":...,"pageNumber":...})': [...]`. This ensures there's only ever one array, and it works because your `merge` (and `read`) functions have a chance to examine `options.args` to interpret the arguments however you like. If you wanted to keep separate lists according to `filterType`, you could use `keyArgs: ["filterType"]` instead.

One additional subtlety: when you define both a `merge` function and `read` function for a field, the cache assumes those functions will take responsibility for interpreting the arguments, so `keyArgs: false` is assumed by default (though you can override it explicitly). For more background on this behavior, see #5680 and #5862. That's why you noticed (correctly) that adding a simple `read` function fixed the problem. However, if you want to have only a `merge` function, you need to specify `keyArgs: false` yourself. Sorry this policy wasn't better documented!

For comparison, our [`concatPagination`](https://github.com/apollographql/apollo-client/blob/master/src/utilities/policies/pagination.ts) helper exported by `@apollo/client/utilities` uses a `keyArgs` configuration that defaults to `false`:
```ts
export function concatPagination<T = Reference>(
  keyArgs: KeyArgs = false,
): FieldPolicy<T[]> {
  return {
    keyArgs,
    merge(existing, incoming) {
      return existing ? [
        ...existing,
        ...incoming,
      ] : incoming;
    },
  };
}
```

If you wanted to use this helper, your code could look like this:
```ts
import { concatPagination } from "@apollo/client/utilities"

const cache = new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        filterId: {
          read() {
            return filterIdVar();
          }
        },
        people: concatPagination(),
      }
    }
  }
})
```
However, even with a helper function available, I think it's useful to understand what's going on behind the scenes.

As one final note, it may be tempting to define a `read` function to go along with your `merge` function, but we've found that `read` functions are often unnecessary when using `fetchMore`, and can complicate things because you have to update the variables for the original query to match the new longer list. With no `read` function and `keyArgs: false`, the list just keeps growing, and you don't have to worry about updating the original query.

I know that's a whole lot of information, but thanks for reading, and thanks for providing a reproduction that made it easy to see exactly what was going on!

**Comment by ErkinKurt** [comment]
Perfect explanation, thank you! For the feature comers, I recommend [this ](https://www.youtube.com/watch?v=n_j8QckQN5I&feature=youtu.be&t=1789) video which helped me to digest the explanation and give more insight about ApolloClient v3.

**Comment by joebernard** [comment]
@benjamn In your explanation above you mention usage of `keyFields` instead of `keyArgs`. Is that a typo?

**Comment by benjamn** [comment]
@joebernard Yes, that was a typo. In this case, I should have only been talking about `keyArgs`. Thanks for pointing that out!

**Comment by TanBeige** [comment]
This thread has solved a lot of problems for me, but one is still left open. 

What if we have 2 different queries that call on the same field (ex: All Users and Only Known Users) where one field calls a fetchMore (All Users) and the other doesn't (Known Users, this just calls users with a different sort). In my case, using KayArgs=false makes it so that it returns the All Users query correctly (with a fetchMore) but it gets called for every query that uses the field users. So whenever I want to view Known Users it brings back the query All Users instead. Removing KeyArgs should fix the problem, both queries show up, except the fetchMore doesn't concatenate a list because my merge function's existing variable returns as undefined (just like issue [#6729](https://github.com/apollographql/apollo-client/issues/6729)). What can I do to be able to call 2 separate queries as well as a fetchMore for only one of them?

**Comment by valeriagrazzini** [comment]
@TanBeige I have the same problem. Same query called with and without fetchmore

**Comment by yairopro** [comment]
For those who will pass by this issue, even after defining the `keyArgs` I still got the `existing = undefined` problem.

My graphQL request was like
```graphql
	query ReservationsList($id: Int!, $offset: Int = 0) {
		user(where: {id: {_eq: $id}}) {
			name
			reservations(
				where: {
					#...
				},
				order_by: {time: asc}, 
				limit: 30, 
				offset: $offset
			) {
				id
				time
				numberOfPlaces
			}
		}
	}
```

It's tricky because here my mistake was that the `user` parent object didn't include its own `id` field request, so Apollo didn't even merge the `fetchMore`'s `user` object with the original. 

The solution was quite simple to set (still hard to identify):
```graphql
	query ReservationsList($id: Int!, $offset: Int = 0) {
		user(where: {id: {_eq: $id}}) {
			id  # <- set the id to help Apollo identify the parent object of the list
			name
			reservations(
				#...
			) {
				#...
			}
		}
	}
```

**Comment by defel** [comment]
After "debugging" my code for the last 2 hours, and read the very well written docs this way, installed the `apollo-client-devtools`, tried out various variantes of `merge` and `read` and wondering why always `existing` is undefined, while there are data in the cache (the data is there, I can see them) .. make sure that you did not mixed up `refetch` and `fetchMore` :facepalm:
