### ISSUE TITLE
How should I import WebSocketLink ?

### ISSUE THREAD

**Issue by ArnaudBarre** [apollographql/apollo-client#6732]
In beta, I was importing it from `@apollo/link-ws": "^2.0.0-beta.3"` and it was working find. 

In 3.1.1, I got a typing issue, because ApolloLink from `@apollo/link-ws` ->` apollo-link-ws` does not match the one from `@apollo/client`.  

I can get it work by importing from `"@apollo/client/link/ws"`.

Is a re-export missing somewhere ?

**Comment by benjamn** [comment]
This _should_ work (although it was improved in v3.1.0 by #6656):
```ts
import { WebSocketLink } from "@apollo/client/link/ws"
```
However, you will probably want to avoid using `@apollo/link-ws` or `apollo-link-ws` at the same time.

Happy to answer follow-up questions, of course.

**Comment by ArnaudBarre** [comment]
Is it to simplify work of tree shaking that we cannot do `import { WebSocketLink } from "@apollo/client"` ?

**Comment by benjamn** [comment]
It's also to avoid cluttering the available top-level imports, and to avoid importing the entire library when using CommonJS (which Node.js still does in most cases). Any use of `@apollo/client` without a bundler benefits from having narrowly-scoped entry points for optional parts of the library, because there's no opportunity for tree-shaking without a bundler like Rollup or Webpack.
