### ISSUE TITLE
Query with optional variables

### ISSUE THREAD

**Issue by spencerpauly** [apollographql/apollo-client#6737]
Hello, so maybe it's just me but I'm having trouble understanding the logic with querying when I want variables to have the potential to be optional. 

So I want my component to be able to function like the code snippet below. I want to have an optional parameter in the query variable. So that "id" variable can either be string or undefined. If it's a string it should do the query and if it's undefined I want the cached query data to be reset, or basically like instead of a skip clause on the query I would just want a query that "pretends" to go get the data when undefined is the variable but actually just returns an empty data object. Why doesn't it function like this? Am I thinking about a piece of this fundamentally wrong?:

```
gql`
	query ProfileImageDetails($id: uuid!) {
		user(id: $id) {
			photoURL
		}
	}
`;

interface Props {
	userId: string | undefined;
}

const ProfileHeader: React.FC<Props> = ({ userId }) => {
	const { data, loading, error } = useProfileImageDetailsQuery({
		variables: { id: userId },
	});

	if (error) return <ApolloErrorHandler error={error} />;
	if (loading) return <SkeletonSpinner />;

	return <ProfileHeader photoURL={data.photoURL || DEFAULT_PHOTO_URL_CONST} />;
};

export default ProfileHeader;
```

I feel like I'm thinking about this wrong, but I'm running into this type of issue many places. Let me know what I should be doing instead! Thanks.

**Comment by 3nvi** [comment]
You  can add do:

```jsx
const shouldQuery =  userId !== undefined
const { data, loading, error } = useProfileImageDetailsQuery({
		variables: { id: userId },
                skip: !shouldQuery
	});

// ...


return <ProfileHeader photoURL={shouldQuery ? data.photoURL : DEFAULT_PHOTO_URL_CONST} />;
```

Alternatively you can add a [read policy](https://www.apollographql.com/docs/react/caching/cache-field-behavior/#the-read-function) on the query results and do any "custom modification"  you  want depending on the variables passed to the query.


In any case, I feel that all  this should be outside of  Apollo, but if you want the cache to "clean" based  on the variable, you can also call `cache.evict(...)`  (you have  to import  the cache  instance) within a `React.useEffect`.

Lastly, I believe that  this  shouldn't be an issue  in the Apollo client,  but a question on spectrum or discord, since questions are outside the scope of issues and Apollo already has a lot of  open issues  :D

**Comment by spencerpauly** [comment]
Yes this makes sense. Thanks for answering!
