### ISSUE TITLE
Way to know at what stage is the polling ?

### ISSUE THREAD

**Issue by laurent-brisbois** [apollographql/apollo-client#6738]
I'm currently using a query with the polling option and there isn't any problem with that.
The thing is that I display some sort of progress bar which is supposed to be synchronized with the polling timer.
The problem is that as things progress, it gets unsynchronized over time.

Is there a way to know at which stage the polling is ?

I mean if it is supposed to poll every 10 seconds, a meta data should say : i'm at second 7.

I imagine something like : `this.$apollo.queries.<queryName>.pollingStatus` or whatever.

I didn't find anything about that.

**Comment by 3nvi** [comment]
There isn't,  but you can easily implement  it  yourself.

Every time the query executes,  you can modify a  `React.useRef` instance within a  `React.useEffect` or the `onCompleted` callback of the `useQuery`. If you need this is multiple places, you can wrap a custom hook around apollo's `useQuery` to always have it available.

Because this is not currently present, you can create a ticket at the [feature requests repo](https://github.com/apollographql/apollo-feature-requests/), but I **personally** feel that this  should not be an issue in the apollo client repo (this repo has already too many open issues)

**Comment by laurent-brisbois** [comment]
Thanks for your hints.
I finally ended up by removing the polling option and use a custom setInterval that calls a refetch() on the query.
However it would be nice to have some sort of built-in mechanism.

**Comment by laurent-brisbois** [comment]
> There isn't, but you can easily implement it yourself.
> 
> Every time the query executes, you can modify a `React.useRef` instance within a `React.useEffect` or the `onCompleted` callback of the `useQuery`. If you need this is multiple places, you can wrap a custom hook around apollo's `useQuery` to always have it available.
> 
> Because this is not currently present, you can create a ticket at the [feature requests repo](https://github.com/apollographql/apollo-feature-requests/), but I **personally** feel that this should not be an issue in the apollo client repo (this repo has already too many open issues)
