### ISSUE TITLE
writeFragment doesn't update objects with extended types

### ISSUE THREAD

**Issue by geiszla** [apollographql/apollo-client#6739]
**Intended outcome:**

Update fragments of all objects with specific id (see exact scenario below).

**Actual outcome:**

`writeFragment` only updated one of the objects with the given id.

**How to reproduce the issue:**

I have two queries, which return objects with two different types extended from one original one. One of the queries is `user({ username: 'name-of-user' })`, which returns an object with type `User`, then the other is the `self` query, which returns an object with type `Self`, which has some extra properties on it. Both of these types are extended from `UserInterface` and this is the type the fragment is defined on.

When I use `writeFragment` to update the data using the fragment and the id (which is the same on both objects), only the `self` query updates in the cache and not `user`.

I tried to specify the id as `UserInterface:<id>` and also as just simply `<id>`. I also tried to manually add `__typename` to the data used to update the cache, but neither of them worked.

**Versions**

```
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 10.22.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Google Chrome Dev: 86.0.4214.2
```

apollo-client: `2.6.10`
apollo-boost: `0.4.9`
react: `16.13.1`

**Edit**: It seems like the update of `self` query is done automatically when the mutation returns and `writeFragment` does nothing. What I understand this is because it doesn't recognize `UserInterface` as the basetype of `Self` and `User`. Is there a way to specify this so that I can update the cache for both types once?

**Comment by benjamn** [comment]
I think you'll have to share a [reproduction](https://github.com/apollographql/apollo-client/blob/master/CONTRIBUTING.md#reporting-bugs) if you want concrete guidance here (and also please include the versions of `@apollo/client` and any other relevant npm packages you're using!).

Cache IDs are expected to be uniquely identifying (for a particular type, since the `__typename` is usually included in the ID), so the idea that you would have two logically different objects with the same ID suggests that you're not meeting this expectation? Generally speaking, whenever the client receives different result objects with the same ID, the objects' fields will be merged together in the cache, because those result objects are considered to be different views of the same logical entity. If that's not the case here, then you need to find a way to keep the IDs of these objects distinct.

**Comment by geiszla** [comment]
@benjamn 
Thanks for your answer. I included the npm package versions in the OP.

The two objects are logically the same, they just include different amount of information from the original object on the server (e.g. `Self` includes email address, while `User` doesn't, so it's not returned when sending data about a user). They should include the same value for each common property.

Do I use extended types wrong? As I understand if an object has a type, which extends an interface, it is also of that type (at least this is the standard interpretation in other programming languages). So if I update a fragment on a type, shouldn't all objects with that type and with all base types of that type should update (if the `_id` or `id` matches)? That would be the intuitive way for me.

> Generally speaking, whenever the client receives different result objects with the same ID, the objects' fields will be merged together in the cache

Does that ID include the type? Because that could be a problem here if extendedness of types are not checked.

**Comment by geiszla** [comment]
Update: I migrated to Apollo v3 and added `possibleTypes` as follows:

```ts
const apolloCache = new InMemoryCache({
  possibleTypes: {
    UserInterface: ['User', 'Self'],
  },
});
```

This fixed my issue.
