### ISSUE TITLE
Passing access token to connectionParams in options of WebSocketLink constructor isn't working for authentication.

### ISSUE THREAD

**Issue by proIT324** [apollographql/apollo-client#6782]
By Apollo GraphQL's official doc, Apollo Client 3.0 supports authentication of WebSocket for its subscriptions. Subscriptions should be authenticated by a secure token in many cases. It was the same to me. I followed the latest doc of authentication over WebSocket of Apollo Client([here][1]). 

Doc:

[![enter image description here][2]][2]

My code:

    import { WebSocketLink } from '@apollo/client/link/ws';
    
    const wsLink = new WebSocketLink({
      uri: `${process.env.REACT_APP_WS_API}/graphql/`,
      options: {
        reconnect: true,
        connectionParams: {
          authToken: `${localStorage.getItem('access_token')}`
        }
      }
    })

Unfortunately, this authentication doesn't work at all. `graphql_jwt.exceptions.PermissionDenied` error occurred in my `Django` backend and no `authToken` value was read by the backend. I've attached a screenshot of the exception below.

[![enter image description here][3]][3]

Is there any valid solution to pass a secure token to `WebSocketLink`? 

  [1]: https://www.apollographql.com/docs/react/data/subscriptions/
  [2]: https://i.stack.imgur.com/asSbq.png
  [3]: https://i.stack.imgur.com/Iz0Od.png

Stackoverflow: https://stackoverflow.com/questions/63253201/how-does-websocketclient-pass-authentication-token-in-apollo-client-3-0

**Comment by benjamn** [comment]
If your backend is expecting the token via headers, `WebSocketLink` may not work for you, because it sends the `connectionParams` as the `payload` property of a message over the `WebSocket` ([see code](https://github.com/apollographql/subscriptions-transport-ws/blob/e25d67ff9bcbdf9dc39cb8ddbbd0e75853252f1d/src/client.ts#L558-L559)). To make it work, your backend would have to wait for the `GQL_CONNECTION_INIT` message to get the token.

If that's not an option, I would be interested in seeing how you'd create/connect a `WebSocket` without using `WebSocketLink` or `subscriptions-transport-ws`, so we can consider adding header-passing functionality to those libraries.

**Comment by AdrienLemaire** [comment]
your connectParams should also be a callback, else the localStorage is read at built time
```ts
import { WebSocketLink } from '@apollo/client/link/ws';

const wsLink = new WebSocketLink({
  uri: `${process.env.REACT_APP_WS_API}/graphql/`,
  options: {
    reconnect: true,
    connectionParams: () => ({
      authToken: `${localStorage.getItem('access_token')}`
    }),
  }
})
```

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
