### ISSUE TITLE
useQuery SSR: false doesn't run on client

### ISSUE THREAD

**Issue by stevez86** [apollographql/apollo-client#6912]
This issue is reported on other repos but since the react functionality is now included in this repo and I didn't see it reported I wanted to create the issue to track it.

The issue:
I'm using nextjs (latest ~9.5) and the apollo example (using latest apollo client)
When ssr: false in useQuery the query is not loaded on the client

I would expect the query to be called on the client

Here are past issues about it:
https://github.com/apollographql/react-apollo/issues/3418
https://github.com/apollographql/react-apollo/issues/4003

**Comment by maapteh** [comment]
I think its your setup :)
I validated it with client version 2 and 3 and both execute on the client with ssr: false
See https://github.com/maapteh/sandbox-react-apollo-issues-3918 this has two versions you can play with the options

Most people make the error here:
https://github.com/apollographql/react-apollo/issues/3500#issuecomment-629726717

I know for sure it works correctly because i started the above issue, where it executed ssr: false twice on server and client and after the fix only on the client.

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
