### ISSUE TITLE
RetryLink no retrying with @apollo/client version 3.1.3

### ISSUE THREAD

**Issue by KarelVerschraegen** [apollographql/apollo-client#6920]
**Intended outcome:**
`RetryLink` from `@apollo/client/link/retry` should retry the request when an error is thrown. `RetryLink` is used in combination with `onError` from `@apollo/client/link/error`. The error is caught by `onError` but `RetryLink` does not retry the operation.

**Actual outcome:**
The error is caught by `onError` but `RetryLink` does not retry the operation. The error is also caught in the `const { error } = useQuery()` hook.

**How to reproduce the issue:**
1. Go to https://codesandbox.io/s/pedantic-sun-wrotv?file=/src/App.js
2. See that an error is thrown, but not retried.

This example uses [https://rickandmortyapi.com/](https://rickandmortyapi.com/graphql/) as example.

**Versions**

  System:
    OS: Linux 5.8 Arch Linux
  Binaries:
    Node: 14.6.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Firefox: 80.0
  npmPackages:
    @apollo/client: ^3.1.3 => 3.1.3 
    @apollo/react-hooks: ^4.0.0 => 4.0.0

**Comment by maxim-isakov-ross** [comment]
I'm having the same problem

**Comment by vinverdy** [comment]
the issue is because, graphQLErrors not handled by RetryLink unlike [ErrorLink](https://github.com/apollographql/apollo-client/blob/master/src/link/error/index.ts#L39)

should we add graphQLError and networkError to align the api with errorlink? i will submit PR if needed. thanks

**Comment by vinverdy** [comment]
```ts
private try() {
    this.currentSubscription = new Observable(observer => {
      let onRetry = false;
      const sub = this.nextLink(this.operation).subscribe({
          next: async result => {
            if(!result.errors) {
              observer.next(result);
              return;
            }

            onRetry = true;
            this.retryCount += 1;

            const shouldRetry = await this.retryIf(
              this.retryCount,
              this.operation,
              result.errors,
            );

            if (shouldRetry) {
              this.scheduleRetry(this.delayFor(this.retryCount, this.operation, result.errors));
            } else {
              observer.next(result);
              observer.complete();
            }
          },
          error: observer.error,
          complete: () => {
            if (!onRetry) observer.complete.bind(observer)()
          },
        })

        return () => {
          if(sub) sub.unsubscribe();
        }
      }
    ).subscribe({
      next: this.onNext,
      error: this.onError,
      complete: this.onComplete,
    });
  }```

**Comment by bfreeman** [comment]
Any word on getting this resolved? I'm encountering it as well.

**Comment by wadehats** [comment]
when my JWT times out I want to fetch a new token with my refresh token and try again but the docks don't seem to give a clear answer

**Comment by mshick** [comment]
My issue is as @vinverdy describes — I need to retry on a category of GraphQL error (with backoff) but `RetryLink` never receives the errors. It would make sense to me if `RetryLink` could evaluate any error for retry, rather than just network errors.

**Comment by MrDesjardins** [comment]
I'm using `@apollo/client": "^3.7.2"` with the same problem as many people in this thread.

@wadehats described very well a scenario that is totally plausible. I am actually surprised that the issue has not more traction by the Apollo team since it is a an issue that every consumer code will hit when it implements the standard authentication process.

To put everything under perspective, if the GraphQL Server returns `false` on the `onConnect` (using the recommended `graphql-ws`), it calls on the client [1] side the `shouldRetry` of the `GraphQLWsLink` (from `@apollo/client/link/subscriptions`). Returning `false` on `onConnect` is the way [2] to indicate that during connection of a client that the authentication failed. However, the problem is still not on the server-side, but more how the `shouldRetry` handle any error. In my case, like many authentication systems, I am relying on JWT that can be refreshed by performing an an asynchronous HTTP request to get a new token. The problem is that the `GraphQLWsLink` is synchronous. 

To illustrate the client side portion, the snippet does not work:

```
const wsLink = new GraphQLWsLink(
    createClient({
      url: `${url}/graphql`,
      connectionParams: {
        authorization: token ? `Bearer ${token}` : "",
      },
      shouldRetry: async (errOrCloseEvent: unknown) => {
        if (isCloseEvent(errOrCloseEvent)) {
          if (errOrCloseEvent.code === 4403 || errOrCloseEvent.code === 4401) {
            return refreshUserJWT() // Issue here, the function cannot return a promise
              .then(() => {
                return true;
              })
              .catch(() => {
                return false;
              });
          }
        }
        return true;
      },
    })
  );
```

I do not have a lot of hope since this ticket has been created in 2020 and it is now 2023. However, it would be nice to get a workaround or an alternative. On my side, I'm thinking to have the asynchronous code running and adjusting the retry delay to many seconds and hoping that the `refreshUserJWT` asynchronous code would be completed before the next try. Hacky, but it seems the only possibility at the moment.

[1] https://www.apollographql.com/docs/apollo-server/data/subscriptions/#onconnect-and-ondisconnect
[2] https://github.com/enisdenjo/graphql-ws/blob/331fe4749227393297da4d97a4370ab6f76cc73a/src/server.ts#L205

**Comment by alessbell** [comment]
Hi @KarelVerschraegen @bfreeman @maxim-isakov-ross @vinverdy @mshick 👋 You can retry operations after GraphQL errors with the `onError` link by returning `forward(operation)` in your `onError` function. For example:

```js
onError(({ graphQLErrors, networkError, operation, forward }) => {
  if (graphQLErrors) {
    for (let err of graphQLErrors) {
      switch (err.extensions.code) {
        // Apollo Server sets code to UNAUTHENTICATED
        // when an AuthenticationError is thrown in a resolver
        case "UNAUTHENTICATED":
          // Modify the operation context with a new token
          const oldHeaders = operation.getContext().headers;
          operation.setContext({
            headers: {
              ...oldHeaders,
              authorization: getNewToken(),
            },
          });
          // Retry the request, returning the new observable
          return forward(operation);
      }
    }
  }

  // To retry on network errors, we recommend the RetryLink
  // instead of the onError link. This just logs the error.
  if (networkError) {
    console.log(`[Network error]: ${networkError}`);
  }
});
```

More information is available here: https://www.apollographql.com/docs/react/data/error-handling/#retrying-operations.

On the question of allowing Retry Link to receive GraphQL errors, the team will consider this for v4. Regardless of whether we decide to make that (breaking) change, I'll be opening a docs PR to make it clearer that this is possible with the existing links `@apollo/client` provides. I'll close out this issue for now, but let me know if I've missed anything. Thanks!
