### ISSUE TITLE
Apollo 3 Migration to merge + read in typePolicies of InMemoryCache from updateQuery in fetchMore may not be possible in certain cases

### ISSUE THREAD

**Issue by Badbreaddead** [apollographql/apollo-client#7054]
Hello. Thank you for your work. Apollo client 3 looks amazing so far.
But I have found a case where I can't migrate to [pagination with typePolicies](https://www.apollographql.com/docs/react/caching/cache-field-behavior/#handling-pagination). I tried to find this situation in docs, issues, stackoverflow, Spectrum - no luck, not sure maybe I am missing something... Anyway:
I have a component which uses useLazyQuery and its fetchMore in two cases: fetch next page of a list(example from docs) and fetch filtered data based on date or scheme. So every time user filters data we need to clear the cache and show new filtered elements from response and when he scrolls down we need to concatenate elements from the response with ones from cache and in both cases we call `fetchMore` with `after` cursor... How can I make `read` method of `typePolicies` distinguish these two situations? Don't want to make any changes on backend if possible

```
const ExampleScreen = () => {
  ...
  const {
    called,
    loading,
    error,
    data,
    networkStatus,
    refetch,
    fetchMore,
  } = useLazyQuery(GET_REQUEST);

  useEffect(() => {
    if (date) {
      fetchFiltered(date);
    } else if (refetch) {
      refetch();
    }
  }, [date, scheme]);

  const fetchNextItems = () => {
    if (fetchMore) {
      fetchMore({
        variables: {
          after: actions.pageInfo.endCursor.toISOString(),
        },
        updateQuery: (
          previousResult: GetMobActions,
          { fetchMoreResult }: { fetchMoreResult?: GetMobActions }
        ) => {
          if (!fetchMoreResult) {
            return previousResult;
          }

          const concatNodes = [
            ...previousResult.mobActions.nodes,
            ...fetchMoreResult.mobActions.nodes,
          ];

          return {
            ...fetchMoreResult,
            mobActions: {
              ...fetchMoreResult.mobActions,
              nodes: concatNodes,
              pageInfo: {
                __typename: 'PageInfo',
                endCursor: fetchMoreResult.mobActions.pageInfo.endCursor,
                hasNextPage: fetchMoreResult.mobActions.pageInfo.hasNextPage,
                startCursor: previousResult.mobActions.pageInfo.startCursor,
                hasPreviousPage:
                  previousResult.mobActions.pageInfo.hasPreviousPage,
              },
            },
          };
        },
      });
    }
  };

  const fetchFiltered = (d: Date | null) => {
    if (fetchMore) {
      fetchMore({
        variables: {
          ...(d ? { after: d.toISOString() } : undefined),
        },
      });
    }
  };

  return (
      <ActionsWithFilter
        data={data}
        networkStatus={networkStatus}
        fetchNextItems={fetchNextItems}
        fetchFiltered={fetchFiltered}
        date={date}
        setDate={setDate}
        scheme={scheme}
        setScheme={setScheme}
      />
  );
};
```

**Comment by benjamn** [comment]
@Badbreaddead A somewhat hacky way would be to pass an additional, made-up field argument, so your `read` function can examine `options.args` and behave appropriately, according to the value of the extra argument.

Just so I fully understand, how are you telling the server to send you filtered data? Is the format of the `after` variable somehow different when it's a `Date` than when it's some other cursor string?

In case you haven't seen the [`relayStylePagination`](https://github.com/apollographql/apollo-client/blob/8d77510e1eee197442c4c56410c2a5d8d00b9eda/src/utilities/policies/pagination.ts#L86) field policy helper function, it might save you some trouble. Basic example here: #6465.

Note that `relayStylePagination().read` does not implement any filtering according to `args.after`, but always gives you the full list of data. You can either do the filtering in application code, or make yourself a copy the `relayStylePagination` code and add some logic to the `read` function to implement the filtering. My one caveat here is that `fetchMore` does not automatically update the variables of the _original_ query to reflect the new range of data, so if you want your `read` function to do the filtering, you might need to update the query variables after `fetchMore` finishes (otherwise the original query may just keep reading the first page of data).

If working on this `relayStylePagination` helper has taught me anything, this may be tricky to get right, so I'm happy to help/collaborate as much as necessary.

**Comment by Badbreaddead** [comment]
@benjamn Thank you for reaching out so fast. 

I thought about providing extra arg, but I don't want to pass it to the server to avoid confusion. Is it possible to somehow pass data from fetchMore to `read` handler in `typePolicies`. `fetchMore` has `context`, but it is probably not for that...

To answer your question: `after` is handled the same way in both cases for pagination and when we filter by date and when we filter by date(which means show elements before that date) we can also paginate. So when we filter data we need to clear the cache and then when we paginate and we need to concatenate. We also use couple of other query params for filtering based on other factors, but I guess we can ignore them in this example.

relayStylePagination is very close to what I implement yes, but as you mentioned without filtering... 

`My one caveat here is that fetchMore does not automatically update the variables of the original query to reflect the new range of data, so if you want your read function to do the filtering, you might need to update the query variables after fetchMore finishes (otherwise the original query may just keep reading the first page of data).` - thank you for the hint.

I guess I will use made-up field argument as you proposed for now, but I think it is worth addressing this issue, I forecast I am not the only one who can stumble upon such situation. Mechanism to share specific options between fetchMore, refetch, etc and InMemoryCache could help
