### ISSUE TITLE
Tying to fetch data from cache using readQuery | getting error "Can't find field 'users' on ROOT_QUERY object"

### ISSUE THREAD

**Issue by ManojKSingh** [apollographql/apollo-client#7091]
Version: Apollo Client 3

`const user = client.readQuery({
      query: gql`
        query ReadUser($id: String!) {
          users(id: $id) {
            id
            name
          }
        }
      `,
      variables: {
        id,
      },
    });`

Trying to fetch data from cache using read query but getting this error 
![image](https://user-images.githubusercontent.com/6726258/94520447-ef901f00-0249-11eb-9766-7f45f69d246a.png)

when i try to get whole and not just the user by ID, I get the result out of it. but trying to fetch single user from cache it doesn't works.

**Comment by benjamn** [comment]
By default, the data received by `query { users { id name }}` is stored within the `ROOT_QUERY` object using the key `users` (because the `users` field has no arguments), but the data for `query { users(id: $id) { id name }}` gets stored separately using the key `users:{"id":"..."}`.

This argument-based separation of field data is essential because the cache cannot automatically know what your arguments mean, so it has to assume all of them are important. In other words, any different combination of arguments has potentially its own distinct result, so the results must be stored separately. When the cache looks up the `users` field with an `id` argument, it doesn't find anything, because it only has data for the `users` field with no arguments.

The reason for the error you saw is that your `ROOT_QUERY` cache data does not have a `users:{"id":"..."}` field to go along with `users` under `ROOT_QUERY`. The error message removes the extra JSON characters from the field name, leaving just the `users` string, though I can definitely appreciate how this shortening leads to confusion here.

In order to teach your cache how to interpret the `id` argument to your `Query.users` field, you need a [field policy](https://www.apollographql.com/docs/react/caching/cache-field-behavior/):
```ts
new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        users: {
          read(existing = [], { args, readField }) {
            // If args.id was provided, return a filtered list (possibly empty)
            // containing just the user we asked for, if found.
            if (args && args.id) {
              // Note that user might be a Reference, which is why we need to use
              // readField("id", user) instead of just user.id.
              return existing.filter(user => args.id === readField("id", user));
            }
            return existing;
          },
          // Disable the default argument-based separation of field data,
          // since the read function handles args.id.
          keyArgs: false,
        },
      },
    },
  },
})
```
This gives the cache the ability to return results for `query { users(id: $id) { id name }}` based on data received for `query { users { id name }}`, without having to make a second network request.

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
