### ISSUE TITLE
Error on query cached and copied onto next query

### ISSUE THREAD

**Issue by diffidentDude** [apollographql/apollo-client#7164]
### Intended outcome
We are using **@apollo/client@3.2.4** and **React**

We have a query that takes variables that we are calling using the **useQuery** hook in our component
```
const { loading, error, data } = useQuery(QUERY, {
    variables: { variable1 },
  });
```
**variable1** defaults to value1 which returns correct data from the server. This is cached as expected in the client.
```
{
    "data":{"array1":[{ "field1": "value1" }]}
}
```
The values of loading, error and data are as follows
```
{ loading: true, error: undefined, data: undefined }
{ loading: false, error: undefined, data: { array1:[{ field1: "value1" }]} }
```

We change the value of **variable1** via a dropdown to **value2**
This rerenders the component with the **value2** in **variable1**

The server returns an error response when it receives **value2**
```
{
    "errors":[{"message":"GraphQL Error."}],
    "data":{"array1":nulll}
}
```
The values of loading, error and data are as follows
```
{ loading: true, error: undefined, data: undefined }
{ loading: false, error: "GraphQL Error.", data: undefined }
```

We change the value of **variable1** via a dropdown back to **value1**
This rerenders the component with the **value1** in **variable1**

We expect the cached result from previous to be returned
```
{ loading: false, error: undefined, data: { array1:[{ field1: "value1" }]} }
```

### Actual outcome
The cached result is returned, however the errors from the previous query are also returned, which confuses the rendering logic
```
{ loading: false, error: "GraphQL Error.", data: { array1:[{ field1: "value1" }]} }
```

### Notes
This only happens when the third call is cached. If it goes through to the server it works as expected.
This only happens if the most recent last call resulted in an error.
I have put together a potential fix in a PR https://github.com/apollographql/apollo-client/pull/7163

### Versions
  System:
    OS: macOS 10.15.6
  Binaries:
    Node: 13.12.0
    Yarn: 1.22.5 
    npm: 6.14.4 
  Browsers:
    Chrome: 86.0.4240.80
    Edge: 85.0.564.60
    Firefox: 80.0.1
    Safari: 13.1.2

**Comment by ShuPink** [comment]
I'm also having this issue.  In my case I am using @apollo/client": "^3.2.5".
I'm trying to implement Next's SSG which renders my component twice: the first with an empty query object and the second after hydration with the query object filled.

    const router = useRouter();
    const { slug } = router.query;
    
    const { loading, error, data } = useQuery(PRODUCT, {
    	variables: { slug },
    });

The first render `(query = undefined)` returns 

    {
      loading: false,
      error: Error: Response not successful: Received status code 400,
      data: undefined
    }

which is as expected, since the query goes through malformed.

The second render `(query = "some-value")` returns

    {
      loading: false,
      error: Error: Response not successful: Received status code 400,
      data: { products: [] }
    }

where the data has been returned as expected, but I had thought the error would be cleared.
The status code 400 with returned data had me scratching my head for a while...

I originally thought it might act this way by design for some reason, or that I am supposed to handle the first error in some way first, but now I'm not entirely sure?

I did try all errorPolicies but this didn't seem to have an effect, is that because this is a graphQL error not a network error? (Sorry I'm pretty new to programming).

**Comment by diffidentDude** [comment]
@ShuPink I doubt it is by design as it only propagates the previous requests error onto the request.

Our workaround currently is to do the following
```
if (error && !data && !loading) {
 // Render error state
}
```

The only problem with this approach is that if the errorPolicy is 'all' it can make it quite difficult to tell the difference between error and non error states.

It works for now however.

**Comment by ShuPink** [comment]
@diffidentDude ahh I see, thanks for the explanation, and the workaround ^^
I ended up doing a workaround to make sure my first render wouldn't throw that specific error... but your method seems a lot simpler.

**Comment by rettgerst** [comment]
bumping as this is still a problem in 3.3.6.

I tried to hack around the issue by tracking the error in a useState hook, setting the error state in the onError callback, and clearing the error state when variables changed - but that didn't solve the problem still, because when the query that results in an error is cached, even the error callback fires _again_ on the next query with the error from the previous query.

for now I am working around this by setting `fetchPolicy: 'no-cache'`, but ofc this means I don't get to leverage apollo's caching features.

I will submit a reproduction repo soon.

**Comment by rettgerst** [comment]
okay, here is my simple reproduction app: https://codesandbox.io/s/hopeful-meitner-hmllm?file=/src/App.tsx

leveraging the [public graphql api from AniDB](https://anilist.gitbook.io/anilist-apiv2-docs/), the app shows information about anime characters. one of the options is Katara from ATLA, which will produce an error because she is not in the AniDB database.

to reproduce the issue - click on the first two options to prime the in-memory cache, then click on the Katara button to issue a request which will error. Then click on one of the other characters again. The data for the selected character is retrieved from cache and displayed onscreen, however the error from the previous request remains.

**Comment by ludwigbacklund** [comment]
> @ShuPink I doubt it is by design as it only propagates the previous requests error onto the request.
> 
> Our workaround currently is to do the following
> 
> ```
> if (error && !data && !loading) {
>  // Render error state
> }
> ```
> 
> The only problem with this approach is that if the errorPolicy is 'all' it can make it quite difficult to tell the difference between error and non error states.
> 
> It works for now however.

We have the same problem and use this workaround for now. Our problem exactly mirrors the one in the reproduction app @rettgerst posted above.
