### ISSUE TITLE
Using relayStylePagination conflicts with cache update

### ISSUE THREAD

**Issue by pontusab** [apollographql/apollo-client#7191]
**Intended outcome:**
Update cache after mutation using cache.modify or cache.writeQuery should update the cache.

**Actual outcome:**
When using `relayStylePagination` on the `typePolicies` the cache will not get updated after a modify nor writeQuery, removing the `relayStylePagination` everything works as expected. 

**How to reproduce the issue:**
```js
// Cache
const cache = new InMemoryCache({
    typePolicies: {
      Query: {
        fields: {
          projectCollections: relayStylePagination(['projectId']), // When removing this the update works as expected
        },
      },
   },
 })

// Mutation

 const { data } = await addCollection({
      variables: {
        name,
        projectId,
      },
      update(cache, { data: { addCollection } }) {
        cache.modify({
          fields: {
            projectCollections(existingCollectionsRefs = {}) {
              const newCollectionRef = cache.writeFragment({
                data: addCollection,
                fragment: CollectionFragmentDoc,
              })

              return {
                ...existingCollectionsRefs,
                edges: [...existingCollectionsRefs.edges, newCollectionRef],
              }
            },
          },
        })
      },
    })
```

**Versions**
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.11.0 - ~/.nvm/versions/node/v14.11.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.11.0/bin/npm
  Browsers:
    Chrome: 86.0.4240.80
    Safari: 14.0
  npmPackages:
    @apollo/client: ^3.3.0-beta.13 => 3.3.0-beta.13 
    apollo3-cache-persist: ^0.7.0 => 0.7.0

**Comment by benjamn** [comment]
@pontusab The decisions [`relayStylePagination`](https://github.com/apollographql/apollo-client/blob/release-3.3/src/utilities/policies/pagination.ts) makes about the internal representation of the data have to be understood and respected when calling `cache.modify`, since that's what `existingCollectionsRefs` will be.

I would recommend setting a breakpoint in your `projectCollections` modifier function, so you can see exactly what `existingCollectionsRefs` data you're getting, and make sure your updates preserve the structure of the data. If that doesn't reveal the problem, please put together a [reproduction](https://github.com/apollographql/react-apollo-error-template) so we can help you dig into this.

If you don't want to worry about the internal representation of data, you can use `cache.writeQuery` instead of `cache.modify`, with an `args.after` cursor that matches the last edge currently in the list (`pageInfo.endCursor`), and `args.first === 1`. Using the higher-level `writeQuery` API will allow `relayStylePagination` to control the update, so you don't have to think about the details.

**Comment by pontusab** [comment]
Thanks for the help @benjamn I manage to get it to work buy actually write the data to the cache as it should be (thanks to a breakpoint as you suggested).

**Comment by bigint** [comment]
@pontusab It would be great if you say us the step hoe you resolved this issue 🙇🏻
