### ISSUE TITLE
A

### ISSUE THREAD

**Issue by TSiege** [apollographql/apollo-client#7193]
**Intended outcome:**
Not sure if this is truly the expected outcome, or if the docs are insufficient. However, setting  custom headers on the `ApolloClient` doesn't work if you supply a custom link object. I would have assumed that since these are two different classes that the header arguments for them are isolated. It's an easy fix on my end, and it seems difficult to fix in the code, but the docs are not clear about this and poses as a gotcha for users.

**Actual outcome:**
The instance of the ApolloClient does not use the headers if a custom link is provided, as per [these lines](https://github.com/apollographql/apollo-client/blob/main/src/core/ApolloClient.ts#L137-L141). Instead the link is used, and headers provider to the ApolloClient constructor are ignored, and subsequently they do not show up on my server.

**How to reproduce the issue:**

```
  return new ApolloClient({
    link: new HttpLink({
      uri: '<graphql endpoint>'
    }),
    headers: { foo: 'bar' },
  })
```

**Versions**

    "@apollo/client": "^3.2.5",

**Comment by benjamn** [comment]
If you provide your own link, it might not necessarily be an `HttpLink` (it could be anything!), so `ApolloClient` can't be responsible for setting `headers` on your custom link. That's why it's your responsibility to move the `headers` from the `new ApolloClient({...})` options into the `new HttpLink({...})` options, just as you did for `uri`.

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
