### ISSUE TITLE
previousQueryResult object is empty in updateQuery when changing query variables while the fetchMore is in progress

### ISSUE THREAD

**Issue by Allaoua9** [apollographql/apollo-client#7241]
**Intended outcome:**
Hypothesis:
For simplicity sake, let's say, all queries take 500ms.

Steps to reproduce :
1. Make a query with variables. and wait for it to resolve (500ms).
2. Call fetchMore, to get next page (500ms).
3. After 20ms (fetchMore still in progress), Change the state that holds the variables of the query => the query should be replayed.

**Actual outcome:**
When the updateQuery is called, the previousQueryResult is empty.

**How to reproduce the issue:**
Here is a reproduction of this bug

https://codesandbox.io/s/reproduction-for-react-apollo-7241-with-successful-response-forked-lvypl?file=/src/ThingsList.jsx

**Versions**
@apollo/client 3.2.5

**Comment by benjamn** [comment]
@Allaoua9 Thanks for the reproduction!

When you change the `filter` argument for the original query by calling `setFilter("New Filter")`, you trigger another cache read, which fails to provide useful data because of the change in `filter`.

Since it sounds like you don't want the change of `filter` argument to invalidate previous results for `Query.thingsList`, you can let the cache know the `filter` argument should be ignored when reading/writing the field value:
```ts
const client = new ApolloClient({
  link: new SchemaLink({ schema: executableSchema }),
  cache: new InMemoryCache({
    typePolicies: {
      Query: {
        fields: {
          thingsList: {
            keyArgs: ["page"],
          },
        },
      },
    },
  }),
});
```
You could also probably use `keyArgs: false` here to ignore the `page` argument as well, since it looks like you want the original query to receive the complete list of data, without splitting it into separate pages.

See #7175 for some new pagination documentation that we've been working on, in case you want a whole lot more detail about how this system works.

**Comment by Allaoua9** [comment]
Thanks for the answer @benjamn ! 
I'll take a look on the new doc :)

**Comment by hwillson** [comment]
Let us know if https://github.com/apollographql/apollo-client/issues/7241#issuecomment-716792871 didn't help. Thanks!

**Comment by Allaoua9** [comment]
@hwillson it dit help thanks you !
