### ISSUE TITLE
Be able to use @client fields as primary keys

### ISSUE THREAD

**Issue by HarrisonHenri** [apollographql/apollo-client#7255]
It would be great if we could use @client field as primary key when solving fragments.

**Comment by benjamn** [comment]
@HarrisonHenri This is an interesting idea, though it would mean invoking `read` functions during cache writes (in order to compute normalized IDs for the objects that are being written to the cache).

In the meantime, I thought I would mention that the `keyFields` configuration (which is usually an array of primary key field names) can be specified as a function, so you can customize ID generation however you like:
```ts
new InMemoryCache({
  typePolicies: {
    Person: {
      keyFields(personResultObject) {
        // return a string, or an array of field names to use as keyFields,
        // or undefined to disable normalization for this object
      },
    },
  },
})
```

**Comment by HarrisonHenri** [comment]
Thanks @benjamn . In the case that I've a `id @client` field it's possible to customize and set that field as primary key using `keyFields` configuration?

**Comment by sraisty1c** [comment]
> Thanks @benjamn . In the case that I've a `id @client` field it's possible to customize and set that field as primary key using `keyFields` configuration?

I have the same question.
