### ISSUE TITLE
Memory Leak: Mutation + OptimisticResponse makes update function to leak

### ISSUE THREAD

**Issue by kamilkisiela** [apollographql/apollo-client#7339]
After executing a mutation with `update` function and `optimisticResponse` the `update` function is hold in memory forever which leaks other referenced objects.

**How to reproduce the issue:**
https://github.com/kamilkisiela/apollo-optimistic-response-pessimistic-memory-leak

    npm install
    npm run start
 
1. Open `chrome://inspector`
1. Connect to a process
1. Click play on first breaking point
1. On next breaking point, take a snapshot
1. Look for `Foo` class

<img width="448" alt="Zrzut ekranu 2020-11-17 o 14 53 35" src="https://user-images.githubusercontent.com/8167190/99401039-ffda8700-28e7-11eb-97f1-569d4ba1acb4.png">
   
@benjamn I can confirm that `Cache.removeOptimistic` is called but `Foo` is still there

https://github.com/apollographql/apollo-client/blob/291e8bd8ab6c9033be2e50af4df3bf56b5c4da43/src/core/QueryManager.ts#L273

**Comment by kamilkisiela** [comment]
I think that

https://github.com/apollographql/apollo-client/blob/2e8cce1748703defb09eb94abafe546be641c4fc/src/cache/inmemory/readFromStore.ts#L156-L161

holds a reference forever because it has no cleanup logic

**Comment by benjamn** [comment]
@kamilkisiela I've updated the `optimism` library so that it no longer holds onto `entry.args` arrays (see https://github.com/benjamn/optimism/pull/104), so memory leaks related to arguments passed to methods like `executeSelectionSet` should no longer be possible.

Following your reproduction steps, I no longer see retainment paths containing lines like `args in Entry @1663111` (or anything above it) in your screenshot.

These changes were published in `optimism@0.13.1` and can be tested by running either `npm i optimism@latest` or `npm i @apollo/client@3.3.0-rc.2`.

It might still be worthwhile to evict/forget `Entry` objects associated with optimistic updates that have been rolled back, but I'd want to see some evidence that's still a problem, now that function arguments are no longer retained.

**Comment by kamilkisiela** [comment]
Thanks, we're going to test it soon

**Comment by smykhailov** [comment]
should #7276 be merged into master too. It should minimize amount of potential memory leaks too

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
