### ISSUE TITLE
array passed as variable is treated as comma-separated string in payload

### ISSUE THREAD

**Issue by adammo94** [apollographql/apollo-client#7349]
Hi, I have a following problem I'm trying to pass a table of strings (sensorId and avgSensorId in my case) in query, let's say: ```["aaa","bbb"]``` in query input I have it as [String]! however when it performs query when I check in network tab in inspector it shows "aaa,bbb" which fails query for more than one element in the table. I tried passing it as ```[sensorId ]```, ```[...sensorId ]``` and simply ```sensorId ```, however it always gives a payload of comma separated values in string. What could be the solution to this?

```
const { loading, error, data, refetch } = useQuery(SINGLE_CHART, { variables: { start: `${start}`, stop: `${stop}`, type: `${type}`, sensorId: `${sensorId}`,avgSensorId: `${avgSensorId}` }, fetchPolicy: "no-cache" });
```

```
export const SINGLE_CHART = gql backtick
  query chart($start: String!, $stop: String!, $type: String!, $sensorId: [String]!, $avgSensorId: [String]!){
    chart(input: {
      start: $start,
      stop: $stop,
      type: $type,
      sensorId: $sensorId,
      avgSensorId: $avgSensorId
    }) {
        labels
        datasets {
          label
          data
          backgroundColor
          borderColor
          borderWidth
        }
    }
  }
backtick
```

**Comment by devkot** [comment]
Hi @adammo94, your issue here seems to be related to JS template literals instead of GQL.

For example, if `sensorId = ["a", "b"]` then ``${sensorId}`` would return `"a,b"`.

Luckily, you don't need to use template literals to pass the variables to your GQL query and you can pass the `sensorId` variable instead. 

So your query variables could look like: 
`{ variables: { sensorId: sensorId } }` or using the shorthand `{ variables: { sensorId } }`

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
