### ISSUE TITLE
When setting FieldPolicy.keyArgs, cache key is in a different format.

### ISSUE THREAD

**Issue by kyle-villeneuve** [apollographql/apollo-client#7364]
**Intended outcome:**
When you set `FieldPolicy.keyArgs`, the cache key should be created using the same conventions as when it's omitted, however it's stored in a slightly different format.

`books({"variable":true})` 

**Actual outcome:**

`books:{"variable":true}`

**How to reproduce the issue:**

Set a field policy and keyArgs specified, then call that field with arguments.

**Versions**

  System:
    OS: macOS 10.15.4
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.198
    Safari: 13.1

**Comment by benjamn** [comment]
@kyle-villeneuve This is an artifact of backwards compatibility, since the first form is what the serialized arguments looked like in AC2, but we dropped the unnecessary parentheses when implementing `keyArgs` for AC3.

Have you experienced any situations where both formats are used for the same data, leading to inconsistencies? Or did you just notice the difference and thought it was strange? If it's causing you any problems, we could definitely consider standardizing the formatting.

**Comment by kyle-villeneuve** [comment]
I haven't had any issues that I know of, but figured the inconsistency might cause some unpredictability. Feel free to close this if that's not the case.

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
