### ISSUE TITLE
Did something change with the way writeQuery works in v3?

### ISSUE THREAD

**Issue by SlovakianCanon** [apollographql/apollo-client#7383]
I'm working on a project with very large amounts of data in Apollo cache on the client (tens of thousands of objects for multiple megabytes of data).

In v2 it worked well. Sure performance has always been an issue, but it was manageable. Now I'm trying to move to v3, to hopefully improve performance, but turns out it got worse instead.

I followed the migration documentation and now everything works, but is much slower. Both `readQuery` and `writeQuery` seem to be slower, but it seems to be worse with `writeQuery`.

For example, when we receive the big "initial query" on the frontend that's usually 5 - 10MB, we transform it into an easily query-able object to suit our needs (because an array is really slow when you need to access objects by certain fields). That operation takes about 400ms on a large dataset, and is then written to the cache using `writeQuery` (on an `@client` query). It used to take a few ms, maybe 10-20 ms to do that. Now it takes between 300 and 500 ms.

Also, when I write something new to that big cache, I use writeQuery to merge the changes with the actual cache. This used to take a few ms, now it sometimes takes up to 2000ms.

Is there something I missed in the migration notes? As-is we simply cannot move forward with Apollo v3, which is a bummer

**Comment by benjamn** [comment]
@SlovakianCanon To answer your high-level question, as the person who implemented almost all of the AC3 `InMemoryCache` changes, I do not believe anything has changed about `writeQuery` that would explain this difference in performance. If anything, cache writes have gotten faster. In other words, I'm pretty confident this issue will come down to something your application can do differently, though I'm curious to find out exactly what that is, since we might be able to detect it and show a warning.

Can you share some more details about your usage?
1. The query you're using with `writeQuery` (fine to abbreviate, but keep the `@client` fields)
2. Any `resolvers` you pass to the `ApolloClient` constructor, especially for the fields that are slow to write
3. Any non-default options you pass to the `InMemoryCache` constructor
4. Anything else you think might be relevant

Of course, a runnable [reproduction](https://github.com/apollographql/react-apollo-error-template) would be ideal, but the above information might make that unnecessary, if we're lucky.

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
