### ISSUE TITLE
Caching does not work for sub-queries

### ISSUE THREAD

**Issue by tomitrescak** [apollographql/apollo-client#7395]
**Intended outcome:**

I have a following query with two sub queries: 

```graphql
query Data($id1: String!, $id2: String) {
   person(id: $id1) {
     id
     name
   }

   pet(id: $id2) {
      id
      name
   }
}
```

When I execute it twice with parameters: `{ id1: '1', id2: '2' }` and `{ id1: '1', id2: '3' }`, that is querying person with the same id but a different pet, I would expect for Apollo to  only query for a fresh pet, not a person.

**Actual outcome:**

 Apollo keeps querying also for the same person, even if it has the same ID.

**How to reproduce the issue:**

I can create a repro, but I think my question is clear and I am affraid this is not a bug but a feature.

**Versions**

  System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.198
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.47)

**Comment by tomitrescak** [comment]
Is this why it does not work? : https://github.com/apollographql/apollo-client/pull/4245

**Comment by benjamn** [comment]
@tomitrescak This is working as intended. The unit of refetching in Apollo Client is (currently) the query, and the client does not try to prune your queries to make them smaller in cases like this.

This coupling ensures consistency between the sub-queries, because you always fetch both `person` and `pet` when you fetch the whole query. If you don't care about that consistency, you can always split the query into multiple queries. And if you want to batch those separate queries together again, before sending them to the server, you can use [`@apollo/client/link/batch-http`](https://www.apollographql.com/docs/react/api/link/apollo-link-batch-http/).

Additionally, some servers implement a query safe-listing system that requires exactly the same query (from some set of registered queries) to be sent each time, rejecting the query otherwise. If you think those systems should be more tolerant of partial/subset queries, I very much agree with you, yet here we are.

There's a good chance we will introduce additional options for refetching in the future, assuming your server supports an API for requesting specific entities, like [`Query._entities`](https://www.apollographql.com/docs/federation/federation-spec/#query_entities), but I think it's less likely that Apollo Client will remove fields from your queries to fetch less data, for the reasons I outlined above.

**Comment by tomitrescak** [comment]
@benjamn thanks for your explanation. Makes sense. Keep up the great work!
