### ISSUE TITLE
How to process heavy response in slow js environemnt?

### ISSUE THREAD

**Issue by punksta** [apollographql/apollo-client#7411]
I am using apollo in react-native for loading data up to few mb in one response.

I am experiencing issues with app responsiveness when it processes response. 
During performance monitoring I found that js event-loop can be taken by apollo cache functions execution.

I am thinking, maybe it can be possible to introduce asynchronous mode for apollo client? it can use "setImmediate" between every next graphql node processing or something similar.

Or is there other way to unblock even loop in Apollo?

**Comment by benjamn** [comment]
So… the `InMemoryCache` API has to remain synchronous so React components can read any existing data on the first call to `useQuery`, rather than always returning a useless `loading: true` result, but I have often wondered if it might be possible to split up cache writes when there are multiple root fields, so there's an async gap between the writes. Each field would be written synchronously, but multiple fields could be written separately/asynchronously. Do your queries have multiple root fields, or just one really big root field?

**Comment by punksta** [comment]
@baerrach One big root field.

**Comment by punksta** [comment]
I think having event-loop queue as free as possible is more important than having fast access to the data on first call. 
I would expect having `loading: true` during the time the apollo client processes the response.
