### ISSUE TITLE
Queries invalidation logs

### ISSUE THREAD

**Issue by lifeisaloha** [apollographql/apollo-client#7424]
Is it possible to log when any query becomes invalidated? It is very difficult to understand what is wrong with my cache update operations in a big project with hundreds queries.

**Comment by benjamn** [comment]
We could use [`invariant.log`](https://www.npmjs.com/package/ts-invariant) for this. Following #7226, the default log level is `warn` rather than `log`, but you could call `setLogVerbosity("log")` to enable more verbose warnings. Note: we don't currently have any usage of `invariant.log`, so this functionality would need to be added.

**Comment by bigcrimeanboss** [comment]
Like

**Comment by hwillson** [comment]
It doesn't sound like there is an outstanding issue here, so closing. Thanks!
