### ISSUE TITLE
Query data is `{}` instead of `undefined`, despite pull request 3388

### ISSUE THREAD

**Issue by ostrebler** [apollographql/apollo-client#7486]
**Intended outcome:**
According to https://github.com/apollographql/react-apollo/pull/3388, unavailable `data` should **not** be `{}` but `undefined`. One reason mentioned in the PR makes a lot of sense (especially using codegen) :
 
> Forcing no data situations to be empty objects can go against application schemas that enforce a value and don't allow empty objects.

**Actual outcome:**
It's actually still `{}` between refetches, when nothing's found in the cache, essentially giving two different semantics for "there's no data" : `undefined` on initial fetch, then `{}`. This feels inconsistent and generates nasty runtime errors that are not catched by TypeScript when using codegen.

It also makes patterns like these (recommended here : https://github.com/apollographql/apollo-client/issues/6603#issuecomment-700282431) pointless : 
```typescript
const continuousData = data ?? previousData
```

**How to reproduce the issue:**
- **[CodeSandbox Link](https://codesandbox.io/s/condescending-driscoll-5oeyb?file=/src/Todos.tsx)**
Let the first page load, then move to another page. Finally, read the `data` value in the console : 

```
undefined
{todos: Object}
{todos: Object}
{}
{todos: Object}
```

**Versions**
@apollo/client: ^3.3.6 => 3.3.6

**Comment by gbiryukov** [comment]
I believe this issue is caused by [this snippet](https://github.com/apollographql/apollo-client/blob/70bf46fa0e3a9483c19bbb1cc0751b196f4d3ad8/src/core/QueryManager.ts#L933-L945).
Seems it had to be removed in [this PR](https://github.com/apollographql/apollo-client/pull/6566) to follow [currently documented behavior](https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#react).

A workaround is to disable `notifyOnNetworkStatusChange` which is not possible in all cases.

**Comment by ostrebler** [comment]
> Seems it had to be removed in [this PR](https://github.com/apollographql/apollo-client/pull/6566) to follow [currently documented behavior](https://github.com/apollographql/apollo-client/blob/main/CHANGELOG.md#react).

Honestly, this PR was just such a bad idea. I switched to urql.
