### ISSUE TITLE
Significantly slower under Meteor and unbundled server contexts

### ISSUE THREAD

**Issue by jimrandomh** [apollographql/apollo-client#7523]
Apollo-Client is significantly slower when running out of a Meteor server environment or a `node_modules` folder than when it's running inside of a bundle which has had `process.env.NODE_ENV` preprocessed into a string. [This PR](https://github.com/apollographql/apollo-client/pull/6660) fixes it, but seems to have fallen through the cracks. The problem is that in node, `process.env` is actually a slow API function, not suitable for being called in any sort of inner loop, but apollo-client is using it as though it was fast.

**Comment by benjamn** [comment]
@jimrandomh You're right about `process.env.NODE_ENV` being slow in Node, but (unfortunately!) the _syntax_ of the `process.env.NODE_ENV === ...` checks is important for minifiers to be able to strip out development-only code in production. I don't love that convention, but it's the same convention React uses, so various bundlers and starter codes will already have it configured, which saves Apollo Client from introducing its own additional requirements for proper minification. In Meteor, although the JS minifier does [automatically replace `process.env.NODE_ENV`](https://github.com/meteor/meteor/blob/056e8ac3c1a8e4001f36afd99cdaa70b4753d591/packages/minifier-js/minifier.js#L14-L16) with a string literal, minification happens only for browser code, which is why `process.env.NODE_ENV` remains intact.

**Comment by hwillson** [comment]
Let us know if this is still a concern with `@apollo/client@latest` - thanks!
