### ISSUE TITLE
relayStylePagination helper breaks on queries with aliased fields

### ISSUE THREAD

**Issue by maxschmeling** [apollographql/apollo-client#7540]
I have a query that looks like this (simplified for the example):
```
query Replies {
  viewer {
    id
    replies(status: [ READY ]) {
      totalCount
      pageInfo { hasNextPage endCursor }
      nodes {
        id
      }
    }
    rejectedReplies: replies(status: [ REJECTED ]) {
      totalCount
      pageInfo { hasNextPage endCursor }
      nodes {
        id
      }
    }
  }
}
```

When I use `relayStylePagination` in the viewer type for the `replies` field, the data from the `replies` field is dropped. Removing the `rejectedReplies` field allows the `replies` field to work.

I'm not sure yet if the issue is the fact that there are two uses of the same field, or if the issue is that there is an alias. I'm guessing it's the two uses of the underlying field.

**Comment by benjamn** [comment]
@maxschmeling It's the latter (two colliding uses of the underlying `replies` field). Aliases generally don't have any effect on the cache, at the level of field policies.

In this case, it looks like you want the two instances of the `replies` field to be distinguished by their `status` arguments, and you probably want their data to be kept totally separate, so you should configure a `keyArgs` field policy for the `Viewer.replies` field, since [`relayStylePagination` assumes `keyArgs: false` by default](https://github.com/apollographql/apollo-client/blob/5d207f9cff1439ca919359d714d07681287fe330/src/utilities/policies/pagination.ts#L92):
```ts
new InMemoryCache({
  typePolicies: {
    Viewer: { // just guessing this type name
      fields: {
        // Pass ["status"] for the keyArgs parameter, to override keyArgs
        replies: relayStylePagination(["status"]),
      },
    },
  },
})
```
In rare cases where you don't have any arguments that you can use to distinguish the fields (uncommon, because how is the server supposed to distinguish the fields, then?), you could pass a `keyArgs` function that examines `context.field.alias` (or anything else that might be relevant about the field):
```ts
        replies: relayStylePagination((args, context) => {
          return context.field?.alias || context.fieldName;
        }),
```

**Comment by maxschmeling** [comment]
This was very helpful. Thank you for the extra bit of detail at the end. I didn't even realize that `relayStylePagination` could take a function like that.
