### ISSUE TITLE
Unable to use files in cache/core and cache/inmemory in a node environment

### ISSUE THREAD

**Issue by FoodProduct** [apollographql/apollo-client#7639]
**Intended outcome:**

I was attempting to use a custom caching library ([apollo-invalidation-policies](https://github.com/NerdWalletOSS/apollo-invalidation-policies)) in an isomorphic app which uses some helper methods from within `@apollo/client/cache/core` and `@apollo/client/cache/inmemory`. I expected the library to run fine on both the client (browser) and server (node 14).

**Actual outcome:**

When the code is executed in a node context, I receive the following error:
```
[redacted]/test-apollo-invalidation-policies/node_modules/@apollo/client/cache/inmemory/helpers.js:1
import { isReference, isField, DeepMerger, resultKeyNameFromField, shouldInclude, } from "../../utilities/index.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> ([redacted]/test-apollo-invalidation-policies/routes/index.js:4:34)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

**How to reproduce the issue:**

I have a small repo set up; it has slightly more than the bare minimum needed because I started debugging from the `apollo-client-invalidation-policies`. Really all you need is an `express` (or similar) server and a `require()` statement.
1. Clone https://github.com/FoodProduct/test-apollo-invalidation-policies
1. `npm i && npm run build && npm run start`

I see that the instructions indicate that I should avoid speculation over what the cause might be, but I'm pretty confident that the reason is because files under any subdirectory of `@apollo/client/cache` are not transpiled into cjs. Note that only `cache.js` has a CJS version, whereas no files under the subdirectories do (I collapsed `inmemory/` for brevity).
<img width="378" alt="apollo-client-cache-subdirectories-missing-cjs-files" src="https://user-images.githubusercontent.com/3069614/106506445-95fd6280-647e-11eb-9b64-3107d69317a7.png">

**Versions**

```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Firefox: 62.0
    Safari: 14.0.2
  npmPackages:
    @apollo/client: ^3.3.7 => 3.3.7
    apollo-invalidation-policies: ^1.0.0-beta11 => 1.0.0-beta11
```

**Comment by benjamn** [comment]
@FoodProduct You should be importing from `@apollo/client/cache` rather than specific subdirectories. In general, if you want things to work both in Node.js and in browsers, you should make sure that the subdirectory you're importing from has a `package.json` file in it, with both a "main" field (for Node.js) and a "module" field (for bundlers/browsers). That's true for `@apollo/client/cache`, `@apollo/client/core`, and all the other entry points configured [here](https://github.com/apollographql/apollo-client/blob/main/config/entryPoints.js), but it's not true for every possible subdirectory.

**Comment by FoodProduct** [comment]
> @FoodProduct You should be importing from `@apollo/client/cache` rather than specific subdirectories.
> 
> In general, if you want things to work both in Node.js and in browsers, you should make sure that the subdirectory you're importing from has a `package.json` file in it, with both a "main" field (for Node.js) and a "module" field (for bundlers/browsers). That's true for `@apollo/client`, `@apollo/client/cache`, `@apollo/client/core`, and all the other entry points configured [here](https://github.com/apollographql/apollo-client/blob/main/config/entryPoints.js), but it's not true for every possible subdirectory.
> 
> More explanation, if you're interested: #6656

Hey @benjamn thanks for the response; I actually missed the entryPoints config file so that explains why some import paths are transpiled fully and not others. However, since several of the methods we're interested in are not currently exposed like that, what are your thoughts on exposing some of the helper methods nested under `/cache` for cache extension libraries like [apollo-invalidation-policies](https://github.com/NerdWalletOSS/apollo-invalidation-policies)?

**Comment by danReynolds** [comment]
> some fields that the aforementioned library uses

Yea I mean for example I used types like the `InMemoryCache`'s `EntityStore` type in `apollo-invalidation-policies`, since the library goes deeper than most client use cases. Those types aren't exposed under the cache folder: https://github.com/apollographql/apollo-client/blob/d96f4578f89b933c281bb775a39503f6cdb59ee8/src/cache/index.ts#L12. I assume Apollo has exported all types that they believe are reasonable to expose in their API to clients so I don't know if we'd want to open it up to more types than typically necessary. If not I could always re-define the types, open to solutions.

**Comment by bignimbus** [comment]
Hi all 👋🏻  I'm cleaning house a bit and saw that discussion on this issue tapered off a while ago.  So I'll close this issue but do feel free to post on our [community forum](https://community.apollographql.com/) with more questions! 🙏🏻
