### ISSUE TITLE
Question on changing updateQuery toTypePolicies

### ISSUE THREAD

**Issue by iakovosvo** [apollographql/apollo-client#7649]
I am having a really hard time switching from updateQuery to the new read/merge ways to handle the cache.
My updateQuery looks like this, and this works fine:
```
updateQuery: (prev, { fetchMoreResult }) => {
        if (!fetchMoreResult) return prev;

        return {
          search: {
            items: [...prev.result.items, ...fetchMoreResult.result.items],
            token: fetchMoreResult.search.token,
            __typename: fetchMoreResult.result.__typename,
          },
        };
      },
```

However, I cannot find a good way to make this work using TypePolicies without having to write some super complex read and merge logic. I should mention that from the endpoint I am hitting, I can also search, using an optional `title` parameter.

**Comment by benjamn** [comment]
@iakovosvo Here's what I would try:
```ts
new InMemoryCache({
  typePolicies: {
    // Make sure this type name matches fetchMoreResult.result.__typename.
    SearchResults: {
      fields: {
        items: {
          // Keep search results separated by title.
          keyArgs: ["title"],
          // Concatenate the items if existing data is defined.
          merge(existing, incoming) {
            return existing ? [...existing, ...incoming] : incoming;
          },
          // You may not need a read function!
        },
      },
    },
  },
})
```
Since this policy handles `SearchResults.items` specifically, you shouldn't need to do anything special with `SearchResults.token` or `SearchResults.__typename`. Those fields will be automatically merged into the `SearchResults` object, based on the `incoming` data.

One potential drawback of this approach is that you won't be able to read all items from the cache by omitting the `title` argument. That will be considered a separate cache entry from the entries that have a `title`, and the client will probably need to make a separate request to get the full results. Another approach would be to use `keyArgs: false` to disable the `title` separation, and then use `args.title` in your `read` function to filter the results by title.

**Comment by iakovosvo** [comment]
Hey @benjamn thanks for your reply. Forgot to mention that I also have a `locale` optional parameter, if it makes any difference. I am trying to do it as you said right now:
```
    Feeds: {
      fields: {
        items: {
          keyArgs: ['title', 'locale'],
          merge(existing, incoming) {
            return existing ? [...existing, ...incoming] : incoming;
          },
        },
      },
    },
```
But `existing` returns _undefined_ when I hit `fetchMore`(I know the when it first loads it is always undefined). The second time I try with `fetchMore`, it gets filled with the exact same items as there are in `incoming`. Looks like a similar situation as [this one](https://github.com/apollographql/apollo-client/issues/6729) ? 


I've also tried with this 
```
    Query: {
      fields: {
        getFeeds: concatPagination(),
      },
    },
```
But I get a `Uncaught (in promise) RangeError: Invalid array length`
