### ISSUE TITLE
@apollo/client drops response data from MSW when it doesn't match the query exactly

### ISSUE THREAD

**Issue by xZarisx** [apollographql/apollo-client#7656]
I am using MSW to mock things for testing and found that my mock response was being dropped by apollo if it didn't match the query exactly. This makes sense but is maddening to work with because there is no warning that tells what is happening, there is just no data.

Also note that apollo adds `__typename` to your queries and those need to be added to the response.

It would be very helpful if there was some kind of console warning that data was drop because it didn't match the query instead of failing silently.

**Comment by johannesbraeunig** [comment]
Hey @xZarisx.
just saw your post and want to share my experience. Since we've configured the "possible types" correctly Apollo tells much more about missing fields, also seems to be more strict if it comes to reading/writing data with fragments. https://www.apollographql.com/docs/react/data/fragments/#using-fragments-with-unions-and-interfaces

**Comment by xZarisx** [comment]
Hey @johannesbraeunig, I added `possibleTypes` to my `InMemoryCache` but, only during tests, and it works like a charm! Thank you so much, this exactly what I was wanting!

**Comment by johannesbraeunig** [comment]
@xZarisx you're welcome! glad I could help you.

**Comment by Paul-Cl-ark** [comment]
This is a very nasty behaviour...
