### ISSUE TITLE
Implement fragment matching on union and interface type conditions

### ISSUE THREAD

**Issue by stubailo** [apollographql/apollo-client#771]
Right now, we just match as much as we can, but if union and interface types are being used heavily inside type conditions we need extra information to resolve those with confidence. This could be as simple as a tool that outputs a JSON map of concrete types to the interfaces and unions they are in.

**Comment by tmeasday** [comment]
@stubailo it might be helpful to post an example of what the problem is here so people can quickly tell if this is the cause of issues they are seeing quickly. (See e.g. https://github.com/apollostack/react-apollo/issues/386)

**Comment by helfer** [comment]
@tmeasday I think you're spot-on, and the issue you referenced is directly related to this. Although in that particular case, I think we might be able to do better by noticing that the droid type has more fields which all match, and no extra data, thus inferring that it's more likely to be a droid than a human.

Also, I'm not quite sure, but shouldn't having `__typename` be enough to help us figure this one out (since it's an interface and not a union type)?

**Comment by tmeasday** [comment]
> Also, I'm not quite sure, but shouldn't having __typename be enough to help us figure this one out (since it's an interface and not a union type)?

Possibly, although I wasn't sure if the example he posted was just an example and what he had going on was more complicated (i.e. the sub-fragment was an interface too).

**Comment by helfer** [comment]
Now tracking this in #1337
