### ISSUE TITLE
Duplicate requests are sent when using fetchPolicy: 'network-only' mode.

### ISSUE THREAD

**Issue by fxioi** [apollographql/apollo-client#7777]
**Intended outcome:**

When using the `fetchPolicy: 'network-only'` mode, send two Query requests and expect the same two requests to be displayed in the Developer Tools Network panel.

**Actual outcome:**

Using `fetchPolicy: 'network-only'` mode.
After the second request is sent, a third request is automatically sent, which is not made by my code.
```
================
network | ...
---------------------------
query (getPage)
query (getDetails)
query (getPage) // This is not the request I was expecting to send out.
================
```

Using `fetchPolicy: 'no-cache'` mode.
This is the result I was expecting, only the two requests I wanted to send were in the Developer Tools network panel.
```
================
network | ...
---------------------------
query (getPage)
query (getDetails)
================
```

**How to reproduce the issue:**

```javascript
    // query bnGetPage($input: PageRequest!) {
    //   bnGetPage(input: $input) {
    //     items {
    //       ...Common
    //     }
    //     total
    //   }
    // }

    // query bnGetDetails($id: ID!) {
    //   bnGetDetails: bnGetPage(input: { id: $id, page: 1, pageSize: 1 }) {
    //     items {
    //       ...CommonAll
    //     }
    //     total
    //   }
    // }

  testQ() {
    this.apollo
      .watchQuery({
        query: this.pg.document,
        variables: { input: { page: 1, pageSize: 10 } },
        // fetchPolicy: 'no-cache',
        fetchPolicy: 'network-only', // error is in this mode
      })
      .valueChanges.subscribe();

    // Request details once after 3 seconds
    setTimeout(() => {
      this.apollo
        .query({
          query: this.dg.document,
          variables: { id: '1366338849696905664' },
          fetchPolicy: 'network-only',
        })
        .subscribe();
    }, 3000);
```

**Versions**

```
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.15.5 - D:\develop\nodejs\node.EXE
    Yarn: 1.22.10 - D:\develop\ng\exam-admin\node_modules\.bin\yarn.CMD
    npm: 6.14.11 - D:\develop\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.428
```

**Comment by benjamn** [comment]
@fxioi This is expected behavior given `fetchPolicy: "network-only"`, but it sounds like you want `network-only` only for the first `getPage` request, followed by `cache-first` after that. To achieve that behavior, the `nextFetchPolicy: "cache-first"` option is probably what you want. See https://github.com/apollographql/apollo-client/issues/7689#issuecomment-780086202 for a similar issue/explanation.

**Comment by fxioi** [comment]
I'm sorry I still don't understand a little bit, let me describe my usage scenario again.
`getPage` is a paginated list request and I want it to be network-first all the time, I looked again at the official documentation https://www.apollographql.com/docs/react/data/queries/#setting-a-fetch-policy and currently `no cache` is available, and I tried `cache-and-network` again and found that a `getPage` request is also automatically issued after a `getDetails` request.

My question now is, why does a request for `getDetails` trigger an automatic request for `getPage`? Is it because getDetails is an alias for bnGetPage, and they are essentially the same api?

My understanding is that `getPage` just gets the list and `getDetails` just gets the details, just with more fields, am I using it the wrong way?

But if in the case where two requests are sent above (using network-only).
```
================
network | ...
---------------------------
query (getPage)
query (getDetails)
query (getPage) // This is not the request I was expecting to send out.
================
```
If I continue to send `getDetails` with the same variables, it won't trigger that `getPage` again.
```
================
network | ...
---------------------------
query (getPage)
query (getDetails)
query (getPage) // This is not the request I was expecting to send out.
query (getDetails)
================
```
If I send another `getDetails` with a different id, it will still trigger the automatic sending of `getPage`.

That means after sending `getPage` once, only `getDetails` with different parameters will trigger the automatic request of `getPage`, if it has already been requested, sending `getDetails` again will not trigger the automatic request of `getPage`.

**Comment by benjamn** [comment]
@fxioi Both of those queries are updating the same data in the cache, namely the field `Query.bnGetPage`. The `bnGetDetails:` alias doesn't make a difference.

Even though the `getPage` query has a fetch policy of `network-only`, it also watches the cache for changes from other queries updating the same data, which `getDetails` does. With a fetch policy of `network-only`, the only possible response to those cache changes is to refetch the query over the network, hence the extra `getPage` request.

If you use `cache-and-network` instead of `network-only`, you get both a cache result and a network result when relevant data in the cache are updated, so there's still (always) a network request.

The `cache-first` fetch policy is typically what folks want when a complete result from the cache should prevent another network request, which is why I recommended switching to that with `nextFetchPolicy: "cache-first"` above.

As a side note, it is possible to use the arguments passed to the `bnGetPage` field to keep the field data separate for different queries that use that field (with different arguments). By default, however, the cache doesn't know what your `input` argument means, so any change to the `Query.bnGetPage` field (regardless of arguments) triggers an update for any query that previously consumed that field. This is all explained in our [pagination documentation](https://www.apollographql.com/docs/react/pagination/overview/). The `keyArgs` field policy option lets you handle different arguments separately, but I recommend reading the rest of that documentation to get a complete mental model.

**Comment by fxioi** [comment]
@benjamn 
I will try to use `nextFetchPolicy `, although I still don't quite understand it, and I will continue to read the documentation.
Thank you for your reply.
