### ISSUE TITLE
Refetch query don't trigger `watchQuery.subscribe` when query network policy is `no-cache`

### ISSUE THREAD

**Issue by denis-manokhin** [apollographql/apollo-client#7830]
Simple example:

```js
client
  .watchQuery({
    query: getEntitiesDocument,
    fetchPolicy: "no-cache",
  })
  .subscribe((response) => {
    // this callback don't called after refetch
  });

client
  .mutate({
    mutation: createEntityDocument,
    refetchQueries: [{ query: getEntitiesDocument }],
  })
  .then(() => {});
```

**Intended outcome:**
`watchQuery.subscribe` called after refetch

**Actual outcome:**
`watchQuery.subscribe` don't call

**How to reproduce the issue:**
Reproduction on [codesandbox](https://codesandbox.io/s/gracious-napier-sds7b).

**Comment by jcreighton** [comment]
@denis-manokhin This is expected behavior but here are some options that'll work:

Use `network-only` instead of `no-cache`. Queries with the `no-cache` fetch policy do **not** watch the cache for changes (since you are explicitly telling that query to skip reading from the cache). A `network-only` policy _will_ watch the cache for changes. 

Or if `no-cache` is a requirement, instead of `refetchQueries: [{ query: getEntitiesDocument }]`, try `refetchQueries: ["GetEntities"]`. Working example [here](https://codesandbox.io/s/youthful-shamir-mzl7v). Using the query name with `refetchQueries` ensures any watched queries with that name are refetch, _including_ queries with a `no-cache` fetch policy.
