### ISSUE TITLE
context object as part of the mutation result is missing

### ISSUE THREAD

**Issue by omerman** [apollographql/apollo-client#7843]
**Intended outcome:**
mutation option, `update`, should include the context object as part of the result arg, as the typescript type suggests.

I am trying to create a default update method for my mutations,
so instead of having an update method for each useMutation call, I will have some sort of manager to redirect to the correct cache update necessary.. 
```
export const apolloClient = new ApolloClient({
  cache: new InMemoryCache(),
  link: ApolloLink.from([
    contextLink,
    httpLink,
  ]),
  defaultOptions: {
    mutate: {
      context: { tryingThatAsWell: true },
      update: (cache, result) => {
       console.log(result.context) // this prints undefined... :(
        mutationUpdatersManager.update(cache, result);
      },
    },
  },
});
```

**Actual outcome:**

The `result` arg does not include the context of the mutation request..
```
...
console.log(result.context) // this prints undefined... :( <---- This is my problem really..
...
```

**How to reproduce the issue:**

```
// This client should do it.. if you have a graphql server with any mutation, when the update function runs, the result will not contain the context field.

export const apolloClient = new ApolloClient({
  cache: new InMemoryCache(),
  link: ApolloLink.from([
    contextLink,
    httpLink,
  ]),
  defaultOptions: {
    mutate: {
      context: { tryingThatAsWell: true },
      update: (cache, result) => {
       console.log(result.context) // this prints undefined... :(
        mutationUpdatersManager.update(cache, result);
      },
    },
  },
});
```

**Versions**

  System:
    OS: macOS 11.2.2
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.82
    Firefox: 81.0.2
    Safari: 14.0.3
  npmPackages:
    @apollo/client: ^3.3.11 => 3.3.11 

Looking froward for your response,
Thank you :)

**Comment by benjamn** [comment]
@omerman Thanks for noticing this oversight!

Some thoughts for anyone who is tempted to implement this:

* Although the [`FetchResult`](https://github.com/apollographql/apollo-client/blob/49b45e311987cb73b7be038c43acd9a761c6ac46/src/link/core/types.ts#L23-L31) type conveniently already has an optional [`context`](https://github.com/apollographql/apollo-client/blob/49b45e311987cb73b7be038c43acd9a761c6ac46/src/link/core/types.ts#L30) field, I wonder if we should also think about the best way to pass other potentially useful information to the `update` function, like the `variables` that were used for the mutation.
* If we go down this path, I think the `update` function should take an object as its third parameter, containing various properties that you can use/ignore, rather than taking separate arguments for each additional piece of information. That's how I would have imagined `context` would be provided, rather than sticking it onto the `FetchResult` (though we could easily provide it both ways).

**Comment by omerman** [comment]
@benjamn I wanted context to be passed so I can store on the context the request of the mutation itself.. I think it makes sense to pass third argument to be the request itself.. which should already include the variables and the context is it?

I think it will be ideal if possible: `update(cache, result, request)`

```ts
export interface GraphQLRequest {
    query: DocumentNode;
    variables?: Record<string, any>;
    operationName?: string;
    context?: Record<string, any>;
    extensions?: Record<string, any>;
}
```

**Comment by omerman** [comment]
@benjamn 2 things -

1. I also think that inside update we should have a way to know if it is the optimistic update or not.
2. Should I move this issue to feature request repo?
