### ISSUE TITLE
Cache doesn't work when formatResponse is used

### ISSUE THREAD

**Issue by lkaratun** [apollographql/apollo-client#7854]
I'm fetching data using `useQuery` hook from apollo server using a formatter (`formatResponse`). In the playground and in the devtools I see that the response from apollo server is correct. However, `data` returned by `useQuery` is `undefined`. 

If I add the `fetchPolicy: "no-cache"` to `useQuery`, everything works. If I delete the `formatReponse` function, everything also works. It just doesn't work together.

![image](https://user-images.githubusercontent.com/17469132/111425711-cad11c00-86b0-11eb-9e3f-11db8edb4215.png)
![image](https://user-images.githubusercontent.com/17469132/111425783-e2a8a000-86b0-11eb-8b7e-76df4633e4bc.png)

**Intended outcome:**
`useQuery` returns correct data

**Actual outcome:**
`useQuery` returns `undefined`

**How to reproduce the issue:**

Front end:
```
import { gql, useQuery } from "@apollo/client";

const getActivitiesQuery = gql`
  query getActivities {
    activities {
      id
      name
    }
  }
`;

export default function createActivityForm() {
  const { error, data, loading, refetch } = useQuery(getActivitiesQuery);
  console.log("data = ", data); // this is undefined
```

Back end:
```
import { ApolloServer } from "apollo-server-express";
const server = new ApolloServer({
  ...
  formatResponse: (response, requestContext) => {
      return { data: {test: 123} }; // doesn't work
      return { data: response.data }; // works
  }
```

**Versions**

  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.82
    Firefox: 78.7.0
    Safari: 14.0.3
  npmPackages:
    @apollo/client: ^3.3.12 => 3.3.12
    next-with-apollo: ^5.1.1 => 5.1.1

**Comment by benjamn** [comment]
@lkaratun Cache writes are driven/guided by the structure of the query, so if the data you're writing doesn't contain any of the fields expected by the query, nothing will be written to the cache. Maybe try `return { data: { activities: [...] }}` instead?

**Comment by lkaratun** [comment]
Thanks for the reply @benjamn!

I used `{test: 123}` for demonstration purposes only, didn't know it would change the result. My actual goal is roughly to convert an array of objects into an object of objects by using `lodash.keyBy`.

I tried the simplified version and it seems you're right, replacing an array with an object is what breaks things:
```
return {data: {activities: []}}; // works
return {data: {activities: {}}}; // doesn't work
```
But I still need an object to take advantage of O(1) lookups by ID. And I'd prefer to take advantage of caching. Is there a way to do it? I tried other caching strategies like `cache-and-network` but nothing except `no-cache` works.

What I don't understand is why does apollo expect an array? It's not like the server responds with an array the first time and then starts responding with an object. The object is returned every single time.

**Comment by benjamn** [comment]
@lkaratun Bad news first. When you use `{data: {activities: {}}}`, that `{}` gets interpreted as a single object that must match the selection set `{ id name }`. When you use `{data: {activities: []}}`, that `[]` gets interpreted as a(n empty) list of objects that must each individually match the selection set `{ id name }`. If your `data.activities` is a dictionary with keys other than `id` or `name`, it's as if your server responded with data that does not match your query, so it's unclear what the client should do with that response.

This is not an Apollo Client-specific behavior. If GraphQL had a notion of dictionaries or sets in addition to lists, what you're doing might make sense, but the only arbitrary-size container-like data structure GraphQL gives us is the list.

Good news: thanks to `InMemoryCache`'s automatic normalization of entity objects, these `Activity` objects will be indexed by their `__typename` and `id` even if they arrive from the network in the form of a list. To see this in action, you can define another root `Query` field, `Query.activity(id: string)`, that returns any matching activity from the cache, when possible, falling back to the network otherwise:
```ts
new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        activity(existing, { args, toReference }) {
          return existing || toReference({
            __typename: "Activity",
            id: args.id,
          });
        },
      },
    },
  },
})
```
Another way to see this indexing in action is to use `cache.readFragment`:
```ts
const result = cache.readFragment({
  id: cache.identify({
    __typename: "Activity",
    id: someActivityId,
  }),
  fragment: gql`
    fragment ActivityFragment on Activity {
      id
      name
    }
  `,
```
The `result` will be `null` if the activity could not be found in the cache. Otherwise you'll get an object with the shape `{ id name }` in O(1) time (no matter how many activities there are in the cache).

Yet another way to understand this system: have a look at `cache.data.data` after you've fetched a query like `GetActivities`. You should see a number of entries in that map with keys like `Activity:<id>`, and object values representing the fields of each activity.

If you're using the `Query.activity` approach, and your server does not support this `Query.activity` field (or something like it), you can mark the field as client-only in your query:
```graphql
query GetActivity ($id: string) {
  activity(id: $id) @client {
    id
    name
  }
}
```
Since it seems like you're also building a server, I would recommend implementing the `Query.activity` field on the server, just so you have a safe fallback.

**Comment by lkaratun** [comment]
Thank you so much for the detailed explanation @benjamn! I'll try the approaches you suggested.
