### ISSUE TITLE
Local resolvers should not be deprecated as long as type policies can't fully replace them

### ISSUE THREAD

**Issue by omerman** [apollographql/apollo-client#7855]
Hi all,
I understand that local resolvers will be deprecated in favor of type policies.. But type policies do not give us the same strength as local resolvers do!

1. Local resolvers are async, the `read` function over a type policy field is sync, or at least thats the signature of it when looking at the TS definition.
2. Local resolvers can access the entire parent, while the `read` function seems to only be able to access the current value.

This two key differences makes local resolvers way powerful and meaningful. unless there is a way to do both using type policies, deprecating it will make Apollo lose some of it's important abilities.

Thanks again for your amazing work,
Looking forward for your response :)

**Comment by benjamn** [comment]
@omerman Although you closed this, I just want to say we're aware of the remaining gaps in functionality, and we will not fully remove the `LocalState` functionality until we feel like we have a full replacement. Providing a single parent object may not be possible, though, since the current entity may have multiple parent objects in the graph.

**Comment by omerman** [comment]
Thank you, I decided to close it cause I realized that apollo will probably bring suitable replacement for the gaps before fully drop this, as u said urself 😏
