### ISSUE TITLE
Partial Refetch + Type Policy (equivalent of cache redirect) causes loop

### ISSUE THREAD

**Issue by cpsnowden** [apollographql/apollo-client#7861]
**Intended outcome:**
- Having enhanced the Country example (https://github.com/trevorblades/countries/tree/master/examples/react) to support single country queries (https://codesandbox.io/s/countries-graphql-api-example-forked-skusz?file=/src/index.js) - similar to https://www.youtube.com/watch?v=ou0fEW1eRjc
- A type policy was added to handle country lookups when the country was already cached (drop in for cache redirect). 
```
typePolicies: {
      Query: {
        fields: {
          country: {
            read: (existing, { toReference, args }) => {
              const contryRef = toReference({
                __typename: "Country",
                _id: args.code
              });
              return existing ?? contryRef;
            }
          }
        }
      }
    }
```
- When a partialRefetch flag was set on the country query 
```
const {
    data: countryData,
    loading: countryLoading,
    error: countryError
  } = useQuery(GET_COUNTRY, {
    client,
    variables: { code },
    skip: code.length < 1,
    partialRefetch: true
  });
```
- Would expect when a code is used for a country that does not exist s(e.g. below), then the result from 'data.country' should be null

```
{
  country(code:"U")
  {
    __typename
    code
  }
}
```
```
{
  "data": {
    "country": null
  }
}
```

**Actual outcome:**
Enters an infinite loop, sending repeated network requests. 

**How to reproduce the issue:**

Repro available in sandbox https://codesandbox.io/s/countries-graphql-api-example-forked-skusz?file=/src/index.js.

Try typing a code for a non existent country e.g. "U" - leads to loop with multiple network requests.

**Versions**

@apollo/client 3.4.0-beta.15
<img width="407" alt="Screenshot 2021-03-18 at 22 50 52" src="https://user-images.githubusercontent.com/15384031/111707669-6642c800-883c-11eb-8ecc-e5d0de792d35.png">

**Comment by brainkim** [comment]
Hello @cpsnowden! Thank you so much for this bug report and reproduction. It led me down a rabbit hole which taught me a lot about interactions between Apollo Client’s cache and link abstractions. Surprisingly, after discussion with the team, it appears that `partialRefetch` is a candidate for deprecation, so I’ve created an additional issue to track that (https://github.com/apollographql/apollo-client/issues/7967). You were probably, like I, misled by the text [for `partialRefetch` in the options](https://www.apollographql.com/docs/react/data/queries/#options), which indicate that `true` should be the default for the option and is only `false` for legacy reasons. This is incorrect advice, and when using a `cache-first` fetch policy, apollo-client will correctly attempt to make a request for the missing country reference if it doesn’t exist! The `partialRefetch` option itself is actually a legacy thing which hasn’t been touched since `react-apollo` was added to this repository.

[Here is an updated codesandbox](https://codesandbox.io/s/countries-graphql-api-example-forked-mf230?file=/src/index.js) which demonstrates how what you may have intended to write without the `partialRefetch` option, proving that it works fine. Here’s the code inline as well.

```jsx
import React, { useState } from "react";
import ReactDOM from "react-dom";
import { ApolloClient, InMemoryCache, gql, useQuery } from "@apollo/client";

const client = new ApolloClient({
  cache: new InMemoryCache({
    typePolicies: {
      Query: {
        fields: {
          country: {
            read: (existing, { toReference, args }) => {
              const countryRef = toReference({
                __typename: "Country",
                _id: args.code
              });
              return existing ?? countryRef;
            }
          }
        }
      }
    }
  }),
  uri: "https://countries.trevorblades.com"
});

const LIST_COUNTRIES = gql`
  query countries {
    countries {
      _id: code
      code
      name
    }
  }
`;

const GET_COUNTRY = gql`
  query country($code: ID!) {
    country(code: $code) {
      _id: code
      code
      name
    }
  }
`;

function CountrySelect() {
  const [code, setCode] = useState("");
  const {
    data: countriesData,
    loading: countriesLoading,
    error: countriesError
  } = useQuery(LIST_COUNTRIES, { client });
  const { data: countryData, error: countryError } = useQuery(GET_COUNTRY, {
    client,
    variables: { code },
    skip: code.length < 1
  });

  if (countriesLoading || countriesError) {
    return (
      <p>{countriesError ? countriesError.message : "Loading Countries..."}</p>
    );
  }

  if (countryError) {
    return <p>{countryError.message}</p>;
  }

  return (
    <div>
      <input
        type="text"
        value={code}
        onChange={(event) => setCode(event.target.value)}
      />
      <div>
        <h4>Name: {countryData?.country?.name}</h4>
      </div>
      <ul>
        {countriesData.countries.map((country) => (
          <li key={country.code}>
            {country.name} ({country.code})
          </li>
        ))}
      </ul>
    </div>
  );
}

ReactDOM.render(<CountrySelect />, document.getElementById("root"));
```

You can track #7967 to stay up to date on the future of `partialRefetch`, including docs changes and refactorings. Again, thank you so much for opening this issue and providing a reproduction! I’m closing this issue for housekeeping purposes, but feel free to reopen it or comment if I haven’t fully addressed your issue.

---

BELOW ARE THE NITTY GRITTY TECHNICAL DETAILS FOR POSTERITY. THEY MIGHT NOT MAKE SENSE TO PEOPLE WHO DO NOT READ THROUGH APOLLO CLIENT CODE.

When a “reference” (an object with a `__ref` property) is returned from a field for an id which doesn’t exist in the cache, `StoreReader.execSelectionSetImpl` returns an empty object, somehow (this is buried in `optimism` callbacks?) causing the wrapped `StoreReader.executeSelectionSet` to return an object with the queried value set to an empty object, and a missing array containing one error stating `Dangling reference to a missing country:${whateverTheKIdWas}`. Typically, this would throw that error, but `StoreReader.diffQueryAgainstStore`, the function which calls the `executeSelectionSet` is passed an additional option which is always `true` which squelches that error. The “diff” returned from this latter function is later used (this process is complicated), in `QueryManager.fetchQueryByPolicy`, which detects that the diff is incomplete, and makes a network request with the Apollo link.

The `HttpLink` which is connected to the example API returns `{country: null}` because the code likely doesn’t exist. Because the network request has fulfilled, it triggers another render of the component, and this calls among other things `QueryData.getCurrentResult`, which in turn calls `ObservableQuery.getCurrentResult`. This kicks off another cache/diffing process, but somehow the result of `{country: null}` is erased at the end of this long process, and the function returns a `currentResult` where `data` is `undefined` and `loading` is `false`.

Now here’s the funny part. Because `partialRefetch` is set to `true`, and because there may have at one point been an edge-case where a mutation which sets fewer fields on a query causes `undefined` to be returned as the `data` property of `currentResult` at some point, there is [this branch of code](https://github.com/apollographql/apollo-client/blob/3a4b0d628a43cf677a24f5b18793df0ab112824d/src/react/data/QueryData.ts#L395-L415) which appears to set the `currentResult` to a `loading` state and cause a `refetch`. Removing these lines of code would stop the infinite loop, but it appears that the test suite is explicitly testing for the existence of this logic, without describing which edge case it was meant to solve, so I am not going to touch it with a 10 foot stick.

Thankfully, `partialRefetch` is unnecessary, and I have confirmed that setting it false seems to work. So whatever.

**Comment by cpsnowden** [comment]
Thank @brainkim for the in-depth analysis! Also confirmed that removing `partialRefetch` on the repro fixed the issue. Thanks for confirming that this is a candidate for deprecation and is redundant with a `cache-first` policy.
