### ISSUE TITLE
How to get the existing field without references to normalised objects

### ISSUE THREAD

**Issue by rossm6** [apollographql/apollo-client#7883]
I have a read function for a field defined in a typePolicy which looks ridiculous because I'm using ```readField``` so many times to grab what I need.  Is there a way of getting all the objects in the existing field without having to grab it manually with readField?

**My Context -**

```
const SQUARES_LIST_QUERY = gql`
  query LOAD_SQUARES ($first: Int, $after: String) {
    viewer {
      id
      squares(first: $first, after: $after) {
        edges {
          node {
            pk
            id
          }
          cursor
        }
        pageInfo {
          hasNextPage
          hasPreviousPage
          startCursor
          endCursor
        }
      }
    }
  }
`;
```

I want to implement a ```read``` function for the ```squares``` field based on node attributes.  Because the node is a normalised object the existing object passed to the ```read``` function receives only references to the nodes.  I therefore have to grab these fields using ```readField``` and construct objects myself to represent the node object where I include the keys ```pk```, ```id```, and ```__typename```.

Is it possible to just get everything at once?

I noticed that ```cache``` is passed to the read function and the flat lookup table is located at ```cache.data.data``` but I'm assuming it's a bad idea to access this directly.

**Comment by benjamn** [comment]
@rossm6 The `readField` helper function has two primary benefits:
* When you call `readField`, it registers a dependency on the field you're reading, so the current query can be invalidated in the future, when/if that field changes again. The precision of this dependency system depends on reading only the fields you care about, not whole objects.
* The `readField` function works the same way whether you pass a reference as the second argument or an ordinary object, so you shouldn't have to change your field policy code to accommodate those different possibilities (if you just stick to `readField`).

Since it looks like you're implementing a field policy for cursor-based pagination, it's not surprising you're finding it somewhat complicated. Here's our [`relayStylePagination`](https://github.com/apollographql/apollo-client/blob/da0a0e52b7b4b0743e9ee01c43e6adf1fa98553d/src/utilities/policies/pagination.ts#L88-L93) helper, for comparison. Writing this kind of code isn't easy, but you only have to get it right once, and it will be applied consistently whenever anyone reads from or writes to the cache.

You might be tempted to call `cache.readFragment` in the `read` function to read a fragment's worth of fields. This will work, but it involves more overhead than just using `readField`.

Though that's how things work today, I could imagine providing a helper called `readFields` (plural) that takes a selection set (and `variables` for any field arguments), and returns an object. Would that be helpful here?

**Comment by rossm6** [comment]
Yes that would be a good feature I think.
