### ISSUE TITLE
QueryResult.fetchMore() triggers unexpected refetch of indirectly related "cache-and-network" queries

### ISSUE THREAD

**Issue by zenflow** [apollographql/apollo-client#7939]
**Intended outcome:**
When I call `query.fetchMore()` I expect this to never affect other queries or cause the other queries to be refetched.

**Actual outcome:**

When I call `query.fetchMore()` it **sometimes** causes a refetch of some "cache-and-network" query on the page.

It seems to happen when both queries (the one for which we call `query.fetchMore()` and the one that uses `fetchPolicy: "cache-and-network"`) request data inside a common object type (e.g. `__typename: "User"`).

**How to reproduce the issue:**

1. Create or find an AC app where `query.fetchMore()` is used on a query that shares data with other queries shown on-screen
2. Change the `fetchPolicy` for the other queries to "cache-and-network"
3. Start the app, open it, open the network tab in Chrome devtools
4. Trigger the `query.fetchMore()` in the app
5. Observe that the other queries (which were set to "cache-and-network") are refetched after first (expected) request

**Versions**
@apollo/client v3.3.13

**Comment by Akryum** [comment]
Maybe related to #6916

**Comment by benjamn** [comment]
This does sound like the same issue as #6916—see my thoughts in https://github.com/apollographql/apollo-client/issues/6916#issuecomment-901466918.

The central idea is that **complete** cache results (broadcast after a successful `fetchMore`, for example) should be delivered immediately, by themselves, without triggering a network request for fetch policies like `cache-and-network` or `network-only`. Setting `nextFetchPolicy: "cache-first"` is a good workaround in the meantime because `cache-first` similarly avoids the network given a complete cache result.

I am actively working on that issue for v3.6. Unfortunately there are a number of test differences to work through, and those disruptions (even if they're ultimately improvements, like fewer network requests) needed more intensive beta testing than we thought we could get before v3.5 was released. I'm still hopeful it will be safe for a minor release (rather than AC4).

Closing this as a duplicate (please join the discussion in #6916), but happy to reopen if my planned changes don't (seem like they will) solve the whole problem here as well.

**Comment by gastonmorixe** [comment]
thank you @benjamn
