### ISSUE TITLE
Apollo client calls `JSON.stringify` unnecessarily on objects with correct `__typename__`

### ISSUE THREAD

**Issue by Pet3ris** [apollographql/apollo-client#7961]
**Intended outcome:**

Trying to return a GraphQL query with a 200 KB response limit, more here: https://github.com/apollographql/apollo-client/discussions/7958

**Actual outcome:**

Apollo causes an exception when trying to call `JSON.stringify` on my object. It's caused by the following code:

![image](https://user-images.githubusercontent.com/224585/113903294-ba502500-97c8-11eb-853b-bc10e48bdc03.png)

Even though `obj` has a valid `__typename__` (it's produced by graphene), the `JSON.stringify` expression still gets called in apollo.

**How to reproduce the issue:**

If not mistaken this `JSON.stringify` operation is run on every simple query.

**Versions**

```
Ok to proceed? (y) y

  System:
    OS: macOS 11.2.2
  Binaries:
    Node: 15.11.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 87.0
    Safari: 14.0.3
  npmPackages:
    @apollo/react-hooks: ^3.1.5 => 3.1.5 
    reason-apollo: ^0.20.0 => 0.20.0 
    reason-apollo-hooks: ^6.0.0 => 6.0.1 
```

**Comment by benjamn** [comment]
@Pet3ris Although `reason-apollo` is under the https://github.com/apollographql GitHub organization, it is not maintained by the Apollo team, and it appears to be using the old `apollo-client` package(s) from Apollo Client 2.

I can't speak to what sort of maintenance `reason-apollo` will receive in the future (the latest commit was almost a year ago), but I can say the behavior of error messages has changed quite a bit in Apollo Client 3.x, allowing the message argument to be stripped out entirely when your minifier is configured to eliminate unreachable code (to name just one improvement).

I know this is not great news because Reason is such an interesting language. Here's an existing `reason-apollo` PR that seems like it might be promising: https://github.com/apollographql/reason-apollo/pull/209.

**Comment by Pet3ris** [comment]
Thanks Ben - it’s really helpful to confirm the issue. I think the latest version is rescript-apollo using client version 3 so I’ll move to that!

**Comment by Pet3ris** [comment]
Verified that this is fixed in v3.
