### ISSUE TITLE
When `useReactiveVar` is used in an async callback which awaits a promise, successive updates are not rendered

### ISSUE THREAD

**Issue by brainkim** [apollographql/apollo-client#8012]
[Reported by @KonstantinLypskyi](https://github.com/apollographql/apollo-client/issues/7614#issuecomment-823319446).
**Intended outcome:**
The following code should render `1` when the button is pressed.

**Actual outcome:**
`2` is rendered instead.

**How to reproduce the issue:**
https://codesandbox.io/s/use-reactive-var-qobw1?file=/src/App.jsx

**Versions**
TODO

**Comment by benjamn** [comment]
@brainkim This seems to be a bug. The relationship between the reactive variable and the cache is established when you read from the variable (in this case using `useReactiveVar`), but you should be able to update the variable from anywhere.

**Comment by benjamn** [comment]
For what it's worth, [this code](https://codesandbox.io/s/use-reactive-var-forked-h3tmm?file=/src/App.jsx) seems to fix the problem:
```ts
const counterVar = makeVar(0);
let nextCount = 1;

const App = () => {
  const counter = useReactiveVar(counterVar);

  const handleClick = async () => {
    await new Promise((resolve) => {
      setTimeout(resolve, 100);
    });

    // counterVar(2);
    // counterVar(1);
    counterVar(nextCount++);
  };

  return (...);
};
```
In other words, if you make sure that the counter always changes with each click, the broadcast happens as expected. However, I would have thought `counterVar(2)` followed by `counterVar(1)` would achieve the same affect (since the count _is_ changing), so that may still be a bug worth investigating.

**Comment by brainkim** [comment]
I’ll look into this as a way to familiarize myself with the reactive var code, unless there are objections or someone else is already looking into it.
