### ISSUE TITLE
MockedLink expects optional variables with default values to be defined in mocked queries

### ISSUE THREAD

**Issue by dannycochran** [apollographql/apollo-client#8023]
**Intended outcome:**

Given this query:

```graphql
query GetFoo($id: ID!, $includeFooBar: Boolean = false) {
  ...
}
```

Be able to provide a mock which does not include a value for `$includeFooBar` if my actual invocation isn't passing it, e.g:

Actual invocation in my app:

```typescript
// getFoo.ts

// Never passes `includeFooBar
const response = useQuery(GetFooDocument, { variables: { id: 5 } });
```

Mocks setup:

```typescript
// testGetFoo.spec.ts

const mocks: ApolloMockedResponse<any>[] = [{
  response: { ... }
  request: {
    query: GetFooDocument,
    variables: { id: 5 }
  }
}]
```

This mock should work correctly since my actual invocation is not passing `includeFooBar`

**Actual outcome:**

The mock fails because `includeFooBar` is expected to be explicitly passed in the mock above. The comparison of variables here flushes out the default values and does not account for them being optional:

https://github.com/apollographql/apollo-client/blob/9b766ad36e6d9097bd6fd87416488bbcd7612589/src/utilities/testing/mocking/mockLink.ts#L80

**How to reproduce the issue:**

The code snippet above.

**Versions**

  System:
    OS: macOS 11.2.2
  Binaries:
    Node: 12.18.4 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/npm-global/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.85
    Safari: 14.0.3
  npmPackages:
    @apollo/client: ^3.3.15 => 3.3.15 
    apollo-upload-client: 14.1.3 => 14.1.3 
    apollo3-cache-persist: 0.9.1 => 0.9.1 
  npmGlobalPackages:
    apollo: 2.27.0

**Comment by jesusfraguio** [comment]
Hello! I have just faced the same issue, it´s quite impressive after 3 years MockedLink and @apollo/client/core still facing this issue in 3.9.11.  There is no way to test a query hook which gql includes an optional variable, therefore breaking graphql RFC spec.

My query hook is returning an ApolloError, which is a network error with message "Cannot read properties of undefined (reading 'type')".

In my case the query is mocked "properly" but the query's hook throws an error. Last line of this fragment being executed of @apollo/client/core/core.cjs  which is inFlightLinkObservables_1.remove(printedServerQuery_1, varJson_1) you might locate in QueryManager.prototype.getObservableFromLink, but I think the bug is directly related to MockedLink as this only happends with that link type.

`QueryManager.prototype.getObservableFromLink = function (query, context, variables,
    deduplication) {
        var _this = this;
        var _a;
        if (deduplication === void 0) { deduplication = (_a = context === null || context === void 0 ? void 0 : context.queryDeduplication) !== null && _a !== void 0 ? _a : this.queryDeduplication; }
        var observable;
        var _b = this.getDocumentInfo(query), serverQuery = _b.serverQuery, clientQuery = _b.clientQuery;
        if (serverQuery) {
            var _c = this, inFlightLinkObservables_1 = _c.inFlightLinkObservables, link = _c.link;
            var operation = {
                query: serverQuery,
                variables: variables,
                operationName: utilities.getOperationName(serverQuery) || void 0,
                context: this.prepareContext(tslib.__assign(tslib.__assign({}, context), { forceFetch: !deduplication })),
            };
            context = operation.context;
            if (deduplication) {
                var printedServerQuery_1 = utilities.print(serverQuery);
                var varJson_1 = cache.canonicalStringify(variables);
                var entry = inFlightLinkObservables_1.lookup(printedServerQuery_1, varJson_1);
                observable = entry.observable;
                if (!observable) {
                    var concast = new utilities.Concast([
                        core.execute(link, operation),
                    ]);
                    observable = entry.observable = concast;
                    concast.beforeNext(function () {
                        inFlightLinkObservables_1.remove(printedServerQuery_1, varJson_1);
                    });
                }
            }`.

My debugger says just before remove function being called:

`printedServerQuery_1 = "query productsImage($input: [ProductDetailInput!]!, $size: Size!, $photoType: PhotoType = plane) {\n  productsDetail(input: $input) {\n    id\n    colorId\n    image(size: $size, photoType: $photoType)\n    __typename\n  }\n}" 

varJson_1= "{\"input\":[{\"articleId\":1,\"colorId\":1},{\"articleId\":2,\"colorId\":2},{\"articleId\":3,\"colorId\":3},{\"articleId\":4,\"colorId\":4},{\"articleId\":5,\"colorId\":5},{\"articleId\":6,\"colorId\":6},{\"articleId\":7,\"colorId\":7},{\"articleId\":8,\"colorId\":8},{\"articleId\":9,\"colorId\":9}],\"photoType\":\"plane\",\"size\":\"SMALL\"}" ` 

It is even failing when passing the optional value as you can see in variables, so it must be related to query's optional parsing $photoType: PhotoType = plane
The error is propagated through Observable, but has its source even further. I could not stop the debugger on mocked-link.js but it seems it might fail in this function `MockLink.prototype.normalizeMockedResponse = function (mockedResponse) {
        var _a;
        var newMockedResponse = cloneDeep(mockedResponse);
        var queryWithoutConnection = removeConnectionDirectiveFromDocument(newMockedResponse.request.query);
        invariant(queryWithoutConnection, 64);
        newMockedResponse.request.query = queryWithoutConnection;
        var query = removeClientSetsFromDocument(newMockedResponse.request.query);
        if (query) {
            newMockedResponse.request.query = query;
        }
        mockedResponse.maxUsageCount = (_a = mockedResponse.maxUsageCount) !== null && _a !== void 0 ? _a : 1;
        invariant(mockedResponse.maxUsageCount > 0, 65, mockedResponse.maxUsageCount);
        this.normalizeVariableMatching(newMockedResponse);
        return newMockedResponse;
    };`


> You can replicate it easily with any query with optional parameter and import { MockLink } from "@apollo/client/testing";

**Comment by phryneas** [comment]
That said, I think I can see the confusion here: By the time the query reaches the `MockLink`, the variable defaults have already been filled in, so if you send a query with `variables: {}` from Apollo Client, and there's a variable defined with a default value like `GetTodo($id: ID = 1)`, then the Link will already be called with `variables: { id: 1 }`.
Your mocks need to contain these values to match up.
