### ISSUE TITLE
Problem in merging mutation's response sub-types with cache data

### ISSUE THREAD

**Issue by foad-salawati** [apollographql/apollo-client#8108]
I describe this problem with a simple example. I have this mutation to update a user data:
```js
const UPDATE_USER = gql`
    mutation UpdateUser($id: ID!, $update: UpdateUserInput!) {
        updateUser(id: $id, update: $update) {
            id
            social {
                telegram
            }
        }
    }
`;
client.mutate({
    mutation: UPDATE_USER,
    variables: {
        id: "123456", 
        update: {
            social: {  
                 telegram: "new_tg_id"
            }
        }
    },
})
```
I have the user in cache store from an other INIT_QUERY and cache data is:

```js
User:123456 {
     id: "123456",
     name: "james",
     social: {
          telegram: "tg_id",
          facebook: "fb_id",
          instagram: "ig_id"       
     }
}
```

**Intended outcome:**
Now I expect that the social data in the mutation response will be merged to the social object in the cache. final cache data would be something like this:
```js
User:123456 {
     id: "123456",
     name: "james",
     social: {
          telegram: "new_tg_id",
          facebook: "fb_id",
          instagram: "ig_id"       
     }
}
```

**Actual outcome:**
but when I check cache index I see the new social has been **replaced** with the previous one:
```js
User:123456 {
     id: "123456",
     name: "james",
     social: {
          telegram: "new_tg_id",    
     }
}
```

**How to reproduce the issue:**
as simple as above.

**Versions**
```
"@apollo/client": "^3.3.7",
"graphql": "^15.4.0",
"react": "^17.0.1",

```

**Comment by hwillson** [comment]
@foad-salawati this isn't a bug. Please review the [Data normalization](https://www.apollographql.com/docs/react/caching/cache-configuration/#data-normalization) section of the docs. In a nutshell, since you aren't providing an id of some kind in your `social` object, the cache doesn't know how to merge the existing with the incoming properly. You can either provide an id with `social` to address this, or consider using another entity identification technique that Apollo Client supports (e.g. field policy [`keyFields`](https://www.apollographql.com/docs/react/caching/cache-configuration/#customizing-identifier-generation-by-type)).

**Comment by foad-salawati** [comment]
> this isn't a bug. Please review the [Data normalization](https://www.apollographql.com/docs/react/caching/cache-configuration/#data-normalization) section...

Yes, Thank you. I used the powerful cache option `typePolicies` to solve this problem:

```js
const typePolicies = {
    User: {
        fields: {
            social: {
                merge: (existing, incoming) => {
                    if (!existing) existing = {}
                    return { ...existing, ...incoming }
                },
            },
        },
    },
}
```

**Comment by foad-salawati** [comment]
@hwillson Are you agree with my Opinion?
