### ISSUE TITLE
Feature: New process polyfill approach

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-client#8187]
This issue tracks the introduction of a new `process` polyfill approach.

Relates to:

- https://github.com/apollographql/invariant-packages/pull/94
- https://github.com/apollographql/apollo-client/issues/7895

**Comment by benjamn** [comment]
Fixed by #8347, though there may still be opportunities to improve the way we throw `invariant` and `InvariantError` exceptions in production, perhaps by dynamically fetching a module with all the error strings in it, or something along those lines. Dynamic `import()` might not be universally supported, but it only has to work with most applications/bundlers to be an improvement over opaque `Invariant Violation 23` errors (improved by #6665, but still annoying).
