### ISSUE TITLE
Better error for overwriting object with no id

### ISSUE THREAD

**Issue by stubailo** [apollographql/apollo-client#819]
Rather than "the application attempted to write an object with no provided id"

**Comment by stubailo** [comment]
Also, add path to these errors.

**Comment by helfer** [comment]
This issue has never come up in the last 5 months, so I think we're good here.

**Comment by clayne11** [comment]
I'm having a ton of trouble with this issue. It's extremely difficult to track down when the app gets large with a lot of fragments. I use a unique `nodeId` for each entity's ID field. If I forget to add a `nodeId` in any single entity anywhere inside any fragment, mutation, or query it causes Apollo to blow up with this error.

As suggested in the initial issue, adding a path would be **extremely** helpful.

**Comment by helfer** [comment]
Thanks @clayne11, let's make sure we print a better error message here!

**Comment by clayne11** [comment]
Keeping this open.

**Comment by hammadj** [comment]
Having the same issues as @clayne11

**Comment by davidtran** [comment]
I am still getting this issue.

**Comment by 0x80** [comment]
Same here

**Comment by jad11v** [comment]
also getting this issue!

**Comment by goldo** [comment]
I'm having the same issue, for a request/object which has no id, how can I fix it ? Thx

**Comment by goldo** [comment]
Ok here's what I found:

When we have this: 
- NO batching (because this problem doesn't appear when both requests are merged into 1)
- 1 of the 2 requests asks for an `id` field, and the other one doesn't, example :
```
// component 1
    config {
      id
      version
    }
// component 2
    config {
      updatedAt
    }
```

=> if the  component 1's request arrives first, apollo doesn't know how to handle the 2nd request. If not, it's OK.
=> if both of the components ask for an `id` field, its ok.
=> if none of the components ask for an `id` field, its ok.

**Comment by joint-song** [comment]
I think apollo client should generate(or any other action) a unique id to resolve this issue, not throwing an error.
It's not a perfect solution as @goldo do, but really helpful for now.

**Comment by goldo** [comment]
@joint-song if your data contains id field it means there should be several of them, right ? If it does, apollo will need to know how to handle them, and merge them.
If your data doesn't contains any IDs and is unique (like a global config query for example), the merge should be simple since there's only 1 element.
i don't know how apollo could handle them any otherway

**Comment by jbaxleyiii** [comment]
I think we can improve this with the goal of better messages / error handling in the post 2.0 launch

**Comment by tizmagik** [comment]
I just hit this error today. Haven't yet dug into the cause/why I'm seeing it, but a path to the error sounds like it might be useful. 😅

**Comment by jbaxleyiii** [comment]
After some discussion, I think its best to adjust this to be an error. We've added some better logging around when this is happening as well

**Comment by nevir** [comment]
👍 to error; we added it as one in Hermes, and it caught a _ton_ of bugs in our client apps

**Comment by hwillson** [comment]
To help provide a more clear separation between feature requests / discussions and bugs, and to help clean up the feature request / discussion backlog, Apollo Client feature requests / discussions are now being managed under the https://github.com/apollographql/apollo-feature-requests repository. 

This feature request / discussion will be closed here, but anyone interested in migrating this issue to the new repository (to make sure it stays active), can click [here](https://github.com/apollographql/apollo-feature-requests/issues/new?title=Better%20error%20for%20overwriting%20object%20with%20no%20id&body=Migrated%20from:%20apollographql/apollo-client%23819) to start the migration process. This manual migration process is intended to help identify which of the older feature requests are still considered to be of value to the community. Thanks!
