### ISSUE TITLE
Watchable/NPM linkable builds

### ISSUE THREAD

**Issue by brainkim** [apollographql/apollo-client#8263]
Working based off tests alone is admirable, but nothing beats trying out your code against a live example. I wish there was a way to 1. have watchable builds and 2. get npm link to work.

This is mostly just for me, but implementing this would lower barriers for contribution.

**Comment by ditransler** [comment]
@brainkim hi,
It appears there was a way for your 1st point but it was removed in v3.3.9 ([commit](https://github.com/apollographql/apollo-client/commit/a7da1c7df2bb77bfa6abae9c0ab8908acfcfada6)). As for your 2nd point it should work as described in [CONTRIBUTING.md](https://github.com/apollographql/apollo-client/blob/v3.3.10/CONTRIBUTING.md#wiring-a-checkout-into-an-application).

@benjamn , should we update/remove the "Wiring a checkout into an application" section considering there's no "watch" script anymore?

**Comment by hwillson** [comment]
@brainkim @benjamn thinking about this, we could add the following 2 `package.json` scripts (after npm installing `shx` of course):

```json
"link": "npm run build && npm link ./dist && shx cp -r node_modules ./dist && shx rm -r ./dist/node_modules/react && shx rm -r ./dist/node_modules/react-dom",
"watch": "tsc --watch"
```

With this in place, we could then `npm run link` once in an `apollo-client` checkout, then `npm link @apollo/client` in any app we want to link it into. This will work because:

- We're `npm link`ing the `./dist` dir
- By copying the `apollo-client` checkouts `node_modules` into `./dist`, we're making sure all dependencies are resolvable when AC is `npm link`ed in an application
- By removing `react` and `react-dom` from the `node_modules` copy we're automatically working around the too many versions of React errors that would come up normally

So with the above, we almost have full `npm link` capabilities, but instead of running `npm link` in the checkout, we're running `npm run link`, which isn't horrible.

Also, with this approach, we can then just leverage `tsc`'s simple `--watch`, meaning super fast watching. In development we don't usually need to worry about the extra bundle stuff we're doing with rollup/etc., so this should let us get away from the extra scripts that were slowing things down previously.

I know it seems kinda kludgy to copy `node_modules` into `./dist`, but we're cleaning `./dist` before building for deploy (so we won't accidentally include `node_modules` when we shouldn't in an official build), and copying means we can kill the extra `react` / `react-dom` deps when linking into other apps. The basically turns our [`Wiring a checkout into an application`](https://github.com/apollographql/apollo-client/blob/cefb3c32621de6973191c7abb6edd365d53cbf41/CONTRIBUTING.md#wiring-a-checkout-into-an-application) steps into 2 lines:

```
cd ~/apollo-client; npm run link
cd ~/some-awesome-app; npm link @apollo/client
```

I've tested this approach with a few apps, and it seems to work well. `npm run link` normally just has to be run once per checkout, unless of course we change any deps, in which case it has to be run again to copy the updated `node_modules` back over. And watching with `tsc` is of course super quick.

Food for thought anyways!

**Comment by hwillson** [comment]
@brainkim I know we both don't like the `node_modules` copying, so what if ... 

We create a new `./watch` directory in the root of the checkout. We then store a simplified `package.json` in this dir, with just deps + `main`, like: 

```json
{
  "name": "@apollo/client",
  "main": "index.js",
  "types": "index.d.ts",
  "dependencies": {
    "@graphql-typed-document-node/core": "^3.0.0",
    "@types/zen-observable": "^0.8.0",
    "@wry/context": "^0.6.0",
    "@wry/equality": "^0.4.0",
    "fast-json-stable-stringify": "^2.0.0",
    "graphql-tag": "^2.12.0",
    "hoist-non-react-statics": "^3.3.2",
    "optimism": "^0.16.0",
    "prop-types": "^15.7.2",
    "symbol-observable": "^2.0.0",
    "ts-invariant": "^0.7.0",
    "tslib": "^1.10.0",
    "zen-observable": "^0.8.14"
  }
}
```

We can then adjust the main `package.json` scripts like:

```
...
"link": "tsc --outDir ./watch && npm link ./watch && cd ./watch && npm i",
"watch": "tsc --watch --outDir ./watch"
...
```

This will let us run the same `npm run link` once in the main checkout, then `npm link @apollo/client` wherever we want to link things (and since the deps don't include `react` / `react-dom`, we're covered for the too many React's error). This will also let us watch things properly.

We could also take this a step further, and have the `link` script auto-generate the modified `package.json`, so we don't have to maintain it separately.

**Comment by bignimbus** [comment]
We added the ability to do snapshot releases here: https://github.com/apollographql/apollo-client/pull/10480

I believe that removes a lot of the pain around manually pulling and testing branches.  So I'm going to close this for now, please feel free to push back if we feel that we don't yet have enough tools available for client development/testing.
