### ISSUE TITLE
Unable to use Apollo GraphQL with external device

### ISSUE THREAD

**Issue by domlimm** [apollographql/apollo-client#8277]
Hi all,

I'm doing a school summer project, React Native with Expo and using Apollo GraphQL (for the first time) as the backend.

I manage to make it work with an Android Virtual Device (AVD) on localhost specifying `http://10.0.2.2:4000/`. However, it did not work when I'm using my Samsung Note 9.

I tried using various IP address npm packages but I am still unsuccessful.

This is my `apollo.js` file
```javascript
import { ApolloClient, InMemoryCache, createHttpLink } from '@apollo/client';
import { setContext } from '@apollo/client/link/context';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Network from 'expo-network';

// const IP_ADDRESS = '10.0.2.2';
// 10.0.2.2, 192.168.xxx.xxx (Samsung Note 9)
let URI;
let IP_ADDRESS;
const PORT = '4000';

const getURI = async () => {
  Network.getIpAddressAsync()
    .then(data => {
      URI = `http://${data}:${PORT}/`;
    })
    .catch(err => {
      console.log(err);
    });
};

getURI();

// const URI = `http://${IP_ADDRESS}:${PORT}/`;

console.log(URI);

const httpLink = createHttpLink({
  uri: URI
});

const authLink = setContext(async (_, { headers }) => {
  const token = await AsyncStorage.getItem('token');

  return {
    headers: {
      ...headers,
      authorization: token || ''
    }
  };
});

export const client = new ApolloClient({
  link: authLink.concat(httpLink),
  cache: new InMemoryCache()
});
```

I have taken a look at the below listed resources using thes keyword `network`, `external` and `external device`, but to no avail.
Even the issues in this repo.

* Apollo GraphQL community forums: https://community.apollographql.com
* StackOverflow (`apollo-client` tag): https://stackoverflow.com/questions/tagged/apollo-client

Appreciate any inputs please, thank you!

**Comment by benjamn** [comment]
@domsterthebot If the app runs in the emulator but not on a device, I would not expect Apollo Client to be the source of the problem, unless you have an error message or stack trace that clearly suggests Apollo Client is involved.

However, glancing at your code, I see that you are calling `getURI()` and then immediately assuming `URI` has been initialized. Since `getURI` is async, you have to wait for its result to be available, by attaching a callback to the `Promise` it returns. You're also going to need to fix `getURI` so that it returns a `Promise` for the URI string rather than initializing the `URI` variable.

If what I'm saying here isn't making much sense, I would recommend reading more about [promises](https://web.dev/promises/) and how they're used in JavaScript.
