### ISSUE TITLE
When initiating a request, is it possible not to clear the data immediately?

### ISSUE THREAD

**Issue by mantou132** [apollographql/apollo-client#8349]
my page is automatically polled for updates, but every time a request is made, the data will be temporarily emptied:

```ts
const [getStatistic, { data, loading }] = useGetStatisticLazyQuery();
const variables = useMemo(() => {
 ...
}, [...]);

useEffect(() => {
  getStatistic({ variables });
}, [variables]);

console.log({ data, loading });
```
<img width="328" alt="Screen Shot 2021-06-04 at 11 16 45 PM" src="https://user-images.githubusercontent.com/3841872/120825194-b56ede00-c58b-11eb-812c-b518f7916f54.png">

the page will flicker. Can I update the data after the request is over?

expect:
```
===> data: some value, loading: false

===> data: some value, loading: true

===> data: new value, loading: false
```

**Comment by benjamn** [comment]
@mantou132 I'm guessing the `data` is undefined because your variables are changing, and the cache doesn't have any data that matches the new variables.

If that's accurate, then you might try using the [`previousData`](https://www.apollographql.com/docs/react/data/queries/#previousdata) property returned by `useQuery`, or perhaps a combination of `data ?? previousData` to prefer `data` but fall back to `previousData` when `data` is undefined.

**Comment by mantou132** [comment]
@benjamn 
Thank you very much, this is exactly what I want.

Since I just started using Apollo client, I haven't noticed this attribute yet, sorry.
