### ISSUE TITLE
updateQuery from subscribeToMore updates cache but not query and UI

### ISSUE THREAD

**Issue by dbachorz** [apollographql/apollo-client#8357]
I've got a following code in my component:
```
  const {loading: queryLoading, error: queryError, data: queryResult, subscribeToMore} = useQuery(GET_ITEMS);
  const unsubscribe = subscribeToMore({
    document: SUBSCRIBE_ITEMS,
    updateQuery: (prev, {subscriptionData: {data}}) => {
      const previous = prev.getItems;
      if (!data) return previous;
      return [data.getItems, ...previous];
    }
  });
```

**Intended outcome:**
Query should execute again after subscription and rerender the component.

**Actual outcome:**
Query doesn't execute again nor UI gets updated.
Cache seems to be updated properly. After executing query I've got the items in my cache with following structure:

```
Item:1
Item:2
Item:3
```

After subscribing, I've got another item in my cache:
```
Item:1
Item:2
Item:3
Item:4 // comes from subscription
```

**Versions**
```
  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 90.0.4430.93
    Edge: Spartan (44.18362.1474.0)
  npmPackages:
    @apollo/client: ^3.3.19 => 3.3.19
    apollo-server-express: ^1.4.0 => 1.4.0
    react-apollo: ^3.1.3 => 3.1.3
```

**Comment by benjamn** [comment]
Are you still using that `react-apollo` package, or just getting everything (like `useQuery`) from `@apollo/client`? I ask because some of our older npm packages don't work with `@apollo/client` at this point.

Unless that random guess was the answer, the next step would be to put together a [reproduction](https://github.com/apollographql/react-apollo-error-template/) that demonstrates the cache update without a UI update. Happy to answer questions if you hit any snags.

**Comment by bignimbus** [comment]
Hi all, since this issue is getting a bit stale and there's nothing actionable emerging I'll close it for now.  Let us know if you need further support 🙏🏻
