### ISSUE TITLE
Relative URI Breaks Apollo Client

### ISSUE THREAD

**Issue by stolinski** [apollographql/apollo-client#8371]
**Intended outcome:**

Create a connection via Apollo client to a local relative path for SSR.

The big problem here is that Svelte Kit will not send credential cookie headers to another server, so it only sends those cookies serverside with a relative fetch path. This however seems to break Apollo. I've seen people mention it around, but much of the documentation shows that the default parameter of the uri property in httpLink is '/graphql'. This indicates that a relative path should be possible no? https://www.apollographql.com/docs/react/api/link/apollo-link-http/#httplink-constructor-options

If not, I'm having a hard time figuring out how to get Apollo to accept a relative url path. 

**Actual outcome:**

`  networkError: TypeError [ERR_INVALID_URL]: Invalid URL`

**How to reproduce the issue:**

`const httpLink = new HttpLink({ uri: '/api/graphql', credentials: 'include', fetch })`

**Versions**

  System:
    OS: macOS 11.5
  Binaries:
    Node: 16.2.0 - /usr/local/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 7.13.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.101
    Firefox: 68.0.2
    Safari: 14.1.2
  npmPackages:
    @apollo/client: ^3.3.20 => 3.3.20
    svelte-apollo: ^0.4.0 => 0.4.0

**Comment by hwillson** [comment]
Sorry for the delay here @stolinski. Apollo Client definitely supports relative URI's when it's being used client side, since it can determine the origin domain to use as part request URL. Running Apollo Client server side is a different story however, since the origin on the server is unknown. The lack of an origin domain server side isn't something Apollo Client can help with unfortunately. This isn't even something a Node fetch implementation can help with (e.g. https://github.com/node-fetch/node-fetch/issues/481) as the origin just isn't available unless explicitly specified. Thanks!
