### ISSUE TITLE
useQuery with 'cache-first' doesn't re-render when cache changes

### ISSUE THREAD

**Issue by Gentlee** [apollographql/apollo-client#8415]
**Intended outcome:**
Component should be re-rendered when cache changes.

**Actual outcome:**
Component is not re-rendered when cache changes.

**How to reproduce the issue:**
1. has custom key for some entities (in my case it is `"name"` for `ProductItem` type) [not sure this is needed]
2. use `useQuery` with `fetchPolicy: 'cache-first'`
2. get some item updated with mutation (in my case updated `ProductItem` is returned) [not sure this is needed]
3. additionally call query that returns updated entities (in my case `getUserProducts` that returns `[ProductItem!]!`)
4. component that uses useQuery with `cache-first` is not re-rendered until you set `cache-and-network`

**Versions**
System:
    OS: macOS 11.4
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 72.0.2
    Safari: 14.1.1
  npmPackages:
    @apollo/client: ^3.3.6 => 3.3.20
    apollo-upload-client: ^14.1.3 => 14.1.3
    apollo3-cache-persist: ^0.9.1 => 0.9.1
  npmGlobalPackages:
    apollo: 2.33.4

**Comment by Gentlee** [comment]
Looks like it is a problem of RN fast refresh..

**Comment by maxdbarton97** [comment]
I'm getting the same thing on React web. I've created a local-only field to store a search value that is used as a query variable (e.g. `searchValue @client @export(as: 'search')`).

When updating this local-only field using `writeQuery`, It runs the query again with the new search value when the `fetchPolicy: cache-and-network` but **not** for `fetchPolicy: cache-first`.

Is this expected behaviour? is the issue with react as the author may suggest?
