### ISSUE TITLE
Cache is not updating while react native app in offline

### ISSUE THREAD

**Issue by naveenst2s** [apollographql/apollo-client#8443]
I am trying to update cache with "cache.writequery"  after Mutation while app is in offline.But there is no update in cache.

**Comment by phryneas** [comment]
I am sorry, but this issue does not contain enough information for us to really give advice based on your situation.

Seeing that the issue is also very old, I am going to close it for now.

For the future, the best place for usage questions is our [Discord Server](https://discord.gg/graphos) or our [Community forum](https://community.apollographql.com/).

If you suspect a bug in Apollo Client, please feel free to open further issues in the future.
