### ISSUE TITLE
Can't find field on ROOT_QUERY object with cacheRedirects

### ISSUE THREAD

**Issue by maxsalven** [apollographql/apollo-client#8635]
I've seen a few github issues around 'can't find field' errors, but they don't seem to be related to cache redirects. Apologies if it's a dup.

I'm unable to reproduce in a simple repro unfortunately, I imagine there is some specific situation my cache is in that isn't emulated by a simple "render this query" reproduction.

I have an entity which is normally key'd and queried by its `id`.

However, I also have a top level query that fetches that entity based on its slug:

```
  const { error, data } = useQuery(
    ROCKET_BY_SLUG_QUERY,
    {
      variables: { slug },
    }
  );
```

This works fine, unless I use a cache redirect:

```
Query: {
  fields: {
    rocket: (_, { args, toReference }) =>
      toReference({
        __typename: "Rocket",
        id: args.id,
      }),
  }
}
```

Then I get an error:
```
Missing cache result fields: rocket [Error: Can't find field 'rocket' on ROOT_QUERY object
    at new MissingFieldError (http://localhost:3…]
```

Queries by `id` work fine.

I am able to fix it by either removing the redirect (not ideal, as I do use it for the queries by id), or by using the following pattern:
```
Query: {
  fields: {
    rocket: (ref, { args, toReference }) =>
      args.id ? toReference({
        __typename: "Rocket",
        id: args.id,
      }) : ref,
  }
}
```

Is this expected in certain circumstances? Is the pattern of checking for `args.id` an appropriate solution?

**Comment by benjamn** [comment]
@maxsalven Yep, if the `id` argument is optional or sometimes missing, dynamically checking `args.id` in your `read` function is a typical/appropriate solution, I would say.

To help ensure `args.id` is defined, you can mark that argument as non-optional (`rocket(id: ID!) {...}`) in your queries, though you have to do it in all your queries (including `ROCKET_SLUG_BY_QUERY`) to achieve any guarantee. Checking `args.id` once seems like potentially less work overall.

Also possibly important to note: the `args` property itself can be `null` if no arguments were passed to the field (like most scalar fields).

Here's how I might write the final code:
```ts
new InMemoryCache({
  typePolicies: {
    Query: {
      fields: {
        rocket(ref, { args, toReference }) {
          if (ref) return ref;
          if (args && args.id) {
            return toReference({
              __typename: "Rocket",
              id: args.id,
            });
          }
        },
      },
    },
  },
})
```
In this version, I always prefer `ref` if it's available, since the `ref` parameter represents existing data that was explicitly written into the cache for this field, rather than a guess about that data. If we have `args.id`, then we can guess the reference, but we don't need to guess if we have `ref`.

If none of the `return` statements returns anything, the `rocket` function returns undefined, which indicates missing data, which seems like a reasonable fallback here (though it may lead to `Can't find field 'rocket' on ROOT_QUERY object` errors).
