### ISSUE TITLE
`ssrForceFetchDelay` option causes useQuery calls to hang.

### ISSUE THREAD

**Issue by brainkim** [apollographql/apollo-client#8644]
Several users are indicating in #8582 that they’re having trouble with an option called `ssrForceFetchDelay`. As far as I can tell, it’s an option which is used in the browser to disable network fetches. I’m not sure how the option ever worked. There is this discussion item (https://github.com/apollographql/apollo-client/discussions/8060) which states that you can manually set `client.disableNetworkFetches` to `true` when hydrating, and then set it to `false` in the hydration callback.

```jsx
client.disableNetworkFetches = true;
ReactDOM.hydrate(
  <ApolloProvider client={client}>
    <MyApp />
  </ApolloProvider>,
  MOUNT_NODE,
  () => {
    // app is hydrated!
    client.disableNetworkFetches = false;
  }
)
```

If anyone can provide a reproduction that would be excellent.

https://github.com/apollographql/apollo-client/issues/8582#issuecomment-895666089 @woong25
https://github.com/apollographql/apollo-client/issues/8582#issuecomment-896179483 @jrsakizci
https://github.com/apollographql/apollo-client/issues/8582#issuecomment-896215262 @tm1000
https://github.com/apollographql/apollo-client/issues/8582#issuecomment-896459460 @mjspollard
https://github.com/apollographql/apollo-client/issues/8582#issuecomment-896628321 @krustyc
https://github.com/apollographql/apollo-client/issues/8582#issuecomment-896927171 @askurat
https://github.com/apollographql/apollo-client/issues/8582#issuecomment-897098745 @simplecommerce

**Comment by tm1000** [comment]
I think this worked in conjunction with `ssrMode`

**Comment by simplecommerce** [comment]
@brainkim ok here is a reproduction similar to my setup to demonstrate the issue I was getting on my end.

https://github.com/simplecommerce/meteor-graphql-app/tree/master 

Let me know if you have any issues getting this working.
I use Meteor and GraphQL together.

By default once you clone and setup the instance locally, it will be using @apollo/client 3.4.7 or latest.

Once the app is loaded, click on the button "Click me".
It will add a new project in an array and should list it below when the incrementation count increases.
But you will notice that nothing happens in the listing even if the increment count goes up.

Stop the app and then install @apollo/client 3.4.2 and then run it again and do the same test.
You should see the project list appear as you click the button.

If you go to this page `/client/main.jsx` and comment `ssrForceFetchDelay` on line `40`, and do the same tests using both version, you should see them working on both versions again.

So the problem seems to only occur when `ssrForceFetchDelay` is used in this case.

**Comment by brainkim** [comment]
Can you test this against 3.4.10? This is probably fixed there.

**Comment by simplecommerce** [comment]
@brainkim I have already tested this since the commit/update, and it works fine on my end yes! I don't know if anyone else can test it on their ends and make sure it works for them also.

**Comment by brainkim** [comment]
@simplecommerce That’s great to hear! Sorry for the trouble! Closing for housekeeping purposes.

**Comment by tm1000** [comment]
Thank you for the work, car and efforts towards to the open source community @brainkim. It does not go unnoticed!
