### ISSUE TITLE
My browser got crashed with "Aw, Snap" error after upgrading to 3.4.8

### ISSUE THREAD

**Issue by dean-g** [apollographql/apollo-client#8690]
I have upgraded my "@apollo/client" from 3.3.21 to the 3.4.8 version. 

Since then, my app got randomly crashed when the request payload is around 15KB. But the same worked well with the 3.3.21 version. 

![image](https://user-images.githubusercontent.com/12157452/130497535-5cbe1e3a-bb52-4f36-bb3e-237b996f29f4.png)

Can someone please help me fix this upgrade issue?

**Comment by j2L4e** [comment]
We've been seeing (seemingly) random STATUS_BREAKPOINT, STATUS_ACCESS_VIOLATION, SIGILL and SIGSEGV errors since upgrading to 3.4.

Most of the time the same operation works right after hitting "reload", so I'm still to figure out how to reproduce this.

I was able to catch a single SIGILL that happened in `lookupArray()` in `@wry/trie`. But I have no idea if that's where stuff actually goes wrong or if it's just a side-effect of a different cause.

https://github.com/benjamn/wryware/blob/a675c8e4f592b334e66f5d1edc4ec686f89cc444/packages/trie/src/trie.ts#L29

**Comment by dean-g** [comment]
it's happened to me when the request payload was around 15 to 20KB size!.

**Comment by benjamn** [comment]
@dean-g @j2L4e Any chance you could take/share a [heap snapshot](https://nolanlawson.com/2020/02/19/fixing-memory-leaks-in-web-applications/) before the crash?

**Comment by benjamn** [comment]
Potentially related issue: #8784

**Comment by j2L4e** [comment]
@benjamn very sorry to get back so late, would that snapshot still be of any use?
