### ISSUE TITLE
Dynamically mutate fields of Query in typePolicies didn't work

### ISSUE THREAD

**Issue by xxleyi** [apollographql/apollo-client#8781]
```ts
// a.ts
export fieldKeyArgs: Record<string, FieldPolicy> = {}
new ApolloClient({
  link,
  cache: new InMemoryCache({
    addTypename: false,
    typePolicies: {
      Query: {
        fields: fieldKeyArgs,
      },
    },
  }),
})
```

```ts
import {fieldKeyArgs} from './a'

fieldKeyArgs.newField = someFunc
```

In above code, fieldKeyArgs is type of `Record<string, FieldPolicy>`, the initial value of  fieldKeyArgs is `{}`, and I will mutate it dynamically in one custom Apollo link, such as `fieldKeyArgs.newField = someFunc`.

**Intended outcome:**
expect client will use the newest content of fieldKeyArgs.

**Actual outcome:**
expect client did not use the newest content of fieldKeyArgs.

**How to reproduce the issue:**

**Versions**
```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    Yarn: 1.22.10 - /Volumes/code/container-service-web/node_modules/.bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
  Browsers:
    Chrome: 93.0.4577.63
    Edge: 91.0.864.54
    Safari: 13.1.3
  npmPackages:
    @apollo/client: ^3.4.10 => 3.4.10 
    apollo: ^2.32.5 => 2.32.8 
```

**Comment by benjamn** [comment]
This is by design. You should think of the policy as frozen once you pass it to `InMemoryCache`. Changing policies in the middle of the session could silently and undetectably invalidate previously written data, so it's not something we support.

If you really need to add new field configurations after creating the `InMemoryCache`, you can use
```ts
(cache as InMemoryCache).policies.addTypePolicies({
  Query: {
    fields: {
      newField: ...,
    },
  },
})
```
However, please be sure you have never previously written or read data involving the `Query.newField` field, since previous data will not be magically updated to respect your new policy.
