### ISSUE TITLE
add operationName into context of KeyArgsFunction

### ISSUE THREAD

**Issue by xxleyi** [apollographql/apollo-client#8802]
https://github.com/apollographql/apollo-feature-requests/issues/313

**Comment by brainkim** [comment]
We do read all feature requests! At times it can feel like a firehose because there are may Apollo Client users and few maintainers. I apologize if you feel that you’ve been ignored. As far as adding the `operationName` to KeyArgFunction contexts, this is a pretty reasonable request, and could probably be implemented by an external contributor if you’re interested. 😉 The one thing is that there are some design considerations, like should we be able to access not just the `operationName` but other parts of the query? Should this data be available from `read` and `merge` functions as well? What should we pass in if we’re calling `cache.readFragment()`/`cache.writeFragment()`?

Lots of things which we’d need to hash out before going forward with implementation.

**Comment by xxleyi** [comment]
I am sorry to response so lately. 

> could probably be implemented by an external contributor if you’re interested.

I am interested, but I never did someting like this, I mean contribute in open souce project. So, I don't know if I have such an ability.

Back to this idea, I look some issues, find some possible issues which may be solved by this feature, such as:
- https://github.com/apollographql/apollo-client/issues/7196
- https://github.com/apollographql/apollo-client/issues/8125
- https://github.com/apollographql/apollo-client/issues/7114

**Comment by alessbell** [comment]
Hi there 👋 Since there's a duplicate issue linked above from the Apollo feature requests repository, which is where this type of request belongs, I'm going to close this one out. Thanks!
