### ISSUE TITLE
How to get that Apollo Client is refetching specific query?

### ISSUE THREAD

**Issue by Gentlee** [apollographql/apollo-client#8888]
I have a [question](https://stackoverflow.com/questions/69410912/how-to-get-that-apollo-client-is-refetching-specific-query) on stackoverflow. Just want to duplicate it here.

There are several places in the app where specific query is refetched after different mutations.

Example:

```typescript
// Some component
const [setUserLocation, setUserLocationResult] = useMutation(setUserLocationMutation, {
  refetchQueries: [{ query: getRecommendationsQuery }],
});
```

And in my RecommendationsComponent I want to know that this query is loading, but useQuery's loading doesn't update when getRecommendationsQuery is refetched.

```typescript
const {
  data,
  loading, // this loading is false all the time except first loading
} = useQuery(getRecommendationsQuery);
```

I can try put useQuery's refetch to the context and use it everywhere rather than refetchQueries prop, but is there a better way to achieve that without that dirty hack - either make loading work or subscribe to that info using apollo client?

**Comment by brainkim** [comment]
Have you tried the option `notifyOnNetworkStatusChange`? https://www.apollographql.com/docs/react/data/queries/#notifyonnetworkstatuschange

This will show query loading states when you perform a `refetch()` (in theory).

**Comment by benjamn** [comment]
@Gentlee I would also recommend passing the query document directly in the `refetchQueries: [...]` array (since v3.4.0):
```ts
useMutation(setUserLocationMutation, {
  refetchQueries: [getRecommendationsQuery],
})
```
This will refetch any active queries with the same `getRecommendationsQuery` document, whereas the `refetchQueries: [{ query: getRecommendationsQuery }]` syntax fires off a separate new query, without updating or refetching your existing queries (more details in this comment: https://github.com/apollographql/apollo-client/issues/8586#issuecomment-892881567).

If you want to intercept the queries that are going to be refetched, you can also provide an `onQueryUpdated` callback to `useMutation`:
```ts
useMutation(setUserLocationMutation, {
  refetchQueries: [getRecommendationsQuery],
  onQueryUpdated(observableQuery) {
    debugger;
    return observableQuery.refetch();
  },
})
```

More documentation about `onQueryUpdated` can be found in the [`client.refetchQueries` docs](https://www.apollographql.com/docs/react/data/refetching/). The options for `client.refetchQueries` are analogous to those for `useMutation`, with [a few differences](https://www.apollographql.com/docs/react/data/refetching/#corresponding-clientmutate-options).

**Comment by Gentlee** [comment]
> @Gentlee I would also recommend passing the query document directly in the `refetchQueries: [...]` array (since v3.4.0):
> 
> ```ts
> useMutation(setUserLocationMutation, {
>   refetchQueries: [getRecommendationsQuery],
> })
> ```
> 
> This will refetch any active queries with the same `getRecommendationsQuery` document, whereas the `refetchQueries: [{ query: getRecommendationsQuery }]` syntax fires off a separate new query, without updating or refetching your existing queries, which is typically not what you want. More details in this comment: [#8586 (comment)](https://github.com/apollographql/apollo-client/issues/8586#issuecomment-892881567).
> 
> If you want to intercept the queries that are going to be refetched, you can also provide an `onQueryUpdated` callback to `useMutation`:
> 
> ```ts
> useMutation(setUserLocationMutation, {
>   refetchQueries: [getRecommendationsQuery],
>   onQueryUpdated(observableQuery) {
>     debugger;
>     return observableQuery.refetch();
>   },
> })
> ```
> 
> More documentation about `onQueryUpdated` can be found in the [`client.refetchQueries` docs](https://www.apollographql.com/docs/react/data/refetching/). The options for `client.refetchQueries` are analogous to the refetch-related options for `useMutation`, with [a few differences](https://www.apollographql.com/docs/react/data/refetching/#corresponding-clientmutate-options).

@benjamn @brainkim thanks, combining both approaches (`notifyOnNetworkStatusChange: true` and using documents in `refetchQuery`) helped!
