### ISSUE TITLE
Graphql module does not work on PWA app written in Angular 12

### ISSUE THREAD

**Issue by ritesh-ranjan-nsi** [apollographql/apollo-client#8901]
I am developing a PWA app using angular 12 and it is connected with Graphql server via Apollo Client. As soon as, I import graphql module in my angular app, its PWA feature does not work (especially in the Chrome browser).
When I remove Graphql module and apollo client and build HTTP post request out the graph query, it works perfectly fine. 

Is there any existing issue with Grpahql module/Apollo Client.

**Comment by bignimbus** [comment]
Hi @ritesh-ranjan-nsi 👋🏻  thanks for your patience!  In order to narrow down what might be happening our community would benefit from more details.  I suggest using https://github.com/apollographql/react-apollo-error-template/generate to create a runnable reproduction so we can compare expected vs. actual behavior in a manner that reflects your use case.  Thanks again!
