### ISSUE TITLE
Reactive Variable Not Updating the UI

### ISSUE THREAD

**Issue by LydiaF** [apollographql/apollo-client#8918]
Dear Apollo,

Reactive variables are not updating the UI as expected. I made a very simple reproduction here... https://github.com/LydiaF/apollo-reactive-variables-reproduction

1. If you click the first button, nothing happens in the UI. I believe the reactive variable is updating because in the console.log, what it should be is what it is.
2. If you *then* click the second button, the UI change you would have expected to see previously happens!

Maybe it is somehow related to this issue? https://github.com/apollographql/apollo-client/issues/6699

Thank you so much for looking into this,

Lydia

**Comment by bignimbus** [comment]
Hi @LydiaF 👋🏻  thanks for your patience.  I think the issue here is that `useMyTasks` mutates the object stored in the reactive variable instead of returning a new object.  Here's the LOC I'm looking at:

https://github.com/LydiaF/apollo-reactive-variables-reproduction/blob/f2ad82c97f88dae5b09ad62b7d77914c08309c6b/src/useMyTasks.js#L8

If you were to modify that line to the following, I think it would resolve your issue:

```js
const y = {
  ...x,
  [task.id]: task
};
```

I'll close this for now but please feel free to let us know if you need further support here 🙏🏻
