### ISSUE TITLE
useQuery inline fragment error got transformed on browser side?

### ISSUE THREAD

**Issue by ardok** [apollographql/apollo-client#9005]
Hello,

Wondering whether anyone ever faced this issue.

So, I intentionally trigger this error locally (my app has server-side rendering).

I just do a simple:
```
const {error} = useQuery(...);
console.log(error?.message);
```

On my terminal (Node side), it prints this:
```
Cannot query field "contact" on type "GetMobileContactResult". Did you mean to use an inline fragment on "GetMobileContactResponse"?
```

Though on the browser console (developer console), the message becomes this:
```
Response not successful: Received status code 400
```

---

Is this by design?
Or it's some kind of configuration mistake from my side?

Thanks!

**Comment by brainkim** [comment]
@ardok It seems like this is an Apollo Server issue. What I think is happening is that `GetMobileContactResult` is an abstract type (a `union` or `interface`), and you need to use fragment syntax to query this type.

Let me know if this is enough information to help you find your way. I’m happy to help. Closing for housekeeping purposes because this isn’t an issue with Apollo Client.

**Comment by ardok** [comment]
Yeah, just close this. It looks like due to our setup where we use different logic between server rendering and browser rendering. That is in browser, we just transform the error message, not keeping it pristine.
