### ISSUE TITLE
Organizing a fork of Apollo Federation

### ISSUE THREAD

**Issue by ddevault** [apollographql/apollo-client#9007]
Good morning to everyone else who woke up to find that Apollo had spat in their bowl of cereal.

https://www.apollographql.com/blog/announcement/moving-apollo-federation-2-to-the-elastic-license-v2/

Apollo is moving to a non-free, non-commercial license. I am opening this issue to start organizing a fork among community stakeholders.

Should this issue be removed by Apollo's moderators, I have set up a temporary mailing list here:

https://lists.sr.ht/~sircmpwn/apollo-fork

You can email comments here without signing up for an account.

Do you depend on Apollo Federation and are you willing to participate in a fork? Please speak up if so. Let's get the ball rolling.

**Comment by darkbasic** [comment]
Forking is definitely a good idea (I'd personally never use something with a non-free license), but it might also be a good moment to ask ourselves whether it's better to stick with Federations or move to the new and improved [schema stitching](https://www.graphql-tools.com/docs/schema-stitching/stitch-combining-schemas).
I'm so sad that Apollo decided to move on the proprietary licenses bandwagon, it's such a great company and I'm truly displeased that they decided to follow that path, especially because I know it won't lead them anywhere good.
I wish them luck, but the community has to move on.

**Comment by ddevault** [comment]
Nice, first I've heard of stitching. I'll do some research on this for my own needs.

**Comment by darkbasic** [comment]
By the way I also don't think the client is the right place to talk about server side features, I'd personally close this.

**Comment by peggyrayzis** [comment]
Hi! I'm closing this issue because it's not the appropriate place to discuss the licensing of Apollo Federation 2. **Apollo Client for Web, iOS, and Android remain MIT-licensed.**

**Please read the [blog post](https://www.apollographql.com/blog/announcement/moving-apollo-federation-2-to-the-elastic-license-v2/) and [FAQ](https://www.apollographql.com/docs/resources/elastic-license-v2-faq/)** for more information on why we're moving to the Elastic License v2 for Apollo Federation 2. There is no impact to most of our community and customers. Just as before, running a federated graph in production (both public and private) is permitted, as is modifying or extending any part of the federation code.

Please [visit our community forums](https://community.apollographql.com/t/moving-apollo-federation-2-to-the-elastic-license-v2/1846) to discuss the move to ELv2 for Apollo Federation 2. We're here to answer your questions and help you navigate the transition. As always, Apollo is committed to building important open-source software for the graph ecosystem, such as Apollo Client, `apollo-rs`, Apollo Server, and Rover.
