### ISSUE TITLE
useQuery loading state starts with false after updating to 3.5.x

### ISSUE THREAD

**Issue by cyanic-webdesign** [apollographql/apollo-client#9145]
I have the following `useQuery` in my code:

``` 
const { loading, data } = useQuery(productOverviewQuery, {
  ssr: true,
  variables: composeVariables({ ...props  }),
});

console.log('loading', loading);
```

Up until version 3.4.8 the outcome of the loading property was:

```
loading: true
loading: false
```

but after updating to 3.5.x the loading state starts with false like:

```
loading: false
loading: true
loading: false
```

After the update, the first false loading state breaks my clientside flow as I act upon that state. Does anybody encounter this issue as well, and how can this be fixed?

**Comment by junajan** [comment]
Hi @cyanic-webdesign - we encountered this behaviour as well. When running a second `useQuery` with same query but different variables, it always returns `loading: false` together with `data` object and then it actually queries the new resource.

This behaviour breaks our app because we expect that the resource will have some extra fields which in the old object were set to `null`.

**Comment by eturino** [comment]
@junajan that's exactly what's happening to us, and giving us loads of problems since the upgrade. We probably will revert to 3.4.x until this is addressed.

**Comment by fabien-somnier** [comment]
any update on this issue? it's already a 4 month old one, and no news since more than 2 months :(

**Comment by dylanwulf** [comment]
Possibly related to #9549, #9580

**Comment by AlexMost** [comment]
Also have met this issue in `3.5.10`, seems like `3.6.0` is fixing it. Thank you

**Comment by cyanic-webdesign** [comment]
Thanks for the fix, seems to be working now!
