### ISSUE TITLE
useLazyQuery doesn't execute onError callback when `errorPolicy: "all"`

### ISSUE THREAD

**Issue by okbytes** [apollographql/apollo-client#9147]
**Intended outcome:**
When calling useLazyQuery with `errorPolicy: "all"`, I expect the onCompleted and onError callbacks to execute when the query returns partial data and errors.

**Actual outcome:**
The onCompleted callback will execute, but the onError callback will not. If I destructure out error like so: ` [lazyQuery, {error}] = useLazyQuery(), I can access the errors from the query. 

**How to reproduce the issue:**
Call useLazyQuery with errorPolicy: "all" and notice how onCompleted will execute but not onError.
_I've tried to get it going with a template, but it's all messed up and won't run._
https://codesandbox.io/s/bold-shirley-53rm1?file=/src/index.jsx

**Versions**
```
System:
    OS: macOS 11.6
  Binaries:
    Node: 16.13.0 - ~/.nodenv/versions/16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nodenv/versions/16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nodenv/versions/16.13.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Firefox: 94.0.1
    Safari: 15.1
  npmPackages:
    @apollo/client: ^3.5.5 => 3.5.5
```

**Comment by benjamn** [comment]
@01brett Did this work for you in v3.4? I have a hunch #9147 will turn out to be related.

**Comment by 01brett** [comment]
@benjamn This is the first time I've tried it in our app.

**Comment by MaLiN2223** [comment]
The same is happening to me, I'm on 3.8.4.
Removing errorPolicy: 'all' fixes the issue.

**Comment by jerelmiller** [comment]
Hey @okbytes 👋 

Thanks for your patience on this issue! I was able to confirm that this issue was present in 3.5.5. I just tried this with the latest version of Apollo Client (v3.8.4 at the time of this writing), and this issue seems to have been resolved. Check out [this sandbox](https://codesandbox.io/p/sandbox/fervent-kare-t753dj) that demonstrates an error returned on the `name` field which returns partial data + errors. You'll notice that `onError` is properly called here even with partial data returned. According to our [docs](https://www.apollographql.com/docs/react/api/react/hooks#oncompleted), `onCompleted` won't be called in this case because `onCompleted` only runs when there are **zero errors**.

Let us know if you need anything else. Thanks for reporting!
