### ISSUE TITLE
@apollo/client has breaking changes in v3.5.x compared to v3.4.17

### ISSUE THREAD

**Issue by mehulmpt** [apollographql/apollo-client#9159]
@apollo/client package completely breaks the following code in newer version (we use graphql-codegen so assume usePricingFieldsQuery under the hood uses useQuery only):

```js
const { data: expiryData } = usePricingFieldsQuery({
		onCompleted: () => {
			// do something with expiryData (broken)
		}
})
```

Before v3.5, inside `onCompleted`, the `expiryData` value was populated correctly. After v3.5, the `expiryData` is undefined if referenced from outside. Instead, one has to use the following code:

```js
usePricingFieldsQuery({
		onCompleted: (expiryData) => {
			// do something with expiryData (correct)
		}
})
```

Looking at the library source code, it seems like beyond v3.5, apollo synchronously calls the `onCompleted` handler the moment it has data from backend, hence not giving enough time for React to re-render component and populate the destructed argument properly.

We mistakenly upgraded this minor version in production today, and this broke our builds. I'm not sure if this package follows semantic versioning, but this should be in the next version if we were supposed to re-write all the query calls to include argument inside onCompleted handler instead of using it from outside as well.

**Comment by riv-bryan** [comment]
The same happened to me, and I had to downgrade the version to `v3.4.17`

**Comment by Mathieuu** [comment]
I have been affected as well. **It seems pretty serious:** The function passed to`onCompleted` is memoized on the first render and ignore any change done by subsequent renders. 

Here's a confirmation of the problem: https://codesandbox.io/s/mutations-example-app-final-forked-dpmqg?file=/src/index.js 

In that example, a react state "label" starts with the value: "initial" then change to "changed" after 2 seconds (setTimeout)

If you open the console and press the button to fire the mutation, you will see that the console.log in onComplete prints "initial" instead of "changed".

If you go to package.json and revert to "3.4.17", it will print "changed" as expected.

**Comment by benjamn** [comment]
@Mathieuu Thanks to your reproduction, I can confirm this will be fixed in the next patch version of `@apollo/client`, 3.5.6. I know @brainkim is investigating some other issues before we publish that release, but we should have this fixed one way or another very soon. Thanks for your patience!

**Comment by benjamn** [comment]
`@apollo/client@3.5.6` has been published, and seems to fix the reproduction provided by @Mathieuu (as expected). 🎉
