### ISSUE TITLE
Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android

### ISSUE THREAD

**Issue by pors** [apollographql/apollo-client#9213]
**Intended outcome:**

I'm using Apollo client in a React Native application. All works as expected, with the exception of the warning below.

**Actual outcome:**

I get this warning on Android devices:
```
Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
(Saw setTimeout with duration 900000ms)
```

The warning comes from the Apollo code, esp. `poll` `core.cjs:360:42`. 

I'm using Apollo 3.5.6

**How to reproduce the issue:**

Simply using Apollo in any React Native application on Android will cause this.

**Versions**

```
  System:
    OS: macOS 12.0.1
  Binaries:
    Node: 16.0.0 - ~/.nvm/versions/node/v16.0.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v16.0.0/bin/yarn
    npm: 8.2.0 - ~/.nvm/versions/node/v16.0.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0
    Safari: 15.1
  npmPackages:
    @apollo/client: ^3.5.6 => 3.5.6
```

**More information:**

This is not unique to Apollo, it happens with Socket.io and Firebase clients as well. More here: https://github.com/facebook/react-native/issues/12981

**QUESTION:**

Is it safe to ignore this warning? What are the consequences of the timers only being able to being awakend when the app is running in the foreground?

**Comment by hwillson** [comment]
> Is it safe to ignore this warning? What are the consequences of the timers only being able to being awakend when the app is running in the foreground?

React Native custom timers shouldn't impact Apollo Client use. The worst that could happen is that timers could be delayed from finishing if an app is backgrounded after they've stated, until the app is opened again. This shouldn't impact Apollo Client's use of timers since those timers are used to watch and notify of data changes, which would only be visible if the app is running in the foreground anyways. In other words, this error should be safe to ignore. If anyone feels otherwise, definitely let us know.
