### ISSUE TITLE
skip option on useQuery does not update loading/networkStatus

### ISSUE THREAD

**Issue by antunespedro80** [apollographql/apollo-client#9289]
**Intended outcome:**

Hi!
I was trying to refetch a query that has *skip: true* on options, but, depite query actually refetch, the states of loading/networkStatus don't, even tho I have *notifyOnNetworkStatusChange: true*

```
const {
        loading: ld,
        refetch: refetchPostsSearch,
        fetchMore: fetchMorePostsSearch,
        networkStatus: net,
    } = usePostsReportSearchQuery({
        skip: true,
        variables: {
            id,
            query: JSON.stringify(query),
            orderBy: {
                field: orderByField,
                direction: orderByDirection,
            },
        },
        notifyOnNetworkStatusChange: true,
    });
```

**How to reproduce the issue:**
Just create a query that use option skip and try to handle with its loading state.

**Versions**
System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    npm: 7.24.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.55)
  npmPackages:
    @apollo/client: ^3.4.15 => 3.4.15
    apollo-upload-client: ^16.0.0 => 16.0.0

**Comment by benjamn** [comment]
Was there a previous version of `@apollo/client` where this behaved differently? If there was, we will figure out why this changed and fix any regressions.

Otherwise, my best defense of this behavior is that `skip: true` is just stronger than (overrides) other options like `notifyOnNetworkStatusChange`, so it's working as designed here?

What problem were you hoping `skip: true` could solve?

**Comment by pedromdantunes** [comment]
I was hopping that `skip: true` would solve the following scenario:
I want render a compontent that has query above, but only executes when I refetch...
I know that I could use `lazyQuery` but I want the networkStatus to be `refetch` to handle where I will show my loading component

**Comment by bignimbus** [comment]
Hi all, thanks for the discussion here!  At this point I think having a [runnable reproduction](https://github.com/apollographql/react-apollo-error-template/generate) that demonstrates the actual vs. desired behavior would help move this discussion forward as I'm not 100% sure there's a shared understanding of what might be actionable here.  Thanks!

**Comment by 70nyIT** [comment]
I'm having the same behavior described above. I'm using `skip: true` the same way described here. When `skip` is set to false, and the call is performed, then I expect `loading` to go to `true` and, once the call is over, to `false`, while it stays `true`.

I'm not though understanding from this conversation if this is an intended behavior (And why) or a fix is planned or necessary. Thanks!

**Comment by phryneas** [comment]
@70nyIT I can only echo @bignimbus here: could you please provide a small reproduction for this?

**Comment by 70nyIT** [comment]
If this can help anyone: I did a deep dive into my code and apparently the issue is that the hook was running without a proper `uri` set. I'm setting it programmatically, based on set-up conditions, and if the whole UI is rendered while the `uri` hasn't been set yet, the very first call is never made.
This brings me to another point: is this behavior intended? Shouldn't it thrown an error instead if no `uri` has been set @phryneas ?

**Comment by phryneas** [comment]
@70nyIT If no `uri` is set and no `link` is set in the options, `ApolloClient` will default to `ApolloLink.empty()`. That's possible because theoretically you could create such an `ApolloClient` and then immediately assign `client.link = myLink`, which is also a valid way of initialization and done in some testing situations.

**Comment by 70nyIT** [comment]
make sense @phryneas . But if I do not assign a `client.link = myLink`, and perform a Query, that should throw an error, right?

**Comment by alessbell** [comment]
Hi all - as @phryneas said, without a reproduction here, on an almost two year old issue it's difficult to determine whether there is an actual bug occurring. I'll go ahead and close this issue, but if it's still occurring please feel free to comment with reproduction steps or open a new issue. Thanks!
