### ISSUE TITLE
Apollo Client cache merging previous (from other route) and new results when using browser back button

### ISSUE THREAD

**Issue by meesfrenkelfrank** [apollographql/apollo-client#9291]
I am using Apollo Client [fetchMore function](https://www.apollographql.com/docs/react/pagination/core-api/#the-fetchmore-function) and configured the Apollo Client cache: 

The Apollo Client [typePolicies](https://www.apollographql.com/docs/react/caching/cache-configuration/#installation) configured like:

```
    typePolicies: {
        NodesTypeOne: {
         keyFields: [],
         fields: {
          nodes: offsetLimitPagination(),
         },
        },
        NodesTypeTwo: {
         keyFields: [],
         fields: {
          nodes: offsetLimitPagination(),
         },
        },,
      },
```

From the Node _detail-page_ when I use the browser **Back button** (so it'a navigating back to the overview page, without refreshing the browser) and navigate from this overview page to another Node _detail-page_, it's merging the results from the previous route and the current route?

In the [useQuery](https://www.apollographql.com/docs/react/api/react/hooks/#usequery) hook I am using:

    notifyOnNetworkStatusChange: true,

Somehow, when I hit the **Back button**, I have to reset the cache or something?

How do I have to solve this issue?

**Comment by bengotow** [comment]
Hey folks! I think this issue is related to https://github.com/apollographql/apollo-client/issues/9334 and I put together a repro case there. When `notifyOnNetworkStatusChange: true`, it seems Apollo is behaving as if `returnPartialData: true` is also true. When you navigate back, I think useQuery is yielding a partial data object from cache.

It might also be mixing data on object 1 with data about object 2 but I didn't observe that, just that it returned a partial state that wasn't asked for.
