### ISSUE TITLE
Running NPM install I get a dependency error related to apollo

### ISSUE THREAD

**Issue by caldevcani** [apollographql/apollo-client#9337]
We have a Centos 7 server and we are trying to install wiki.js on a sub domain. If I run npm install I get the following error
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0" from apollo-link-persisted-queries@0.2.2

and the network administrator tells me it is because the module is not returning a 200 response. 

How do I fix this please?

**Comment by benjamn** [comment]
@caldevcani Generally speaking, I would suggest replacing usage of `apollo-link-persisted-queries` package with `@apollo/client/link/persisted-queries`. However, it's not a drop-in replacement because you need to provide your own sha256 hashing function (good for flexibility and bundle size, but more work).

In the meantime, if you can update `apollo-link-persisted-queries` to version 0.2.6, the `graphql` peer dependency version constraint has been relaxed to include v15 and v16 ([here](https://github.com/apollographql/apollo-link-persisted-queries/blob/70937795396931ac4c0a7c16db40e168fa2da38a/package.json#L45)), so your error ought to disappear.

**Comment by caldevcani** [comment]
Ok I am a newbie and I simply ran the command npm install to get all the node modules. How do I do what you are suggesting please?

**Comment by benjamn** [comment]
I don't think any of those packages (`wiki`, `pug-loader`, or `pug`) are in the dependency graph of `@apollo/client`, so that's not something we can fix, though I would suggest running `npm ls wiki` and/or `npm ls pug-loader` to see what's depending on those packages in your project.

**Comment by caldevcani** [comment]
Ok thanks but now we get a different error:
```
`npm ERR! While resolving: wiki@2.5.268
npm ERR! Found: graphql@15.3.0
npm ERR! node_modules/graphql
npm ERR!   graphql@"15.3.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0" from apollo-link-persisted-queries@0.2.2
npm ERR! node_modules/apollo-link-persisted-queries
npm ERR!   dev apollo-link-persisted-queries@"0.2.2" from the root`
```
Something about the version of GrphQL being wrong apollo expecting version 14 but only version 15 is available. This is preventing wiki.js from working

Help is appreciated thanks

**Comment by bignimbus** [comment]
Hi @caldevcani 👋🏻 thanks for your patience - I don't think we're able to assist without more info here. Our [discord server](https://discord.gg/graphos) is a great place for Q&A on specific implementation questions like this.  I'll close this issue since this isn't an issue with the client but again, it would be great to see you on the discord and the community would be happy to try to help out.
