### ISSUE TITLE
Item list and item details queries link to the same cache object

### ISSUE THREAD

**Issue by brampurnot** [apollographql/apollo-client#9365]
Hi all,

I have a bit of situation I'm struggling with and I'm not entirely sure how to handle it. It goes as follows.

In my backend, I have 1 type which represents a product. The product has a couple of key fields: 
  type MarketplaceProduct {
    _id: ID!
    brand: String
    productDescription: String!
    mfrPartId: String
    productLink: String
    sku: String
    batch_number: String
}

To fetch the products, I have 2 queries: one called "get_products" to fetch a list of all the products. And another one called "get_product" to fetch a single product. All good here.

When I execute the "get_products" query to get the list of products, I only request a couple of fields (_id, brand and productDescription). When I execute the "get_product" query, I basically retrieve all fields. In the chrome devtools, I'm noticing that both queries are sharing the same cached object. 

When I run "get_products" and look at a particular cached object, I only see few details; when I click on the actual product and fetch the rest of the details, the cached object is enriched with the rest of the fields. Again all good here. 

The problem I'm facing is the following:
1. I first get a list of all the products which are cached (first time it does this, it uses the network; second time it uses the cache)
2. I then click on a specific product and see the rest of the details (first time it does this, it uses the network; second time it uses the cache).
3. When in the product details screen and I click on the back button, it goes back to my list of products. Since these are stored in cache, I would expect this to be read from the cache. However it is always calling my backend API. 

Why is this happening? I noticed that if I request all the fields in the "get_products" query, then this issue is not occurring. So it seems to be caused by the fact that the details of a single product contains more fields than when I retrieve the list.

What is the best approach here? I don't want to fetch all fields when retrieving a list of products and I of course want to leverage the cache when I move back from a product details screen into the products list screen.

Should I make a distinction between both and have separate cache object for the list and for the product details? This seems a bit of an overkill as well.

Any help is appreciated here!

Bram

**Comment by ramonwenger** [comment]
Hey @brampurnot 

Apollo can automatically serve your query from the cache, if **all** requested properties are present. If not, the query goes to the server first, and then the values get cached. At least if the default fetch policy is set, that is. For that see [here](https://www.apollographql.com/docs/react/data/queries/#setting-a-fetch-policy) and [here](https://www.apollographql.com/docs/react/data/queries/#supported-fetch-policies).
That explains why your app fetches from the server for your product detail view. It needs more info, so it gets those from the server, can't get them from the cache. If you were to fetch all the same props in the list view, you could save yourself the trips to the server for the detail views. But here's where every app is different: If you always need the details of multiple products during the lifetime of an app session, it may make sense to fetch all the details in the list. Otherwise, you might be better off to have a request for every detail view. That's for you to decide.
The products list screen in your example probably should still use the cache, so there could be a couple possibilities for why it doesn't. First: does your back button reload the page? If so, your cache probably will be gone. The cache seems to be only stored in the memory, if you need something else you need to configure it yourself. There's a [library](https://www.apollographql.com/docs/react/caching/advanced-topics/#persisting-the-cache) for that, too.
Or maybe your fetch policy is set to network-only?

**Comment by brampurnot** [comment]
Thanks for that. It was indeed caused by a difference in properties requested in both queries. Apparently I was fetching property when getting the list of items which I missed when fetching the item details.

Problem solved! Thanks for the help.
