### ISSUE TITLE
[Documentation Request] Explicit examples and/or best practices for querying from react class components

### ISSUE THREAD

**Issue by kaysond** [apollographql/apollo-client#9413]
The current documentation has no mention of ReactJS class components, and this is a question that seems to come up: #7111, [StackOverflow 1](https://stackoverflow.com/questions/57874784/fetching-query-in-method-of-a-class-component) [Stack Overflow 2](https://stackoverflow.com/questions/69742267/how-to-render-react-class-component-with-react-hashrouter-and-apollo-client)

Ok actually there is one tiny mention! In the section on typescript, there's a brief mention of [Classes vs Functions](https://www.apollographql.com/docs/react/development-testing/static-typing/#classes-vs-functions) which rightly points out that sometimes components depending on graphql data have state! Except the example uses `@apollo/react-hoc` which is deprecated.

It would be great to have something more explicit here. It seems that most people have resorted to passing the client object around and running a `.query()` on it directly in a lifecycle function and updating component state. That's... clunky. Obviously HOC is not the best choice. 

I did notice the [ApolloConsumer component docs](https://www.apollographql.com/docs/react/api/react/hooks/#the-apolloconsumer-component) mention that 

> You can think of the ApolloConsumer component as similar to the Consumer component from the [React Context API](https://reactjs.org/docs/context.html).

Is there actually a `Context` here that can be used by the static `MyClass.contextType`?

Thanks!

**Comment by alessbell** [comment]
Hi @kaysond 👋

I'm doing some housekeeping and came across this issue. While I recognize that the lack of documentation for usage within React class components has created some challenges for you and others in the past, Apollo Client's render prop and HOC APIs have been deprecated since 2020. In our upcoming 3.9 release, we've added a missing `@deprecated` tag in their respective docblocks so a warning about their deprecated status will appear in your IDE once you upgrade (and use TypeScript).

With that being said, I'm going to close this issue since we'd like to discourage use of these deprecated APIs and won't be fielding PRs to add this documentation. Please feel free to join our [Discord](https://discord.gg/graphos) where you can direct any questions about usage to the #frontend channel. Thanks!
