### ISSUE TITLE
onError not working

### ISSUE THREAD

**Issue by aminsaedi** [apollographql/apollo-client#9449]
`useMutation` errors are not handled by global `onError` link.

I'm trying to execute a mutation and it fails with status code of 500. as I set `onError` when configring `ApolloClient` I expected to show the error there and prevent the app from crashing. but it seems that it's not working. Only if I pass `onError` in the `useMutation` the app is not crashing otherwise the global `onError` run and immediately after that my app crashs.

```js

const errorLink = onError(({ graphQLErrors, networkError }) => {
  if (graphQLErrors)
    graphQLErrors.forEach(({ message, locations, path }) =>
      console.log(
        `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`,
      ),
    );

  if (networkError) console.log(`[Network error]: ${networkError}`);
});

const combineLink = from([errorLink, cleanTypeName, httpLink])

const gqClient = new ApolloClient({
  link: combineLink,
  cache: new InMemoryCache(),
  defaultOptions: {
    mutate: { errorPolicy: 'all' },
  },
})
```

**Versions**
System:
    OS: macOS 12.1
  Binaries:
    Node: 17.4.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
    Firefox: 97.0.1
    Safari: 15.2
  npmPackages:
    @apollo/client: ^3.5.9 => 3.5.9 
    apollo-upload-client: ^16.0.0 => 16.0.0

**Comment by bignimbus** [comment]
Hi @aminsaedi 👋🏻  thanks for your patience!

Can you share some sample code from the place where your app is crashing?

As a general note, Error Links won't suppress errors.  See the [Network errors](https://www.apollographql.com/docs/react/data/error-handling/#network-errors) heading in that doc.  We recommend handling errors in your UI code as well so they can be reported to users and/or otherwise handled according to specific business logic.

I hope that helps, let us know if you still need support here!
