### ISSUE TITLE
Subscriptions link is not exposed

### ISSUE THREAD

**Issue by joshforisha** [apollographql/apollo-client#9472]
**Intended outcome:**

Import the `GraphQLWsLink` to setup a subscriptions link, as per docs `import { GraphQLWsLink } from '@apollo/client/link/subscriptions'`

**Actual outcome:**

A failure to find the mentioned module, with error `Failed to resolve import "@apollo/client/link/subscriptions"`

**How to reproduce the issue:**

Attempt the import from `@apollo/client/link/subscriptions` and verify no such module path exists from the package.

**Versions**

`@apollo/client 3.5.9`

---

I'm able to get the example code to work by using the `GraphQLWsLink` class source directly in my own modules, but the mentioned `link/subscriptions` is not available from the installed package.

**Comment by benjamn** [comment]
@joshforisha We intentionally kept `@apollo/client@3.5.10` tagged as `next` rather than `latest` on npm so we could test it before opening the floodgates of update PRs. You should be able to install that version directly with `npm i @apollo/client@next` or `npm i @apollo/client@3.5.10`. That said, it's already gotten [2300 downloads this week](https://www.npmjs.com/package/@apollo/client?activeTab=versions), so I'll probably just promote 3.5.10 to `latest` shortly.

**Comment by benjamn** [comment]
Ok, `npm i @apollo/client` with no explicit tag or version should give you 3.5.10 now (since I promoted it to `latest`), and 3.5.10 should give you `@apollo/client/link/subscriptions`. I know it's a bit strange to release new functionality in a patch release, but I did my best to explain the rationale in my `CHANGELOG.md` note.

Please feel free to close this issue if updating to 3.5.10 solves the problem for you (and thanks for reporting)!
