### ISSUE TITLE
Document that concurrent fetchMore use is OK

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-client#948]
Motivating example: Let's say you have a query that represents a window into the middle of a list of items, and you have two buttons that extend the list in either direction using fetchMore.  Ideally, you'd like the user to be able to click on both buttons very quickly (before roundtrip time is up) and issue the two fetchMore queries in parallel, and feel confident that two updateQuery calls will be invoked and that the second one will see the result of the first one.

As far as I can tell from manual testing, this is the current behavior of fetchMore. I wasn't able to find any documentation to show that this is intentional behavior that I can rely on!

Note that there are two pieces to this: the "correctness" aspect (one updateQuery sees the results of the other instead of both of them seeing the first state as the previous result) and the "performance" aspect where both queries get sent over the network in parallel rather than one waiting for the other to finish.

**Comment by stubailo** [comment]
I'd say everything should be good, depending on what you mean by:

> that the second one will see the result of the first one.

Currently, we have no guarantee that the results will arrive in the same order that the buttons were clicked. However, both of your statements are true:

1. updateQuery is applied atomically when the result is received, regardless of when the request for fetchMore was initiated. I think this might actually be a problem if a refetch happened in the middle, because then you might get duplicate data - not sure if we handle that case explicitly.
2. Currently no queries block on other queries as a general thing, so they are indeed sent in parallel.

Where would people expect to see this documented? It's not unique to fetchMore - similar semantics are relevant for mutations, for example.

**Comment by glasser** [comment]
Ah yes, by "second" and "first" I just mean the ordering of invocation of updateQuery, not of fetchMore.

(I assume that updateQuery has to return synchronously, not via a Promise, right?  That's my current reading of the course.  Of course if you're running this on a Node server (SSR) with Fibers you might get in trouble, but presumably SSR doesn't call fetchMore much.)

**Comment by stubailo** [comment]
Yes, in alignment with the Redux philosophy, `updateQuery` is expected to be synchronous, and to not mutate the input arguments.

Any ideas about where this should be documented? Perhaps we could have a new section titled, simply, "concurrency" about some of the edge cases one can run into about different orderings of various operations.

**Comment by glasser** [comment]
Yeah, that could be nice, since there might be multiple issues like this.

Other places include http://dev.apollodata.com/react/cache-updates.html#fetchMore and http://dev.apollodata.com/react/pagination.html . fetchMore doesn't appear to have real docs in the Vanilla section.
