### ISSUE TITLE
data returned from useLazyQuery, and lazy query's promise are not referentially equal

### ISSUE THREAD

**Issue by Grsz** [apollographql/apollo-client#9511]
**Intended outcome:**

`data` returned from `useQuery`, and lazy query's promise's `data` referentially equal.
```
  const [items, setItems] = useState<GetItemsQuery['getItems']>([])
  const [lazyGetItems, { data, loading }] =
    useGetItemsLazyQuery({
      fetchPolicy: 'network-only',
      notifyOnNetworkStatusChange: true,
    });
  const getItems = (variables: GetItemsQueryVariables) =>
    lazyGetItems({ variables }).then(({ data }) => {
      setItems(data?.getItems || [])
      return data?.getItems || [];
    });
  console.log(items, data?.getItems, items === data?.getItems);
```
I would expect `data.getItems` to be equal to `items`, where as you can see `items` is the result of `lazyGetItems`, and visibly they are equal, but referentially they aren't.

**Actual outcome:**

`data` returned from `useQuery`, and lazy query's promise's `data` aren't equal.

**How to reproduce the issue:**
[Sandbox to check behaviour](https://codesandbox.io/s/jolly-brook-upgbpu?file=/src/index.jsx)

**Versions**
3.5.10, but tested with 3.4.16 too.

**Comment by bignimbus** [comment]
Hi @Grsz 👋🏻  thanks for opening this issue and thanks for your patience!  There's a few reasons why this wouldn't be possible given the structure of `InMemoryCache`.  Unfortunately I'm not able to compose a more thorough explanation of these reasons at the moment, but the lack of referential equality is a result of intentional design decisions.  Please do feel free to add a [Feature Request](https://github.com/apollographql/apollo-feature-requests/issues) if you feel strongly about your use case 🙏🏻
