### ISSUE TITLE
How to debug apollo query initiated in server Side.

### ISSUE THREAD

**Issue by Amerr** [apollographql/apollo-client#9631]
Hi i am running `next.js` (node) server and using `@apollo/client v3`. 
I need to know how can i debug/inspect the queries request from the server.

The actual motivation behind this discussion is 
- I am requesting a query to a `third party graphql server` 
- there is something wrong with my requested query as it has multiple Fragments so i need to inspect what is the resolved 
query before the graphql makes the request.

**Comment by bignimbus** [comment]
Thanks @Amerr for opening this issue!  Since this is more of an open-ended question I think it would be perfect for our [community forum](https://community.apollographql.com/).  Feel free to open a new issue if there's something to request or fix in the Apollo Client code.

As a brief suggestion, consider using our Apollo Client Devtools browser extension if you're not doing so already, it's a great tool for learning what's happening under the hood in the client.  Also, the `Network` tab in your web browser dev tools is great for showing network requests and responses.
