### ISSUE TITLE
migrating away from deprecated HOC

### ISSUE THREAD

**Issue by petyavok** [apollographql/apollo-client#9654]
Hi,

What is the best way to migrate away from the deprecated hocs in apollo client?

https://www.apollographql.com/docs/react/api/react/hoc/

It would be extremely difficult for us to use hooks, since all of our components are built on recompose and class based components, which would need a complete rewrite.

Do any of you know a still maintained drop-in replacement with zero or minimal changes required, for the graphql() hoc?

We also evaluated creating our own hoc implementation based on the deprecated one, but it doesn’t seem like an easy solution, if we want to cover all the features it has.

If anyone has a suggestion, or was in the same situation please let me know, thanks.

**Comment by isnifer** [comment]
@petyavok 
```js
export const withHooksHOC = (Component: any) => {
  return (props: any) => {
    const screenWidth = useScreenWidth();

    return <YourClassBasedComponent width={screenWidth} {...props} />;
  };
};
```

**Comment by jpvajda** [comment]
@petyavok  Thanks for the question.  You can try posting this in our [Apollo Community](https://community.apollographql.com/) for guidance from other Apollo users, as other's may have input into your question. 

I'll leave this open an issue as well, in case others have ideas.

**Comment by alessbell** [comment]
Hi @petyavok 👋

I'm doing a bit of housekeeping and came across this issue. I don't have any advice to add here, but I wanted to give you a heads up that the deprecated HOC APIs (deprecated since 2020) will be indicated as deprecated in 3.9 onward in their respective docblocks, so you will see that in your IDE if using TypeScript.

I'm going to go ahead and close this issue, but please feel free to ask any usage-related questions like this in our [Discord](https://discord.gg/graphos) going forward. Thanks.
