### ISSUE TITLE
useSubscription stop working in React v18 StrictMode

### ISSUE THREAD

**Issue by pobch** [apollographql/apollo-client#9664]
### Intended outcome:
In React v18 `StrictMode`, `data` should be received from `useSubscription()`.

### Actual outcome:
`data` is always `undefined` even though the server actually sends it via websocket. Find more details in **"How to reproduce the issue"** below.

### How to reproduce the issue:
1. Use React v18
2. Turn on `StrictMode`
3. The complete code should look like this:
```javascript
import React from 'react'
import ReactDOM from 'react-dom/client'
import {
  ApolloClient,
  InMemoryCache,
  ApolloProvider,
  HttpLink,
  split,
  useSubscription,
  gql,
} from '@apollo/client'
import { WebSocketLink } from '@apollo/client/link/ws'
import { SubscriptionClient } from 'subscriptions-transport-ws'
import { getMainDefinition } from '@apollo/client/utilities'

const INSTRUMENTS_SUBSCRIPTION = gql`
  subscription OnInstrumentsUpdated {
    instruments {
      ...
    }
  }
`

// ----------------------------- Component ---------------------------------
function App() {
  const { data, loading } = useSubscription(INSTRUMENTS_SUBSCRIPTION, {
    fetchPolicy: 'network-only',
  })

  if (loading) return <p>Loading...</p>

  return (
    <>
      <pre>{JSON.stringify(data, null, 2)}</pre>
    </>
  )
}

// ----------------------------- Setup Apollo ---------------------------------
const httpLink = new HttpLink({
  uri: 'http://localhost:8088/api/graphql',
})

const wsLink = new WebSocketLink(new SubscriptionClient('ws://localhost:8088/ws/graphql'))

const splitLink = split(
  ({ query }) => {
    const definition = getMainDefinition(query)
    return definition.kind === 'OperationDefinition' && definition.operation === 'subscription'
  },
  wsLink,
  httpLink
)

const client = new ApolloClient({
  link: splitLink,
  cache: new InMemoryCache(),
})

// ----------------------------- React v18 StrictMode ---------------------------------
const root = ReactDOM.createRoot(document.getElementById('root'))
root.render(
  <React.StrictMode>
    <ApolloProvider client={client}>
      <App />
    </ApolloProvider>
  </React.StrictMode>
)
```
4. Start the app
5. In `App` component, `loading` will be `false`, and `data` will always be `undefined`.
6. In the network tab, it shows that Apollo immediately sends `{ type: "stop" }` message right after `{ type: "start" }`

<img width="318" alt="Screen Shot 2565-05-03 at 18 18 01" src="https://user-images.githubusercontent.com/19894957/166444062-417a5beb-a7e5-4bb1-a2d8-603a06108916.png">

If I remove `<React.StrictMode>` from the code, the app would work properly. We got `data` from the server, and `{ type: "stop" }` message would not be fired.

<img width="318" alt="Screen Shot 2565-05-03 at 18 21 45" src="https://user-images.githubusercontent.com/19894957/166444505-35676927-075f-475a-b6de-03ddc0165a05.png">

### Versions
```
  System:
    OS: macOS 12.3.1
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.8.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Firefox: 99.0
    Safari: 15.4
  npmPackages:
    @apollo/client: ^3.6.2 => 3.6.2
```

### Dependencies in `package.json`
```
  "dependencies": {
    "@apollo/client": "^3.6.2",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^13.0.0",
    "@testing-library/user-event": "^13.2.1",
    "graphql": "^16.4.0",
    "react": "^18.1.0",
    "react-dom": "^18.1.0",
    "react-scripts": "5.0.1",
    "subscriptions-transport-ws": "^0.11.0",
    "web-vitals": "^2.1.0"
  },
```

**Comment by chegger** [comment]
https://github.com/apollographql/apollo-client/issues/7608 seems to be a related issue

**Comment by kazekyo** [comment]
I have created a repository that reproduces this issue.
https://github.com/kazekyo/react-apollo-error-template/tree/strict_mode_subscription

I think it is related to React18 restoring state when StrictMode is enabled.

> To help surface these issues, React 18 introduces a new development-only check to Strict Mode. This new check will automatically unmount and remount every component, whenever a component mounts for the first time, restoring the previous state on the second mount.

https://reactjs.org/blog/2022/03/29/react-v18.html#new-strict-mode-behaviors

[useSubscription.ts](https://github.com/apollographql/apollo-client/blob/main/src/react/hooks/useSubscription.ts)
1. Mount a component
2. [Create an `observable`](https://github.com/apollographql/apollo-client/blob/f0cd32177c0c62118e9cac3d146bfb43141917d5/src/react/hooks/useSubscription.ts#L28-L39)
3. Unmount and [call `subscription.unsubscribe()`](https://github.com/apollographql/apollo-client/blob/f0cd32177c0c62118e9cac3d146bfb43141917d5/src/react/hooks/useSubscription.ts#L120)
4. Re-mount and state is restored, so the ubsubscribed `observable` is used

If I have more time today, I will check the Apollo Client source code.

**Comment by kazekyo** [comment]
[useSubscription.ts](https://github.com/apollographql/apollo-client/blob/main/src/react/hooks/useSubscription.ts)

Once a `subscription` is created by `observable.subscribe()` is unsubscribed, it seems not to work when the `subscription` is created again from the `observable.subscribe()`.
By commenting out `subscription.unsubscribe()`, `useSubscription` works correctly.

I don't understand why reusing an `observable` would cause such a problem.


---

A commit for debugging: 
https://github.com/kazekyo/apollo-client/blob/0b055e28fa8b202ad1e9484a4eceb2ce921a3bc5/src/react/hooks/useSubscription.ts#L122-L135

StrictMode
![スクリーンショット 2022-05-10 21 03 49](https://user-images.githubusercontent.com/456381/167625427-36b0fa0c-ea6b-41a3-b47c-773b88761543.png)

Removed StrictMode
![スクリーンショット 2022-05-10 21 05 51](https://user-images.githubusercontent.com/456381/167625562-49f2fa87-e634-4b92-a768-8ffede6f3404.png)
From this log, I guess it is working because `subscription.unsubscribe()` is not called when StrictMode is removed.

**Comment by kazekyo** [comment]
I understand why we should not reuse `observable`.

When `useSubscription` creates an `observable`, the `observable` adds a first `observer`. By subscribing to this `observer`, our program can communicate with our server.
Basically, when adding an `observer`, the `observable` increments `addObserver` but does not increment `addObserver` the first time it adds the `observer`.
https://github.com/apollographql/apollo-client/blob/9bcda653bf4a3eaf64a61c515d72cec5b6bf20b0/src/core/QueryManager.ts#L985-L996
https://github.com/apollographql/apollo-client/blob/9bcda653bf4a3eaf64a61c515d72cec5b6bf20b0/src/utilities/observables/Concast.ts#L235-L240

When React unmounts a component, `useSubscription` unsubscribes the created `subscription`. And `observable` decrements `addObserver` from 1 to 0. When setting `addObserver` to 0, the `observable` calls `this.handlers.complete()` and the first observer calls `complete()` finally.
https://github.com/apollographql/apollo-client/blob/9bcda653bf4a3eaf64a61c515d72cec5b6bf20b0/src/react/hooks/useSubscription.ts#L120
https://github.com/apollographql/apollo-client/blob/9bcda653bf4a3eaf64a61c515d72cec5b6bf20b0/src/utilities/observables/Concast.ts#L141-L147
https://github.com/apollographql/apollo-client/blob/9bcda653bf4a3eaf64a61c515d72cec5b6bf20b0/src/utilities/observables/Concast.ts#L208

Even if `useSubscription` subscribes to anything after that, our program can't communicate with the server because the `observable` does not have the first observer.

I think it is easier to recreate the `observable` when re-mounted than to rewrite the `observable` to be reusable.

I'm not familiar with zen-observable and Apollo Client code, so please let me know if there is something wrong 🙏

**Comment by jurgelenas** [comment]
Copying my comment from https://github.com/apollographql/apollo-client/pull/9707#issuecomment-1169933791:

I think apollo-client has an issue when re-mounting subscription components without the StrictMode now.

This issue is reproducible on our open source desktop app ExpressLRS Configurator. We were able to fix subscription re-mount issues in development build by wrapping whole app inside <React.StrictMode> component. See https://github.com/ExpressLRS/ExpressLRS-Configurator/pull/351. But nightly builds are still not working at https://github.com/ExpressLRS/ExpressLRS-Configurator-Nightlies.
