### ISSUE TITLE
useQuery requests omitted properties from previous variables (Working 3.5.10 but breaking in 3.6.1/2)

### ISSUE THREAD

**Issue by obo-spi** [apollographql/apollo-client#9671]
**Intended outcome:**

```
const [variables, setVariables] = useState({deleted: true, someOther: "value"})

const { data } = useQuery(query, { variables })

// Omit the deleted property
const breakIng = () => setVariables({someOther: "value"}

```

If the variable omits a property that was queried before, then the old value of that variable is used in the request.

**Actual outcome:**
The request must transfer the variables as is.

**How to reproduce the issue:**
See above, hope it helps you.

**Versions**
3.5.10: works as expected
3.6.1 and 3.6.2: requests previous properties

**Comment by yura3d** [comment]
Just made codesandboxes to reproduce the issue. The only difference is AC version:

- 3.6.2: https://codesandbox.io/s/musing-shaw-y4c6rl
- 3.5.10: https://codesandbox.io/s/dazzling-bird-tyjejf

**Comment by benjamn** [comment]
@obo-spi @yura3d My proposed fix can be tested now by running `npm i @apollo/client@beta` to get version `3.7.0-alpha.6`. Note: while that version says 3.7, PR #9741 is targeting the `main` branch, implying a 3.6.x patch release (not 3.7). Please let us know if that alpha version seems to help (or not)!

**Comment by yura3d** [comment]
@benjamn Thanks, after `3.7.0-alpha.6` installing the issue is gone.

**Comment by Titozzz** [comment]
@benjamn I was taking a look at https://github.com/apollographql/apollo-client/issues/9152 that's been opened for a while.
 Then I tried the reproduction I submitted on the other issue few months ago.
 - It was working < 3.5.0-beta6
 - Then broken in 3.5.0-beta6
 - Then fixed in 3.6.0-beta11
 - Then broken in 3.7.0-alpha by this commit.
 
 While I understand that comparing to 3.5 it looks like a regression, 3.5 was actually a regression from 3.4 and 3.6 was a good release compared to 3.4
 What to expect now ? Open to discuss
 cc #9736

**Comment by benjamn** [comment]
@Titozzz Thanks for surfacing that issue. I believe we may be able to interpret the role of the `useLazyQuery` execution function a little differently from what happens when we call `useQuery(query, { variables })` or even `useLazyQuery(query, { variables })` (where the variables are replaced), and I think I agree the execution function's variables should be merged with any `variables` provided originally.

**Comment by Titozzz** [comment]
I get what you mean, so we always want to merge the function variables with the one provided to the hook, but we don't want the one provided within the function to be merged with the next function call ? That would be fine / logical to me.
