### ISSUE TITLE
multiple identical queries using useLazyQuery with a fetch policy of "no-cache" result in only one network call

### ISSUE THREAD

**Issue by SimonMueller** [apollographql/apollo-client#9920]
**Intended outcome:**
When e.g. a property changes we want to execute a react effect to fetch some data with unchanged variables. So the request is identical to the initial request done from the effect.

We expect that with a fetch policy of "no-cache" multiple network calls are made to fetch the latest data. One for each execution of the effect.

**Actual outcome:**
The effect is executed twice but only one network call is made. 

(Sometimes even no network request is made in our app but we currently cannot reproduce this behaviour)

**How to reproduce the issue:**
I wrote two tests reproducing this in a minimal repo. One passes and the other fails as written above.

https://github.com/SimonMueller/apollo-lazy-query-fetch-policy-issue-reproduction

**Versions**
System:
    OS: Windows 10
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.16 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @apollo/client: 3.6.9 => 3.6.9

**Comment by jerelmiller** [comment]
Hey @SimonMueller 👋 

So sorry that its taken a while for us to get back to you! Thanks for your patience.

I ran your reproduction and I'm not sure the reproduction properly captures the issue here. I was able to get your test to pass if I wait a small duration of time between the time your component initially renders then rerenders:

```jsx
  const view = render(<Component fetchPolicy="no-cache" input="something" />, {
    wrapper: wrapper(spy),
  });

  await new Promise((res) => setTimeout(res, 100));

  view.rerender(<Component input={"something 2"} />);
```

I believe what you're seeing in the failing test is due to [query deduplication](https://www.apollographql.com/docs/react/api/core/ApolloClient#apolloclientoptions-querydeduplication) which will attach a new request to an in-flight request if the same query/variables are used for the 2nd query. In fact, if I disable query deduplication in your test, I see that `no-cache` will result in the 2 network requests you're looking for:

```jsx
  const [getData, { data }] = useLazyQuery(GET_DATA, {
    fetchPolicy,
    context: {
      queryDeduplication: false,
    },
  });
```

(NOTE: you may see a failure due to "No more mocked responses for the query", which means you either need to add a 2nd entry to your `mocks` array, or use `maxUsageCount` option, which is available in [v3.9.0](https://github.com/apollographql/apollo-client/releases/tag/v3.9.0) or later)

See if your app is perhaps making requests in quick succession. Its possible you're just seeing query deduplication in practice. You can either disable this per-query with the `context` solution that I have above, or disable it entirely by passing `queryDeduplication: false` to your `ApolloClient` constructor.

Please let me know if you're seeing anything different. Thanks!

**Comment by SimonMueller** [comment]
Hey thx a lot for the explanation! That makes perfect sense to me and we are indeed making requests with the same variables in quick succession so i will try to disable query deduplication and it should work fine.

**Comment by jerelmiller** [comment]
@SimonMueller awesome! If you discover this does not fix the problem, let me know and I'd be happy to reopen this issue.
