### ISSUE TITLE
Investigate testing timeouts on CI

### ISSUE THREAD

**Issue by alessbell** [apollographql/apollo-client#9982]
Placeholder issue for investigating testing timeouts that began when we started running more tests.

Example timeout: https://app.circleci.com/pipelines/github/apollographql/apollo-client/16498/workflows/84b5eb64-9dd5-44ae-a4d5-e422e3bdfff9/jobs/92982/steps

**Comment by hwillson** [comment]
Running our tests with `--detectOpenHandles` brings back 2 open handles, caused by our usage of `sha256` in the `@apollo/link/persisted-queries` tests. I'll adjust to make sure things are closed.

![Image](https://user-images.githubusercontent.com/137740/182837298-b712c823-b957-46bf-804d-786ee04d22f3.png)
