### ISSUE TITLE
Tests failing when running with more than one jest worker

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-client#9988]
We merged https://github.com/apollographql/apollo-client/pull/9986 to get tests in CI passing again, but we'll want to look into a better solution that doesn't require running tests serially (ie. remove the Jest `--runInBand` setting). While we're at it we might also want to split things like the performance tests out into their own CI job(s) to better leverage Circle's parallelism.

**Comment by alessbell** [comment]
There is an open upstream bug (https://github.com/facebook/jest/issues/11956) for memory consumption issues in Node JS 16.11.0+ and the current community workaround is `--runInBand` _or_ a new `--workerIdleMemoryLimit` API introduced in Jest 29.

In https://github.com/apollographql/apollo-client/pull/10424, I experimented with `--workerIdleMemoryLimit` on CircleCI but our tests repeatedly stalled so we reverted to `--runInBand`.

Given that this issue is pervasive and `--runInBand` is an accepted workaround, I'm going to close this issue for now, but we may re-open/re-visit in the future. Thanks!
